### ISSUE TITLE
13 - Support direct uploads to Rackspace's Cloud Files storage service (modern browsers)

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#1025]
Cloud Files [has CORS support](http://docs.rackspace.com/files/api/v1/cf-devguide/content/CORS_Container_Header-d1e1300.html), supports [form posts for uploading (including a redirect parameter)](http://docs.rackspace.com/files/api/v1/cf-devguide/content/FormPost-d1a555.html), and [support for chunking](http://docs.rackspace.com/files/api/v1/cf-devguide/content/Static_Large_Object-d1e2226.html).  

With all of this in mind, we should be able to support the same workflow for uploads directly to RackSpace Cloud Files that we currently support for uploads directly to AWS S3.

I'm interested in hearing how popular this feature might be.  The demand for this feature will likely influence its priority.

**Comment by pratik60** [comment]
@rnicholus Any idea when work on this feature could resume?

**Comment by rnicholus** [comment]
Work on this never started. There are a number of other features ahead of it at this time, so I don't have a date for you.

**Comment by zmilan** [comment]
Hi @rnicholus ,
I just play around to setup direct uploading to RS cloud files. I'm able to upload file directly using simple plain javascript, but for our need it will be great if I can setup fineuploader to do same. So I try to do it with fineuploader 5.2.2 using traditional endpoint with PUT method and RS tempUrl. I get file uploaded but it is corrupted.
Here is example of original file content and uploaded file content:

**Original file content:**
This is begining of note.txt
This is second line of note.txt

**Uploaded file content:**
------WebKitFormBoundaryfBz63adwZDN4eB3c
Content-Disposition: form-data; name="qquuid"

543a79c1-3659-4165-b01b-23b657b06860
------WebKitFormBoundaryfBz63adwZDN4eB3c
Content-Disposition: form-data; name="qqfilename"

note.txt
------WebKitFormBoundaryfBz63adwZDN4eB3c
Content-Disposition: form-data; name="qqtotalfilesize"

61
------WebKitFormBoundaryfBz63adwZDN4eB3c
Content-Disposition: form-data; name="qqfile"; filename="note.txt"
Content-Type: text/plain

This is begining of note.txt
This is second line of note.txt

------WebKitFormBoundaryfBz63adwZDN4eB3c--

Is there anyway that I can configure fineuploader to escape this and keep file same like original? Do you have any other suggestion how I can use fineuploader to get this done?

One more thing is that fineuploader report failed upload in this case, even file exist on RS cloud files container.

Thanks for any help.

**Comment by rnicholus** [comment]
By default, Fine Uploader will send all upload request multipart encoded. This is a default settings as traditional `<form>` submits are _also_ multipart encoded, so it is quite easy to parse these types of requests since this has been the _only_ way to upload files for a very long time, before the File API was standardized and implemented in most browsers. In fact, this is _still_ the only way to upload files in IE9 and older.

You can have Fine Uploader send only the file bytes in the request payload by setting [the `request.forceMultipart` option to `false`](http://docs.fineuploader.com/branch/master/api/options.html#request.forceMultipart). Any parameters will be included in the URI query string in that case. 

When using the traditional uploader, Fine Uploader requires that the endpoint responding with valid JSON, and the response _must_ include a `success` property with a value of `true`. If the upload endpoint does _not_ send this in the response, the upload is considered a failure.

**Comment by zmilan** [comment]
Hi @rnicholus , thanks for help. I try to force multipart with false, but it still send same data. I can't parse it on server because it directly upload it to RS cloud files.
Here is last code what I try:

`var uploader = new qq.FineUploader({
            debug: true,
            element: document.getElementById('fine-uploader'),
            request: {
                endpoint: '<?= $uploadUrl;?>',
                method: 'PUT',
                forceMultipart: false,
                paramsInBody: false
            }
        });
`
`$uploadUrl` is RS tempUrl with right signature and expiration date. So it success create file on right container and upload it, just I have this extra part that belong to request and not to file. There is also no change when I add forceMultipart to be false.

Also it return only HTTP 201 Created ,what I believe is enough, but I dont see any way to customize what FineUploader expect to get like result.

Is there way to handle this with current FineUploader 5.2.2, or maybe option that RS will get official support in some close date?

**Comment by rnicholus** [comment]
@zmilan There are no concrete near-future plans to support uploads to Rackspace due to the rlatively small userbase that uses this cloud storage (compared to Azure and S3). If there is something we can do to make it easier for individual users to upload directly to RS using the traditional Fine Uploader module, we can take that into consideration. 

I can see allowing the expected response to be customized via options. This will probably make uploads to RS in most browsers easier, but there may be other challenges related to EI9 and older. For example, the request will _have_ to be multipart encoded.

**Comment by zmilan** [comment]
Hi @rnicholus thanks for fast response. I can understand this and I think making this what done by patch to be option to setup in configuration will be enough good.
For our application, IE<10 is not an issue and also it will not be too hard to setup IE<10 specific version of upload (I think file uploading is not only one thing that you need to handle specially for IE<10 in today applications :))
So, if I can vote, I will give +1 to add configuration for accepting 201 status like success for uploading.

**Comment by zmilan** [comment]
@rnicholus Is there any info about when we can expect configuration for accepting 201 status response like success for uploading?

**Comment by rnicholus** [comment]
@zmilan We currently accept 200-204 (#1314), but for traditional endpoints, we still expect a JSON response of `{"success": true}`. Removing this requirement will be a breaking change (and a major one at that).

**Comment by zmilan** [comment]
@rnicholus yes, I understand this. I will create feature request and until 6.0 we will go with our patched version.

**Comment by rnicholus** [comment]
I see Rackspace CloudFiles is as being a very small piece of the commoditized cloud file storage service provider. Even Azure is a much bigger player, AFAICT. I'm closing this as I don't see this happening anytime in the near future. Priorities, priorities.
