### ISSUE TITLE
Support direct upload to Dreamhost Dreamobjects from browser.

### ISSUE THREAD

**Issue by nin9creative** [FineUploader/fine-uploader#1068]
DreamObjects has a compliant S3 API that I'm using for uploading files using the AWS SDK from PHP.

However I'd like to bypass the server side "middle man" and upload directly from the client browser.  

However in reading your documentation - it seems that it may not work as DreamObjects doesn't have all the security setup that AWS has.

**Comment by robbat2** [comment]
@feltnerm 
DreamObjects is NOT based on Swift, rather the S3 provided by Ceph's RADOS gateway component.
