### ISSUE TITLE
3 - Use contenteditable html5 attribute to edit file names

### ISSUE THREAD

**Issue by afurculita** [FineUploader/fine-uploader#1079]
This is a suggestion. It will be nice to use Html5 at its whole power, at least in the browsers that supports it. Maybe it's a nicer approach to use contenteditable html5 attribute when the edit file names feature is on.

**Comment by rnicholus** [comment]
After some more thought, I don't think `contenteditable` is appropriate for this situation. A simple text input is best for renaming a file. As such, I'm closing this.
