### ISSUE TITLE
Homepage Automation

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/fine-uploader#1095]
The homepage has recently undergone a redesign, and I think a concentrated "clean-up" effort along with some automation of common homepage tasks would be beneficial for future maintenance.

A few things I'd like to see (in order of importance):
* Gruntfile added with a task to automate deployment of new versions of Fine Uploader to homepage (a Gruntfile also adds opportunities to do tons of other useful things too) [enhancement]
* All JS errors on any pages stifled [bug, to fix]
* All extra JS on any pages removed [technical debt]
* A base "template" page to base all pages off of so we don't have competing versions of bootstrap, jquery, etc. [enhancement]

One idea is to use a static site generator to generate the site. There would need to be another branch to hold the source files, but this branch would generate a site and merge it into gh-pages if needed. An example project demonstrating this layout: https://github.com/feltnerm/blog

**Comment by rnicholus** [comment]
I don't see an obvious need to "automate" anything related to fineuploader.com ATM, other than maybe updating the version number. But that is a pretty easy variable to update manually.
