### ISSUE TITLE
Prevent Multiple Uploads of Same File

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/fine-uploader#1101]
Steps to reproduce:

Requires a modern browser (i.e., File API support) and Fine Uploader with `autoResume` & `chunking` enabled.
1. Select a file and submit it to the uploader.
2. After the first chunk has been sent for file 0, select and submit the same file again.

Fine Uploader believes the user submission of file 1 was actually a resumption of file 0. At this point, file 1 will begin uploading at the same point file 0 was in the upload process. This is because -- based on the filename, size, and resumable file data -- these two files _are_ the same file to Fine Uploader. So if file 0 was 50% done, file 1 would begin at 50%. This results (in the S3 uploader) in a bug where the request to S3 to combine the parts is sent twice for the same `uploadId`. The second time this request is sent the `uploadId` does not exist (because the `CompleteMultipartUpload` request to that `uploadId` has already been sent).

Ideally, Fine Uploader would prevent duplicate submission of the same file. How to go about that is another problem: Client-side hashing is possible, but produces much more overhead. FU could ensure that no files with the same filename and total size are currently in progress or resumable before allowing an upload to continue. Is it possible that a user could have two distinctly different files that happen to have the exact same size and name? In this case, maybe an integrator would want to allow the user to rename the file before the upload begins.

This probably affects the traditional uploader as well.

**Comment by alphestdev** [comment]
How can duplicate prevention be activated in 5.5.x?

**Comment by rnicholus** [comment]
This feature was never implemented.
