### ISSUE TITLE
File is not added to internal stored list in manual upload mode before onSubmitted

### ISSUE THREAD

**Issue by KRTac** [FineUploader/fine-uploader#1106]
Running uploadStoredFiles() in a submitted event for an added file doesn't add that file to the upload queue.

If I add files to fine uploader and run uploadStoredFiles(), then add one other file and in the submitted event for that file I run uploadStoredFiles() again, that file won't be added to the upload queue. So when the original files finish uploading, the file that is last added won't start it's upload and will have a status of undefined.

I think that when the submitted event runs, the file that it references must already have a SUBMITTED status and must be ready to be added to the upload queue.

**Comment by rnicholus** [comment]
Will probably look into this as part of 5.2.3.

**Comment by rnicholus** [comment]
@KRTac @bjornbos The fix for this is currently being staged in the develop branch as part of 5.3.0-5. Please let me know if this fixes your issue.

**Comment by bjornbos** [comment]
Fixes it for me
