### ISSUE TITLE
FileUploaderBasic - how do you use it?

### ISSUE THREAD

**Issue by rokcarl** [FineUploader/fine-uploader#114]
is there some documentation on how to implement the FileUploaderBasic or do I have to go through the source code ("qq.FileUploader = function(o){...") to figure it out?

**Comment by rakeshmotghare** [comment]
Below is the code I am trying to do with fileuploadbasic but didt work, it dont allow me to pass all these parameters. I need to upload files to webapi. I am switich to fileuploadbasic from fileuploadtraditional as there is no type definition file available for fileuploadtraditional. Thanks in advance.



export class FileUpoader extends React.Component<FileUploader, FileUploaderState> {
    private uploader = new FineUploaderBasic({
        debug: true,
        request: {
            method: 'POST',
            endpoint: uri.concat('/api/UploadFile'),
            customHeaders: {
                Authorization: 'aaa ' + idToken,
                'Access-Control-Allow-Origin': uri
            },
            forceMultiplart: true,
        },
        deleteFile: {
            enabled: true,
            endpoint: '/uploads'
        },
        retry: {
           enableAuto: true
        },
        chunking: {
            enabled: true,
            partSize: 150000,
            mandatory: true,
        },
        cors: {
            expected: true,
            sendCredentials: true
        },
        callbacks: {
            onUpload: () => {
                if (this.props.onFileUploadStart !== undefined) {
                    this.props.onFileUploadStart();
                }
            },
            onComplete: (id: number, name: string, response: FileUploadResponse, xhr: string) => {
                if (this.props.onFileUploadComplete !== undefined) {
                    this.props.onFileUploadComplete(response.fileId);
                }
            },
            onError: function (id: number, name: string, errorReason: string, xhr: string) {
                // console.log('Error occured while uploading a file chunk for the file: ' + name + ' Error: ' + errorReason);
            },
        }
    });
