### ISSUE TITLE
Edit filename in an initial file list

### ISSUE THREAD

**Issue by bogal** [FineUploader/fine-uploader#1142]
Following from a suggestion on stackoverflow:

The potential for a user to rename a file when fineuploader has been populated with an initial file list.

Currently (4.3.1) files displayed in the initial file list do not have the ability to edit the filename, like is possible when uploading a file. Is it possible to enable this function when the initial file list is populated - as it stands, files from the initial file list can be deleted, it would be helpful to rename at a later date too.

The main reason i have come across this is for a post-upload renaming policy. 

The file renaming would use the standard fineuploader UI as is currently implemented, and a normal request / endpoint parameter configured would send the new name as a normal file upload, perhaps with a json property of edited = true or something to differentiate it from a typical upload request. Or perhaps a separate endpoint?

Or for the fineuploader UI trigger a filenameEdited event, which the user can hook into and send a customer request themselves (uuid and new filename as params).

**Comment by NickJorens** [comment]
Just came across this, this would be great for my project. I'm currently implementing this as something custom. I'd love to see this in fine-uploader
