### ISSUE TITLE
3 - Two Endpoints, One Error

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/fine-uploader#1144]
Begot by: http://stackoverflow.com/questions/21939087/fine-uploader-using-both-direct-s3-and-traditional-in-same-project

When using fineuploader.com/customize it is currently not possible to select more than one endpoint. This means the solution for supporting multiple endpoints would be to include two distinct copies of Fine Uploader on your page. When one includes two instances of custom Fine Uploader builds (each build referring to a distinct endpoint type) on a page it is only possible to use the latter endpoint handler since the `qq` global object is redeclared in `client/js/utils.js`. Another (smaller) matter is the code duplication and an extra HTTP request.

Example, if my scripts are laid out like so:

```
<script src="fineuploader/s3.fineuploader-4.3.1.js"></script>
<script src="fineuploader/traditional.fineuploader-4.3.1.js"></script>
```

Then I am not able to instantiate a new S3 endpoint handler because `qq.s3` is not in the `qq` object once the traditional uploader is interpreted.

**TO FIX**:

a) Update website customize form to accomodate multiple endpoints. This will require changing endpoint radio buttons to checkboxes. Theoretically, the custom build grunt task and assembler server should still continue to work as expected. The server may need to be tweaked to parse the checkboxes instead of the radios.

b) Test builds / assembler server

----

Another workaround I found was to redeclare the `qq` namespace/object like so in `client/js/utils.js`

```
var qq = window.qq || function(element) {
// ...
}
```

**Comment by ayelkawar2** [comment]
I have single page AngularJS application where I want to be able to choose the between traditional or S3 uploader instance before creating it. The type of uploader is chosen based on the response of a GET request I send just before creating the uploader.

How do I download a custom build of fine-uploader containing both s3 and traditional uploaders? This was supported before but has been removed recently.

**Comment by rnicholus** [comment]
Hmm, this seems to have fallen through the cracks when we updated our download/build system. I'll be sure to have this fixed when 5.3.0 is released. In the meantime, you can build all.fineuploader.js by following the instructions in the [building Fine Uploader guide](http://docs.fineuploader.com/contributing.html). 

@ayelkawar2 I'd be happy to build the version of your choice for you and send the combined version via email. If you're a license-holder, send an email to support and I'll get back to you with a zip file.

**Comment by ayelkawar2** [comment]
Thanks for the link. I can use the all.fineuploader.js version until 5.3.0 version is released.

**Comment by rnicholus** [comment]
My plan is to simply publish an additional combined JS file that includes Azure, S3, and the traditional endpoint handler. This will essentially be the all.fineuploader.js file that is created (but not published) when the build is run.

**Comment by rnicholus** [comment]
Completed as part of 5.3.0. This is the last scheduled case for 5.3.0, so if testing goes well release will be next.
