### ISSUE TITLE
Direct Camera Upload no longer working with Windows 8.1 RT (Microsoft Surface)

### ISSUE THREAD

**Issue by Philbert123** [FineUploader/fine-uploader#1145]
Per conversation with Ray Nicholus on StackOverflow it is apparent that with Windows 8.1 RT Microsoft has removed the native 'direct camera upload' capability present in Windows 8.0 RT on the Microsoft Surface. We have been able to reproduce this problem on a number of devices including the Surface 1 (RT), Surface 2 and Surface 2 Pro.

**Comment by rnicholus** [comment]
Does anyone know if this is an issue with recent Surface tablet?

**Comment by rnicholus** [comment]
Closing, but willing to re-open if this is still an issue.
