### ISSUE TITLE
[docs] 404 Logic

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/fine-uploader#1167]
The logic for handling 404 errors in the documentation is a bit sketchy. I'll outline some problems while I have it fresh in my head ...

The [htaccess](https://github.com/Widen/fine-uploader/blob/master/docs/_scripts/htaccess#L88) redirects **all** 404s to "/" which is actually [rewritten as '/branch/master'](https://github.com/Widen/fine-uploader/blob/master/docs/_scripts/htaccess#L52). 

This allows us to give users URLS like docs.fineuploader/features/session.html rather than the full docs.fineuploader.com/branch/master/features/session.html.

The problem is when someone enters a 404, the links are not always correct if we are using relative links.

**Comment by rnicholus** [comment]
Docs will be moving to a GH repo or possibly S3, so there is no reason to keep this open.
