### ISSUE TITLE
Total Progress Bar Shows/Hides in rapid succession

### ISSUE THREAD

**Issue by jetheredge** [FineUploader/fine-uploader#1175]
I have implemented the total progress bar with fine upload ui (to s3), and if I upload a large number of small items, the total progress bar will flash visible and invisible as the list of items uploads. Just as a test, I was uploading the js directory out of bootstrap since it has a good number of very small files.

Let me know if you need me to record a video of it occurring so you can see it happening, but it is consistently reproducible for me.

**Comment by innamhunzai** [comment]
Hi @rnicholus I am facing this issue in 2.15.0 release.
