### ISSUE TITLE
Add ability to clean up Fine Uploaders upload history

### ISSUE THREAD

**Issue by csquire** [FineUploader/fine-uploader#1196]
I am using FU in a single-page application with AngularJS wrapped in a UIWebView for an iOS app using PhoneGap.  Since my SPA is "long running", I have concerns about a long list of completed uploads building up over time and consuming a large amount of memory and creating a long list in the FU UI template.  It would be quite handy if I could somehow control that.  I am thinking something like setting a max number of completed/failed uploads that stay in the list and having FU prune those when the list gets too big.

**Comment by rnicholus** [comment]
This is the last planned feature for 5.4.0.

**Comment by rnicholus** [comment]
For some reason, the title of this case has diverged from the original description. The request was for Fine Uploader to clean up the DOM once the number of file representations became "too large". The title was changed, by me, to shift this focus to the internal upload history store. Each item in the upload history store should probably only take a _very_ small amount of memory, and it doesn't seem to be worthwhile to expend any effort to auto-prune that list. If the DOM is the focus, then this is not Fine Uploader needs to tackle. Integrators are free to remove `<li>` elements that represent files from the DOM at any time.
