### ISSUE TITLE
Fine Uploader on cdnjs

### ISSUE THREAD

**Issue by chrylis** [FineUploader/fine-uploader#1203]
[cdnjs](https://github.com/cdnjs/cdnjs) is a resource CDN run by CloudFlare that will host open-source Web components. There's [an existing package for the 3.7.0 version of Fine Uploader](https://cdnjs.com/libraries/file-uploader), but it's under the name "File Uploader" instead, and it hasn't been updated since then.

Would Widen submit a package to add current versions to cdnjs? The process looks fairly easy, but I barely speak JavaScript and know essentially nothing about `npm` and Node.

**Comment by rnicholus** [comment]
We already distribute Fine Uploader via npm, which, in my opinion, is sufficient.
