### ISSUE TITLE
3 - Azure: set Content-Type, Content-Disposition, etc blob headers

### ISSUE THREAD

**Issue by AnalogJ** [FineUploader/fine-uploader#1212]
I'm sorry if this is the wrong place to ask this, but I wasn't able to find anything in the docs or on SO. 

With the Azure fineuploader jquery plugin, is it possible to set the content-type or content-disposition headers for a file that is being uploaded? The `params` object seems to have all its headers name-spaced with `x-ms-meta`.

**Comment by Korijn** [comment]
Imho, not prefixing keys passed into setParams should be fine? Overwrite an existing header: no problem... it's apparently the developer's choice.

**Comment by Korijn** [comment]
Or provide an option to toggle auto prefixing of params?

**Comment by rnicholus** [comment]
I think params should always be prefixed. I can see allowing creation of any headers via a `setCustomHeaders` API method for the Azure module though.

**Comment by Korijn** [comment]
:+1:

**Comment by Korijn** [comment]
I went ahead and created a pull request, as I'm eager to start using the validation mechanism provided by Content-MD5.
