### ISSUE TITLE
iPad broswing and uploading doesn't work

### ISSUE THREAD

**Issue by yairEO** [FineUploader/fine-uploader#1216]
Tested with my iPad 3, on your demos page. I get to browse my files and when I choose a file, it eventually does nothing. It actually doesn't work with dropzonejs also, so I don't know if it's my specific iPad or what...I am merely reporting this issue.

iOS6.0.1 (10A523)
Model - MD511LL

**Comment by kapouer** [comment]
Reproduced with the fine-uploader jquery plugin 3.5.2 in epiphany 3.18 (which embeds webkitgtk).

**Comment by rnicholus** [comment]
That build of Fine Uploader is ancient. I'm not aware of any such issue with the current version.

**Comment by kapouer** [comment]
Did i say 3.5.2 ? I meant 5.3.2 of course !

**Comment by rnicholus** [comment]
What version of iOS?

**Comment by kapouer** [comment]
Linux ! debian/stretch gnome 3.18 / epiphany 3.18.
It seems to be a well known bug in webkit, see
https://github.com/jrburke/requirejs/commit/d09afa77cc956ae5062a76350bd4db6302c7e873
and
https://bugs.webkit.org/show_bug.cgi?id=49739

**Comment by rnicholus** [comment]
Ah, I see. Thanks for the report!

**Comment by kapouer** [comment]
Debugging it, actually that is not caused by "use strict". It's caused by
`container.innerHTML = templateHtml.template`
where container is null.
Instead of writing "container is null" the error message is " Attempted to assign to readonly property." which lead to another problem.

**Comment by kapouer** [comment]
ha damn, it was me passing `button` option instead of `element`. Sorry for the noise.

**Comment by rnicholus** [comment]
No problemo
