### ISSUE TITLE
Huawei P6 stock browser

### ISSUE THREAD

**Issue by bjornbos** [FineUploader/fine-uploader#1247]
I got a bug report from a customer with a Huawei P6 phone with Android 4.4.2 saying the upload feature does not work on the stock browser, but does work on the Chrome browser.

We have tried the stock browser on a Galaxy S4 with Android 4.4.2, and here the upload works fine.

Since we don't have a Huawei P6 available here, I was hoping someone with such a device would be able to confirm (or invalidate) this issue.

**Comment by Partho-paul** [comment]
I too faced the Same issue with Huwaie mate 9 stock browser..
File picker window' opens fine, but after selecting the file, the file picker closes but nothing happens (no upload start).

![uploadissue](https://user-images.githubusercontent.com/20564444/28006050-303bb2b4-656b-11e7-8b09-a200ad8e13d7.jpg)

![huwaie mate 9](https://user-images.githubusercontent.com/20564444/28006127-97f36ece-656b-11e7-8b7a-c3a950f23d55.jpg)
