### ISSUE TITLE
Upload button click - on Firefox: must click more times to trigger it

### ISSUE THREAD

**Issue by firepol** [FineUploader/fine-uploader#1248]
Hi, using fine uploader 5.0.2, I had this problem myself during the development (with 5.0.1, then updated but still had the same problem, I tried also version 4.4, same problem), then it disappeared (don't know what could have been the problem). Now I have a Form in production and somebody reported the same exact problem I had, which is:

Windows 7, Firefox 30, when clicking the "Upload" button (the one to browse for a file to upload) in Firefox, nothing happens, when clicked again, nothing happens. If clicked multiple times (like 10 times) very fast, then the "Browse" dialog appears. Sometimes it works already on the 2nd click. But when the bug occurs, the problem is that the "Browse" dialog doesn't appear on the 1st click as it should.

Unluckily I can't reproduce it anymore on my computer (to me it works perfectly with all browsers), but I went to a colleague of mine, on her Firefox, when I try I exactly get this buggy behavior.

This is the online contest with the form: https://www.i-am.ch/de-ch/home/komplimente-karussell.aspx (you have to click the checkbox, go next, the page with all contact details doesn't save anything, so you can enter test data, then next. the Group screen allows to upload a picture and there you can see the problem). Nothing is saved unless you go next next till the preview and submit the compliment. So to test this it's enough you arrive at the Group screen. Or in the scripts console, run this command: sequence.next() (this will go to the next screen, skipping the validation).

Probably you will try it and it will work for you. If not, then you reproduced the bug ;) You can see the javascript directly inline in the same page when you check the source code.

The competition itself has also several javascripts for the screen animations, checkbox styling etc. and there are other javascripts as well.

With Chrome and IE 11 it works perfectly. This time Firefox is the browser giving issues. I will appreciate if you can have a look at this, as other Firefox users may have the same issue. As said I can't reproduce this myself, but maybe you have better testing tools or you can see in the javascript if I did a mistake or a not-proper implementation and suggest an improvement (or maybe it's a little bug in fineuploader)... THANK YOU.

**Comment by rquast** [comment]
Just a note if it is of any use to anyone else in future.. I have this issue on firefox 49.0.2 for mac too. Using FineUploaderBasic like this..

```
this.fu = new qq.FineUploaderBasic({
      button: this.file_upload_button,
```

No problems on any other platform/browser.
