### ISSUE TITLE
S3-specific Feature: Preserving empty directories

### ISSUE THREAD

**Issue by phwh** [FineUploader/fine-uploader#1266]
At the moment, when uploading folders with subfolders to S3, empty folders get lost.

This is because S3 does not have a directory or folder concept. There are only "Keys" which are best comparable to files. The folder structure displayed by visual tools is just derived from the key's path.

Because of this, when uploading to S3 with Fineuploader, only folders which contain files are preserved. Empty folders disappear.

But there are use cases (for example backups) that rely on keeping the directory structure intact.

Fortunately, there is a workaround which is also used by the S3 console:
In the Amazon S3 Web Console there is the possibility to create a folder by clicking on a button. What the console does is this: It creates an empty file (0 bytes) that is named like the folder and ends with a slash.

Example:
Let's assume, we have two files in our bucket:

```
testfolder/file-a.txt
testfolder/file-b.txt
```

Now we open the folder `testfolder` with the web console and click "create folder". We name it `another-folder`.

This leaves us with 3 keys in our bucket:

```
Key("testfolder/file-a.txt")
Key("testfolder/file-b.txt")
Key("testfolder/another-folder/")  <-- Name ends with a slash and the key's size is 0 bytes
```

It would be great to have an option in Fineuploader which creates this type of key for every directory it encounters during the upload.

**Comment by vladgolubev** [comment]
@rnicholus just stumbled upon this issue.
Since it's 2 years after, is the browser situation better now and it's worth implementiong?

**Comment by rnicholus** [comment]
No, the web specification tied to this feature has been deprecated, so browser support is forever limited to Chrome.
