### ISSUE TITLE
iOS8 GM file input element does not allow files to be read client-side or uploaded to server

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#1284]
This is a serious bug that prevents any sort of file uploads in iOS8 Safari.  There is no known workaround.  Below is the content of the bug report I filed with Apple.

> Summary:
> It seems like there is some issue with access to the files associated with an `<input type="file">` element.
> 
> A few big issues:
> 1. FileReader can't seem to read any files associated with a `<input type="file">`.
> 1. URL.createObjectURL with a file associated with the <input type="file"> element returns an object URL that has no content when loaded.  
> 2. If files are uploaded to a server, even via a simple multipart-encoded form submit, no actual file bytes are sent with the request.
> 
> None of these issues occurs in Chrome on iOS8, only Safari.
> 
> Steps to Reproduce:
> 1. Create a simple form with a file input and a submit button
> 2. Create a simple PHP server that handles file uploads via a multipart encoded POST request.
> 3. Load the page, select a file, press submit
> 
> Expected Results:
> File is saved to the server.
> 
> Actual Results:
> Either an empty file is saved to the server, or the page loading indicator spins forever after clicking submit due to the lack of file bytes included in the request by Safari.
> 
> Version:
> 8.0 (12A365)
> 
> Configuration:
> iPad

**Comment by jkodroff** [comment]
@rnicholus What's your feel on the issues with iOS8?  Have they been largely resolved with 8.latest, or are they still present?

**Comment by rnicholus** [comment]
This particular issue was resolved in iOS 8.0.1.
