### ISSUE TITLE
Create Release Notes

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/fine-uploader#1294]
Release notes should be generated and pinned to the tag/release in GitHub. The release notes are aimed towards the end-user and should avoid specific technical lingo (referring to particular objects or functions). Release notes should NOT show specific commits. Release notes should show an overview of issues that have been closed. 

Note that this is different from the Changelog (#1295).

**Comment by rnicholus** [comment]
I don't think there is a pressing need to auto-generate these. The current practice of writing up a blog post explaining the new release is probably sufficient. We could (and arguably should) include a list of changes in the release section of the GitHub project as well though.
