### ISSUE TITLE
Treat any `20x` response as success, instead of just `200`

### ISSUE THREAD

**Issue by vikynandha** [FineUploader/fine-uploader#1314]
There are cases where the response could be not `200`, but is a valid HTTP status code that indicates success. For example, if the server is *RESTful*, it would return `201` ([Resource Created](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.2.2)).

In general, the logic to detect success response could be more lenient, may be something like [jQuery](https://github.com/jquery/jquery/blob/master/src/ajax.js#L680):

```.js
isSuccess = status >= 200 && status < 300 || status === 304
```

**Comment by rnicholus** [comment]
5.2.0-4 in the develop branch will accept 200-204 for all upload and generic POST requests.  This will be part of the upcoming 5.2.0 release.

**Comment by rnicholus** [comment]
5.2.0-5 adds the same support to PATCH and PUT requests.

**Comment by vikynandha** [comment]
That's awesome! Thanks.
