### ISSUE TITLE
isErrorUploadResponse: successful response without success flag shouldn't fail

### ISSUE THREAD

**Issue by mrjoelkemp** [FineUploader/fine-uploader#1325]
I have a successful xhr response that doesn't have the `success` property and is still marked as an erroneous response – triggering the uploader's `onError` callback. I would expect this response to succeed and trigger `onComplete` or `onAllComplete`.

Should this line https://github.com/FineUploader/fine-uploader/blob/178dcbf35a652c0a7505eb030c8c6a6005670dab/client/js/traditional/traditional.xhr.upload.handler.js#L79 change: `!response.success` to be `response.success === false`?

The XHR: 

![image](https://cloud.githubusercontent.com/assets/865203/5304327/b6fe35ee-7bbf-11e4-929c-dcc086698c43.png)

The `response`:

![image](https://cloud.githubusercontent.com/assets/865203/5304321/a368904c-7bbf-11e4-9722-25d92ebf6f1a.png)

**Comment by rnicholus** [comment]
Moving this into the 6.0 milestone. With Microsoft dropping support for IE9 and older, I think it makes sense to focus even more on modern browsers going forward. Plan is to treat 2xx as successful, unless the JSON response indicates failure with `success: false`, just in case any existing integrations utilize this approach, or if integrators want to always return 200 but use the response to indicate failure for easier cross-browser support. IE9 and older will have to always return a 200 but can signal failure with a success property with a value of false in the JSON response.

**Comment by rnicholus** [comment]
Working on this next as part of 6.0.0.

**Comment by rnicholus** [comment]
This is complete and being staged on the release/6.0.0 branch.

**Comment by DaveStein** [comment]
:+1:

**Comment by rnicholus** [comment]
Finally getting around to this in #1917. I expect this to be a non-breaking change (5.16.0) with the addition of a new option: `request.requireSuccessJson`.
