### ISSUE TITLE
Lazily bind forms for form support

### ISSUE THREAD

**Issue by mrjoelkemp** [FineUploader/fine-uploader#1334]
I have a use case where one popup shows the upload button (instantiating an uploader) and after submission, another popup renders the submitted image along with a form (for annotating the image). The form does not exist at the time of uploader creation, but I would still like to leverage form support (since the submitted image is to be uploaded along with the form data).

I know that the form is expected to be part of the uploader's initialization options, but is there currently a way to bind to a form after instantiation?

If there is no current way of doing this, do you see value in lazy binding? I'm thinking of something like a `uploader.bind($form)` as the public api. If a form element is supplied in the options, fineuploader would then call `bind` internally.

**Comment by rnicholus** [comment]
Looking into this now as part of 5.3.0 work.

**Comment by rnicholus** [comment]
This is complete in the develop branch - 5.3.0-7.

**Comment by mrjoelkemp** [comment]
Awesome work! Thanks.
