### ISSUE TITLE
(re)move gradle, intellij-specific files, and built-in java server

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/fine-uploader#1340]
99.99% of our development scripts are in javascript/nodejs, and the remaining *0.01% is in java/groovy. I believe this should change. *(actually, according to GitHub it is 3.2% java)

I think the java-centric stuff should be moved into its own project. This project could pull down the latest version of fine-uploader and allow testing from there for those who prefer that stack.

I understand that this server is used by some for development and testing purposes, but I think it should be moved out of the sources repo, and instead moved into its own project. The best likely place would be -- like `node-fine-uploader-server` -- its own project, but I guess the Fine Uploader server repo would work too.

I think, if we did want to include a server for manual testing, we'd want to be able to define it in our `devDependencies`. This also means if Fine Uploader were publish to say `npm`, that integrators would not receive our development dependencies and a bunch of `gradle` and `java` crap that they're unable to run (leading to increased install time) unless they chose to.

Gradle is also redundant (the `grunt` and `npm` are already included -- why have even more build systems?), and it generates a lot of useless crap in our source tree.

This overall cleanup will not only result in a few saved kBs, but also less mental-clock-cycles spent ignoring these files repeatedly.

**Comment by rnicholus** [comment]
I'm going to remove all the Java stuff in 5.2 and replace it with PHP.  This seems like the best choice, since PHP is likely the most common server-side language for integrators.

**Comment by rnicholus** [comment]
The develop branch is now Java-free!  No more IntelliJ!  Yay!
