### ISSUE TITLE
Fine Uploader: Add class to upload button after itemLimit reached

### ISSUE THREAD

**Issue by ajschmaltz** [FineUploader/fine-uploader#1341]
Our UI should be aware of this limit being reached and also when it reverts.  Adding a class of qq-limit-reached would be great, right?  I know we alert when we attempt to exceed the limit, but adding a class would allow hiding the upload button, disabling it, showing a message, etc...

**Comment by rnicholus** [comment]
Once #1301 is complete, you will be able to more easily react to a specific validation error. That should address this case, so I'm closing as a duplicate.
