### ISSUE TITLE
Uploading via Fastly/

### ISSUE THREAD

**Issue by vinnyglennon** [FineUploader/fine-uploader#1342]
"An example of a CDN that should work fine is fastly"

Do you have an example of the options needed for 5.1? Putting in an S3 bucket name is fine, as per doc, but how do I put the uploader at Fastly?
Best,
Vinny

**Comment by rnicholus** [comment]
First off, Fastly (or any other CDN) will need to be configured to point at an S3 endpoint.

After you setup your fastly account, make sure you set Fine Uploader S3's [`request.endpoint`](http://docs.fineuploader.com/branch/master/api/options-s3.html#request.endpoint) to your fastly endpoint, and the [`objectProperties.bucket`](http://docs.fineuploader.com/branch/master/api/options-s3.html#objectProperties.bucket) to your bucket (or a function that can dynamically determine the bucket name per file).

The related changes to Fine Uploader should also allow uploads to S3-like endpoints, that is, endpoints that use the S3 API but are not actually S3.  Google Cloud Storage offers an S3 compatibility layer, which may work perfectly with these changes #1158.
