### ISSUE TITLE
Initial File List (Session) Order

### ISSUE THREAD

**Issue by woozyking** [FineUploader/fine-uploader#1347]
As it currently stands, it seems that it just sorts the initial file list by filename. However some other options such as order by upload timestamp, file size, are also logical and common enough to support various use cases.

**Comment by rnicholus** [comment]
The initial file list is an array returned by your server.  The files will appear in the order represented by the array.  If you'd like a different order, this can be accomplished by adjusting the order of the items in the array returned by your server.  Another option is to implement a widget in your UI that sorts the way the items appear based on whatever characteristics are most important to your project.  This would involve moving around the list items in Fine Uploader UI's file list.  Or, you can implement your own UI entirely using Fine Uploader's API.

If there is an issue specifically with the way Fine Uploader interprets the initial file from your server, we can discuss further and re-open this if necessary.

**Comment by woozyking** [comment]
@rnicholus that makes perfect sense.

**Comment by abhimanyu-ahex** [comment]
@rnicholus 
I am using fine uploader plugin to upload images. The image upload is working fine. What I am trying to do is when the page is refreshed after image upload fine uploader should show previously uploaded images.

Here is my code..

$('#accordion').on('shown.bs.collapse', function () {
    activeShopId1 = $(".collapse.in").attr("id");

    $('#' + activeShopId1 + '  #fine-uploader-gallery' + '.single-image').fineUploader({
        template: 'qq-template-gallery',
        request: {
            endpoint: 'upload_internal_image'
        },

        validation: {
            allowedExtensions: ['jpeg', 'jpg', 'gif', 'png'],
            itemLimit: 1
        },
        messages: {
        tooManyItemsError: 'You can only add 1 image'
            },
        deleteFile: {
            enabled: true,
            forceConfirm: true,
            endpoint: 'delete_internal_image'
        },
        callbacks: {
            onSubmit: function (id, fileName) {
                this.setParams({shop_id: shopId4Map});
            },
        },
    });

})
