### ISSUE TITLE
Meteor.js support?

### ISSUE THREAD

**Issue by morgunder** [FineUploader/fine-uploader#1350]
I'm learning meteor and was looking at converting site that uses fine uploader over to this platform.  has anyone made a meteor package for fine-uploader ?

**Comment by rnicholus** [comment]
It's likely that someone has, but I'm not aware of a specific implementation.  Is there something in particular you're struggling with?

**Comment by rnicholus** [comment]
I'm going to close this for now, but if you and other comment on specific integration issues with meteor, I'd be happy to consider re-opening.

**Comment by ajschmaltz** [comment]
Ok, I pulled an all nighter and am banging my head against the wall with the client-side only integration.  (https://fineuploader-s3-client-demo.s3.amazonaws.com/index.html).  Has anyone else had success?  I've been debugging why I get an error with the signature response yes I have good credentials...  8 hours and counting ...

**Comment by ajschmaltz** [comment]
The most trouble I'm having personally is implementing the nodejs server s3 example.  It requires express which seems to be incompatible with Meteor.

**Comment by aramk** [comment]
I've put together an example here https://github.com/aramk/fine-uploader-meteor-demo
