### ISSUE TITLE
setItemLimit API not working

### ISSUE THREAD

**Issue by nskarl** [FineUploader/fine-uploader#1351]
i don't know why, but it still not working
but I solved the problem through "reset" API

in JS: 
var photoCount = 5;
$('#UploadImages').fineUploader('reset', photoCount);

in fineUploader.js:
reset: function(newItemLimit) {
...
this._currentItemLimit = newItemLimit;
...
}

i hope in new versions setItemLimit will working :)

**Comment by rnicholus** [comment]
What isn't working?  Where is your code that isn't working?  What version are you using?

**Comment by nskarl** [comment]
version 5.1.3

just try that:

setItemLimit: function(newItemLimit) {
	this._currentItemLimit = newItemLimit;
	this.log(this._currentItemLimit);
}

and you will see in log that this._currentItemLimit not changing

**Comment by nskarl** [comment]
5.1.3

code: $('#UploadImages').fineUploader('setItemLimit', 10);

if do that:
setItemLimit: function(newItemLimit) {
            this._currentItemLimit = newItemLimit;
			this.log(this._currentItemLimit);
        },

in log it will return 10
but its not working, global this._currentItemLimit not set to 10

sorry for my English (

**Comment by rnicholus** [comment]
The `setItemLimit` API method seems to work fine.  I just tested to verify (and there are unit tests as well).  There must be some issue with your code that you are not showing here, or perhaps you have made changes to Fine Uploader.  I would suggest setting a breakpoint to see what the value of `this` is in that method, and go from there.

**Comment by nskarl** [comment]
all my code i show - $('#UploadImages').fineUploader('setItemLimit', 10);
no changes in Fine Uploader
but it works correctly through Reset, why?
