### ISSUE TITLE
Admin for Fine-uploader php

### ISSUE THREAD

**Issue by nyala1** [FineUploader/fine-uploader#1352]
Apologies if this seems a ridiculous question, but after successfully, and easily, installing fine-uploader php, there seems to be no /admin folder or page available. I imagine that I am missing something really easy here. Can someone point me in the right direction please?

Documentation says, "...Visit /admin in your browser and enter the default username and password (user: admin, password: changeit) to secure the site."

(I am assuming,  that this is not a reference to Wordpress Admin as I am not using wordpress)

Thanks in advance.

**Comment by rnicholus** [comment]
Hi there.  For now, I think the best place to open up a Fine Uploader PHP issue is [in the fine-uploader-php-docs repository's issue tracker](https://github.com/FineUploader/fine-uploader-php-docs/issues/new).

**Comment by nyala1** [comment]
Cheers, have done so now.
