### ISSUE TITLE
the propiety itemLimit, that limit the uploads to the server dont working for me

### ISSUE THREAD

**Issue by jpasosa** [FineUploader/fine-uploader#1357]
I use this propiety in a project, using <a href="https://github.com/scoumbourdis/image-crud">image_crud</a> and dont respond. I want to know if its possible force this Limit in any way . . .
I edit this item directly in the library and in some file that call the library fine-uploader and dont respond.

I just need to limit the upload images.

Sory for my english, im from Argentina.

**Comment by rnicholus** [comment]
Hello there.  We only handle bug reports and feature requests in this issue tracker.  If you are looking for help solving a problem involving Fine Uploader, please post in Stackoverflow under the fine-uploader tag.  Also be sure to explain your exact problem clearly and include code to illustrate your problem.  Thanks.
