### ISSUE TITLE
Thumbnail preview outside template?

### ISSUE THREAD

**Issue by firepol** [FineUploader/fine-uploader#1358]
Hi,

in this document http://docs.fineuploader.com/branch/master/features/thumbnails.html I read "Fine Uploader will attempt to render the path in the template’s <img> element".

Now I have a complex form and I need the thumbnail img element to be outside of the fine uploader template (see I use bootstrap, I have a column on the left, with the fine uploader selector, but I want the preview to appear in a separate column, on the right).

Is this possible? How to achieve this?

Thank you

**Comment by rnicholus** [comment]
You can generate thumbnails at will, for any `<img>` or `<canvas>` via [the `drawThumbnail` API method](http://docs.fineuploader.com/branch/master/api/methods.html#drawThumbnail).

**Comment by firepol** [comment]
Can you be a bit more specific? I'm using fine uploader jquery plugin. My code looks like this:
```
        $('#file-upload').fineUploader({
            template: "qq-simple-thumbnails-template",
            thumbnails: {
                placeholders: {
                    waitingPath: "/scripts/js/fineuploader/placeholders/waiting-generic.png",
                    notAvailablePath: "/scripts/js/fineuploader/placeholders/upload-success.png"
                }
            },
            request: {
                endpoint: '/Handlers/FileUpload.ashx'
            },
            multiple: false,
            validation: {
                allowedExtensions: allowed
            },
            text: {
                failUpload: failedTxt
            }
        }).on("complete", function (event, id, xhr, isError) {
            drawThumbnail(id, $('#preview'), 400, true);
        });
```
Caught error in Fine Uploader jQuery event handler: drawThumbnail is not a function.

How/where exactly should I use the drawThumbnail function?

**Comment by firepol** [comment]
Never mind, got it working (googled fine uploader drawThumbnail and found some stackoverflow questions/answers that helped). This did the job:
```
.on('submitted', function (event, id, filename) {
            console.log('On submitted');
            console.log('Calling draw thumbnail on id: ' + id + ' with filename: ' + filename);
            $(this).fineUploader('drawThumbnail', id, $('#preview'), 400, false);
        })
```

I had to call the function in a different way...

Also, the last parameter (fromServer) had to be false. I was wrongly thinking that the thumbnail was coming from the server (as I have a handler) but it's not the case, it's all done client side, that explains why with some old browsers the preview doesn't work ;)

Cheers

**Comment by rnicholus** [comment]
Glad you were abel to get this working.  May I suggest that you avoid using the jQuery plug-in wrapper?  It really doesn't add any value, and just clutters up your code.  

Your code sans that wrapper looks like this:

```javascript
$(document).ready(function () {
       var uploader = new qq.FineUploader({
            template: "qq-simple-thumbnails-template",
            element: document.getElementById("file-upload"),
            thumbnails: {
                placeholders: {
                    waitingPath: "/scripts/js/fineuploader/placeholders/waiting-generic.png",
                    notAvailablePath: "/scripts/js/fineuploader/placeholders/upload-success.png"
                }
            },
            request: {
                endpoint: '/Handlers/FileUpload.ashx'
            },
            multiple: false,
            validation: {
                allowedExtensions: ['jpg', 'jpeg', 'png']
            },
            text: {
                failUpload: 'Error'
            },
            callbacks: {
                onComplete: function(id, fileName, response) {
                    this.drawThumbnail(id, document.getElementById("preview"), 400);
                }
            }
        });
});
```


..also, the last parameter to `drawThumbnail` can be omitted entirely instead of explicitly passing `false`.
