### ISSUE TITLE
Method request: Start single file

### ISSUE THREAD

**Issue by rainbowdash28** [FineUploader/fine-uploader#1373]
I want to request a new method to start single files, the reason is quite simple:

So I set "autoUpload" to "false" and add individual endpoints for each file being submitted simply using the "setEndpoint" method.

But now I need to fire the upload process for this single file id. As far as I can see sadly "uploadStoredFiles ()" is the only method to start uploading - but this will start all queued uploads, including freshly added ones possibly even those with yet-to-be-set endpoints.

So my idea is either to extend the existing method "continueUpload (id)" to also work on queued uploads, or to just extend "uploadStoredFiles" to take an argument for the file id.

Or maybe someone could point me to how to achieve this with existing methods.
There is a solution I can think of off the top of my head, this would however imply the use of jQuery promises on the validation process and I'd need to keep "autoUpload" "true".

I think my suggestion'd work way better also it doesn't needlessly involve jQuery promises.

Thanks in advance,
Christian.

**Comment by rnicholus** [comment]
Why not just set the endpoint, per file, in the onSubmit callback handler?

**Comment by rainbowdash28** [comment]
Hey, thanks for the quick reply :)

The problem is - I forgot to mention this before - my endpoints are set by requesting them from the server via Ajax, while starting the upload.

**Comment by rnicholus** [comment]
The onSubmit callback allows you to return a promise.  So, you can return a promise, make your call, update the endpoint, and then resolve the promise.
