### ISSUE TITLE
Disallowed File Types

### ISSUE THREAD

**Issue by tjsail33** [FineUploader/fine-uploader#1374]
Currently, FineUploader has an option to allow certain mime types, but I am looking for a way to allow all types EXCEPT for a few. Is this currently possible, and is this a validation option that can be added?

**Comment by rnicholus** [comment]
This was [answered on Stackoverflow](http://stackoverflow.com/questions/18412787/restrictions-in-file-types-in-fineuploader-3-7-0/18412974#18412974) a while back.  The code in that example can perhaps be a bit simpler by making use of [the `qq.getExtensions` utility method](http://docs.fineuploader.com/branch/master/api/qq.html#qq.getextension).
