### ISSUE TITLE
S3 JQuery Fineuploader - extraButtons element (when specified using class) only binds to the first element

### ISSUE THREAD

**Issue by thomas83** [FineUploader/fine-uploader#1375]
I'd like to file an issue.

I'm using S3 JQuery Fineuploader (Version 5.1.3)

I've created a JS Fiddle:
http://jsfiddle.net/beamstyle_thomas/fyp5dqwt/3/

The symptom here, here, I specified the following as my options:
            
            extraButtons: [{
                element: $('.file-trigger')
            }]

However, when I have several file-trigger class elements in my DOM, only the first one gets converted into a fine-uploader button.  The rest stays as-is.

<div class="file-trigger" style="width:100px;height:100px;background-color:#9999ff;">Drop Zone</div>
<div class="file-trigger" style="width:100px;height:100px;background-color:#9999ff;">Drop Zone</div>
<div class="file-trigger" style="width:100px;height:100px;background-color:#9999ff;">Drop Zone</div>

If possible, please kindly take a look into this issue.

Thanks!

Cheers,
Thomas

**Comment by thomas83** [comment]
This problem still happens even on the non-Jquery version.  I've ported over to the non-JQuery version as per Ray's advice.

**Comment by rnicholus** [comment]
Please show your code without the jquery wrapper as well

**Comment by thomas83** [comment]
Hi Ray,

I've created a forked fiddle, here it is:
https://jsfiddle.net/beamstyle_thomas/heabz1bs/

Thanks!

**Comment by rnicholus** [comment]
You are explicitly only passing one extra button element in your fiddle, so I don't see any issue there.

**Comment by thomas83** [comment]
Oh, I have 3 DIVs with class="file-trigger".

In my JS script, I did $('.file-trigger').  So I guess that should query all 3 DIVs correct?  But only one gets captured.

Perhaps, did I misunderstand anything about its usage?

Cheers,
Thomas

**Comment by rnicholus** [comment]
You are explicitly accessing only the first element returned by the jquery selector in your fiddle.  That is what $(...)[0] does.

**Comment by thomas83** [comment]
Ah yes you're right.  However, it returns JS error if I remove the [0].

So I can't do this in a bundle for some reason.

**Comment by rnicholus** [comment]
Yes, of course it does.  You cannot pass a jquery object into fine uploader without the jquery wrapper.  You'll need to pass a separate extra button array item for each actual button element.

**Comment by thomas83** [comment]
Ah, I think I got what you mean.  So you mean I cannot expect FineUploader to be iterating over my jquery object on either versions.  And I would have to first build something like this, and t:


var myExtraButtons = [
                {
                    element: $('.file-trigger')[0]
                },
                {
                    element: $('.file-trigger')[1]
                }
            ];


and then passing this into the FindUploader options:

FineUploaderS3({
            ...
            extraButtons: myExtraButtons,
            ...
});


It seems like the above is working for me.  But just to make sure, did I get your point correctly?

Cheers,
Thomas

**Comment by rnicholus** [comment]
Yes, that is correct.  




No real benefit to using jquery if you are only selecting elements.  It just gets in the way, as you can see here.  If you'd like to get more comfortable with the web and JavaScript outside of jquery, for instances such as this, have a look at my blog on the subject at http://blog.garstasio.com/you-dont-need-jquery/.

**Comment by thomas83** [comment]
Thanks Ray!  All good now and cleared out now.  

Just one thought though, it might be nice to show an example or two on the documentation, especially for users who are using the JQuery wrapper, as they may tend to think they can simply just put in a JQuery object (of multiple elements) into that area.

Thanks again!

Cheers,
Thomas

**Comment by rnicholus** [comment]
Sure.  I'll investigate further during the workweek.

**Comment by rnicholus** [comment]
Looking again at the jQuery plugin wrapper code I wrote, only array elements that are also jQuery objects are expanded to take into account all elements that match the selector.  In all other cases, the first element that matches the selector is used, and all others are discarded.  I'll update the documentation to make this more clear.

**Comment by rnicholus** [comment]
This marks the last planned task for 5.2.0. Integration testing will begin, and once all is looking solid, 5.2.0 will be released.
