### ISSUE TITLE
Where is all.fine-uploader.js?

### ISSUE THREAD

**Issue by Mds92** [FineUploader/fine-uploader#1379]
I wanna test this library.
I've downloaded it from github, in `fine-uploader-master\test` folder I ran `test.html`.
But it has error because of can not find the following file:
`<script src="_temp/all.fine-uploader.js" type="text/javascript"></script>`

I couldn't find `all.fine-uploader.js` file in current repository.
were is `all.fine-uploader.js`?

**Comment by rnicholus** [comment]
You need to build it, or you can download one of the various versions from the home page and try it out by following the getting started guide in the documentation.

**Comment by Mds92** [comment]
So, how can I build it, Could you please post a link to describe it?

**Comment by rnicholus** [comment]
http://docs.fineuploader.com/contributing.html
