### ISSUE TITLE
File uploader issue - multiple file selection - more than 900 files from windows explorer

### ISSUE THREAD

**Issue by Manidipa** [FineUploader/fine-uploader#1380]
Hi Ray
Please check the attached image. We are trying to select 2400 files ( multiple selection for 2400 items) from windows explorer and then click on open. Nothing happens.
Please help us on this. Thanks!
![fineuploader](https://cloud.githubusercontent.com/assets/4376952/6525242/35654c2c-c429-11e4-8a02-e8da41b66ae9.jpg)

**Comment by rnicholus** [comment]
Sorry, without more information regarding how fine uploader may be at fault, there is no advice I can provide. Looks like an issue with windows at this point.
