### ISSUE TITLE
Allow for custom S3 policy error messages

### ISSUE THREAD

**Issue by studiorepublic** [FineUploader/fine-uploader#1382]
Currently there's no way to customise the error messages displayed to the user when there's an issue with the S3 policy. It would be really useful to be able to send the user a more meaningful message instead.

**Comment by rnicholus** [comment]
I'm curious as to how this would help users, since there is nothing they can do about this type of error.

**Comment by studiorepublic** [comment]
It could ask the user to report the error at a certain email address, try again later and just generally be more user-friendly.

**Comment by rnicholus** [comment]
This type of error is generally unrecoverable. We can consider making the message customizable, instead of reporting the message from S3, but I would suggest detecting the error in your code and automatically reporting it instead of relying on the user to do so.

**Comment by studiorepublic** [comment]
Implementing both would be great. How would I detect the error?

**Comment by rnicholus** [comment]
Via an `onComplete` handler. The response object will contain an `error` property w/ the message text, and a `code` property with the S3 error code.

**Comment by rnicholus** [comment]
Should be solved in #1724. If not, let me know.
