### ISSUE TITLE
Fine uploader issue - Multiple file selection - More than 900 files

### ISSUE THREAD

**Issue by Manidipa** [FineUploader/fine-uploader#1383]
Hi ray

We are able to drag and drop more than 900 file in fine uploader control from a folder. But when we select more than 900 files at a time and click open in windows explorer then files are not added in the fine uploader control. But if we select less than 900 files at a time and click open in windows explorer then files got added in the fine uploader control. Hope you understand the issue. Please provide us the solution.

Regards
Manidipa

**Comment by rnicholus** [comment]
Please see my response to all of the other duplicate cases you previously opened.
