### ISSUE TITLE
onUploadSuccess callback (S3) missing?

### ISSUE THREAD

**Issue by cj** [FineUploader/fine-uploader#1384]
Hi,

This callback `onUploadSuccess` doesn't seem to exists right now or am I missing something?  When using S3 and the `uploadSuccess endpoint` option, after the url gets called is it possible to bind a callback to access that success response?

Many thanks!

**Comment by rnicholus** [comment]
You can contribute an onComplete event handler to deal with the result of any upload attempt.

From the S3 server-side documentation:

>You can also pass any data to your Fine Uploader complete event handler, client-side, by including it in a valid JSON response to the uploadSuccess.endpoint POST request. In fact, the S3 demo server-side code on FineUploader.com is passing a signed URL to the complete handler which allows you to view the file you've uploaded.
