### ISSUE TITLE
QuotaExceededError when trying to upload file when using Safari private browsing

### ISSUE THREAD

**Issue by fschwahn** [FineUploader/fine-uploader#1395]
Hi,
one of our users is experiencing the following error:

    QuotaExceededError: DOM Exception 22: An attempt was made to add something to storage that exceeded the quota.

It happens when the user tries to upload a file which is large enough that chunking is used. This is caused by Safari private mode (see http://stackoverflow.com/questions/21159301/quotaexceedederror-dom-exception-22-an-attempt-was-made-to-add-something-to-st), but I guess it could also happen when localStorage is full for other reasons. 

You can reproduce the error like this:
1. Use Safari, enable private mode
2. Go to http://fineuploader.com/demos.html#amazon-demo
3. Upload a file large enough to use chunking (my file was 14.3 MB)
4. The upload starts, but starts hanging as soon as the first chunk has finished uploading, because `localStorage.setItem` fails.

All the best,
Fabian

**Comment by rnicholus** [comment]
Reproduced myself. We'll fix this as part of 5.2.0.

**Comment by rnicholus** [comment]
Workaround is to turn off [the `resume` feature](http://docs.fineuploader.com/branch/master/api/options.html#resume) until 5.2.0 is released if you are concerned about supporting large uploads in a Safari private browsing session.

```javascript
resume: {
   enabled: false
}
```

**Comment by fschwahn** [comment]
Thanks @rnicholus , we'll do that.

**Comment by rnicholus** [comment]
Fixed in Fine Uploader 5.2.0-22. If you'd like to try this out before the release, please let me know. I'm hoping to release 5.2. in the next few weeks, provided no issues come out of integration testing.
