### ISSUE TITLE
Thumbnails.maxCount restricting server-side thumbnails

### ISSUE THREAD

**Issue by ovlstuff** [FineUploader/fine-uploader#1397]
As per the documentation the thumbnails.maxCount UI option restrict the number of client side generated previews, our application will allow the users to add hundreds of images and we don't want to stress the user's browser generating all these previews but at the same time we want to show a thumbnail for all of them once a file has been uploaded. We tried to set the maxCount to -1 so we don't generate any preview on the client but this also restrict the display of server-side thumbnails, see code below from the processUpdateQueuedPreviewRequest function,

```
if (thumbnail) {
                if (thumbnailUrl) {
                    if (options.limits.maxThumbs && options.limits.maxThumbs <= generatedThumbnails) {
                        maybeSetDisplayNotAvailableImg(id, thumbnail);
                        generateNextQueuedPreview();
                    }
                    else {
                        if (showWaitingImg) {
                            displayWaitingImg(thumbnail);
                        }

                        return options.imageGenerator.generate(thumbnailUrl, thumbnail, spec).then(
                            function() {
                                show(thumbnail);
                                generatedThumbnails++;
                                setTimeout(generateNextQueuedPreview, options.limits.timeBetweenThumbs);
                            },

                            function() {
                                maybeSetDisplayNotAvailableImg(id, thumbnail);
                                setTimeout(generateNextQueuedPreview, options.limits.timeBetweenThumbs);
                            }
                        );
                    }
                }
```
Can a different option be created to control the number of server-side thumbnails independently of the client-side max count?

**Comment by rnicholus** [comment]
Server-returned images are nothing more than a URL which must be rendered and potentially resized in the browser. With this in mind, it's unlikely that we will add such an option. 

The current setup should prevent the browser from being continually stressed, since there is a pause between generation of previews. This pause allows other tasks to be completed, such as scrolling.

**Comment by ovlstuff** [comment]
Agree with your statements, my scenario here is that I don't want to produce any client-side preview (or maybe a small number) to avoid any stress on the browser and I can control this with the current thumbnails.maxCount option. So far so good, now I want to return a thumbnailUrl for every single file that gets uploaded, in this case the thumbnailUrl does not get rendered if the maxCount limit has been reached, so restricting client-side previews via the maxCount option also restricts the rendering of server-side thumbnails.

**Comment by rnicholus** [comment]
Yes, that is the intention of the maxCount option.

**Comment by ovlstuff** [comment]
Ok, then the documentation is a little misleading as it doesn't mention restricting the server-side generated thumbnails,

>maxCount
>Maximum number of client-side generated previews to render per Fine Uploader instance. A call to the reset method resets this value as well.

**Comment by rnicholus** [comment]
Yes, you are correct. We will adjust the docs before releasing 5.2 this week.

**Comment by ovlstuff** [comment]
Any suggestion for my issue, i.e. restricting client-side previews but not server-side ones?

**Comment by rnicholus** [comment]
You have access to the server response via an onComplete event handler. From their, you can get a handle on the thumbnailUrl and render the images however you require.

**Comment by ovlstuff** [comment]
Sounds good, thanks
