### ISSUE TITLE
addFiles bug

### ISSUE THREAD

**Issue by jardakotesovec** [FineUploader/fine-uploader#1398]
I was trying to do following 
```
        uploader.addFiles([event.target]);
```
And end up with:
```
Uncaught TypeError: Cannot read property '_handleNewFile' of undefined
```

I think problem is in this code:
```
                        qq.each(files, function(idx, file) {
                            this._handleNewFile(file, batchId, verifiedFiles);
                        });
```
Because this is not defined inside each.

So I tried passing FileList which also should be valid input:
```
        uploader.addFiles([event.target.files]);
```

But also does not like it:
```
[Fine Uploader 5.2.0] [object FileList] is not a valid file container!  Ignoring!
```

And finally using worked ok:
```
uploader.addFiles([event.target.files[0]]);
```

But two previous inputs also should be valid..  or Am I missing something?
Using latest FineUploaderBasic 5.2.0

**Comment by rnicholus** [comment]
It looks like you are trying to pass in an array of an array, which is definitely not valid.

**Comment by jardakotesovec** [comment]
Thanks for response.

In first case `uploader.addFiles([event.target]);` target is not array: 

```
console.log(event.target)
<input type=​"file" data-reactid=​".e.1.0.0.2.0.2.1.0.0.1.1">​
```

In second case `uploader.addFiles([event.target.files]);` files is also not array, but FileList object:
```
console.log(event.target.files)
FileList {0: File, length: 1, item: function}
```

And according to docs input should be array of inputs or fileLists or ... .

**Comment by rnicholus** [comment]
A `FileList` is a pseudo-array, and an array of an array is not an acceptable value for this method. The docs do seem to suggest that this is acceptable, but that is a typo. I'll update the docs to clarify how `FileList` should be passed.

It does look like there is one bug here - file input elements cannot be passed into `addFiles`. This is an uncovered area of our unit tests at the moment (passing in file inputs). I'll fix this an release a hotfix release probably today or tomorrow at the latest.

**Comment by jardakotesovec** [comment]
Ok, makes sense. Thanks!

**Comment by rnicholus** [comment]
Just to clarify, should pass in the raw FileList by itself, not inside of another array. I'll fix the issue with passing in an <input type="file"> next.

**Comment by rnicholus** [comment]
Note that this bug only applies to `<input type="file">` elements passed into `addFiles` on browsers with File API support. Older browsers are unaffected. It looks like this particular issue has been in place since 5.1.0 and was introduced in eb5b396aed127f2c4285e0a2d05eb10345a07b1d#diff-a0a0b3463657f89b811492f709d2c893 during work on #1198.

**Comment by rnicholus** [comment]
Fixed in 5.2.1 (just released). I'll update the blog, download page, and npm shortly.

**Comment by rnicholus** [comment]
Everything has been updated. Thanks for the report.

**Comment by jardakotesovec** [comment]
Impressed with such support :+1: .

**Comment by rnicholus** [comment]
We aim to please. I added a unit test for this code path as well to hopefully prevent this from happening again.
