### ISSUE TITLE
Feature request: Prevent sleep while upload is in progress

### ISSUE THREAD

**Issue by jdq22** [FineUploader/fine-uploader#1405]
Hello,

I was wondering if y'all were considering implementing something that would prevent browser sleep while an upload is in progress. This (https://github.com/ivanmaeder/computer-sleep) works in Chrome and Firefox and seems simple by looking at the codebase.

We've already integrated this alongside FineUploader and haven't come across any problems yet.

**Comment by rnicholus** [comment]
This is the first such request we have received. I don't anticipate integrating anything like this into Fine Uploader at the moment. The library is already quite complex and diverse in its support of workflows and endpoints. The library you referenced seems interesting, and I will certainly keep it in mind should someone ask about this type of support in the future.

**Comment by jdq22** [comment]
Thanks. We've had several customers request it, but our use case is usually one user doing 100GB up a day.

**Comment by feltnerm** [comment]
That library seems like a dirty hack. It's really smart, but still ... do we really want to make a request to some random GitHub URL and *trust* that their video is indeed muted and invisible? I wouldn't ...

Maybe [service workers](http://www.w3.org/TR/service-workers/) would fit better here ... maybe not.
