### ISSUE TITLE
Browser crashed

### ISSUE THREAD

**Issue by lavinachitara** [FineUploader/fine-uploader#1408]
Browser get crashed while trying to upload a small file in fineuploader demo site(http://fineuploader.com/demos). Tried in all browsers(chrome/IE/firefox) same issue is coming. Even I added this plugin in my website, my site also throwing the same issue when I try to upload any file using this extension, it closes browser. 
Help me to track this issue, it is plugin issue or something else.

**Comment by feltnerm** [comment]
What issue? What plugin? What extension? Please provide steps to reproduce.

**Comment by rnicholus** [comment]
You haven't provided any information here that would help us to reproduce or even look into the issue. Useful information would include the browser, version of fine uploader, properties of the file causing the issue, or any steps at all required to reproduce.

It does indeed sound like a browser extension is causing your problem. I suggest you start removing or disabling extensions until you locate the offending extension.
