### ISSUE TITLE
Control Cache-Control header in setUploadHeaders

### ISSUE THREAD

**Issue by antongorodezkiy** [FineUploader/fine-uploader#1410]
Hello,

I have an issue with Cache-Control header when trying upload directly to Vimeo:

Here is the error from Chrome console:
XMLHttpRequest cannot load http://1511655198.cloud.vimeo.com/upload?ticket_id=69d.......ae231c. Request header field Cache-Control is not allowed by Access-Control-Allow-Headers.

If I comment the line with `Cache-Control` header ( https://github.com/FineUploader/fine-uploader/blob/master/client/js/traditional/traditional.xhr.upload.handler.js#L176 ) the uploader works fine.

Here are headers from the Vimeo's response:

```
Access-Control-Allow-Headers:Content-Type, Content-Range,  X-Requested-With
Access-Control-Allow-Methods:POST, PUT, GET, OPTIONS
Access-Control-Allow-Origin:*
Connection:keep-alive
Content-Type:text/html
Date:Tue, 12 May 2015 19:08:05 GMT
Server:Vimeo/1.0
Transfer-Encoding:chunked
```

Is there a way to override this behaviour?

**Comment by rnicholus** [comment]
This header was added to overcome a bug in introduced by Apple into iOS6 browsers. See #396 for more details.

I suppose this can be changed to only append the header for POST, GET, (and probably DELETE requests). I'd have to give that some thought though.

**Comment by rnicholus** [comment]
I don't anticipate changing this. The best course of action is to ask Vimeo to add `Cache-Control` to the `Access-Control-Allow-Headers` preflight response.
