### ISSUE TITLE
How to make a progress bar run or move ?

### ISSUE THREAD

**Issue by xlkit456852** [FineUploader/fine-uploader#1414]
I added progress event ,and I want to see the progress or persentage change when the file is uploading . But i found that the progress bar didn't move and it immediately change to 100% and finished . But I want to see the progress . Here is my js and i've add the UI template:

$('#jquery-wrapped-fine-uploader').fineUploader({
            request: {
                endpoint: wap_url+'/rules/handleupload'
            },
            debug: true,
            acceptFiles:"image/;capture=camera",
            camera:{
                ios:true
            }
        }).on('progress', function (event, id, filename, uploadedBytes, totalBytes) {
            alert('uploadedBytes: ' + uploadedBytes + '\n totalBytes: ' + totalBytes);
            if (uploadedBytes < totalBytes) {
                progress = '"' + fileName + '" uploading...  ' + Math.round(uploadedBytes /
                        totalBytes * 100) + '%';
                $('#qq-progress-bar').html(progress);
            }
            else {
                $('#qq-progress-bar').html('saving');
            }
        }).on('complete', function(event, id, fileName, responseJSON) {
            if (responseJSON.success) {
                $(this).append('<img src="'+web_path+responseJSON.target+'" alt="' + fileName + '">');
            }
        });

**Comment by rnicholus** [comment]
Before you open up any more issues, please read https://github.com/FineUploader/fine-uploader/blob/master/CONTRIBUTING.md.
