### ISSUE TITLE
No thumbnails are generated after removing item in gallery mode

### ISSUE THREAD

**Issue by micmicovich** [FineUploader/fine-uploader#1416]
After removing image from upload list, using (X) in right upper corner,
thumbnails are not generated for images coming after removed item.

Checked in:
Firefox 38.0.5
Chrome 43.0.2357.81 m
Opera 29.0.1795.60
IE 10.0.9200.16866

**Comment by rnicholus** [comment]
Are you talking about a situation where you drop a lot of image files, and then remove one of them, which causes previews to not be generated for the remaining files?

**Comment by micmicovich** [comment]
Yes

**Comment by rnicholus** [comment]
I suspect this is a bug, and will look closer soon.

**Comment by rnicholus** [comment]
Looking into this now.

**Comment by rnicholus** [comment]
Easily reproducible, probably some logic in the image.js module that is causing the process that generates previews from the queue to prematurely end when a file or img element associated with a queued item no longer exists.

**Comment by rnicholus** [comment]
Fixed in the hotfix/5.2.2 branch, to be part of the 5.2.2 hotfix release, along with #1417.
