### ISSUE TITLE
Problems with trash button alignment in gallery mode

### ISSUE THREAD

**Issue by micmicovich** [FineUploader/fine-uploader#1418]
Fine Uploader 5.2.1
For 
Chrome 43.0.2357.81 m
Opera 29.0.1795.60

![1](https://cloud.githubusercontent.com/assets/8446467/8006642/64170968-0b9e-11e5-9124-e2c69b566df0.jpg)
![2](https://cloud.githubusercontent.com/assets/8446467/8006643/641ace18-0b9e-11e5-8da7-951e94352322.jpg)

**Comment by rnicholus** [comment]
This is an interesting positioning error that I am not able to easily reproduce, but I can see it happening every once in a while. It seems like the easiest solution is to include the following style in in your document:

```css
.qq-gallery .qq-upload-size {
   float: left;
}
```

This _should_ prevent that the file size element from pushing the trash icon (which is floated right) onto the next line. Does this fix the issue for you without causing any other obvious issues in other browsers?

**Comment by micmicovich** [comment]
Yes, it fixes. No obvious issues in other browsers.

**Comment by rnicholus** [comment]
Great. I'll include this as a default style in the gallery css file in v5.2.2.
