### ISSUE TITLE
Support Microsoft Edge browser

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#1422]
If this already works, then we simply need to update the documentation to indicate support. Support for Edge must be complete before or very close to the release of Windows 10 (scheduled for July 29). If this does not coincide with a planned release of Fine Uploader, a hotfix release should be pushed out instead.

**Comment by rnicholus** [comment]
I just tested Spartan/Edge/whatever via a Windows 10 Insider Preview against Fine Uploader 5.2.2. _Brief_ tests suggest that everything obvious is working well _except_ for file dropping. This is not a big surprise as each new version of Explorer in the past has required adjustments to Fine Uploader's DnD module.

The next task will involve fixing DnD for Spartan. Then, I'll spend some time with more in-depth testing.

**Comment by rnicholus** [comment]
It looks like Spartan may not yet support dropping of files from the desktop. I assume that will be ironed out before release.

**Comment by rnicholus** [comment]
Official word is that drooping of files will not be supported by Edge in the initial release. https://twitter.com/morris_charles/status/611997674460479488

**Comment by rnicholus** [comment]
pushing this to 6.0.0 since Edge still does not support file dropping, AFAIK.

**Comment by rnicholus** [comment]
I'm dropping this from the schedule as Microsoft doesn't seem to have any specific plans to support this feature.

**Comment by rnicholus** [comment]
According to the [Edge changelog](https://dev.windows.com/en-us/microsoft-edge/platform/changelog/desktop/10586/?compareWith=10240), support for this feature was added in build 10565. Assuming this passes verification, Edge will be supported as part of Fine Uploader 5.5.0.

**Comment by rnicholus** [comment]
This is the last task scheduled for 5.5.0. I'll begin work on this next week.

**Comment by rnicholus** [comment]
When attempting to test out the DnD feature in Edge, I noticed that the available Windows 10 VMs only support Edge 10240. I reached out to the Edge team, and [they informed me that indeed there is no support for 10565 in Windows 10 VMs](https://twitter.com/kylealden/status/684893112355794945) at the moment. No known date for release of a VM with this build of Edge. So, I'll need to remove this from the schedule yet again.

**Comment by JW301** [comment]
Still not working in Edge. The drop-zone appears and immediately disappears when dragging a file onto the browser window, flickering when moving the file around. Dropping does not work.

BUT, when I manually remove the "display: none;" from the drop-zone in developer tools, I'm able to drag a file onto it and have it uploaded, without any problems and no flickering of the drop zone. The drop zone then disappears after the upload as normal.

Any chance you could fix this?

**Comment by rnicholus** [comment]
Edge is not yet supported by Fine Uploader. This has not been possible for various reasons (all on the Microsoft side). Edge didn't even support file dropping until a few months ago, and then there was no VM available with the build of edge that included support for file dropping. I'll check again to see if there is an updated VM. If there is, I'll try to add edge support again.

**Comment by JW301** [comment]
good news :) I checked the code myself and found a solution for DnD

The problem is not in the DnD module itself, that one is fully working. The problem is in the browser being incorrectly detected as Firefox, while not all Firefox features seem to work.
This same problem seems to have happened with IE11 in the beginning. See master/client/js/util.js Line 554:

`qq.firefox = function() {
        return (!qq.ie11() && navigator.userAgent.indexOf("Mozilla") !== -1 && navigator.vendor !== undefined && navigator.vendor === "");
    };`

Here you explicitly say it is not Firefox if it is also IE11. You just need to do the same thing with Edge
So I added another function to identify Edge and then changed the Firefox function as following:

`qq.edge = function() {
	return navigator.vendor === "" && navigator.userAgent.indexOf("Edge") !== -1;
};
qq.firefox = function() {
	return (!qq.edge() && !qq.ie11() && navigator.userAgent.indexOf("Mozilla") !== -1 && navigator.vendor !== undefined && navigator.vendor === "");
};`

With these lines changed, the DnD (and all other features I have used) work as expected.

Maybe you can use this information to fix the DnD problem in Edge :)

**Comment by rnicholus** [comment]
Thanks for looking into this! I'll take a closer look and add support for edge in a near future release.

**Comment by rnicholus** [comment]
Sorry, still blocked on this. Microsoft has _still_ not released a VM with a current build of Edge. The latest one available is 10240, which does not support file dropping. Without that VM, there isn't much I can do here. I'd suggest pinging someone at Microsoft about this. I'm going to mention this to them again, as I did a couple months ago.

**Comment by rnicholus** [comment]
Microsoft tells me an updated VM will be available in a couple weeks.

**Comment by rnicholus** [comment]
I now have a VM to work with, so I'll begin updating investigating support for Edge. Once this is complete (assuming I don't run into any more blockers) this will be released as 5.7.0.

**Comment by rnicholus** [comment]
PR to release Edge support is #1557. Anyone here interested in giving it a whirl to verify before I release?

**Comment by rnicholus** [comment]
This is completed and Microsoft Edge is now supported as of Fine Uploader 5.7.0.
