### ISSUE TITLE
FineUploader File upload support from Box, Dropbox

### ISSUE THREAD

**Issue by Manidipa** [FineUploader/fine-uploader#1427]
Hi Ray
           Can you please let us know whether fineuploader control supports file upload from Box, Dropbox and other cloud storage. If yes then please send us the sample link. 

Thanks in advance,

Regards
Manidipa

**Comment by rnicholus** [comment]
Fine Uploader will accept files, file input elements, or canvas elements from any location to desire, provided they are passed into the addFiles API method.

**Comment by Manidipa** [comment]
what do you mean by any location. is it cloud location please explain in detail.
