### ISSUE TITLE
Please add a unique resize id per batch of resized images

### ISSUE THREAD

**Issue by MikeSmith01** [FineUploader/fine-uploader#1432]
Hi Ray, 

It's Mike. I just wanted to thank you for answering questions quickly and building such great and feature rich product. It gives me pleasure to work with it in the application.
I wanted to suggest a feature enhancement that I think would be helpful in a batch of resized images. Right now when uploading different sizes of the same image, with upload original turned off, you get the file name of original image with each version of resized image. I was thinking that while the file name is certainly helpful to have and is unique enough to help link different resized versions of image in the database, the user could technically rename a file name, to the name of the file that was already uploaded, and that could cause problems in the database when deleting/retrieve images, because the file name per/batch of resized images is no longer unique to a single batch.
Looking at how things already work with FineUploader, when sending original image is set to true, a unique guid - qqparentuuid - is sent with each version of resized image, and that works perfectly as a unique link for CRUD operations of different versions of resized images. So I wanted to suggest a feature of a similar type of a guid based id as qqparentuuid to be sent along with each version of resized image when uploading original image is set to false. I think that this is a more reliable type of link for resized image batches to put in a database and could possibly be sent along with the name parameter as well.

Thanks,
Mike

**Comment by MikeSmith01** [comment]
Thank you so much!:))

**Comment by rnicholus** [comment]
Seems like we can just include the `qqparentuuid` param on all scaled images in all cases. Arguably, that should have happened from the start.

**Comment by MikeSmith01** [comment]
Well, I think that your answer made sense where an id named "qqparentuuid" would be stamped on resized versions of images if the original was uploaded, since the resized versions originated from a parent. I can see the thought behind that:) In this case probably the easiest thing is to just include "qqparentuuid" on resized images as well if the original is not sent, since technically speaking, it would serve the same purpose. Or, maybe, you could name it something along the lines of a qqresizeuuid, since the parent is not there, just the kids;) It's entirely up to you.
I made it work with name as a unique identifier for now. But I have to strip out the "name" from file names, the extra brackets "()", and I also remove spaces from the file name just for cleanliness. And it works...just not exactly that dependable or pretty. We are still developing things...so no rush on a release version.
p.s. I will provide feedback about the demo page in another post with a few ideas. Just wanted to let you know that I have not forgotten:)

Thanks again,
Mike

**Comment by MikeSmith01** [comment]
Did a little more testing today, and found out that name won't work as a unique link for resized images because if I upload the same image twice, the name is the same for both uploaded images and code breaks. Will have to wait for the enhancement:)

**Comment by rnicholus** [comment]
You could perhaps append the UUID to the filename as a temporary workaround
using setName.

**Comment by MikeSmith01** [comment]
Thanks Ray, I'll give it a try:)

**Comment by rnicholus** [comment]
Looking into this now as part of 5.2.3. Perhaps I can sneak this in...

**Comment by rnicholus** [comment]
@MikeSmith01 I've made an adjustment, which is currently being staged in the hotfix/5.2.3 branch. Please let me know if this will address your issue.

**Comment by MikeSmith01** [comment]
Hi Ray, thanks for making the adjustment. I will certainly take a look at it either this weekend if I find time or early next week (I'm out of town due to holiday). Happy 4th of July!

**Comment by MikeSmith01** [comment]
Hi Ray, I'm sorry, but how do I get to that branch? I would need azure.fine-uploader.min.js for testing.

Thanks,
Mike

**Comment by rnicholus** [comment]
Sorry, I just merged the hotfix branch into develop as I plan on skipping the hotfix release and making this part of [5.3.0](https://github.com/FineUploader/fine-uploader/milestones/5.3.0).

You can access zips of anything on the develop branch by following a little convention we have in place. For example, to grab the azure build of 5.3.0-4 (currently the latest build on develop): http://releases.fineuploader.com/develop/5.3.0-4/azure.fine-uploader-5.3.0-4.zip.

**Comment by MikeSmith01** [comment]
Ok, I just tested, everything works as expected, now there's a qqparentuuid present without the original image being sent:) Thank you!

Mike

**Comment by rnicholus** [comment]
@MikeSmith01 Great, thanks for verifying. This will go out with 5.3.0, hopefully in the next few weeks or so.

**Comment by MikeSmith01** [comment]
Thanks Ray, I will use this version meanwhile:)
