### ISSUE TITLE
Please add an event that fires when all instances of a resized image have been uploaded

### ISSUE THREAD

**Issue by MikeSmith01** [FineUploader/fine-uploader#1435]
Hello,

I was going to suggest a feature for an event that gets fired when all instances of a resized image have been uploaded. For example, when uploading three versions of a resized image, let's say, a large version, a medium version, and a thumbnail version, it would be helpful to have an event that gets fired as soon that resized "batch" gets finished uploading. This event can have a resize batch id of some sort (requested earlier) as one of the arguments, maybe individual uuid's of each file can also be helpful. The reason I am suggesting this feature is that, in our application we build several manipulated versions of a large image and save them back to Azure storage. It would be good to start the processing on the image batch as soon as all resized versions have been uploaded, because we would like to save the manipulated images under the same uuid's as their resized versions. 

Thanks,
Mike

**Comment by rnicholus** [comment]
Wouldn't this be something you would track server-side? Fine Uploader can send a POST when each file has been uploaded successfully.

**Comment by MikeSmith01** [comment]
Hi Ray,
Thank you for your comment. It certainly can be tracked server side and I did play with both events, onComplete() and onAllComplete(). The onComplete() event fires for each file, for example, in case of a resized images it would fire once for large, medium, and thumbnail version of the image. But when images get uploaded to the server I already know which image it is by looking at its name prefix. So onComplete() event doesn't tell me anything new. I also could make it work server side and check the database to see if all resized instances of an image have been uploaded when images get saved. But I would have to do it upon each individual image arrival because images get saved to database out of order just to the way the threads are scheduled. So this could certainly work, just won't be as polished. That's why I wanted to suggest an event something along the lines of onAllComplete() but for each batch of resized instances of an image. That way when this event fires, I know that all resized instances of an image have been uploaded and it's safe to schedule processing for that batch with just one simple call. The code would just look more professional that way.

Mike

**Comment by rnicholus** [comment]
I understand that this may be useful for your specific use case, but I don't see a general use for this, and I'd like to avoid cluttering up the API any further. However, I would be glad to consider re-opening if other users show an interest in this.

**Comment by MikeSmith01** [comment]
Hi Ray, thanks for the update. It definitely would help in my case, but it's not critical, so I understand where you are coming from. Thanks for being open minded towards future feedback.

Thanks,
Mike
