### ISSUE TITLE
The documentation page is not working

### ISSUE THREAD

**Issue by andr3s2** [FineUploader/fine-uploader#1444]
When I enter to  http://docs.fineuploader.com/
The page shows an error.

http://docs.fineuploader.com/features/delete.html

**Comment by rnicholus** [comment]
Looking into this now...

**Comment by rnicholus** [comment]
It looks like Dreamhost (which should be renamed to Nightmarehost) lost everything on our shared instance that hosts the docs site since late January. I'll have to contact them and get the sorted out. We'll be moving away from Nightmarehost after the last of many issues.

**Comment by rnicholus** [comment]
Site is back up now. I'm guessing Dreamhost (which hosts a shared instance housing our docs site) had some sort of outage, at least on our shared instance. Looks like it was out for several hours, nothing noted on their status page or twitter feed. I'm going to follow up with them to find out what went wrong.

I'm not very impressed with Dreamhost, to say the least. I'll probably move our docs site to an AWS EC2 instance in the near future.
