### ISSUE TITLE
Validation 

### ISSUE THREAD

**Issue by andr3s2** [FineUploader/fine-uploader#1446]
-There is some way in order to validate in an uploader for example that images can have maximum file size of 10MB but for .docs a maximum of 100MB ?

-And also validate in one uploader that I just can upload 2 .doc files and 3 .jpg files  (in total 5 but with different quantity depending on their type?) thank you in advance!.

**Comment by subinvarghesein** [comment]
1. [validate event](http://docs.fineuploader.com/api/events.html#validate) returns filename (which contains extension) and size. You can use that
2. Currently you would need to keep a model on your side to track how many docs and jpgs where submitted and on the same validate event, based on your model, can return false to reject the file
