### ISSUE TITLE
Pass custom headers to server for chunking success endpoint also

### ISSUE THREAD

**Issue by subinvarghesein** [FineUploader/fine-uploader#1447]
Usecase: Server needs some information ("userid" etc for logging purposes) as custom headers with each request.

Upload endpoint and others has an option to pass the information as custom headers which we want but *not* chunking success endpoint.

**Comment by rnicholus** [comment]
Any [custom headers you set for the upload request](http://docs.fineuploader.com/branch/master/api/options.html#request.customHeaders) will be sent with the chunking success request.
