### ISSUE TITLE
Posting json multipart along with the file

### ISSUE THREAD

**Issue by jardakotesovec** [FineUploader/fine-uploader#1448]
Would be possible to send json along with the file?

```
Content-Disposition: form-data; name="myJsonString"
Content-Type: application/json
```

Thanks!

**Comment by rnicholus** [comment]
The multipart boundary header included in your question is representative of a JSON file. Of course, you can include JSON in an input field, or pass JSON to the [`setParams` API method](http://docs.fineuploader.com/branch/master/api/methods.html#setParams), but there will be no `Content-Type`, as that is reserved for files/blobs.

**Comment by cariquitanmac** [comment]
@rnicholus do we have any workaround for this?
