### ISSUE TITLE
FileUploaderBasic: input element doesn't work in Firefox

### ISSUE THREAD

**Issue by yangez** [FineUploader/fine-uploader#145]
``` javascript
var uploader = new qq.FileUploaderBasic({
    button: $('input#imgUpload')[0],
    //...
});
```

The above works in Google Chrome 12 but not in Firefox 4.0.1. Note that if you replace "button" with "element" in the above example (like in the documentation), it will also stop working in Chrome. Are there any workarounds I can use for Firefox? Thanks much.

**Comment by carolinesalib** [comment]
Really helpful, thanks!
