### ISSUE TITLE
Feature Request: Endless retries

### ISSUE THREAD

**Issue by Korijn** [FineUploader/fine-uploader#1454]
I'd like to request a setting to enable endless retries, perhaps even with exponential backoff but that is not a strict requirement. I'll code it myself (like #1404) if it's non-trivial, but it'd be great if you could point me in the right direction if you feel that's the way to go forward. :)

**Comment by rnicholus** [comment]
You should already be able to do this by calling the `retry` API method. You can add this call to an `onComplete` or `onStatusChange` event handler.

**Comment by Korijn** [comment]
For anyone else viewing this thread:

```
uploader = new qq.azure.FineUploader({
    callbacks: {
        onStatusChange: function (id, oldStatus, newStatus) {
            if (status === qq.status.UPLOAD_FAILED) {
                uploader.retry(id);
```

**Comment by rnicholus** [comment]
And you can add exponential backup by making use of `window.setTimeout`.

**Comment by Korijn** [comment]
Can you retrieve the retry count?

**Comment by rnicholus** [comment]
No, but you can certainly keep track,

**Comment by Korijn** [comment]
When I use uploader.retry(id); the retry does start but the Retry button also remains visible. Bug or am I missing a configuration setting?

**Comment by rnicholus** [comment]
Looks like a bug.

**Comment by Korijn** [comment]
I'll file a bug tomorrow and subsequently submit a  PR to fix it...
