### ISSUE TITLE
Retry button remains visible when initiating a retry programmatically 

### ISSUE THREAD

**Issue by Korijn** [FineUploader/fine-uploader#1455]
For example, when applying the following mechanism to arrange for endless retries, the Retry button remains visible, even after the upload succeeds.

```javascript
uploader = new qq.azure.FineUploader({
    callbacks: {
        onStatusChange: function (id, oldStatus, newStatus) {
            if (newStatus === qq.status.UPLOAD_FAILED) {
                uploader.retry(id);
```

**Comment by Korijn** [comment]
After some initial inspection of the source, I think the `onRetry` event handler in `uploader.api.js` is not being called when a retry is scheduled programmatically, since it only appears to be wired up to the UI click event of the retry button.

This is the `onRetry` handler, which updates the UI:

```
onRetry: function(fileId) {
    qq(self._templating.getFileContainer(fileId)).removeClass(self._classes.retryable);
    self._templating.hideRetry(fileId);
    self.retry(fileId);
},
```

It looks like my hypothesis is correct when looking at the `_manualRetry` method in `uploader.basic.api.js`:

```
/**
 * Conditionally orders a manual retry of a failed upload.
 *
 * @param id File ID of the failed upload
 * @param callback Optional callback to invoke if a retry is prudent.
 * In lieu of asking the upload handler to retry.
 * @returns {boolean} true if a manual retry will occur
 * @private
 */
_manualRetry: function(id, callback) {
    if (this._onBeforeManualRetry(id)) {
        this._netUploadedOrQueued++;
        this._uploadData.setStatus(id, qq.status.UPLOAD_RETRYING);

        if (callback) {
            callback(id);
        }
        else {
            this._handler.retry(id);
        }

        return true;
    }
},
```

I'm not sure how to call the event handler from this piece of code, or alternatively how to trigger the event manually. Can you give me a hint, @rnicholus?

**Comment by rnicholus** [comment]
The easiest solution is probably just add a call to the [`hideRetry` method of the templating module](https://github.com/FineUploader/fine-uploader/blob/5.3.0/client/js/templating.js#L782) to the [`qq.status.UPLOAD_RETRYING` check in the `_onUploadStausChange` method](https://github.com/FineUploader/fine-uploader/blob/5.3.0/client/js/uploader.api.js#L252). You can then remove any other code that duplicates this logic on retry.

**Comment by Korijn** [comment]
Please see #1458.
