### ISSUE TITLE
Incorrect formatted size displayed

### ISSUE THREAD

**Issue by akhilaj** [FineUploader/fine-uploader#1456]
Small issue

The function uses 1000 but it should use 1024 instead --

  _formatSize: function(bytes) {
            var i = -1;
            do {
                bytes = bytes / 1000 -- bytes / 1024 ;
                i++;
            } while (bytes > 999);  --  (bytes > 1023)

            return Math.max(bytes, 0.1).toFixed(1) + this._options.text.sizeSymbols[i];
        },

**Comment by rnicholus** [comment]
No, 1000 is the correct value.
