### ISSUE TITLE
When using itemLimit the net count of files is not calculated properly

### ISSUE THREAD

**Issue by antonsarov** [FineUploader/fine-uploader#1457]
I have a FineUploader instance with _itemLimit: 10_ and using the client-side scaling feature.

With this limit I am allowed to upload only 5 images (because I have defined a single scaled copy per image) and this is working fine.

Now the problem is that if I **successfully** delete one of the uploaded images (along with the scaled image in the background), Fine Uploader still thinks that I have used all 10 slots and does not let me upload any more images - I should be allowed to upload one more image.

**Comment by rnicholus** [comment]
Seems to be working fine for me - just tested on 5.3.0. If you are still seeing the issue and are using the latest version of Fine Uploader, I'd be happy to re-open if you are able to provide your code and any additional info required to reproduce.

**Comment by antonsarov** [comment]
I am commenting under this issue cause the problem seems to be related but not exactly as described above.
The problem comes actually from the fact, that the original image is deleted (my onDeleteComplete is executed) but the scaled image is not deleted (from a Fine Uploader's point of view). This happens because I have defined `hideScaled: true` - and this is documented. However I am missing a functionality where I can delete the scaled image as well.
I thought about making a separate `deleteFile(...)` call when my `onDeleteComplete` callback is executed but how do I get the ID of the scaled image? And even if I get it, this seems to be a bit overcomplicated.

It would be really cool to have something like:
```
scaling: {
        sizes: [
            {name: "small", maxSize: 100, deleteWithOriginal: true},
            {name: "medium", maxSize: 300, deleteWithOriginal: false}
        ]
    }
```
where you can specify which scaled versions should be deleted along with the original image.

**Comment by rnicholus** [comment]
I don't see ever adding that sort of fine-grained control. However, I _can_ see updating the code to perhaps delete all hidden scaled images when the reference image is deleted. This would be exposed by a new  `scaling` option property.

**Comment by antonsarov** [comment]
Having a global `scaling` option to delete scaled images along with the reference image would be super cool!

Meanwhile, is there any way to force the deletion of the hidden scaled images? Getting the ID would help here.

**Comment by rnicholus** [comment]
should be available via getUploads().
