### ISSUE TITLE
Propagate Amazon S3 errors

### ISSUE THREAD

**Issue by TimDaub** [FineUploader/fine-uploader#1462]
Often I'm getting Amazon S3 specific errors like this one:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>RequestTimeTooSkewed</Code><Message>The difference between the request time and the current time is too large.</Message><RequestTime>Fri, 04 Sep 2015 09:25:14 GMT</RequestTime><ServerTime>2015-09-03T09:25:19Z</ServerTime><MaxAllowedSkewMilliseconds>900000</MaxAllowedSkewMilliseconds><RequestId>D2F4DA145C0DE358</RequestId><HostId>epleyY5wJz+OJD3TfH2xRXqOMjztR+Edoxth1rZk1TUV08s/mZVzntEaE/oh8y7Kabf98qjIPoY=</HostId></Error>
```

However in `onError` and `onComplete`, fineuploader only returns "Problem initiating upload request." as the error message but logs:

"Specific problem detected initiating multipart upload request for 0: 'The difference between the request time and the current time is too large.'."

Since we would like to log all the errors user's are getting (with ravenjs), it would be great if fineuploader would actually return the real error message from amazon rather than a generic one.

**Comment by rnicholus** [comment]
You want Fine Uploader to make the entire XML response available to you? The messages sent to these callbacks are meant to be generic. If you'd like to tap into all details logged by Fine Uploader, you should consider intercepting calls to `qq.log`.

**Comment by TimDaub** [comment]
> The messages sent to these callbacks are meant to be generic.

Why? A developer could still make them generic if he doesn't want to see the individual ones.
