### ISSUE TITLE
getButton returns undefined in onStatusChange event handler

### ISSUE THREAD

**Issue by rohanc** [FineUploader/fine-uploader#1465]
Similar to issue #1116 , if you call getButton in the SUBMITTING phase, it returns undefined. It would be preferable if it returned the button object, seeing as presumably this is known by this stage.

I use the onStatusChange event to enable/disable various upload control buttons and at the moment I have to put in a special check:
if (typeof button == 'undefined') { return true; }

If this is a difficult change, it would be good to at least document this limitation in the onStatusChange documentation. I think this same issue may apply to the onError event handler too.

**Comment by rnicholus** [comment]
The button is not tracked until the file is officially submitted. That is, all validation checks have passed and the file has been associated with an upload handler. Your best bet is to move your logic to [an `onSubmitted` callback](http://docs.fineuploader.com/branch/master/api/events.html#submitted).
