### ISSUE TITLE
[Fine Uploader 5.3.0] Problem drawing thumbnail!

### ISSUE THREAD

**Issue by standus** [FineUploader/fine-uploader#1467]
Always I got wtis error in console when fine-uploader wand to draw thumb for non picture file. ZIP for example. And twice.

**Comment by rnicholus** [comment]
This is expected, as zip files are not previewable.

**Comment by standus** [comment]
Yes sure, but why error message in log?

**Comment by standus** [comment]
I have another problem.
With this setting: "scaling": { "sendOriginal": "false", "sizes": [ {"name": "sized", "maxSize": "1900"} ]}
, but in uploader UI a see 2 preview images: 1x sized + 1 original. 1 is in files folder and second in chunks folder.

**Comment by standus** [comment]
And next trouble:
{ "validation": {  "itemLimit": "1", "allowedExtensions": ["jpeg", "jpg","avi","png"] }, "scaling": { "sendOriginal": "false", "sizes": [ {"name": "sized", "maxSize": "1900"} ]} }
and with sessions setting:
session : { params: { files: uploaded }, endpoint: '/libs/scripts/uploaded.php', refreshOnRequest:true  }

After reload page I have one already uploaded file which I see in UI of FU. But after try to upload next image I got error: Too many items (3) would be uploaded.  Item limit is 1. But I have only one. OK, I deleted that one image, soo in UI is no image, I try upload newone, but with message: Too many items (2) would be uploaded.  Item limit is 1.

**Comment by rnicholus** [comment]
Neither of these are issues either. The chunks folder is where file chunks
are temporarily stored. And the itemLimit, of course, is a strict limit of
the number of files you can upload/submit.

Please do not create one thread and the post several unrelated issues under
it.
