### ISSUE TITLE
sizeLimit and chunking enabled

### ISSUE THREAD

**Issue by am05mhz** [FineUploader/fine-uploader#1469]
there is a problem in limiting upload size when chunking is enabled, as the size limit is compared to each chunk, which result in upload always allowed when chunk size is smaller than size limit

**Comment by rnicholus** [comment]
I'm not seeing this issue at all. I tested with a `validation.sizeLimit` of 10000000 and a `chunking.partSize` of 2000000. Files greater than 10MB were rejected as expected. If this were as you described, there would have been a large number of bug reports already, as this is a commonly used feature. I suspect you have either misinterpreted your issue, or perhaps there is some problem with code on your end, outside of Fine Uploader's scope. 

If you are able to provide all of your Fine Uploader related configuration code, your Fine Uploader version, and specific steps required to reproduce, I can re-open this issue.

**Comment by am05mhz** [comment]
hi @rnicholus, sorry I forgot to mention that I don't use `validation.sizeLimit` as it is client side protection, what I use id PHP's class sizeLimit property in order to do server side validation.

Thanks

**Comment by rnicholus** [comment]
Then the issue is in your server code, so this does not involve Fine Uploader.

**Comment by am05mhz** [comment]
umm, I use FineUploader PHP class, so it is involved to FineUploader, or may be its a different project? sorry if I did not know this as what I understood, that is a part of the same project.

**Comment by rnicholus** [comment]
You did not mention this either. If there is a specific bug in the example PHP server code, please file that in the [php-traditional-server repo](https://github.com/FineUploader/php-traditional-server).

**Comment by am05mhz** [comment]
ah, okay, sorry for the mix up, i'll post that in that section
