### ISSUE TITLE
How to handle 1000 concurrent users uploads using FineUploader Azure API

### ISSUE THREAD

**Issue by hemlata09** [FineUploader/fine-uploader#1470]
We are using FineUploaded Azure API/library to upload large files. Now its failing to handle 1000 concurrent users request / uploads.

Is there any mechanism to handle it?

Please provide some suggestion, its urgent.

**Comment by rnicholus** [comment]
I'm not sure what you mean by "1000 concurrent uploads". Please provide details.

**Comment by rnicholus** [comment]
Closing this due to lack of information.

**Comment by hemlata09** [comment]
"1000 concurrent uploads" means 1000 users are going to upload media files per second.
 
Can FineUploader handle 1000 concurrent users per second?

**Comment by rnicholus** [comment]
Fine Uploader is a client side JavaScript library, not a server. I suggest you take a break from github until you figure out how to use the issue tracker. You opened up 2 exact copies of this issue today, which I've closed.
