### ISSUE TITLE
Double loaded thumbs

### ISSUE THREAD

**Issue by standus** [FineUploader/fine-uploader#1472]
I do know why, but it happen only with session images/files. See attach. picture. There are all files loaded twice. When I upload new image it is OK. 
I checked/logged some events, but everywhere it is only one event /not duplicated/.
What problem schould be?
![2015-09-17_18-02-06](https://cloud.githubusercontent.com/assets/4818430/9938852/9a75ae68-5d67-11e5-8ed5-d526d386f697.jpg)

**Comment by rnicholus** [comment]
I'm not seeing a problem. Fine Uploader internally makes use of data URIs when displaying scaled thumbnails. Subsequent attempts to access the same URI come from the cache, as expected. But either way, there is no round-trip to the server.

**Comment by standus** [comment]
But why its takeing twise from cache?
