### ISSUE TITLE
Feature Request: Expose showDialog method

### ISSUE THREAD

**Issue by jammy-git** [FineUploader/fine-uploader#1473]
My use case: I'm using FineUploader to allow users to upload files which will be used as attachments to a system generated email. As a lot of mail servers have a total file size limit of X Mb for incoming emails I'd like to impose a total batch file size limit. I've managed to do this via the onValidateBatch event, I return false if the batch is over the size limit. However this does not show any error message to the user. I can use a JavaScript alert, which functionally achieves the requirement, but is bad UX as it's a different dialog to the one used for all the other validation messages.

Exposing the showDialog method would allow me to hook into the same dialog system (whether that is the standard dialog used with FineUploader UI, or a custom one I've set using showMessage).

On a slightly related note, is there a reason why there isn't get/set methods for all the Core/UI options? I did think I could achieve the above by dynamically set the validation.sizeLimit option after each upload (so validation.sizeLimit = maxAllowedBatchUploadFileSizeLimit - currentUploadedBatchUploadFileSize). Unfortunately there is no setter for validation.sizeLimit (that I could see), so this wasn't possible either.

**Comment by rnicholus** [comment]
I guess I don't really see the need to clutter up the api with another method in this case. If you are using the default showMessage impl, this would be nothing more than an alias for window.alert. If you provided your own impl during initialization, then it would be an alias to a function you already should have access to.

Addressing your second question; allowing any configuration option to be changed at any time adds unnecessary complexity to a library that is already complex.
