### ISSUE TITLE
Unicode (umlauts) in filenames and Firefox

### ISSUE THREAD

**Issue by bionik** [FineUploader/fine-uploader#1476]
When submitting files on Firefox 40.0.3, the filename that Fineuploader draws to the file list, contains corrupt unicode characters. This issue is not present in Chrome or Safari.
I tried to serve the script with utf-8 encoding with no effect.
This also happens in your own demo site.

**Comment by rnicholus** [comment]
This is not a Fine Uploader issue. Instead, the issue seems to be in rendering of umlauts using the "Maven Pro" font provided by Google Font in Firefox. You can verify at http://typecast.com/preview/google/Maven%20Pro. The next best course of action is to either file a big with Firefox and/or Google Fonts.

**Comment by bionik** [comment]
Thanks for responding. I'm not totally convinced that it's the Google Fonts' fault, instead I think it's the templating engine not working correctly in Firefox. If I edit the generated dom and add umlauts by hand, everything works. Seems to me that it's the templating engine's internal character encoding that does not work correctly. Here is a screenshot of your demo, I added some umlauts to the second filename by hand, the part of the DOM is visible in Firefox inspector. 
![image](https://cloud.githubusercontent.com/assets/2960296/10076001/a90b403a-62e1-11e5-9e20-9db1f0ed2564.png)

**Comment by rnicholus** [comment]
It _is_ a Google Fonts or firefox issue. Please look at the link I sent you and paste in a word containing an umlaut.

**Comment by bionik** [comment]
Well okay then, strange. Anyway, I got no problem pasting paragraphs containing umlauts to the test tool you linked. This is a confusing problem :) Maybe I have to try something else then. Thanks.

**Comment by rnicholus** [comment]
I've attached pictures of a word with an umlaut entered into the google fonts typecast demo page on FF and Chrome - no Fine Uploader involved. You can see there is a clear rendering issue in FF. You'll need to contact either the Fonts or the Firefox team for further support.

Firefox:
![screen shot 2015-09-24 at 10 39 34 am](https://cloud.githubusercontent.com/assets/593312/10078083/cdf8fd08-62a8-11e5-9b8c-9b1207aa1458.png)

Chrome: 
![screen shot 2015-09-24 at 10 40 09 am](https://cloud.githubusercontent.com/assets/593312/10078082/cdf705fc-62a8-11e5-815c-0b2073963e2d.png)

**Comment by bionik** [comment]
Ok. Thanks for responding and keep up the great work!

Lauri Hakkarainen
+358 40 5432188
