### ISSUE TITLE
Blobs uploaded via Azure module in uuid mode get .undefined extension if original filename has no extension

### ISSUE THREAD

**Issue by Korijn** [FineUploader/fine-uploader#1479]
Blobs uploaded in uuid mode get .undefined extension if original filename has no extension. PR incoming.

**Comment by rnicholus** [comment]
Can you describe the steps needed to reproduce?

**Comment by Korijn** [comment]
When you use the Azure FineUploader, by default it will upload files using uuid's as the blob name. If the file you upload has no extension, FineUploader appends ".undefined" to the uuid.

Also see the PR I submitted, it's pretty obvious.

**Comment by Korijn** [comment]
I just confirmed my custom build with the PR included as working on our testing servers, as we needed to get this live quickly.

**Comment by rnicholus** [comment]
Ah, that's the critical piece that is missing from your PR and issue - Azure. I'll update both cases.

**Comment by Korijn** [comment]
Yeah, sorry about that. It's so natural for me that I forgot to mention it. :)

**Comment by rnicholus** [comment]
No problem. I'll probably release this as part of 5.4 instead of a hotfix release. Use of Azure, compared to S3, is _very_ small, so this likely doesn't affect many users.

**Comment by Korijn** [comment]
Sure, we'll merge upstream into our custom builds until it's included. Thanks!
