### ISSUE TITLE
Cross-domain requests in Internet Explorer 9 aborted

### ISSUE THREAD

**Issue by michaeljmx** [FineUploader/fine-uploader#1484]
There is a problem with cross-domain requests (e.g. upload success requests) in Internet Explorer 9 that get aborted. It seems that it is a known issue, e.g. it is discussed at https://social.msdn.microsoft.com/Forums/ie/en-US/30ef3add-767c-4436-b8a9-f1ca19b4812e/ie9-rtm-xdomainrequest-issued-requests-may-abort-if-all-event-handlers-not-specified?forum=iewebdevelopment

I've tried the solution and according to my tests it works correctly. What I did is added the following lines after the line "xhrOrXdr = new XDomainRequest();":

xhrOrXdr.onload = function () { };
xhrOrXdr.onerror = function () { };
xhrOrXdr.ontimeout = function () { };
xhrOrXdr.onprogress = function () { };

**Comment by rnicholus** [comment]
I've not run into this myself, and this is the first such report. How exactly does on reproduce this issue?

**Comment by michaeljmx** [comment]
We use the S3 uploader on one domain and it calls the uploadSuccess callback on another domain, so it has to do a cross-domain request. All the required CORS settings are configured correctly, and we have no problems with Chrome, Firefox or IE10+. However, in IE9 the requests get stuck.

Generally if 3 files are uploaded (with 3 maximum connections enabled), so they are uploaded at the same time, the first callback works but the next two got stuck. If I check IE11 in IE9 emulation mode, I see in F12 developer tools that these requests are "pending". However, when I check it in real IE9, I see that the requests are aborted.

The changes I mentioned above seem to have fixed the issue, while more tests may be required.

**Comment by rnicholus** [comment]
Thanks for the information. Do you have a pull requests to offer that addresses this issue?

**Comment by michaeljmx** [comment]
Unfortunately no, for the moment I changed it in the bundled script. The change I made is the following: I replaced the following code:
```javascript
    function getCorsAjaxTransport() {
        var xhrOrXdr;

        if (window.XMLHttpRequest || window.ActiveXObject) {
            xhrOrXdr = qq.createXhrInstance();

            if (xhrOrXdr.withCredentials === undefined) {
                xhrOrXdr = new XDomainRequest();
            }
        }

        return xhrOrXdr;
    }
```

with this one:
```javascript
    function getCorsAjaxTransport() {
        var xhrOrXdr;

        if (window.XMLHttpRequest || window.ActiveXObject) {
            xhrOrXdr = qq.createXhrInstance();

            if (xhrOrXdr.withCredentials === undefined) {
                xhrOrXdr = new XDomainRequest();

                // Fixes bug with IE9 - https://social.msdn.microsoft.com/Forums/ie/en-US/30ef3add-767c-4436-b8a9-f1ca19b4812e/ie9-rtm-xdomainrequest-issued-requests-may-abort-if-all-event-handlers-not-specified?forum=iewebdevelopment
                xhrOrXdr.onload = function () { };
                xhrOrXdr.onerror = function () { };
                xhrOrXdr.ontimeout = function () { };
                xhrOrXdr.onprogress = function () { };
            }
        }

        return xhrOrXdr;
    }
```

**Comment by rnicholus** [comment]
Thanks for the update. This looks like a reasonable change. I'll be sure to include it as part of the next release.
