### ISSUE TITLE
Error "Cannot read property 'xhr' of undefined"

### ISSUE THREAD

**Issue by michaeljmx** [FineUploader/fine-uploader#1486]
Some users of our site get error "Cannot read property 'xhr' of undefined":

Stack: TypeError: Cannot read property 'xhr' of undefined
    at getXhrOrXdr (s3.fine-uploader.js:3783:39)
    at XMLHttpRequest.<anonymous> (s3.fine-uploader.js:3938:17)

It seems that this error occurs mostly in Chrome. We use FineUploader for uploading files to S3 with concurrent chunking and auto-retry enabled.

**Comment by rnicholus** [comment]
Can you provide specific steps needed to reproduce? I haven't encountered this issue myself, and I don't recall any reports either. I'll need other information as well, such as your client side code and version of Fine Uploader.

**Comment by michaeljmx** [comment]
The version we use is 5.2.2. Unfortunately I don't know how it is possible to reproduce the issue - we received the errors using an ajax callback in onerror handler and could not reproduce it in our own environment. Unfortunately I cannot share our code at the moment.

Sorry, I know that it's not very helpful. I thought that maybe other users encountered the same error and/or you may suggest a general idea of what could cause the issue that can help with finding the source of the problem.

**Comment by rnicholus** [comment]
Ok, can you tell me what specific issue this message is causing, other than a log message in the dev console?

**Comment by michaeljmx** [comment]
About half of people that get this exception cannot finish the upload process and the upload seem to be stuck (onAllComplete isn't called for them and onComplete with error response is neither called), while some of them upload few files before getting this error. Other half finishes upload successfully. 

We'll try to get more information on the issue and I'll post here if we find something that could help with fixing the issue.

**Comment by rnicholus** [comment]
That sounds like a pretty serious issue, but this is the first I've heard of it. Have you tried using a more recent version, such as 5.3.2?

**Comment by michaeljmx** [comment]
Unfortunately we didn't have a chance yet. Probably we'll wait for the next version and then try it in production - we could not reproduce the problem in our own tests.

**Comment by rnicholus** [comment]
Without any information to go on or a way to reproduce, I'll have to close. Could be a browser plug-in on some user's machines that is causing the problem. If not, and you see a pattern, let me know and I can re-open.

**Comment by fschwahn** [comment]
We are seeing the same issue with some of our users, but unfortunately I cannot contribute much. The error occurs here: https://github.com/FineUploader/fine-uploader/blob/339a80a99f08dbc9408b3f8960d59dfca8ecc99d/client/js/ajax.requester.js#L94, with `requestData[id]` being undefined.

Also, one of the users who got this error also triggered an error here https://github.com/FineUploader/fine-uploader/blob/339a80a99f08dbc9408b3f8960d59dfca8ecc99d/client/js/upload-handler/xhr.upload.handler.js#L293 with `handler._getFileState(id)` returning `undefined`.

It seems that all users seeing this issue had very bad connectivity, it may be related to that. For some of them the upload succeeded nonetheless.

Our configuration looks like this:

```javascript
...
  function() {
    this.FileUploader = function() {
      function e(e, t) {
        null == t && (t = {}), this.el = e, this.options = t, this.setupUploader()
      }
      return e.prototype.setupUploader = function() {
        var e, t;
        return t = this, e = null, this.el.fineUploaderS3({
          uploaderType: "basic",
          button: this.el,
          multiple: this.options.multiple,
          maxConnections: this.options.maxConnections || 3,
          validation: {
            acceptFiles: this.options.acceptFiles || null,
            sizeLimit: this.options.sizeLimit || 0,
            minSizeLimit: this.options.minSizeLimit || 0,
            allowedExtensions: this.options.allowedExtensions || []
          },
          request: {
            endpoint: "https://xxx.s3-eu-west-1.amazonaws.com",
            accessKey: "XXX"
          },
          objectProperties: {
            acl: this.options.acl || "public-read",
            key: function(e) {
              var n, i, r;
              return r = "production/" + qq.getUniqueId(), i = this.getName(e), n = t.options.extension || qq.getExtension(i), void 0 !== n && (r += "." + n), r
            }
          },
          signature: {
            endpoint: "/upload_signatures",
            customHeaders: {
              "X-CSRF-Token": $("meta[name=csrf-token]").attr("content")
            }
          },
          uploadSuccess: {
            customHeaders: {
              "X-CSRF-Token": $("meta[name=csrf-token]").attr("content")
            },
            endpoint: this.options.endpoint,
            params: this.options.params || {}
          },
          chunking: {
            enabled: !0,
            concurrent: {
              enabled: !0
            }
          },
          resume: {
            enabled: !0
          },
          iframeSupport: {
            localBlankPagePath: "/upload_success.html"
          },
          retry: {
            autoAttemptsDelay: this.options.autoAttemptsDelay || 5,
            maxAutoAttempts: this.options.maxAutoAttempts || 20,
            enableAuto: !0
          }
        }
....
```
