### ISSUE TITLE
How will fine-uploader perform with bad network connection, i.e. handle ERR_CONNECTION_RESET from s3

### ISSUE THREAD

**Issue by Marak** [FineUploader/fine-uploader#1491]
Hello.

I'm interested in potentially purchasing a SaAS license for this product.

I have one specific technical question, how will Fine handle large uploads over an unreliable network?

If our client's connection to s3 is unreliable, they sometimes can experience an `ERR_CONNECTION_RESET`. How will fine handle this situation? Will it be able to gracefully resume the upload, or will it require the entire upload start from scratch?

Thank you.

**Comment by rnicholus** [comment]
Fine Uploader has an auto-retry feature. By default, it will wait a few seconds between attempts, and then auto-retry up to 3 times. The time between attempts and number of attempts is [configurable](http://docs.fineuploader.com/branch/master/api/options.html#retry). You can also manually initiate a retry via the [API](http://docs.fineuploader.com/branch/master/api/methods.html#retry) or the UI. 

If you are using the [chunking feature](http://docs.fineuploader.com/branch/master/features/chunking.html), which is turned on by default in the S3 module, Fine Uploader will attempt to retry only the failed chunk, not the entire upload from byte 0.

More information is at

**Comment by Marak** [comment]
@rnicholus - Looks like your last sentence got cut off?

**Comment by rnicholus** [comment]
@Marak I just edited/updated my comment.

**Comment by Marak** [comment]
@rnicholus -

Thank you for the question answer.

Can you specify or comments on the trade-off between specifying a high or low chunk size. Let's say, what is the performance difference 5meg chunks and 50meg chunks.

In my current solution I have a few users with unreliable internet getting too many `ERR_CONNECTION_RESET ` from s3. In some cases they can't get past a whole chunk.

**Comment by rnicholus** [comment]
I don't think there is a one-size-fits-all answer to that question. The chunk size is configurable so you can adjust it based on your results. Large chunks = less efficient retries. Smaller chunks = more HTTP requests.
