### ISSUE TITLE
Support for Incremental stitching of chunks instead of only of success callback

### ISSUE THREAD

**Issue by subinvarghesein** [FineUploader/fine-uploader#1492]
## Usecase
In our application, uploading GBs of files is pretty normal (some of them 30GB or more). We have concurent chunking enabled with chunk size around 5MB. FineUploader, by the way, does an impressive job uploading it. 
When fineuploader sends chunk uploaded success request, Server tries to stitch these chunks which can take pretty long time (even can go upto 30 mins). This is huge problem for us as users, looking at the progress bar, sees that the file has uploaded but can't understand why the delay in marking the upload as completed.

One proper solution, according to me, is incremental stitching of chunks. Let's say, if all 10 chunks in a sequential order has reached server, do a stitch. Since server is stateless, it would be great if client can provide this information.

So on `uploadChunkSuccess` event, update a model to keep information of chunks which got uploaded.
On `uploadChunk` event, client sends an additional custom header saying first `x` chunks have reached the server. When server sees that it can stitch those chunks. This feature of adding dynamic custom headers on each chunk upload is not currently supported by FineUploader.

Does this usecase and solution makes sense or is there a better solution?

**Comment by rnicholus** [comment]
This sounds pretty complicated, and I don't see it being an appealing feature for most. This becomes even more complicated with the concurrent chunking feature enabled. I don't plan on implementing something like this.

If you are having issues with the time required to combine all chunks, you have a number of options to mitigate this:
- Use Fine Uploader S3 or Fine Uploader Azure. Chunk combining seems to be very quick.
- Send larger (fewer) chunks. In my experience, this reduces some of the overhead.
- Combine the chunks in a separate thread, and simple return a 202 to the chunking success request.
