### ISSUE TITLE
Proper support for "standard" request headers/params when uploading to S3

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#1494]
Work to support `Cache-Control`, `Content-Disposition`, `Content-Encoding`, `Content-MD5`, `x-amz-server-side-encryption-customer-algorithm`, `x-amz-server-side-encryption-customer-key`, and `x-amz-server-side-encryption-customer-key-MD5` started with #1258, but there are still some issues that prevent use of these headers.

TODO:
- [x] Do _not_ escape values for these fields. This type of escaping will, for example, break the `Content-Disposition` header. If any of these standardized header values needs to be encoded, the integrator must do so before passing the value on to Fine Uploader.
- [x] The header names are being converted to lower-case before deciding if they are custom. Since the list of standard/non-custom headers is mixed-case, we are still prefixing non-custom headers w/ `x-amz-meta`. 
- [x] We need unit tests to cover use of some of these headers.
- [x] Documentation updates?

**Comment by rnicholus** [comment]
Regarding header values of custom headers, I think the best approach is to simply leave these alone. If encoding is needed, the developer integrating with Fine Uploader S3 will need to properly encode these values before forwarding them on to Fine Uploader.

**Comment by rnicholus** [comment]
This has been completed and is available in the develop branch as 5.5.0-2. I plan to release this with 5.5.0.

**Comment by neilchaudhuri** [comment]
What's the ballpark for the 5.5.0 release? Curious for my own migration planning purposes.

**Comment by rnicholus** [comment]
@neilchaudhuri I will be on a short vacation for most of this, and I plan to release 5.5.0 mid-next week, perhaps around the 20th or 21st. If I run into issues during final testing, I'll aim for a release the following week, provided the issue encountered are not significant.

**Comment by rnicholus** [comment]
All tests are passing in all supported browsers, so the release of 5.5.0 next week is likely.
