### ISSUE TITLE
Bug Fix, Feature Request?

### ISSUE THREAD

**Issue by 100ent** [FineUploader/fine-uploader#1497]
My issue was closed prematurely, please review my responses. I believe you do not quite understand the issue. If you simply do not wish to work on this, I will change the code myself. But it is in fact a problem that should be addressed.

https://github.com/FineUploader/fine-uploader/issues/1496

**Comment by 100ent** [comment]
If screenshots are need please let me know I can show a complete walk through of this problem.

**Comment by rnicholus** [comment]
Comment in that case, not in a new one.
