### ISSUE TITLE
How to upload a file on s3  using vb6

### ISSUE THREAD

**Issue by webproofmt** [FineUploader/fine-uploader#1500]
How to upload a file on s3  using vb6 or vbscript
Is fine upload support vb6 or vbscript?

**Comment by dbeg** [comment]
A Fine Uploader S3 signing server can be implemented in almost any language you wish. However only [PHP](https://github.com/FineUploader/php-s3-server), Java, and Node.js [example servers](https://github.com/FineUploader/server-examples) are actively maintained by the FU team (though a few other examples are included). To leverage this functionality within VB6 or VBScript you will need to [write you own server](http://docs.fineuploader.com/branch/master/endpoint_handlers/amazon-s3.html), which is a fairly simple endeavor and is [heavily documented](http://blog.fineuploader.com/2013/08/16/fine-uploader-s3-upload-directly-to-amazon-s3-from-your-browser/#server-side-integration).

If you have any further questions that are not actual issues or feature requests, please ask within [StackOverflow](http://stackoverflow.com/questions/tagged/fine-uploader).

**Comment by webproofmt** [comment]
Is it possible you will send me the response formats that we use in fine uploader so that I can write my own code for it?

**Comment by dbeg** [comment]
Everything you will need to know in order to create your own server can be found in our [documentation](http://docs.fineuploader.com/branch/master/endpoint_handlers/amazon-s3.html) as well as an [in-depth, step-by-step blog post](http://blog.fineuploader.com/2013/08/16/fine-uploader-s3-upload-directly-to-amazon-s3-from-your-browser/).

**Comment by webproofmt** [comment]
I am using below Policy format and creating a application/json format with policy base 64 and signature sha base 64 but getting "Error attempting to parse signature response: SyntaxError: Unexpected token s" error. Can you suggest where I am wrong:

strToPolicy =  "{""expiration"": ""2015-01-01T12:00:00.000Z"", ""conditions"": [ {""bucket"": manishtests3.s3-website-ap-southeast-1.amazonaws.com }, {""acl"": ""public-read"" },{""key"": my access key id},{""x-amz-meta-qqfilename"": Search.png}, ]}"

**Comment by dbeg** [comment]
This issue tracker is not for general troubleshooting. Please leverage [StackOverflow](http://stackoverflow.com/questions/tagged/fine-uploader).
