### ISSUE TITLE
Request not working from vb6

### ISSUE THREAD

**Issue by webproofmt** [FineUploader/fine-uploader#1501]
I am using below Policy format and creating a application/json format with policy base 64 and signature sha base 64 but getting "Error attempting to parse signature response: SyntaxError: Unexpected token s" error. Can you suggest where I am wrong:

strToPolicy = "{""expiration"": ""2015-01-01T12:00:00.000Z"", ""conditions"": [ {""bucket"": manishtests3.s3-website-ap-southeast-1.amazonaws.com }, {""acl"": ""public-read"" },{""key"": my access key id},{""x-amz-meta-qqfilename"": Search.png}, ]}"

**Comment by dbeg** [comment]
This issue tracker is not for general troubleshooting. Please leverage [StackOverflow](http://stackoverflow.com/questions/tagged/fine-uploader).
