### ISSUE TITLE
Need support to integrate fine uploader from vb6

### ISSUE THREAD

**Issue by webproofmt** [FineUploader/fine-uploader#1502]
I have already done all the steps to generate policy document and vb6 code to solve the problem but getting Error attempting to parse signature response: SyntaxError: Unexpected token s.
What to look and where to ask. I am in the final stage of implementation and buying your product but not getting any useful help from any where to finish my demo part.
If possible kindly reply over this :
 http://stackoverflow.com/questions/34046983/fine-uploader-request-not-working-from-vb6

**Comment by webproofmt** [comment]
Dbeg are you going to help me out???????????

**Comment by dbeg** [comment]
Please be patient. Your question has [been answered](http://stackoverflow.com/questions/34046983/fine-uploader-request-not-working-from-vb6/34048261#34048261).
