### ISSUE TITLE
Feature Request - Allow s3 custom headers

### ISSUE THREAD

**Issue by NamespaceValentine** [FineUploader/fine-uploader#1511]
We are running into an issue with the out of box FineUploader, we cant set custom headers on our requests. When we try to upload through Cloudfront, the owner of the upload (on chunked uploads) is the Cloudfront OAI. This leads to all sorts of headaches when dealing with the access permissions on an object, public read is too open, owner access settings are too closed off. We would like to be able to specifically grant access to a given identity using the x-amz-grant-read headers (http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadInitiate.html), but are unable to using FinUploader.

**Comment by NamespaceValentine** [comment]
A workaround for anyone experiencing this issue is to set ACL to authenticated-read and give the user you want (in our case the canonical id of another cloudfront distro) full permissions on the bucket. However, I would still think that allowing this feature is a Good Idea.

**Comment by rnicholus** [comment]
You can set custom headers/params using the [`setParams` API method](http://docs.fineuploader.com/branch/master/api/methods.html#setParams) _or_ the [`request.params` option](http://docs.fineuploader.com/branch/master/api/options-s3.html#request.params). In most cases, Fine Uploader S3 will include an x-amz-prefix to this params.

There are a few enhancements, along with a dedicated documentation section on the S3 feature page. These enhancements likely don't pertain to your case, but you can see the updated docs for the next scheduled release (5.5.0) at http://docs.fineuploader.com/branch/develop/features/s3.html#headers.

Your request makes it sound like there is no way to set custom headers, which I've answered, so I will close this case. If you were actually looking for something else, let me know and I can consider re-opening.

**Comment by NamespaceValentine** [comment]
As far as I am able to see, setting x-amz-grant-read as a param is not respected as a header request by AWS s3. They require that the grant be sent as a custom header and I see no documentation showing it being possible as a param instead. I did a test using fineuploader to process the request under two syntax:
'x-amz-grant-read':'id="<canonical id>"'
'x-amz-grant-read':'id=<canonical id>'

Two things I noted:
1) On non-chunked uploads, the headers came through as:
x-amz-meta-x-amz-grant-read
But did not correctly allow access to the canonical id given, access was denied
2) On chunked uploads the metadata header was not set on the object at all

This leads me to believe that for this header, it cannot be sent as metadata, or the synax for it differs from their documentation (http://docs.aws.amazon.com/AmazonS3/latest/API/RESTBucketPUT.html)

**Comment by NamespaceValentine** [comment]
As a note, we are delivering this content through CloudFormation if that makes a difference. Here are my options:
`{
                element: document.getElementById('sr-fine-uploader'),
                template: 'qq-template-s3',
                request: {
                    endpoint: 'https://subdomain.cloudfront.net',
                    accessKey: "access key here",
                    params: {
                        'x-amz-grant-read':'id="canonical id here"'
                    }
                },
                cors: {
                    expected:true
                },
                chunking: {
                    enabled:true,
                    partSize: 10485760,
                    concurrent: {
                        enabled:true
                    }
                },
                objectProperties: {
                    bucket: "bucket name here",
                    host: "s3 host name here",
                    region: "us-west-2",
                    serverSideEncryption: true,
                    key: function(id){
                        return keyPrefix() + s3Uploader.getName(id);
                    }
                },
                signature: {
                    endpoint: '/signature',
                    version: 4
                },
                retry: {
                    enableAuto: true
                }
            }`

**Comment by NamespaceValentine** [comment]
Deleted my last two comments, please disregard as our testing suite was bugged. Sending the header as a meta param is working correctly, thank you.

**Comment by NamespaceValentine** [comment]
Syntax:
params: {
                        'x-amz-grant-read':'id=canonical id here'
                    }
