### ISSUE TITLE
Feature Request: Allow for Re-uploading of chunks

### ISSUE THREAD

**Issue by psusmars** [FineUploader/fine-uploader#1513]
Recently, some of our users were reporting corrupted data when uploading to S3 and then downloading the file. We're currently using the javascript/jquery FineUploader interface to do multi-part uploads direct to S3. To replicate the issue, and I'm sure there are other ways, we created a zip with a bunch of image files, initiated the upload and then used a utility (like Clumsy) to tamper with a percentage of the packets. The chunks complete successfully, but when the upload completes and we download the file, we'd use 7zip to check the zip for errors and found that there was corruption of the bytes.

What would be great is if there was some way to re-initiate a chunk around "uploadChunkSuccess" if the etag response from S3 for the chunk was different than the initially calculated MD5 checksum. 

I know that currently I could calculate the checksum for the entire upload and if the etag from s3 doesn't match the checksum, but that would force the user to re-upload the entire file, and the average upload size is >1GB with the users using slow internet.

**Comment by rnicholus** [comment]
The best way to handle this situation is to use version 4 signatures with Fine Uploader S3. With version 4 signatures, the entire chunk is hashed and included as part of the signature. AWS re-calculates the hash/signature server-side, and if there is a mistmatch, the upload fails.

**Comment by psusmars** [comment]
Oh duh, thanks! It didn't even occur to me that the documentation that was referring to this exact scenario in the S3 documentation required V4 signatures: http://docs.aws.amazon.com/AmazonS3/latest/API/mpUploadUploadPart.html. Also thank you again for the phenomenal effort you put into this project. It's greatly appreciated.

**Comment by rnicholus** [comment]
You're quite welcome. Version 4 signature support was added to Fine Uploader in version 5.4.0. The blog post I linked to (which I wrote) explains how to get up and running with that workflow. There are sections on the docs site that deal with version 4 (and version 2) signature generation server-side as well, such as http://docs.fineuploader.com/branch/master/endpoint_handlers/amazon-s3.html.

**Comment by psusmars** [comment]
In the off chance someone stumbles here, or if you have a better place to put this, I've put up a gist of how to create the V4 signature in Ruby: https://gist.github.com/psusmars/7b0966711752bee28c12

**Comment by rnicholus** [comment]
@psusmars A pull request into the server-examples repo would be most appropriate. If your code works and you are sure to include it in a ruby dir, I'd be happy to include it there.
