### ISSUE TITLE
What if we don't include signature handler while uploading to amazon s3?

### ISSUE THREAD

**Issue by sudipbhandari126** [FineUploader/fine-uploader#1517]
I am trying to set up fineuploader for amazon s3 however I am having difficulties in understanding handler part.

**Comment by dbeg** [comment]
> Signing policy documents server-side is the one mandatory task your server must perform, regardless of features enabled and browsers supported.

Fortunately this process is [heavily documented](http://blog.fineuploader.com/2013/08/16/fine-uploader-s3-upload-directly-to-amazon-s3-from-your-browser/#server-side-integration) with numerous [server-side examples](https://github.com/Widen/fine-uploader-server) available.

If you have any further questions that are not actual issues or feature requests, please ask within [StackOverflow](http://stackoverflow.com/questions/tagged/fine-uploader).
