### ISSUE TITLE
Documentation Update: Note to escape keys properly for S3

### ISSUE THREAD

**Issue by psusmars** [FineUploader/fine-uploader#1518]
When I've been trying to sign my requests using Version 4 I noticed I would receive 'The request signature we calculated does not match the signature you provided. Check your key and signing method.' from AWS when I had a file with a "+" sign in it. I generate my own file names using the objectProperties:key option with a callback. Below is the first portion of the headers passed to my signing function that has the S3 key that I specify:
```
POST\n/uploads/missions/FINE-a1da0f54-d2c8-4423-a037-995556c7f178/66ft+High+Overlap+8-14.zip...
```

What amazon expects for the canonical request:
```
POST\n/uploads/missions/FINE-a1da0f54-d2c8-4423-a037-995556c7f178/66ft%2BHigh%2BOverlap%2B8-14.zip...
```

When I properly return the escaped the "+", everything runs smoothly. Since it should probably fall on me to properly escape everything per AWS requirements (since I may add slashes), a note on the documentation to use "encodeURIComponent" would be helpful. 

For reference, here's my setting of the key:
```javascript
initializing_hash["objectProperties"]["key"] = function(fileId) {
        return "uploads/missions/FINE-" + this.getUuid(fileId) + "/" + this.getName(fileId);
      };
```

**Comment by psusmars** [comment]
This may actually be a bug, since if I specify "filename" as the key property (leaving it to Fine Uploader to specify), I still don't receive the properly escaped path for signature generation in the canonical request:
```
POST\n/66ft+High+Overlap+8-14.zip\
```

**Comment by rnicholus** [comment]
Yes, this may very well be a bug. I'll look into this further and if I am still able to reproduce on develop, I'll hold up the 5.5.0 release and include this as a fix as well.

**Comment by rnicholus** [comment]
I tested on master and on develop, and am not able to reproduce this issue. I tested using two different filenames with at least one `+` in the filename, both chunked and non-chunked. Both uploads completed without issue using the PHP signature server 1.1.0 included at https://github.com/FineUploader/php-s3-server.
