### ISSUE TITLE
API documentation does not work

### ISSUE THREAD

**Issue by dofinium** [FineUploader/fine-uploader#1520]
Sorry, it is related to your hosting, not to project. It is impossible to open http://docs.fineuploader.com/branch/master/api/methods.html, http://docs.fineuploader.com/branch/master/api/events.html and some other pages. Connection timeout...

Is it possible to upload somewhere full documentation in archive? Thank you

**Comment by dbeg** [comment]
I receive an HTTP 200 response when attempting to access both of those docs pages. Can you further explain what responses you're receiving?

Also, all the documentation is included within the [fine-uploader repository](https://github.com/FineUploader/fine-uploader/tree/master/docs), should you care to build it locally.

**Comment by dofinium** [comment]
![capture](https://cloud.githubusercontent.com/assets/8024202/12490703/8f5cdb7a-c07f-11e5-9b15-e483369e51b2.PNG)
Probably some problem with my connection. It works through translate.google.com. Thank you.
