### ISSUE TITLE
Upload S3 : send thumbnails to a different bucket

### ISSUE THREAD

**Issue by fundup** [FineUploader/fine-uploader#1532]
## Type of issue 
"feature request"
## Uploader type
"S3"

## Feature details

Hy,
I'm wondering if there is any possibility to upload scaled images in a different bucket. 
I'm aware of scaling option : 
`scaling: {
                    sizes: [
                        {name: "small", maxSize: 100},
                        {name: "medium", maxSize: 300}
                    ]
}`
But those thumbnails are send the same bucket. So if this bucket has a restricted access you will not be able to retrieve thumbnails. I would like to send those scaled images in a 'public' bucket (or to cloudfront ?) .

So a second option is to move thumbnails to another bucket when upload is done ... but maybe there is a better option.

Thanks for your help.

**Comment by dbeg** [comment]
I'm fairly certain this feature is not available within FU, as the [`request.endpoint`](http://docs.fineuploader.com/branch/master/api/options.html#request.endpoint) is not something that is configurable beyond one value for all requests.

Your second option of moving the thumbnails upon upload completion is perhaps the best, and easiest option. There are a number of ways to accomplish this, and as always you will have a handle on complete files within the [`onComplete` callback](http://docs.fineuploader.com/branch/master/api/events.html#complete).

**Comment by fundup** [comment]
OK thanks for that. I will post my solution when I will finish.

**Comment by keyeh** [comment]
My solution to this was to move the image in the create endpoint.

**Comment by fundup** [comment]
Here is an example of solution using Php and Aws/sdk, after having upload thumb : 

`public function moveToAnotherBucket($objectKey) {
        $s3Client = $this->getS3Client();
        /** @var Aws\Result $copy */
        $copy = $s3Client->copyObject([
            'Bucket' => self::thumb_bucket, //target
            'Key' => self::thumb_prefix."{$objectKey}", //new key
            'CopySource' => "{$this->expectedBucketName}/{$objectKey}", //source :bucket/key
        ]);
        $this->deleteFileInBucketAfterCopy($s3Client, $copy, $objectKey);
        return self::thumb_bucket;
    }
`
deleteFileInBucketAfterCopy use $s3Client->deleteObject() function.
