### ISSUE TITLE
Compatibility issue with Kaspersky anti-virus (uploads get stuck) on Chrome/Windows

### ISSUE THREAD

**Issue by alphestdev** [FineUploader/fine-uploader#1536]
Symptoms: Uploads freeze at a random %.

Type of issue: bug
Uploader type: traditional
Fine Uploader version: 5.5.1
Browsers where the bug is reproducible: Chrome 49.0.2623.75 (latest)
Operating systems where the bug is reproducible: Windows 7 x64 (up-to-date)
Exact steps required to reproduce the issue:
1. Try to upload files. The larger the file, the bigger the chance to get it stuck.

Incompatible product: Kaspersky Internet Security 2016 (16.0.0.614 / latest).

**Detailed explanation of the problem:**
The issue occurs with and without chunking. With chunking enabled, the it takes longer to time out, but it gets stuck as quickly. Files of ~200KB upload ok most of the time. Files of 2MB get stuck most of the time. Files of 10MB+ get stuck 100% of the time. I think how much is uploaded before it hangs depends on upload speed + machine performance. Developer tools show that every few seconds Kaspersky sends requests needed for it's internal functioning. These requests probably interrupt the uploading of fineuploader. It does not happen on other browsers (IE,FF) although Kaspersky uses the same thechnique there (can be observed in FireBug). If Kaspersky is turned off, the issue still occurs. If Kaspersky is closed completely, the issue disappears.

**Comment by rnicholus** [comment]
I'd suggest either not using Kaspersky, or contacting Kaspersky support to further troubleshoot this issue. There is nothing Fine Uploader can do to prevent another application from intercepting the HTTP requests it sends.

**Comment by alphestdev** [comment]
I haven't investigated it further, but I doubt that the requests are being "intercepted". It would not make sense for KIS to let some through and block others from the same upload. The fact that it still happens when KIS is turned off, means that the requests are not being blocked on purpose. I think it's a bug in Chrome while handling parallel requests. 

I can contact Kaspersky or Google, but I don't think they will move a finger for that. Their products are working fine.

**Comment by rnicholus** [comment]
The issue is, without a doubt, caused by Kaspersky. I've seen this more times than I can count. As you mentioned yourself, this issue goes away when Kaspersky is closed.
