### ISSUE TITLE
Feature Request - Allow file validation function before upload.

### ISSUE THREAD

**Issue by NamespaceValentine** [FineUploader/fine-uploader#1538]
## Type of issue [REQUIRED]
Feature Request

## Uploader type [REQUIRED]
Core/S3

### Detailed description of the feature
Arbitrary file validation function

A function that would be called with expected return of true/false for whether the file can be uploaded.
Our use case for this is... ridiculous, but the functionality for this is broadly useful. In our case we are required by our IT dept to disallow certain file extensions/names to be uploaded. Fineuploader currently allows us to add a whitelist for extensions, but we require a blacklist instead, and beyond that we also require certain file names to throw an alert.

**Comment by rnicholus** [comment]
This is already possible by examining the proposed files and either returning true/false or a Promise inside of an onValidate, onValidateBatch, or onSubmit callback. All of this and more related to file validation is detailed at http://docs.fineuploader.com/branch/master/features/validation.html.

**Comment by NamespaceValentine** [comment]
Ah ok, I see it now, it is in the callbacks options rather than the validation options, for anyone who comes across this issue:
http://docs.fineuploader.com/branch/master/api/events.html#validate

**Comment by Tailzip** [comment]
Hi,

I'm trying to validate a file before upload, I followed the documentation, so I'm returning a promise in my `onSubmit` callback but my file isn't being uploaded (I'm using S3 wrapper) when the promise is fullfilled. Here a simple code, that I believe should work, but it doesn't...

```js
const onSubmit = (id, name) => {
  const p = new qq.Promise();

  setTimeout(() => {
    p.success();
  }, 2000);

  return p;
};
```

Any thoughts?

Thanks!
