### ISSUE TITLE
chunked upload in CEF Chromium embedded Framework

### ISSUE THREAD

**Issue by madjarian** [FineUploader/fine-uploader#1539]
## Type of issue
{Choose one: "bug" or "feature request"}
bug

## Uploader type
{Choose at least one: "traditional", "S3", "Azure"}
Traditional

### Fine Uploader version
5.5.1

### Browsers where the bug is reproducible
Chromium Embedded Framework 3 in adobe premiere

### Operating systems where the bug is reproducible
Windows 7 64 bits

### Exact steps required to reproduce the issue
For example:
1. Select 1 files with size greater than 10MB
2. The file is sent with chunk
3. The endpoint url is sent in post, but no variable inside
4. on the server side the UploadHandler cannot find filename

### All of your Fine Uploader initialization JavaScript code
var manualuploader = new qq.FineUploader({
			        d:true,
			        maxConnections:3,
			        multiple:true,
			        request: {
			        endpoint: currentServer.baseUrl+'/app_groupe_prod.php/fr_FR/fineuploader/endpoint',
			        customHeaders:{ 'X-Requested-With':'XMLHttpRequest' },
			        forceMultipart: true },
			        autoUpload: true,
			        text: { uploadButton: '<i class="icon-plus icon-white"></i> Select Files'
			        },
			        debug: true,
                                chunking:{
		                enabled: true,
		                multiple: { enabled: true },
		                partSize: 4048576
		                maxConnections:3,
		                concurrent: {enabled: true},
		                success: { endpoint: currentServer.baseUrl+'/app_groupe_prod.php/fr_FR/fineuploader/endpoint' }
		            },
		            retry: {
		                enableAuto: true,
		                maxAutoAttempts:2
		                },
                    validation:{
                        sizeLimit:0
                    },
		            cors:{
		            	allowXdr:true
		            },
		            resume: {
		                enabled: false,
		                recordExpireIn: 100
		                }, 
		 				}
			    );

### Detailed explanation of the problem [REQUIRED]
when i upload a small file (without chunking) all is fine
When i upload a bigger file 10MB, the request sent with post is empty
qquuid, qqfilename, qqtotalfilesize qqfile[name] are empty !

**Comment by rnicholus** [comment]
Please show the request headers for a chunked request, according to your browser's dev tools.

**Comment by madjarian** [comment]
# REQUEST:
Request URL:http://open-demo.groupetransatlantic.com/app_groupe_prod.php/fr_FR/fineuploader/endpoint
Request Method:POST
Status Code:200 OK200 OK
Request Headersview source
Accept:application/json
Cache-Control:no-cache
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryOruK3bKL4xPyEvBA
Origin:file://
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/27.0.1453.110 Safari/537.36
X-Requested-With:XMLHttpRequest, XMLHttpRequest
Request Payload
------WebKitFormBoundaryOruK3bKL4xPyEvBA
Content-Disposition: form-data; name="qquuid"

69b91e78-fe45-4519-af52-4be134568fe0
------WebKitFormBoundaryOruK3bKL4xPyEvBA
Content-Disposition: form-data; name="qqfilename"

ADAM_AA0437.mov
------WebKitFormBoundaryOruK3bKL4xPyEvBA
Content-Disposition: form-data; name="qqtotalfilesize"

52589829
------WebKitFormBoundaryOruK3bKL4xPyEvBA
Content-Disposition: form-data; name="qqfile"; filename="ADAM_AA0437.mov"
Content-Type: application/octet-stream


------WebKitFormBoundaryOruK3bKL4xPyEvBA--
Response Headersview source
Cache-Control:no-cache
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:65
Content-Type:text/plain; charset=UTF-8
Date:Mon, 07 Mar 2016 17:18:03 GMT
Keep-Alive:timeout=5, max=100
Server:Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.5.30
Vary:Accept-Encoding
X-Powered-By:PHP/5.5.30

# RESPONSE:
{"error":"File name empty.","uploadName":null} <- we checked the $_REQUEST['qqfilename'] or ($_FILES[$this->inputName]

**Comment by rnicholus** [comment]
According to the request headers you just posted, the parameters _are_ being sent to your server. The issue appears to be with your server-side code. The PHP example at https://github.com/FineUploader/php-traditional-server handles chunked and non-chunked requests correctly. You might either want to pull that down using composer, or model your code according to that example.

**Comment by uyson** [comment]
@rnicholus   chunk upload send wrong content-type, 
```
Content-Disposition: form-data; name="qqfile"; filename="ADAM_AA0437.mov"
Content-Type: application/octet-stream
```
why the component send wrong content-type,

**Comment by rnicholus** [comment]
Nothing Fine Uploader can do to fix that. The browser makes that determination.

**Comment by uyson** [comment]
@rnicholus  thanks, I got it.
