### ISSUE TITLE
How to alter FineUploader's in-memory file list?

### ISSUE THREAD

**Issue by Korijn** [FineUploader/fine-uploader#1540]
## Type of issue
Feature Request

## Uploader type
Azure

### Detailed description of the feature
Our clients use FineUploader to upload datasets of ~1MB files, usually having a total size in the range of 100 - 400 MB. Sometimes we encounter outliers which are > 500 MB in size. Since we have to pre-process the binary data in the client (using webworkers etc.) before uploading, we read the files into memory.

It turns out that browser have a limit on the amount of memory `Blob` objects can take up in total, [see this page for a browser overview](https://github.com/eligrey/FileSaver.js/#supported-browsers). When we go over that limit, any new `Blob` objects are simply not stored resulting in errors.

I've checked our codebase, and we don't keep references to these `Blob` objects, so I can only point my finger at FineUploader at this point. I'm trying to see if I can release these objects from FineUploader's memory somehow, but it's not clear to me from the docs. They're pretty much stored as a property on FineUploader's objects, so I think I should be able to remove them post-op. 

This isn't really a feature request, but I'd definitely like some pointers on how I should approach this problem.

**Comment by rnicholus** [comment]
I'm sorry, but Fine Uploader does not store blobs in memory. In fact, I was extra careful about this when writing the scaling feature as well. If you can point to a specific bug in the code where I am caching blobs by accident, I'll be happy to re-open and fix, but I would be very surprised to find that this is happening. 

Keep in mind that blobs that reference files selected or dropped by the user do not take up any memory, they are just pointers to bytes on a file system. The only time blobs consume memory is when they are created, such as with the scaling feature.

**Comment by Korijn** [comment]
OK, then it's probably my own code that is creating the problem. Thanks for the info.

**Comment by Korijn** [comment]
Just an FYI for others looking at this:

Scaling calls `createObjectURL` but it never calls `revokeObjectURL`, so be careful about that.

Otherwise, you can do:

```
                onComplete: function (id, name, responseJSON, xhr) {
                    this._handler.expunge(id);
                },
```

**Comment by rnicholus** [comment]
Can you please open up a new issue with your above finding? Fine Uploader really should call `revokeObjectURL` once the scaled `Blob` is created. I'm not sure if this can be done for thumbnails as well, but it merits investigation.

**Comment by Korijn** [comment]
Sure. I'm not actually using scaling feature though, I just concluded that from a search through FineUploader's source.

Turns out we're simply the victim of a browser bug present in _every single browser_. :( For example, [here's Chromium's bug](https://bugs.chromium.org/p/chromium/issues/detail?id=375297), and [here's an overview of the limits/bugs per browser](https://github.com/eligrey/FileSaver.js/#supported-browsers). Hope this helps anyone who stumbles upon this thread.
