### ISSUE TITLE
RE: chunked upload in CEF Chromium embedded Framework

### ISSUE THREAD

**Issue by madjarian** [FineUploader/fine-uploader#1541]
## Type of issue
{Choose one: "bug" or "feature request"}
bug

## Uploader type
{Choose at least one: "traditional", "S3", "Azure"}
Traditional

### Fine Uploader version
5.5.1

### Browsers where the bug is reproducible
Chromium Embedded Framework 3 in adobe premiere CC 2015

### Operating systems where the bug is reproducible
Windows 7 64 bits

### Exact steps required to reproduce the issue
For example:
0. on traditional server side : php configured with post_max_size = 10M 
1. Select 1 files with size greater than 10MB
2. The file is sent with chunk partsize configured : 2000000 (default)
3. The endpoint url is sent in post.
4. on the server side i got php warning post size 
PHP Warning:  POST Content-Length of 52590783 bytes exceeds the limit of 10485760 bytes

### All of your Fine Uploader initialization JavaScript code
var manualuploader = new qq.FineUploader({
			        d:true,
			        maxConnections:1,
			        multiple:false,
			        request: {
			        endpoint: currentServer.baseUrl+'/app_groupe_prod.php/fr_FR/fineuploader/endpoint',
			        customHeaders:{ 'X-Requested-With':'XMLHttpRequest' },
			        forceMultipart: true },
			        autoUpload: true,
			        text: { uploadButton: '<i class="icon-plus icon-white"></i> Select Files'
			        },
			        debug: true,
                                chunking:{
		                enabled: true,
		                multiple: { enabled: true },
		                partSize: 2000000
		                maxConnections:1,
		                concurrent: {enabled: false},
		                success: { endpoint: currentServer.baseUrl+'/app_groupe_prod.php/fr_FR/fineuploader/endpoint' }
		            },
		            retry: {
		                enableAuto: true,
		                maxAutoAttempts:2
		                },
                    validation:{
                        sizeLimit:0
                    },
		            cors:{
		            	allowXdr:true
		            },
		            resume: {
		                enabled: false,
		                recordExpireIn: 100
		                }, 
		 				}
			    );

### Detailed explanation of the problem [REQUIRED]
In chromium embedded, the post size is the total file size, not the chunk size.

this guys, had the same issue in CEF with Plupload in the past:
http://www.magpcss.org/ceforum/viewtopic.php?f=6&t=11242

**Comment by rnicholus** [comment]
This indicates that chunking is not supported in whatever browser you are using.

**Comment by madjarian** [comment]
I always got true on qq.supportedFeatures.chunking and qq.supportedFeatures.uploading

**Comment by rnicholus** [comment]
Sounds like a bug in the `slice` method of your browser then. I'll keep this open for others to discover, but there's not much else I can do as far as I can tell.

**Comment by madjarian** [comment]
ok thx you
