### ISSUE TITLE
Option to exclude exe file in Fineuploader

### ISSUE THREAD

**Issue by Manidipa** [FineUploader/fine-uploader#1544]
Hi Ray

Is there any option to exclude exe or any other file type in Fine Uploader

Regards
Manidipa

**Comment by rnicholus** [comment]
You can use built-in validation using some of the built-in `validation` options, or even write your own custom validation by registering an `onValidation` or `onValidationBatch` handler. See the [validation feature page](http://docs.fineuploader.com/branch/master/features/validation.html) for details.
