### ISSUE TITLE
Session Upload Progress, PHP

### ISSUE THREAD

**Issue by deviprsd21** [FineUploader/fine-uploader#1546]
## Feature Request (Traditional) [5.5.0]
Support for PHP Session Upload Progress. Fine Uploader is pretty capable of showing the progress, but this feature will support old browsers, as the progress will be tracked by php in some other remote server.

**Comment by rnicholus** [comment]
Given the fact that all browsers that would benefit from this feature are no longer supported by Microsoft, I doubt this will make it into any future release as there are far more pressing issues to be dealt with. That said, I'm going to close this accordingly, but I do thank you for the request.
