### ISSUE TITLE
Capitalization prevents dialogs from being displayed in Chrome

### ISSUE THREAD

**Issue by bengal75** [FineUploader/fine-uploader#1548]
## Type of issue
Bug

## Uploader type
Reproduced when using S3 (but probably irrelevant)

### Fine Uploader version
5.5.2

### Browsers where the bug is reproducible
Chrome 49. Firefox 45 does NOT have the same issue. No others tested.

### Operating systems where the bug is reproducible
Ubuntu 14.04

### Exact steps required to reproduce the issue
Enable deletion and force confirm:
```javascript
...
	deleteFile: {
		enabled: true,
		forceConfirm: true,
		endpoint: "/server/file"
	},
...
```
Then upload a file and attempt to delete it once the upload is complete.

### Detailed explanation of the problem
On following the above steps we expect a dialog box asking for confirmation. Nothing is shown and the file is not deleted. No request is made to the server.

In this file:

https://github.com/FineUploader/fine-uploader/blob/a0461a8d858f3c0f0ff186af79158cc988104d87/client/js/templating.js

on line 223, in getDialog(), changing the string "Dialog" to "dialog" resolves the issue.

**Comment by rnicholus** [comment]
Please show your HTML template and the rest of your JavaScript code, along with any log messages printed to your browser's dev tools console. As it stands, with what you have provided, this is not reproducible, so there is something specific about your environment or code that is causing this issue to occur.

**Comment by bengal75** [comment]
Apologies, it seems that this is due to my including CSS from Zurb Foundation 5, which by default sets the visibility property on the dialog element to 'hidden'. Fine Uploader evidently doesn't expect this, and does not change the element's visibility.

Changing the string in getDialog() appears to force Chrome to use native dialogs instead, which are obviously visible. This seems related to why the whole thing is a non-issue in Firefox, where the HTML5 dialog element gets used in both cases.

Thanks for the prompt response in any case!

**Comment by rnicholus** [comment]
Thank _you_ for the detailed explanation!
