### ISSUE TITLE
setCredentials documentation missing second parameter

### ISSUE THREAD

**Issue by jfwblog** [FineUploader/fine-uploader#1550]
## Type of issue
documentation

## Uploader type
S3

## Bug details

The documentation for the `setCredentials` function is missing any reference to the optional second parameter `ignoreEmpty`

see:
http://docs.fineuploader.com/branch/master/api/methods-s3.html#setCredentials

**Comment by rnicholus** [comment]
I'm fairly sure that this second parameter was mean to be for internal use only.
