### ISSUE TITLE
Handling Azure 503 error - Server is busy

### ISSUE THREAD

**Issue by GFoley83** [FineUploader/fine-uploader#1551]
I'm using Fine Uploader 5.6.0 Basic for Azure in Chrome 49 64x on Windows 10.

My config file is similar to the following:

```javascript
var fineUploaderConfig = {
    autoUpload: false,
    //debug: true, // log all fine uploader actions
    maxConnections: 3,
    request: {
        endpoint: storageEndpoint
    },
    signature: {
        endpoint: signatureEndpoint,
    },
    chunking: {
        enabled: true,
        partSize: 4000000, // 4MB is max for Azure storage
        concurrent: {
            enabled: true // Upload in parallel 
        }
    },
    retry: {
        enableAuto: true,
        autoAttemptDelay: 10, // seconds
        maxAutoAttempts: 5
    },
    callbacks: {
        onComplete: (id, name, response, xhr) => {
            // code to notify server 
        },
        onError: (id, name, errorReason, xhr) => {
            // log error with raygun 
        }
    }
};
```
Our business revolves around uploading large files (e.g. mostly GBs in size) and recently we've started running into this issue during busy periods: 

![](http://i.imgur.com/64Sdk5D.jpg)

Obviously the 503 means Azure is under load and that we need to wait before retrying the upload.

My question is, how can we handle this error without having to re-upload the entire file?  Will manually calling [retry(id)](http://docs.fineuploader.com/branch/master/api/methods.html#retry) re-upload the entire file or just retry from whatever state the file upload is currently at? 
E.g. if a user encounters a 503 and is still in the middle of uploading, or, as in my example above, sending the final PUT request to join all the uploaded parts.

Obviously I'd like to avoid telling our customers that they have to upload their 10GB file again so any help is much appreciated.

**Comment by rnicholus** [comment]
As long as you have chunking enabled, and you are using a browser that supports chunking (anything other than IE9 and older), then Fine Uploader will retry the upload starting with the last failed chunk. In the case of a finalization error, it will only attempt to re-finalize. This behavior is standard across Fine Uploader S3, Azure, and the traditional endpoint uploader, and reflects one of the big advantages of chunked file uploading. If you are seeing an issue with this expected behavior, I'd be happy to re-open.

**Comment by GFoley83** [comment]
Thanks for the fast response Ray. So when you say:
> In the case of a finalization error, it will only attempt to re-finalize

So you mean that Fine Uploader will retry the finalize call one time and if that fails I'll just have to manually retry the upload?

My worry is that is that we'll hit the max the auto retries when chunking before Azure stops throwing 503s and it's in this scenario that I'm unsure of what to do next with Fine Uploader; start the whole upload again or manually call `retry(id)`.

**Comment by rnicholus** [comment]
>So you mean that Fine Uploader will retry the finalize call one time and if that fails I'll just have to manually retry the upload?

No, every retry attempt will repeat the same logic, whether it is manual or automatic. The only instances where the upload will restart from byte 0 is if you cancel the file, or if Fine Uploader determines that there is no way for the upload to ever succeed.

**Comment by GFoley83** [comment]
Ok great. In the case above I can probably store the file uploader instance and retry the upload after a few minutes have passed (i.e. given Azure time to recover).

**Comment by rnicholus** [comment]
What do you mean by "store the uploader instance"?

**Comment by GFoley83** [comment]
Something like below. Essentially I want to avoid abandoning the upload at all cost but also give Azure time to recover from the 503. 
E.g. All 5 auto retry attempts have failed, wait 2 minutes and retry manually. 

```javascript
// Init fine uploader object
var fineUploader = new qq.azure.FineUploaderBasic(fineUploaderConfig);
fineUploader.addFiles(file);

// Start the upload
fineUploader.uploadStoredFiles();

.....

// Below methods gets called only after some period of time (e.g. 2 minutes) if we've reached the max amount of auto retry attempts.
fineUploader.retry(someId);
```

**Comment by rnicholus** [comment]
Looks good to me!
