### ISSUE TITLE
Support S3 Transfer Acceleration

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#1556]
This _should_ just work, simply by setting the endpoint option to "BUCKET_NAME.s3-accelerate.amazonaws.com" and turning on the feature at the bucket level, but AWS is notorious for oversimplifying their announcements and leaving large gaping holes their new offerings. So this will require testing and an update in docs. The new S3 feature is documented (initially) at https://aws.amazon.com/blogs/aws/aws-storage-update-amazon-s3-transfer-acceleration-larger-snowballs-in-more-regions.

**Comment by SohKai** [comment]
They've added [more docs here](http://docs.aws.amazon.com/AmazonS3/latest/dev/transfer-acceleration.html).

It sounds like they're just leveraging Cloudfront with the accelerated endpoint, but from what I can tell in https://github.com/FineUploader/fine-uploader/issues/1016, Amazon's fixed the issues with Cloudfront that prevented FineUploader from working with it before?

**Comment by DaveDeCaprio** [comment]
I have been successfully using S3 Transfer Acceleration for a couple days with Fine Uploader and so far it's been working as advertised.  However, I don't think I've actually seen a transfer that has really leveraged the edge network yet (so far all uploads have been originating in the US and going to US-East).  I should have European and Australian uploads coming in this week though.

**Comment by rnicholus** [comment]
Thanks for the update! Can you share your Fine Uploader S3 config/options code? Have you run into any specific issues?

**Comment by DaveDeCaprio** [comment]
I can't easily share a full example, but I can say all I had to do was hit the "enable S3 Transfer Acceleration" option in the AWS Console and then set my endpoint to the s3-accelerate one.  The only code change was setting the endpoint below:

      request:
        accessKey: "XXXXXXXXX"
        endpoint: "https://my-bucket-name.s3-accelerate.amazonaws.com"

**Comment by rnicholus** [comment]
Great, then it does seem to work as I expected. This seems on track for official support in 5.8 w/ accompanying doc updates. Thanks again for your information!

**Comment by e-tip** [comment]
I confirm that fineuploader works perfectly with s3 accelerate

**Comment by SohKai** [comment]
Totally forgot about this thread, but we've been using this feature for 3 months (it's already been that long?!) without fail.

**Comment by rnicholus** [comment]
@SohKai Thanks for the update! Anything special required on your end to get this working? I'm asking in terms of Fine Uploader config and AWS config, other than turning on transfer acceleration in the associated bucket(s)?

**Comment by SohKai** [comment]
@rnicholus Nope, we did exactly what @DaveDeCaprio did a few months ago and it seems to be holding up. Just a change to the endpoint for FineUploader.

**Comment by ludofleury** [comment]
Basically, this totally override CloudFront PUT... except if you upload > 350TB per month. 
pricing for PUT accelerate is like $0.04/Gb.

**Comment by rnicholus** [comment]
If anyone is up for updating the S3 features page in the documentation to describe S3 Transfer Acceleration support, I'd be happy to review & merge. This PR can be based off of master since it's only a doc update.
