### ISSUE TITLE
Please update your document, just one line out-of-date document(maybe?) that waste me a couple of hours.

### ISSUE THREAD

**Issue by xiaoyuze88** [FineUploader/fine-uploader#1560]
## Type of issue [REQUIRED]
Document out of date(maybe?) 

### Fine Uploader version [REQUIRED]
5.6.0

## Uploader type [REQUIRED]
"traditional"

## Bug details [DELETE EVERYTHING IN THIS SECTION IF THIS IS A FEATURE REQUEST]
Today, when I'm trying the `Concurrent Chunking` feature, [In this page](http://docs.fineuploader.com/features/concurrent-chunking.html), the `Expected response for the chunking success POST` part, it says that for successful responses, just send empty body with status 200~204 back from my server. Unfortunately, it waste me a couple of hours to find out that in the `isErrorUploadResponse` function, it's like this.

```javascirpt
isErrorUploadResponse = function (xhr, response) {
  return qq.indexOf([200, 201, 202, 203, 204], xhr.status) < 0 || !response.success ||
  response.reset;
}
```
Which is telling me that besides sending status 200~204 back, I should also send a response body with a  `success=true` in there.

Maybe the document is out-of-date? Please check this out, thanks!

**Comment by rnicholus** [comment]
You are mistaken - all that needs to be returned from a chunking success endpoint is a status code.
