### ISSUE TITLE
video thumbnails from client side

### ISSUE THREAD

**Issue by siddo420** [FineUploader/fine-uploader#1564]
Its an FR for any server type but traditional in my case.

Can we use something like https://github.com/Iragne/videoThumbHtml5 to also upload thumbnails generated on the client side (so most servers that do not have support for thumbnail generation can partially support it)? The lib appears to be light weight but I haven't tested how fast it is on files with small size. 

There may be other libs available.

**Comment by rnicholus** [comment]
First, please don't delete all of the template that appears when you open an issue. I expect that to be followed. Second, I have no plans to integrate any libraries for any reason directly into Fine Uploader. It is large enough as it is, but you are of course free to integrate what vet you like, and this should all be possible without changing any source.
