### ISSUE TITLE
Download missing main file

### ISSUE THREAD

**Issue by neotropic2023** [FineUploader/fine-uploader#1578]
_build/all.fine-uploader.js Is not in the download, therefore I can not properly "demo" this.

**Comment by rnicholus** [comment]
It's certainly there for me after I build the project. Perhaps you're either not building, or there is some error when you build on your machine. Can you walk me through the steps needed to reproduce?

**Comment by rnicholus** [comment]
I presume by "download" you mean [the download page](http://fineuploader.com/customize.html) on FineUploader.com, correct? Which option have you selected under "server type"?

**Comment by neotropic2023** [comment]
Sorry, I should have been more clear. Was rushing things. I downloaded from here on GitHub. I attempted to test it, but it kept failing as it was trying to load a file that did not exists in.

**Comment by rnicholus** [comment]
Yes, if you'd like to download a pre-built version, you must either use npm or the download page. I'll close this, but feel free to re-open if the same issue persists.
