### ISSUE TITLE
i guess this is the quickest way to contact you - your blog is down

### ISSUE THREAD

**Issue by avipinto** [FineUploader/fine-uploader#1594]
blog’s domain blog.fineuploader.com expired!

**Comment by rnicholus** [comment]
ugh, thanks. I'll fix this ASAP

**Comment by rnicholus** [comment]
Fixed! Thanks again for the alert.

**Comment by mgurnani** [comment]
Your blog is down again !!

Secure Connection Failed

An error occurred during a connection to blog.fineuploader.com. Cannot communicate securely with peer: no common encryption algorithm(s). Error code: SSL_ERROR_NO_CYPHER_OVERLAP_

**Comment by rnicholus** [comment]
Thanks, I'm aware. Currently moving the blog away from WordPress, which sucks in every imaginable way, to medium, which isn't going as well as I'd hoped

**Comment by rnicholus** [comment]
back up now

**Comment by mgurnani** [comment]
Great !! Thanks !
