### ISSUE TITLE
Total Progress Bar shows progress for each file

### ISSUE THREAD

**Issue by TekLord1** [FineUploader/fine-uploader#1601]
bug
traditional
5.10
Firefox
Windows 10

The Total Progress bar shows the progress for each file instead of the total progress. This happens on both the demos section of the website and the templates.

I believe this is WRONG...

            <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
            </div>

I believe the following code change will fix the problem...

            <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-total-progress-bar"></div>
            </div>

**Comment by rnicholus** [comment]
I'll take a look at this closer when I'm near a computer, but i would be quite surprised if the total progress bar was not functioning correctly. The CSS classes could not produce the behavior you are claiming. I suspect this may be a misunderstanding on your part regarding how total progress works. To confirm this, please let me know exactly how you are able to reproduce this behavior. Total progress represents the total progress of a current batch of files. Meaning if you only select or drop one file, total progress will only reflect the progress of that single file. If you drop or select two files at once after the first file has completed, total progress will represent the progress of those two new files only. And if you drop another file while a single file is still in progress or queued, total progress reflects the progress of both of those files, etc, etc. For more information regarding the behavior of this feature, please see the total progress section at the end of the [progress bars feature page](http://docs.fineuploader.com/branch/master/features/progress-bars.html).

**Comment by TekLord1** [comment]
Thanks for the quick response.

 

I believe I understand how the total progress bar is supposed to work.

 

In the “Manually Trigger Uploads” example you can select multiple files to upload. Once selected, you click on “Upload” to start the upload process.

 

When I use this example on my traditional server I see one “total progress” bargraph at the top of the page and one bargraph associated with each file being uploaded.

 

Before the code change, the total progress bar would duplicate the value as shown for each bar. 

 

After the change, the total progress appears to work correctly.

 

In other words, if you are uploading 3 files, the total progress bar would replicate the same completion value as each file would be uploaded. After the change, the total progress bar would show 33% complete after the first file was uploaded, 66% after the second file, and finally 100% after the third file.

 

I removed qq-progress-bar  from the following line and it appeared to fix the issue …

 

<div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>

 

On another note…

 

The demo shows an “Upload” button with an embedded graphic arrow. But, the 5.10 download does not include this feature…

 





 

I would like to have this if possible.

 

Thanks again for your efforts.

 

Wayne Harris

**Comment by rnicholus** [comment]
I'm not sure what you mean by "embedded graphic arrow". To my knowledge, this sort of thing has never been included in the library. I'll take a closer look at total progress sometime next week. Thanks for the report!

**Comment by TekLord1** [comment]
Here are the two buttons. The on-line demo has a button that incorporates a graphic download icon. But when I use the exact same code the graphic does not appear. There must be something different in the CSS that is included with 5.10 vs the CSS that the demo is using.
![2016-06-25_21-35-44](https://cloud.githubusercontent.com/assets/20146885/16360928/9362fa8c-3b41-11e6-94ba-4b738c4270bf.jpg)
![2016-06-25_21-36-11](https://cloud.githubusercontent.com/assets/20146885/16360929/96b2688a-3b41-11e6-927d-04286d33868b.jpg)

**Comment by rnicholus** [comment]
That particular button, if you look at the source, includes some bootstrap css classes that add this icon. I suspect that particular demo used to demonstrate integration with bootstrap. I believe I removed that demo so that I could focus more on the native styles provided by fine uploader after I overhauled the provider style sheets, but I obviously forgot to remove a couple old bootstrap classes from that demo. I'll be sure to remove that soon.

**Comment by TekLord1** [comment]
Thanks. I have created some button graphics.
This is a very nice application. It is really great that users can resize the images and view thumbnails prior to uploading. Keep up the great work.

**Comment by rnicholus** [comment]
I'm not seeing the issue you are seeing. In fact, removing the "qq-progress-bar" CSS class from the total progress bar breaks it completely (which is what I would expect). Everything appears to be functioning as expected. If you are seeing an issue on your end, it may be due to a browser extension or some other scripts/stylesheets causing interference on the page. I think this is a more likely scenario, as this code has not changed for a very long time, and I have not received any other reports of malfunction in this regard.
