### ISSUE TITLE
close button/icon for drop zone

### ISSUE THREAD

**Issue by siddo420** [FineUploader/fine-uploader#1615]
Feature request
Traditional

In my case, once the drop zone appears successfully, there is no way to close/hide the drop zone from view using default template. I did not find a close/hide method 
If this has been done then docs need to be modified to properly highlight this feature.

**Comment by rnicholus** [comment]
Use case please

**Comment by rnicholus** [comment]
Please open a new issue (this time without deleting the template). Also provide a compelling use case for this feature request.
