### ISSUE TITLE
Problem with Azure Thumbnailgeneration using SAS Uris

### ISSUE THREAD

**Issue by Eneuman** [FineUploader/fine-uploader#1616]
## Type of issue: BUG
Uploader type: "Azure"

## Bug details
Fine Uploader version: 5.10.1
Browsers where the bug is reproducible: Edge
Operating systems where the bug is reproducible: Windows 10 x64

## Exact steps required to reproduce the issue
1) Use default azure demo template
2) Add a session.endpoint that returns a JSON containing a thumbnailUrl pointing to a blob and includes a SAS. Like this: 
`"http://127.0.0.1:10000/devstoreaccount1/arende-1/adc267d9-34bf-4504-b842-e71099f6064a.jpg?sv=2015-12-11&sr=b&sig=zw%2F%2FiwGWhhDWae%2FKVpWt2BD0vfmm6LfswObLFoVzkYs%3D&st=2016-07-18T16%3A01%3A40Z&se=2016-07-18T16%3A21%3A40Z&sp=r"`

## Details
Edge browser will return the following (debug):
[Fine Uploader 5.10.1] Session query request.
azure.jquery.fine-uploader.js (252,17)
[Fine Uploader 5.10.1] Sending GET request for sessionRefresh
azure.jquery.fine-uploader.js (252,17)
[Fine Uploader 5.10.1] Attempting to update thumbnail based on server response.
azure.jquery.fine-uploader.js (252,17)
**[Fine Uploader 5.10.1] Problem drawing thumbnail!
azure.jquery.fine-uploader.js (257,21)**

The JSON returned from my service looks like this:
`[{"name":"GetPersonaPhoto.jpg","uuid":"7ea29d4d-f4e8-4f35-8ef8-6dfee8f21554","size":"1789","deleteFileEndpoint":null,"deleteFileParams":null,"thumbnailUrl":"http://127.0.0.1:10000/devstoreaccount1/arende-1/adc267d9-34bf-4504-b842-e71099f6064a.jpg?sv=2015-12-11&sr=b&sig=zw%2F%2FiwGWhhDWae%2FKVpWt2BD0vfmm6LfswObLFoVzkYs%3D&st=2016-07-18T16%3A01%3A40Z&se=2016-07-18T16%3A21%3A40Z&sp=r","blobName":"7ea29d4d-f4e8-4f35-8ef8-6dfee8f21554.jpg"},{"name":"image4.jpg","uuid":"c263d732-f9dd-400f-9059-2a16528b2f5a","size":"501286","deleteFileEndpoint":null,"deleteFileParams":null,"thumbnailUrl":"http://127.0.0.1:10000/devstoreaccount1/arende-1/3b8fcf47-4690-4786-9b2a-d8cb40a8377e.jpg?sv=2015-12-11&sr=b&sig=PN6jWdr01AEt0uVxe7GS%2FLrHNCI8joxDLJXK3nqh2Hg%3D&st=2016-07-18T16%3A02%3A25Z&se=2016-07-18T16%3A22%3A25Z&sp=r","blobName":"c263d732-f9dd-400f-9059-2a16528b2f5a.jpg"}]`

Calling the thumbnailurl directly from a browser works to SAS is working.

Can there be a problem parsing the url for the thumbnail or am I missing something?

**Comment by Eneuman** [comment]
The problem was on my end.
When using thumbnails from Azure, you also need to add CorsHttpMethods.Get to CORS or it will not work.
Might be good to add this to docs at http://docs.fineuploader.com/branch/master/endpoint_handlers/azure.html

Thanks for a great component!

**Comment by rnicholus** [comment]
I was typing up an answer that suggested a lack of CORS headers on the Azure end. This is not an Azure-specific issue, and is documented at http://docs.fineuploader.com/branch/master/features/thumbnails.html#cross-origin-thumbnails.

Thanks for the follow-up. I'm going to close this as the issue has been resolved.
