### ISSUE TITLE
close button/icon for drop zone 

### ISSUE THREAD

**Issue by siddo420** [FineUploader/fine-uploader#1618]
## Type of issue [REQUIRED]
Feature request

## Uploader type [REQUIRED]
traditional

In my case, once the drop zone appears successfully, there is no way to close/hide the drop zone from view using default template. I did not find a close/hide method 
If this has been done then docs need to be modified to properly highlight this feature.

The use-case as requested in 1615 is a chat application. In order to attach/upload a new file, user clicks on attachment icon and the chat area becomes a drop zone, so user must be given a way to close it later to reveal the actual chat area (with messages).

**Comment by rnicholus** [comment]
Why not just hide it yourself with JavaScript and CSS?
