### ISSUE TITLE
ability to directly open system file selector on mobile devices

### ISSUE THREAD

**Issue by siddo420** [FineUploader/fine-uploader#1619]
## Type of issue 
feature request

## Uploader type
traditional

I want to be able to detect if dragging & dropping files is possible on the device and if not then I'd trigger the system file selector instead of showing the drop zone to user.

This should be possible because I can see that drop zone is disabled on mobile devices automatically.

**Comment by rnicholus** [comment]
This is covered in the [feature detection](http://docs.fineuploader.com/branch/master/browser-support.html#feature-flags) section on the docs site. See the `fileDrop` property in this case.

**Comment by siddo420** [comment]
Ok thanks.

And, is it possible to configure FU to open file selection dialog as soon as new qq.FineUploader(...) is called?

**Comment by rnicholus** [comment]
You can certainly try to do that via JS. It's conceivable that some browsers may prevent that sort of thing though. Historically that has been an issue.
