### ISSUE TITLE
Delete file problem

### ISSUE THREAD

**Issue by suhaotian** [FineUploader/fine-uploader#1621]
The Gallery View for Images example in [Demo](http://fineuploader.com/demos) has a problem.

When I select a image to upload, and click `x` cancel it, the image removed from the DOM.

But it didn't remove from memory. You can got  it from ` galleryUploader.getUploads()`.

Maybe we need a method to delete file that remove it. It's not mean the `deleteFile (id)` method that require a http request. I mean it's locally delete file from the queued files array.

**Comment by suhaotian** [comment]
@rnicholus

**Comment by rnicholus** [comment]
This isn't a problem. Fine Uploader is functioning as expected. We don't want to remove the file record from memory. Instead, we want to update the status of the record, which _is_ happening.

**Comment by suhaotian** [comment]
Saga
