### ISSUE TITLE
Invalid extensition status error

### ISSUE THREAD

**Issue by suhaotian** [FineUploader/fine-uploader#1622]
The invalid extensition file select to upload. It's status was `submmiting`.
But I think the invalid extensition file's status is `rejected`, or maybe somthing else and not the `submmiting`.
It's a feature maybe?

**Comment by rnicholus** [comment]
i don't understand the problem you are reporting

**Comment by rnicholus** [comment]
Please do not delete the template. I expect those instructions to be followed. As it stands, I cannot make any sense of your question.

**Comment by suhaotian** [comment]
I use it in react, so I don't need the template 😢

**Comment by rnicholus** [comment]
I'm talking about the issue template, the text that appeared in the text area when you opened a new issue.

**Comment by suhaotian** [comment]
Sorry
