### ISSUE TITLE
Invalid extensition status shouldn't be `submmiting` at the beginning

### ISSUE THREAD

**Issue by suhaotian** [FineUploader/fine-uploader#1623]
## Type of issue

bug

## Uploader type 

UploaderBasicApi

## Bug details

The invalid extensition file select to upload. It's status was `submmiting`.

Then I select a valid file to upload. the previous invalid extensition file's status become `rejected`

And I think it's should be `rejected` at the beginning or else something not the `submmiting`.

### Fine Uploader version 

5.10.1

### Browsers where the bug is reproducible 

chrome

### Operating systems where the bug is reproducible 
windows 10

### Exact steps required to reproduce the issue 
For example:
1. Select one invalid extensition file 
2. Log the `uploader.getUploads()`, the file's status was `submitting`
3. Select another file. Log the `uploader.getUploads()`. 
4. You can see previous invalid extensition file's status became `rejected`

### All of your Fine Uploader initialization JavaScript code 
```js

   this.uploader = new qq.FineUploaderBasic({
      debug: true,
      autoUpload: true,
      button: this._upload_btn,
      request: {
      },

      retry: {
        // enableAuto: false 
      },

      deleteFile: {
        enabled: true,
        // endpoint: path,
        // params: {},
      },

      validation: {
        allowedExtensions: allowedExtensions,
        // itemLimit: 3,
        // sizeLimit: 51200 // 50 kB = 50 * 1024 bytes
      },

      messages: {

      },

      callbacks: {    
        onValidate: (data, btn) => {
        },
        onUpload: (id, name) => {
          console.log(id)
        },                            
        onProgress: (id, name, uploadedBytes, totalBytes) => {
          this.handleSetState()
        },
        onSubmit: (id, name) => {
          this.handleSetState()
        },

        onError: (id, name, errorMsg, xhr) => {

        }
      }
    })
```

### Detailed explanation of the problem
The invalite file shouldn't be `submmiting` status

**Comment by rnicholus** [comment]
I just attempted to reproduce myself, after submitting an invalid file, the file's status was indicated as 'qq.status.REJECTED` in the associated record _and_ the appropriate `statusChange` event was triggered.
