### ISSUE TITLE
unable to merge chunks after uploading 

### ISSUE THREAD

**Issue by pooranravabe** [FineUploader/fine-uploader#1629]
I am trying following code : 

Please let me know what set of code I will write on "/chunksdone" url on our PHP server

    var duplicateCheck = 0;
    galleryUploader = new qq.FineUploader({
        element: document.getElementById("fine-uploader-gallery"),
        template: 'qq-template-gallery',
        request: {
            endpoint: URL + '/upload-file',
            method: 'POST'
        },
        chunking: {
            enabled: true,
            concurrent: {
                enabled: false
            },
            partSize: 20000,
            success: {
                endpoint: URL + '/chunksdone'
            }
        },

        resume: {
            enabled: true
        },
        retry: {
            enableAuto: true,
            showButton: true
        },
        thumbnails: {
            placeholders: {
                waitingPath: URL + '/assets/img/waiting-generic.png',
                notAvailablePath: URL + '/assets/img/not_available-generic.png'
            }
        },
        validation: {
            sizeLimit: 1073741824 * 2
        },
        callbacks: {
            onSubmit: function(id, name) {

                duplicateCheck = 0;
                var parfolder = /* physical folder name */
                    var pos = name.lastIndexOf(".");
                var ext = name.substr(parseInt(pos) + 1);

                galleryUploader.setParams({
                    'folder': parfolder,
                    'qqfilename': name,
                    'qquuid': id,
                    'ext': ext

                });

            },

            onError: function(id, name, errorReason, xhrOrXdr) {},

            onComplete: function(id, fileName, responseJSON) {

            },
            onProgress: function(id, fileName, loaded, total) {
                if (loaded < total) {
                    progress = Math.round(loaded / total * 100) + '% of ' + Math.round(total / 1024) + ' kB';
                    $('#file-' + id).removeClass('alert-info')
                        .html('<img src="' + URL + '/assets/css/loading.gif" alt="' + varInProgressPlzHold + '"> ' +
                            varMsgUploading + '&nbsp;' +
                            '“' + fileName + '” ' +
                            progress);
                } else {
                    $('#file-' + id).addClass('alert-info')
                        .html('<img src="' + URL + '/assets/css/loading.gif" alt="' + varSavingPlzHold + '"> ' +
                            +varMsgSaving + '&nbsp;' +
                            '“' + fileName + '”');
                }
            },

        },
        debug: false
    });

**Comment by rnicholus** [comment]
Sorry, but the issue tracker is for bugs and feature requests only. Please see the [support page](http://fineuploader.com/support.html) for information on how to properly ask for help. Also, a fully functional php example can be found at https://github.com/FineUploader/php-traditional-server.
