### ISSUE TITLE
Mimetype validation for Adobe Indesign files

### ISSUE THREAD

**Issue by MarkTierney1975** [FineUploader/fine-uploader#1631]
## Type of issue
bug

## Uploader type
traditional

## Bug details
I've added 'application/octet-stream,application/x-indesign,application/x-adobe-indesign' to my acceptFiles option but indesign files are still grayed out when trying to select files.

### Fine Uploader version
5.10.1

### Browsers where the bug is reproducible
Chrome

### Operating systems where the bug is reproducible
Centos 6 linux

### Exact steps required to reproduce the issue
For example:
1. Try to select .indd file to upload

### All of your Fine Uploader initialization JavaScript code
<script>
        var uploader = new qq.FineUploader({
            debug: true,
            element: document.getElementById('fine-uploader'),
            request: {
                endpoint: "http://bam.dev/assets/create",
                inputName: 'file',
                filenameParam: 'filename',
                totalFileSizeName: 'filesize'
            },
            validation: {
                itemLimit: 1
            },
            deleteFile: {
                enabled: false
            },
            retry: {
               showButton: false
            },
            addInitialFiles: [""],
            validation: {
                acceptFiles: "application/octet-stream,application/x-indesign,application/x-adobe-indesign,application/postscript,application/pdf,application/zip,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.ms-powerpoint,application/vnd.ms-powerpoint.addin.macroenabled.12,application/vnd.ms-powerpoint.presentation.macroenabled.12,application/vnd.ms-powerpoint.slide.macroenabled.12,application/vnd.ms-powerpoint.slideshow.macroenabled.12,application/vnd.ms-powerpoint.template.macroenabled.12,application/vnd.ms-excel,application/vnd.ms-word.document.macroenabled.12,application/vnd.ms-word.template.macroenabled.12,text/plain,text/rtf,image/vnd.adobe.photoshop,image/tiff,image/svg+xml,image/vnd.microsoft.icon,image/x-icon,image/bmp,image/gif,image/png,image/jpeg"
            },
            callbacks: {
                onError: function(id, name, errorReason, xhrOrXdr) {
                    //console.log(xhrOrXdr);
                    var errors = $.parseJSON(xhrOrXdr.responseText);
                    var errorsHtml= '';
                    errorsHtml += '<span class="col-md-6 col-md-offset-3 help-block"><h3>Errors:</h3>';
                    $.each( errors, function( key, value ) {
                        
                        errorsHtml += '<li><strong>' + value[0] + '</strong></li>'; 
                    });
                    errorsHtml += "</span>";
                    $('#errors').html(errorsHtml);
                    var file = uploader.getFile(id);
                    uploader.cancel(id);
                    uploader.addFiles([file]);
                },
                onAllComplete: function(succeeded, failed) {
                    if (failed.length == 0 && succeeded.length > 0) {
                        window.location.href = 'http://bam.dev/assets/success';
                    }
                },
                onUpload: function(id, name){
                    var file = uploader.getFile(id);
                    console.log('file: '+file);
                    
                    var formData = {
                        file:JSON.stringify(file),
                        title:$('input[name="title"]').val(),
                        description:$('textarea[name="description"]').val(),
                        categories:$('input[name="categories[]"]:checked').val(),
                        tags:$('input[name="tags[]"]:checked').val(),
                        new_tags:$('input[name="new_tags"]').val(),
                        filename:name
                    };
                    
                    uploader.cancel(id);
                    
                    $.ajaxSetup({headers:{'X-CSRF-Token': $('input[name="_token"]').val()}}); // CSRF protection
                    
                    $.ajax({
                      type: 'post',
                      file: file,
                      url: "http://bam.dev/assets/validate",
                      data: formData,
                      dataType: 'json',
                      success: function(data){
                        console.log('file again: '+this.file);
                        uploader.addFiles([file]);
                        //alert('success');
                        //uploader.addFiles([file]);
                        //uploader.continueUpload(id);
                      },
                      error: function(data){
                        console.log(data);
                        console.log('file again: '+this.file);
                        
                        uploader.addFiles([file]);

                        var errors = $.parseJSON(data.responseText);
                        var errorsHtml= '';
                        errorsHtml += '<span class="col-md-6 col-md-offset-3 help-block"><h3>Errors:</h3>';
                        $.each( errors, function( key, value ) {
                            errorsHtml += '<li><strong>' + value[0] + '</strong></li>'; 
                        });
                        errorsHtml += "</span>";
                        $('#errors').html(errorsHtml);
                      }
                    });
                }
            },
            disableCancelForFormUploads: false,
            multiple: false,
            chunking: {
                enabled: false
            }
        });
    </script>

### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
<script type="text/template" id="qq-template">
                            <div class="qq-uploader-selector qq-uploader" qq-drop-area-text="Drop files here">
                                <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                                    <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
                                </div>
                                <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                                    <span class="qq-upload-drop-area-text-selector"></span>
                                </div>
                                <div class="qq-upload-button-selector qq-upload-button">
                                    <div>Upload a file</div>
                                </div>
                                <span class="qq-drop-processing-selector qq-drop-processing">
                                    <span>Processing dropped files...</span>
                                    <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
                                </span>
                                <ul class="qq-upload-list-selector qq-upload-list" aria-live="polite" aria-relevant="additions removals">
                                    <li>
                                        
                                        <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                                        <img class="qq-thumbnail-selector" qq-max-size="100" qq-server-scale>
                                        <span class="qq-upload-file-selector qq-upload-file"></span>
                                        
                                        <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                                        <span class="qq-upload-size-selector qq-upload-size"></span>
                                        <button type="button" class="qq-btn qq-upload-cancel-selector qq-upload-cancel">Cancel</button>
                                        
                                        <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">Delete</button>
                                        <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                                    </li>
                                </ul>
                    
                                <dialog class="qq-alert-dialog-selector">
                                    <div class="qq-dialog-message-selector"></div>
                                    <div class="qq-dialog-buttons">
                                        <button type="button" class="qq-cancel-button-selector">Close</button>
                                    </div>
                                </dialog>
                    
                                <dialog class="qq-confirm-dialog-selector">
                                    <div class="qq-dialog-message-selector"></div>
                                    <div class="qq-dialog-buttons">
                                        <button type="button" class="qq-cancel-button-selector">No</button>
                                        <button type="button" class="qq-ok-button-selector">Yes</button>
                                    </div>
                                </dialog>
                    
                                <dialog class="qq-prompt-dialog-selector">
                                    <div class="qq-dialog-message-selector"></div>
                                    <input type="text">
                                    <div class="qq-dialog-buttons">
                                        <button type="button" class="qq-cancel-button-selector">Cancel</button>
                                        <button type="button" class="qq-ok-button-selector">Ok</button>
                                    </div>
                                </dialog>
                            </div>
                        </script>

### Detailed explanation of the problem
Doesn't seem to recognise the Adobe InDesign file's mimetype. I can't select the file as it is greyed out.

**Comment by rnicholus** [comment]
This indicates one of two things: either the browser/OS is not capable of identifying these files, or your MIME types are incorrectly specified. Either way, this is not something that can be addressed by Fine Uploader. The `acceptFiles` validation property simply delegates to the [`accept` attribute on the underlying `<input type="file">` element](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input).
