### ISSUE TITLE
Document 5.11 breaking changes (moving of files)

### ISSUE THREAD

**Issue by sergei-maertens** [FineUploader/fine-uploader#1639]
## Type of issue
bug

## Uploader type
traditional

### Fine Uploader version
5.11.2

### Browsers where the bug is reproducible
n/a

### Operating systems where the bug is reproducible
all

### Exact steps required to reproduce the issue
1. Existing code references `node_modules/fine-uploader/jquery.fine-uploader/jquery.fine-uploader.min.js`
2. Upgrade to FU 5.11.2 (possibly any 5.11.x)
3. File now 404's

### All of your Fine Uploader initialization JavaScript code
Reference in HTML template:
`<script src="node_modules/fine-uploader/jquery.fine-uploader/jquery.fine-uploader.min.js"></script>`

### Detailed explanation of the problem
This is a combination of an undocumented/breaking change combined with `npm`'s lax version pinning by default.

My `package.json` contained a caret instead of a tilde:
```
  "dependencies": {
    "fine-uploader": "^5.1.3"
  },
```

On Travis CI this leads to npm fetching the latest available version, which is now 5.11.2. My tests are failing because the file can no longer be found.

Fixed on my end by pinning the version to 5.1.x (yes, I need to upgrade), but a note or maybe even a 'big' version bump would be nice.

**Comment by rnicholus** [comment]
This looks like a bug in the build process, there were no intended breaking changes, and I'm very careful to not make any breaking changes without a major version bump, following the semantic versioning spec.

Looking closer, the originally included jQuery bundles are missing, other than the source maps (which are new). I completely rewrote the build code in 5.11.0, so this looks like a regression. I'll look into this further and push out 5.11.3 once its fixed.

Though I would never intentionally introduce a breaking change without a major version bump, and this issue will be scheduled for a hotfix release, there isn't really any benefit to using Fine Uploader's jQuery wrapper, and you're probably better off using the non-jQuery wrapper version anyway.

**Comment by sergei-maertens** [comment]
Thanks for the quick reply - I wasn't sure if it was intentional or not, but at least we have CI's that cover our asses :-) It's not really affecting me other than that my build unexpectedly broke.

I know that the jQuery wrapper versions are things that shouldn't be used anymore, and I'm excited to upgrade to 5.8+ to be able to use ES6 imports. As with many things, there is legacy code that should be tackled some day.

**Comment by rnicholus** [comment]
Regression caused by incorrect naming of the jQuery minified and unminified artifacts generated by the new Makefile build recipes - https://github.com/FineUploader/fine-uploader/blob/5.11.0/Makefile#L242. Once I fix these, the issue should be resolve. The Azure & S3 builds do no suffer from this issue - it's specific to the traditional endpoint build.

**Comment by rnicholus** [comment]
ugh, still missing from the zip files, though npm is fixed. I can't wait to remove the jQuery wrappers in 6.0.

I'll have to fix this and push out 5.11.4. Completely forgot to verify the zip files before 5.11.3 was released.

**Comment by rnicholus** [comment]
Fixed in 5.11.4.
