### ISSUE TITLE
Setting general/default options

### ISSUE THREAD

**Issue by andresespinosapc** [FineUploader/fine-uploader#1644]
## Type of issue
Feature Request
## Uploader type
Any

## Feature request details
A way of setting fineUploader default options so they are the same for all fineUploader instances.
### Detailed description of the feature
It would maintain the code more organized and save code. Many times you will have multiple uploaders in the same website and maintain certain options through them (for example, if you want to write the messages in another language).
In jQuery the options could be set by something like `$.fn.fineUploader.options`

**Comment by rnicholus** [comment]
Why does Fine Uploader internal code need to handle this. Can't you just define an options object and pass it into each uploader when you initialize it?

Also, no improvements will be made to the jQuery wrappers, since they will be eliminated in 6.0.

**Comment by andresespinosapc** [comment]
Defining an options object and passing it into each uploaded is not the same, it's still very uncomfortable to add new settings apart of the default ones.
 Sadly, I don't know how to implement this without jQuery, I'm more a jQuery user. i've only seen it on another library that requires jQuery and I've found it a great idea.

**Comment by rnicholus** [comment]
I'm still not exactly sure what you are asking for here, or what changes you are proposing.

**Comment by rnicholus** [comment]
Closing this, but I'm will be happy to consider re-opening if more specific details are provided regarding the required changes to Fine Uploader.
