### ISSUE TITLE
Feature request (S3 uploader): Add support for signed URLs

### ISSUE THREAD

**Issue by emilecantin** [FineUploader/fine-uploader#1647]
## Feature request details

Add support for signedUrls
### Detailed description of the feature

Add another server endpoint type that would simply return a signed URL that we can use to upload directly to S3.

Reasoning: The policy validating and signing process is pretty complex, as evidenced by the need to supply sample code and extensive documentation, whereas generating signed URLs is supported in the AWS SDK. This would also eliminate a good deal of configuration, as the front-end no longer needs to know about bucket configuration and access keys.

I can implement the feature myself, but I want to know if it has a chance to be accepted first. Also, I'd need a few pointers on the best way to add this support.

**Comment by rnicholus** [comment]
I'm not sure I understand how generating signed URLs will reduce any complexity. Each request sent to S3 is different, and therefore requires a unique signature based on the request to be sent to S3. This is especially true when splitting a file into chunks and uploading to S3 via the multipart upload API.

**Comment by emilecantin** [comment]
Generating a signed URL: http://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/S3.html#getSignedUrl-property

Signing a policy: https://github.com/FineUploader/server-examples/blob/master/nodejs/s3/s3handler.js#L132

To me, it seems more like the "supported" case with S3 is with signed URLs, but I might be wrong. I don't really understand the rationale with signing the policy, but you seem to be pointing towards multipart uploads, is that the reason? It's not really explained in the documentation.

**Comment by rnicholus** [comment]
Some of this is coming back to me now, regarding why I didn't support signed URLs initially. As far as I can tell, signed URLs cannot be used with the S3 multipart upload API. This eliminates chunking and all chunking-related features. With that in mind, I don't see a benefit to supporting signed urls.

**Comment by emilecantin** [comment]
"It's for chunking" is an acceptable explanation for me. I believe it should be mentioned in the documentation, but for now it solves my issue. Thanks!

**Comment by rnicholus** [comment]
Turns out this may actually work, and in fact is a workflow I need to support for another closed-source project I'm working on now. 

I believe support for signed URL uploads has been requested many times. I actually see this as being implemented into core Fine Uploader code such that support is added for a request to be sent to the server for each chunk, which can then be used to influence that chunk's upload endpoint, params, and headers. 

Additionally, the `onUpload` callback will need to support promissory return values in case a request needs to be made to influence all chunk uploads for that file.

**Comment by rnicholus** [comment]
So here's my current though process:

Make `onUploadChunk` accept a `Promise` as a return value. The resolved param will be used to influence the URL, params, and headers of the request sent for that chunk. If no such param is included with the resolved `Promise`, or if a `Promise` is not returned, the existing logic will be used to determine URL/params/headers for the chunk's upload request. A rejected `Promise` will exercise the failed upload code path.

Seems `onUpload` should do the same, optionally. So I don't see this being an S3-specific change. In fact, it seems to make most sense to use the traditional endpoint uploader to upload to S3 using signed URLs.

**Comment by raresserban** [comment]
Hello.Sorry for commenting on such an old request, but how exactly can I use a presigned url generated from the backend into FineUploader?
I have looked through the docs and I can not seem to find anything...
