### ISSUE TITLE
Can't build 5.11.* release on Windows

### ISSUE THREAD

**Issue by feryardiant** [FineUploader/fine-uploader#1648]
Hi @rnicholus,

Just notice changes in v**5.11.**\* and i've got some issue when I'm trying to build bower distribution for 5.11.1. Currently I'm working on Windows 10 64 bit with node.js v6.2.1 then I got this when running `npm test`.

```
$ npm test

> fine-uploader@5.11.0 test D:\Workspaces\Codes\fineupload-dist\src
> make lint && make test

D:\Workspaces\Codes\fineupload-dist\src\node_modules\.bin/jscs client/js/*
/bin/sh: D:WorkspacesCodesfineupload-distsrcnode_modules.bin/jscs: No such file or directory
Makefile:207: recipe for target 'lint' failed
make: *** [lint] Error 127
npm ERR! Test failed.  See above for more details.
```

And I guess that this issue might be happen on windows only (not tested on linux yet), any advice for this issue?

**Update:**

It run well on Linux environment.

Regards

**Comment by rnicholus** [comment]
That's expected. You will need a Linux or UNIX filesystem to build fine uploader going forward. On Windows I imagine cygwin will work or Windows 10 bash.

**Comment by feryardiant** [comment]
Actually I'm working with cygwin, spesificly on [babun](http://babun.github.io).

**Comment by rnicholus** [comment]
I'm not sure what the problem might be then as I don't use Windows for development. If you find a fix, please let me know or open up a PR. Or, i you can locate the specific issue with the build, let me know so we can discuss further.

**Comment by rnicholus** [comment]
Is this preventing you from updating the bower distribution? Something definitely looks "off" in the error message above. Cygwin is supposed to be mostly POSIX compliant, but I haven't tested myself and I don't know if the flavor of cygwin you are using is suitable.

**Comment by feryardiant** [comment]
I think the problem is [here](https://github.com/FineUploader/fine-uploader/blob/master/Makefile#L7), which is `npm bin` command will return `bin` directory for our current project. On linux of course it will return something like `/some/project/node_modules/.bin` but on windows it will return `D:\some\project\node_modules\.bin` which is `\` (backward slash) will be escaped by POSIX it self, in that case if we call `$(npm-bin)/jscs` will return `D:someprojectnode_modules.bin/jscs` instead of `D:\some\project\node_modules\.bin/jscs`.

**Comment by rnicholus** [comment]
I'm not certain what the solution is here. I was under the assumption that this would work as-is in cygwin.

**Comment by fromkeith** [comment]
Created pull request to fix cygwin.

#1698

**Comment by SinghSukhdeep** [comment]
@rnicholus this can be closed I think

**Comment by rnicholus** [comment]
@SinghSukhdeep Good call.
