### ISSUE TITLE
Create TypeScript type definitions for methods, events, and options

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#1652]
https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by JugerHiTech** [comment]
It is great to see this^^ waitring so long

**Comment by rnicholus** [comment]
You'll probably we waiting for a while still, unless someone picks this up and works on the feature. I'll be busy for a while with a number of other Fine Uploader related features and bugs.

**Comment by rnicholus** [comment]
Should be covered by #1719.
