### ISSUE TITLE
qq.WindowReceiveMessage is missing from all.fine-uploader.zip release

### ISSUE THREAD

**Issue by vincentray21** [FineUploader/fine-uploader#1653]
## Type of issue
bug

## Uploader type
s3

### Fine Uploader version
5.11.5

### Browsers where the bug is reproducible
IE 8, IE 9

### Operating systems where the bug is reproducible
Windows 7 (using modern.ie VM)

### Exact steps required to reproduce the issue
For example:
1. Load demo page using IE 8 or IE 9.

### Detailed explanation of the problem [REQUIRED]
Downloaded all.fine-uploader.zip and created a sample page to test uploading files directly to S3 (based on the demo). The page is working for IE 10, IE 11, Chrome. But when loading the page using IE 8, and IE 9, the page failed indicating that qq.WindowReceiveMessage is missing.

Loading the demo page with IE 8 and IE 9, the same error also appeared.

Could not find the definition in the javascript files extracted from the release zip file. Modifying the sample page by downloading the source and importing window.receive.message.js to the page, the page worked.

**Comment by rnicholus** [comment]
Ugh, that's a nasty one. I'll fix this ASAP and release a hotfix - 5.11.7.

**Comment by rnicholus** [comment]
This likely affects S3 and traditional builds too.

**Comment by rnicholus** [comment]
Released as [5.11.7](https://github.com/FineUploader/fine-uploader/releases/tag/5.11.7).
