### ISSUE TITLE
Open uploaded file

### ISSUE THREAD

**Issue by G89Angel** [FineUploader/fine-uploader#1654]
## traditional

Hello!
I've been using fine uploader in my project with Symfony and everything is going great, upload, rename, delete orphanage files not linked to any Symfony entity, load an initial list of already uploaded files and handle the deletion, everything working like a charm...  but I'm missing just a little feature.

Once the file has been uploaded it would be great to have a button, or maybe just turn the filename into a clickable text to download/open this file. 

This would make the InitialFiles feature more complete.

**Comment by rnicholus** [comment]
I'm not sure how downloading files is an appropriate feature for an upload library. Besides, this is pretty easy to do without a library.

1. Return a `downloadUrl` for each entry in your server's response to the initial file list GET request
2. Render an anchor link next to each file with that URL.

**Comment by azmeuk** [comment]
@rnicholus How can we get the `downloadUrl` variable from the template, to render the full download link in the anchor link?

**Comment by speedev196** [comment]
i used as this code in callback of FineUploader.
             ```
   onComplete: function(id, name, response) {
                    console.log('res='+JSON.stringify(response));
                    if (response.success) {
            ........    stuff........    
                    }
                },
```

but result is res={"success":true}  
So i can't get any file link.  (i want to get res.tempLink field)
Can u explain why it happened ?

**Comment by speedev196** [comment]
Mr Ray Nicholus, Can u do me a favor ?
