### ISSUE TITLE
Problem Signing the Chunk!

### ISSUE THREAD

**Issue by hummerz5** [FineUploader/fine-uploader#1657]
## Type of issue 
Bug

## Uploader type 
S3

### Fine Uploader version
5.10.0
Dated 2016-06-16

### Browsers where the bug is reproducible 
Safari

### Operating systems where the bug is reproducible 
OSX Yosemite

### Exact steps required to reproduce the issue 
For example:
1. Select one file
2. File upload fails before completion.

### All of your Fine Uploader initialization JavaScript code 

```
    FineUpload.uploader = new qq.s3.FineUploaderBasic({
      debug: true,
      element: document.getElementById('fineUploader'),
      request: {
        endpoint: 'BUCKET.s3.amazonaws.com',
        accessKey: 'KEY'
      },
      chunking: {
        enabled: true
      },
      resume: {
        enabled: true
      },
      signature: {
        endpoint: 'sign-endpoint.php'
      },
      uploadSuccess: {
        endpoint: 'response_code200.php'
      },
      validation: {
        sizeLimit: 2000000000
      },
      objectProperties: {
        key: 'uuid'
      },
      callbacks: {
        onSubmitted: function (id, name) {
          $('upload-progress').addClassName('active');
        },
        onError: function (id, name, errorReason, req) {
          alert(errorReason);
        },
        onProgress: function (id, name, bytesDone, bytesTotal) {
          var progress = (bytesDone / bytesTotal);
          if (progress < 1) {
            var progressPercent = Math.floor(Math.floor(progress * 100));
            document.title = 'Uploading... (' + progressPercent + ' %) ';       
          }    
        }
      }
    });
    $('upload-file').on('change', function (e) {
      var e = $('upload-file');
      FineUpload.uploader.addFiles(e.files);
    });
```

### Detailed explanation of the problem 
A user had the error "Problem Signing the Chunk!" while using Safari. The file size was 896 MB. The user failed to upload three times, but the fourth was successful. Error occurred 30-40 seconds into the upload. This bug is difficult to reproduce.
#1519 appears to be a similar issue, but it appears to be closed. Another issue here involved CPU spikes, which do not appear to be the case. 
Could using Version 4 be a solution?

Thanks

**Comment by rnicholus** [comment]
This error indicates an issue with your signature server, not with Fine Uploader. Especially given the circumstances:

- user failed to upload three times, but the fourth was successful
- This bug is difficult to reproduce

Do you have any information about the response?

**Comment by hummerz5** [comment]
Thanks for your advice; the issue was indeed server side. The server sends a very infrequent 502 error for an unknown reason, with little explanation. For the time, I have enabled the overlooked autoRetry option.

Thanks again.
