### ISSUE TITLE
OnComplete callback for fineuploader

### ISSUE THREAD

**Issue by 1dot44mb** [FineUploader/fine-uploader#1658]
I want to access callback of finuploader oncomplete callback when fineuploader initialization is complete. Not the "item completed upload" callback. 
What i need is sth like this;
```
var uploader = new qq.FineUploader(options)
  .on('complete', function() {
    alert("Fine Uploader is ready");
  });
```

I searched through docs and issues but couldn't find an example.

**Comment by rnicholus** [comment]
Fine uploader is ready after you create a new instance. What are you trying to do? What problem are you having?

**Comment by 1dot44mb** [comment]
I have custom labels applied to items in upload queue list (like order number for example). I have to wait for qq.FineUploader to complete (applying its template, getting previously uploaded files, etc) and then run my custom javascript method to apply labels to items based on their order, name, etc.

**Comment by rnicholus** [comment]
You left "getting previously uploaded files" out of your question. If you want to know when Fine Uploader has completed handling an initial file list, observe the [`onSessionRequestComplete` callback](http://docs.fineuploader.com/branch/master/api/events.html#sessionRequestComplete).

**Comment by 1dot44mb** [comment]
Thanks, _onSessionRequestComplete_ callback solves "getting previously uploaded files" problem. 
However it would be good if qq.FineUploader has an "initialization complete callback" imho. So that we know when FineUploader form (dropzone) is ready for user interaction and we can make post processing of template, file list, visual stuff, etc.

**Comment by rnicholus** [comment]
>it would be good if qq.FineUploader method has an "initialization complete callback" 

I'm not seeing a need for this. Just do whatever you need to do after initializing the uploader. If you are performing an async task, such as requesting initial files, then wait until that is complete.

**Comment by rnicholus** [comment]
...and please do not delete the question template going forward. It exists for a reason.
