### ISSUE TITLE
DELETE request URL not consistent

### ISSUE THREAD

**Issue by 1dot44mb** [FineUploader/fine-uploader#1659]
When i try to delete a file that was previously uploaded; FineUploader sends the DELETE request without file UUID at the end of the endpoint URL. eg: http://localhost/server/upload

However, when the file is freshly uploaded (no navigation after file upload) and the form is not submitted yet (autoSubmit: false). When i click delete; the request sent to server contains file UUID in the URL. (eg. http://localhost/server/upload/4facf65c-b116-4bd5-8e8b-fef079387df3) (Mentioned in the docs as: _all delete file requests will be sent using a DELETE request, with the file UUID at the end of the URI_)

This makes it hard to handle the DELETE request on the server side.

**Comment by rnicholus** [comment]
Yes, this is correct, this is how delete requests are sent. What is your question?

**Comment by 1dot44mb** [comment]
Thanks,

In two separate scenarios i mentioned above; the delete requests are different. One of them contains UUID in URL and other does not. My question is; why are they not consistent? They are both delete file requests.

Because they are different, we have to handle two separate request scenarios on the server side (routing, custom logic, etc.)

**Comment by rnicholus** [comment]
>FineUploader sends the DELETE request without file UUID at the end of the endpoint URL. eg: http://localhost/server/upload

If you are seeing this and can reliably reproduce, then this is a bug. A pull request to fix this bug is welcome.

**Comment by 1dot44mb** [comment]
Thanks

**Comment by rnicholus** [comment]
I just attempted to reproduce and I'm not seeing any issue. The UUID was appended to the end of the URL for an initial file delete. Since you deleted the question template, I have no idea what version or build of Fine Uploader you are using, so I can only assume that the issue is on your end.
