### ISSUE TITLE
Progress bar

### ISSUE THREAD

**Issue by pyaesone17** [FineUploader/fine-uploader#1668]
## Type of issue [REQUIRED]
"bug"

## Uploader type [REQUIRED]
"traditional"

### Fine Uploader version [REQUIRED]
5.11.8

### Browsers where the bug is reproducible [REQUIRED]
 "Chrome" 

### Operating systems where the bug is reproducible [REQUIRED]
"Ubuntu"

### Exact steps required to reproduce the issue [REQUIRED]
For example:
1. Select 3 files
2. Pause the 2nd file before it completes, but after it has started.
3. Attempt to resume the paused file.

### All of your Fine Uploader initialization JavaScript code [REQUIRED]
     
        var galleryUploader = new qq.FineUploader({
            element: document.getElementById("fine-uploader-gallery"),
            template: 'qq-template',
            validation: {
                allowedExtensions: ["jpeg", "jpg"],
                sizeLimit: 20000000 // 20 MiB
            },          
            request: {
                endpoint: '/server/uploads',
                customHeaders: {
                    "X-CSRF-TOKEN": csrf_token
                },
            },
            deleteFile: {
                enabled: true,
                endpoint: 'server/file',
                customHeaders: {
                    "X-CSRF-TOKEN": csrf_token
                }            
            },          
            thumbnails: {
                placeholders: {
                    waitingPath: '/plugins/fine-uploader/placeholders/waiting-generic.png',
                    notAvailablePath: '/plugins/fine-uploader/placeholders/not_available-generic.png'
                }
            },
            validation: {
                allowedExtensions: ['jpeg', 'jpg', 'gif', 'png']
            },
            callbacks: {
                onUpload: function(){
                    this.setEndpoint('/shop/'+currentSlug+'/image')
                },
                onSubmitDelete: function(id){
                    this.setDeleteFileEndpoint('/shop/image/'+currentSlug)
                },
                onDeleteComplete: function(id,xhr){
                    var response = JSON.parse(xhr.response)
                    uploadedImage = uploadedImage.filter(function(image){
                        return image.newUuid != response.id;
                    })
                },
                onComplete: function(id,name,response,xhr){
                    uploadedImage.push(response)
                },
                onError: function(id, name, reason, xhr){
                    if(xhr.status===403){ alert('Session expired. Please try to login again.'); window.location= loginUrl}
                }
            }

### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
same as gallery template

### Detailed explanation of the problem [REQUIRED]
Global Progress bar only show. Each of the file individual progress bar always hide. You can also see on documentation page. qqhide class is always added on individual progress bar.

**Comment by rnicholus** [comment]
The above is _not_ your Fine Uploader configuration code. Your bug report mentions pausing an in-progress upload as part of the reproduction steps, but chunking is required for that. Chunking is not enabled in your configuration code above. 

After enabling chunking, I was not able to reproduce the reported issue. All is working as expected. Perhaps there is an issue in your environment, possibly CSS related.

**Comment by pyaesone17** [comment]
I am not talking about chunking upload. What I mean is progress bar inside 

<li> list is always hiding. You may also inspect this on documentation demo page.

**Comment by rnicholus** [comment]
Step 2 says:

>Pause the 2nd file before it completes, but after it has started.

This is not possible without chunking enabled.

**Comment by pyaesone17** [comment]
Sorry I edited my comment

**Comment by pyaesone17** [comment]
[
![selection_033](https://cloud.githubusercontent.com/assets/11407146/18924693/314bcc62-85d7-11e6-9d01-e0648c712d24.png)
](url)

What i mean is this individual progress bar is always hiding.  It is not multi upload . I upload one by one.

**Comment by rnicholus** [comment]
Sorry, I'm not seeing any issue with the individual progress bars myself. They are supposed to hide after the upload completes. Demo page is working as expected as well.
![screen shot 2016-09-28 at 12 31 09 pm](https://cloud.githubusercontent.com/assets/593312/18924931/8d6f954c-8577-11e6-8b7b-3a4c8110d967.png)

**Comment by pyaesone17** [comment]
Thank you for your reply .btw  Is there a way to set event handler in runtime for event handling.
