### ISSUE TITLE
Social and Cloud Storage Integration

### ISSUE THREAD

**Issue by ewcindia** [FineUploader/fine-uploader#1672]
We are working on a SAAS project where users will be posting images. We want to facilitate them by uploading files directly from their Social accounts like Facebook, Instagram, etc. and their Cloud storage accounts such as Google Drive, OneDrive, etc.

These features are offered on commercial products like Uploadcare and Filestack, etc.

Are there any plans for such integrations or if not then how to do that in FileUploader?

**Comment by rnicholus** [comment]
You may utilize the provided API for any integrations you desire. If you have a specific question regarding integration or code, please post on SO.
