### ISSUE TITLE
surplus quotation mark in the sample code

### ISSUE THREAD

**Issue by RayCLin** [FineUploader/fine-uploader#1676]
there is a surplus quotation mark in the sample code
http://docs.fineuploader.com/quickstart/01-getting-started.html

Traditional endpoint, UI feature set, at line 7...

```

    <script src="fine-uploader/fine-uploader.min.js""></script>

```

**Comment by RayCLin** [comment]
I can't, it is quickstart sample code on the web page, not in the repository.
location: http://docs.fineuploader.com/quickstart/01-getting-started.html

**Traditional endpoint, UI feature set**
`<script src="fine-uploader/fine-uploader.min.js""></script>`

**Comment by rnicholus** [comment]
Repo is at https://github.com/FineUploader/fineuploader.com.

**Comment by rnicholus** [comment]
The markup for the docs are hosted in this repo under the docs directory.
