### ISSUE TITLE
qq.DragAndDrop returns url in files array

### ISSUE THREAD

**Issue by pablocrs** [FineUploader/fine-uploader#1678]
## Traditional

I'm triyng to use the core drag and drop and uploader, but drag and drop FilesComplete callback doesn't returns the url just for put the image on a input type file. 

Thanks!

**Comment by rnicholus** [comment]
Sorry I don't understand the question/problem.

**Comment by pablocrs** [comment]
Thanks!

just needed to create a objectUrl from the file like this:

`processingDroppedFilesComplete: function(files, dropTarget) {
                    //TODO: hide spinner/processing graphic

                    var theUrl = window.URL.createObjectURL(files[0]);
                }`
