### ISSUE TITLE
onComplete catches a chunk-upload response instead of the actual finish response

### ISSUE THREAD

**Issue by zelding** [FineUploader/fine-uploader#1680]
## Type of issue 
Bug

## Uploader type 
traditional

### Fine Uploader version 
5.11.8

### Browsers where the bug is reproducible 
Chrome, Firefox (haven't tried others)

### Operating systems where the bug is reproducible: 
Linux Mint 18 x64, Win 10 x64

### Exact steps required to reproduce the issue
For example:
1. Select a file (preverably over 300 Mb)
2. upload

### All of your Fine Uploader initialization JavaScript code
```
    $(function () {
            window.uploader = new qq.FineUploader({
                element:        document.getElementById('fine-uploader'),
                multiple:       false,
                maxConnections: 3,
                request: {
                    endpoint: "<some_url>"
                },
                retry: {
                    enableAuto: false
                },
                resume: {
                    enabled: true
                },
                chunking: {
                    concurrent: {
                        enabled: true
                    },
                    enabled   : true,
                    //mandatory : true,
                    partSize  : 20971520 //20M
                },
                //debug: true,
                callbacks: {
                    onComplete: function (id, name, responseJSON, xhr) {
                        console.log('Cmp ', {
                            Response : responseJSON,
                            name        : name,
                            req           : xhr
                        });

                        if (responseJSON.success && responseJSON.video_id) {
                            window.location.href = responseJSON.url;
                        }
                        else {
                            alert(responseJSON.error);
                        }
                    },
                    onAllComplete: function (a, b) {
                        console.debug(a, b);
                    },
                    onError: function(id, name, errorReason, xhrOrXdr) {
                        console.error(id, name, errorReason);
                    },
                    onManualRetry: function() {
                        //prevent retry
                        return false;
                    }
                }
            });
        });
```

### Detailed explanation of the problem 

When I enable concurrent chunking and the upload supposedly finishes sometimes the `onComplete` callback catches some response and not the very last response, which would have the correct data; so i get the error:
`[Fine Uploader 5.11.8] Error when attempting to parse xhr response text (t is undefined)`

The weirdest thing is, that I pass additional data to the chunk-responses and to the finish response too, but when this happens the response only contains a `success: true` property and no extra data.
The network log shows everything is fine with the responses (extra data and whatnot).
This seems to happen when the uploader finishes the last chunks.
If i disable the concurrent chunking this never happens.

I am using [OneupUploaderBundle](https://github.com/1up-lab/OneupUploaderBundle) on the server side.

Might this be a backend issue?

**Comment by rnicholus** [comment]
What is "the very last response"? There is no guarantee regarding order of requests/responses. Since you are using the concurrent chunking feature, you are required to define a `chunking.success.endpoint`. This is where your server should combine the chunks and return a response that describes the entire effort.

**Comment by zelding** [comment]
I see; thank you!

**Comment by rnicholus** [comment]
Closing, but let me know if this is not yet resolved or needs more discussion.
