### ISSUE TITLE
Display initial file list thumbnails is really slow

### ISSUE THREAD

**Issue by rdptz** [FineUploader/fine-uploader#1682]
## Type of issue
thumbnailUrl

## Uploader type
traditional

## Feature request

Hi, is it possible to display the images provided into the initial file list, **without** having fine-uploader writing and reading the image to the canvas? It is really slow and useless as long as the thumbnailUrl already contains the already resized images urls. 
I'd just use plain `<img src>` and let the browser display the images.

We must show 10-12 thumbnails and fine-uploader takes seconds to render them. 

Thanks,

**Comment by rnicholus** [comment]
Fine Uploader doesn't actually take seconds to render them. There is a default pause between each thumbnail generation to work around a GC issue in Chrome #1279. I'm not sure if this issue still exists in Chrome. Regardless, you can control the delay between thumbnail generations via the [`thumbnails.timeBetweenThumbs` UI option](http://docs.fineuploader.com/branch/master/api/options-ui.html#thumbnails.timeBetweenThumbs).

**Comment by rdptz** [comment]
Hi, 

you are right, lowering the pause the performance issue disappears.
I still wonder if it would not be better to let the browser render the image, when the thumbnailUrl is explicitly given from the session endpoint JSON. This way there would be no issues with chrome too, I guess.

Thanks!

**Comment by rnicholus** [comment]
>I still wonder if it would not be better to let the browser render the image, when the thumbnailUrl is explicitly given from the session endpoint JSON.

Even in that case, Fine Uploader scales and potentially orients the image, which means `<canvas>` is used. So, the same GC issue is possible in Chrome.

Glad to be of assistance. I'll close this now.
