### ISSUE TITLE
FineUploaderBasic: inputName doesn't run as a function. (feature request)

### ISSUE THREAD

**Issue by agamemnus** [FineUploader/fine-uploader#1685]
(yes, I followed the template, and I assume/believe it is a feature issue now)

Type of issue: actually this one might be a feature request, but I don't know.

Uploader type: traditional, FineUploaderBasic.

Feature request details
Detailed description of the feature:
I think earlier versions allowed things like inputName to be runnable functions. At present, the inputName variable, if not a string, just turns into a string instead when sent to the server.

I tried many ways to modify a file name before it's sent to the server but I striked-out on all of them. Maybe I am not using the right callback function. I decided the simplest path was to allow inputName to be a function. I think that might be useful, too, assuming other ways work somehow.

I made the following modifications to the code:
1) in `qq.traditional.XhrUploadHandle`, in the `setParamsAndGetEntityToSend` function:

a) `var inputName = (typeof spec.inputName == "function") ? spec.inputName() : spec.inputName`

b) `params[spec.inputName] = name;` -> `params[inputName] = name;`

c)  `formData.append(spec.inputName, fileOrBlob);`-> `formData.append(inputName, fileOrBlob);`

2) In `qq.FormUploadHandler`,
`fileInput.setAttribute("name", inputName)` -> `fileInput.setAttribute("name", (typeof inputName == "function") ? inputName() : inputName);`

**Comment by rnicholus** [comment]
The file name can be changed per file via the [`setName` API method](http://docs.fineuploader.com/branch/master/api/methods.html#setName). The input name property is unrelated to the file name.

**Comment by agamemnus** [comment]
Please re-Open!

**Comment by rnicholus** [comment]
Why does the input name need to be modified?

**Comment by agamemnus** [comment]
Well, the back-end gets data from that variable and, then uses it to generate the file name. I would do it differently, but I am not the backend developer so can't change it... maybe it could still be a useful variable to other people for random uses.

But, I was just thinking that maybe this behavior could extend to every setting variable that is not immediately run/evaluated.

One idea -- maybe if a variable is static, make it a function, and then always run it as a function, or something like that. Or, just individually modify it with for example the method I suggested above.

**Comment by rnicholus** [comment]
I don't see much value in making the input name variable to this extent. If you'd like to pass dynamic data with the file, this can be done via upload parameters. See the `params` option and the `setParams` API method for specifics.

**Comment by agamemnus** [comment]
Oh ok. I thought I tried it but it didn't seem to work. I will try again.

**Comment by rnicholus** [comment]
There are no known issues with setting params, either through the API or via options. If you are having issues, please open a question on SO with all of your code for assistance.
