### ISSUE TITLE
email recive issue

### ISSUE THREAD

**Issue by lior800900** [FineUploader/fine-uploader#1690]
hi im using fine uploader
and when user upload images and fill the form im get email
but from some users i dont get email about the uploaded that they did!
here is the form in my website http://www.picapic.co.il/%D7%97%D7%9C%D7%95%D7%A7-%D7%A8%D7%97%D7%A6%D7%94-%D7%A2%D7%9D-%D7%AA%D7%9E%D7%95%D7%A0%D7%94.html

i think its problem with user browser or user OS
how can i monitor it and check it?

**Comment by lior800900** [comment]
Hi why you close it???

**Comment by rnicholus** [comment]
1. You deleted the template
2. You didn't read the contributing instructions, especially the part related to asking for support.
3. You didn't provide any information necessary to troubleshoot your issue.
