### ISSUE TITLE
S3 Upload Failure when chunks > 10000

### ISSUE THREAD

**Issue by EZWrighter** [FineUploader/fine-uploader#1697]
Bug - Maybe Feature Request?

S3

Version: 5.11.9

Chrome, maybe others

Mac OS X, maybe others

1. Select a file greater than 50GB
2. Set chunk size to 5MB (Default)
3. Upload

Failure will always happen at the first chunk > 10000.  We receive a Bad Request from S3 Server.

Looks like this is a limit of Amazon S3: http://docs.aws.amazon.com/AmazonS3/latest/dev/qfacts.html that doesn't seem to be documented in fineuploader anywhere.

The uploader should know this limit and warn or change chunk size to accommodate the limit.

Workaround would be to set chunk size to 10.5MB to allow files up to 100GB...but that would not get us to the 5TB limit of which would require a chunk size of 525MB.  Is chunk size stored with the resume data?  Could chunk size be set on a per file basis?

**Comment by rnicholus** [comment]
Chunk size is only configurable for all files as an initial config option. The best option would be to limit the upload size based on your configured chunk size.

**Comment by rnicholus** [comment]
Another option would involve updating the codebase to expose an option that automatically adjusts the chunk size to an optimal setting before the upload begins, taking into account the file size.

**Comment by EZWrighter** [comment]
The optimal solution from my perspective would be to have a setting be for minimum/default chunk size that is used for all files, unless that would cause more than 10000 parts to be created, then the chunk size would be file size / 10000.  The chunk size would get stored locally for resume.  This would be very similar to your second suggestion.

**Comment by rnicholus** [comment]
Yes, that sounds like a good approach. I think a change at https://github.com/FineUploader/fine-uploader/blob/c1b4954f21381dbd664e379abf571c988e2265c0/client/js/upload-handler/xhr.upload.handler.js#L222 may be all that is needed. But unit tests would need to be added as well.

**Comment by EZWrighter** [comment]
I took a look through that code, but not familiar enough with it to make code changes.  Seems like the tricky part would be to deal with chunk size in the persisted state.

Simple unit test would attempt to transfer a 1MB file to Amazon S3 with minimum part size set to 100 bytes, which should break up into a little over 10000 chunks.

**Comment by rnicholus** [comment]
Unfortunately there are no simple changes in a codebase of this age and complexity. This has the potential to break any chunked uploads that are waiting to be resumed from `localStorage`. So that will need to be accounted for.

**Comment by EZWrighter** [comment]
I assume any config change to partSize would break uploads waiting to be resumed.  Technically a modification like this wouldn't change partSize from the global configuration unless it was specified differently in localstorage for that specific file.  

Thinking this through,any destination could have a maximum part limit, so each extension of XhrUploadHandler should define this someplace and _getChunkData should use that limit to determine # of parts and actual chunk size if larger than maximum parts.

**Comment by rnicholus** [comment]
Long time coming, but I expect to address this in #1916. Probably will allow a function to be returned from `chunking.partSize`. The function would be invoked by Fine Uploader with the file ID. Integrators could determine the optimal `partSize`, and this would not be S3-specific.
