### ISSUE TITLE
sizeLimit validation

### ISSUE THREAD

**Issue by SJhioui** [FineUploader/fine-uploader#1699]
- Type of issue : bug
- Uploader type : traditional
- Fine Uploader version : 5.11.8
- Browsers where the bug is reproducible : All
- Operating systems where the bug is reproducible : All

- Exact steps required to reproduce the issue :
1. Select 1 file bigger than 30 Mb  (31 457 280 bytes)
2. See the validation message

The message indicate that the file is bigger than 31.5 Mb  baut this is not true, the file is bigger than 30 Mo
The bug is that the sizeLimit : 31457280  is not converted correctly to Mb by the function "_formatSize". The value of the size must be divided by 1024 and not by 1000.

Thanks for your support.

**Comment by rnicholus** [comment]
This is not a bug, and what you are asking for is for Fine Uploader to report MiB, not MB. As it stands, the current measurement follows SI standards. Please read #378 for more info.
