### ISSUE TITLE
Fineuploader Scaling not working in Firefox

### ISSUE THREAD

**Issue by kawaljeetb** [FineUploader/fine-uploader#1701]
Bug
S3
Version: 4.4.0 [Licensed]
Firefox
Windows

Upload an image in Firefox browser that needs to be scaled in three different formats for eg: big, small and medium

scaling: {
	             	includeExif: true,
	                 sizes: [
	                     {name: "big", maxSize: 480},
	                     {name: "medium", maxSize: 420, quality:100},
	                     {name: "small",  maxSize: 100}
	                 ]
	             },

1) Upload an image that needs to be scaled in three different formats for eg: big, small and medium
2) It throws multiple errors saying
[Fine Uploader 4.4.0] Could not render preview, file may be too large!  
[Fine Uploader 4.4.0] Failed attempt to generate scaled version for [imagename.png]
[Fine Uploader 4.4.0] Failed to generate scaled version for ID 0.  Error message: Failed to scale.

**Comment by rnicholus** [comment]
Does this happen with any image? Have you tried with a recent version of Fine Uploader (your version is very old)? What version of Firefox?

**Comment by kawaljeetb** [comment]
This is happening with every image I upload in firefox [version - 50.1.0]

**Comment by rnicholus** [comment]
The version of Fine uploader you are using is exceptionally old. Have your tried with a newer version? Yours is the only such report, so it seems unlikely that there is an issue, at least in recent versions of the library.

**Comment by kawaljeetb** [comment]
Yes.. Tried using the latest version of Fineuploader(5.11.10). But still throws the same error in Firefox.
But both the versions are working in chrome. Images gets scaled in chrome.

**Comment by rnicholus** [comment]
I'm not seeing any issues myself. Most likely you have left out details needed to reproduce. I will be happy to reopen the issue once a foolproof set of steps needed to reproduce are include.

**Comment by kawaljeetb** [comment]
there is one more issue that occurs in Firefox before scaling is 'Error: No createObjectURL function found to create blob url'. Following are the lines of code that is throwing error only in firefox:

           var URL = window.URL && window.URL.createObjectURL ? window.URL :
                window.webkitURL && window.webkitURL.createObjectURL ? window.webkitURL :
                null;
      if (!URL) { throw Error("No createObjectURL function found to create blob url"); }
 img.src = URL.createObjectURL(srcImage); 


So I m replacing these lines of code with the following ones:

function createObjectURL ( file ) {
	    if ( window.webkitURL ) {
	        return window.webkitURL.createObjectURL( file );
	    } else if ( window.URL && window.URL.createObjectURL ) {
	        return window.URL.createObjectURL( file );
	    } else {
	        return null;
	    }
    	}
 img.src = URL.createObjectURL(srcImage);



So the createobjecturl issue gets resolved but then image scaling gets failed.
Is Is it because the above code.

Again, this is happening for me in both the versions of Fineuploader.

Thanks.

**Comment by rnicholus** [comment]
There is something terribly wrong with your copy of Firefox then, as that method certainly should be available. Most likely a browser extension or some other code on the page is the culprit.

**Comment by temirfe** [comment]
I have similar issue in Firefox. When I select large image the scaled version is only some part of image. In chrome it works ok. 

When I checked console of firefox it says "Image corrupt or truncated". This seems to be common [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=941823) in firefox because it "requests image [too fast](https://stackoverflow.com/a/12889166/614026)". 

Is there any work around for this? Maybe set some delay time before scaling so that firefox finishes loading image?
(Fine Uploader 5.13.0)
(Firefox 59.0.2)
