### ISSUE TITLE
Confirm folder drop support in Firefox 50+ and Microsoft Edge 14

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#1703]
Even though the W3C specification that makes folder dropping possible (the Filesystem API) has been deprecated, both Firefox and Edge have added support, at least on paper. We need to verify that this actually works as expected in these browsers before feature charts are updated and DnD support becomes officially supported by Fine Uploader in these browsers.

As a user, you can help by reporting your success or issues here. I suspect folder dropping should just work in these browsers though.

**Comment by sgarcialaguna-mms** [comment]
I filed https://bugzilla.mozilla.org/show_bug.cgi?id=1319053 for Firefox. Other than that, dropping folders works fine for us in Firefox.

**Comment by rnicholus** [comment]
Confirmed in Firefox

**Comment by SinghSukhdeep** [comment]
Works in MS Edge as well, tested on following version

![ms-edge-snip](https://cloud.githubusercontent.com/assets/3210920/26027397/511d117a-37db-11e7-9e30-afe3450d4f5f.PNG)

**Comment by rnicholus** [comment]
Updating `qq.supportedFeatures.folderDrop` to better detect this as support moves to additional browsers. Staged in #1917.
