### ISSUE TITLE
Problem in object iteration when other JS libraries are included

### ISSUE THREAD

**Issue by sschuerz** [FineUploader/fine-uploader#1704]
## Type of issue
JS error on initialization when other JS libraries are included

## Uploader type
traditional

### Fine Uploader version
5.11.10

### Browsers where the bug is reproducible
all browsers

### Operating systems where the bug is reproducible
all OS

### Exact steps required to reproduce the issue
1. Just initialize Fine Uploader on a page where some code extending the `Object` prototype is included

### All of your Fine Uploader initialization JavaScript code
```javascript
(function($) {
    $('#my_uploader').fineUploader({
        "template": "qq-template-manual-trigger"
    });
})(jQuery);
```

#### First problem

If there is some JS code included that extends the Object prototype (e.g. adding an `extend` method), there occurs an error in function `addCallbacks` in the file `client/js/jquery-plugin.js`. The problem is that all properties (variable `prop` in iteration over `newUploaderInstance._options.callbacks`) must begin with "on", otherwise an error occurs when where the variable `name` is assigned (`name = /^on(\w+)/.exec(prop)[1]`); and that there is no "hasOwnProperty" check.

**Suggested solution:** Add a "hasOwnProperty" check as only "own" properties should be iterated in this case:
```javascript
$.each(newUploaderInstance._options.callbacks, function(prop, nonJqueryCallback) {
    if(!newUploaderInstance._options.callbacks.hasOwnProperty(prop)) {
        return;
    }

    // ...
}
```
**OR (alternatively and maybe better as it more compact):**  Use `qq.each` instead of `$.each` for iteration.

#### Second problem

Even with the "hasOwnProperty" check for the first problem, one problem remains:
The function `_wrapCallbacks` in the file `client/js/uploader.basic.api.js` iterates over *all* properties of `this._options.callbacks` and adds the "not own" properties as "own" properties to the object. Therefore, the fix for the first problem is no more effective.

**Suggested solution:** Use `if (!this._options.callbacks.hasOwnProperty(prop)) { ...` at the beginning at the loop body.

**OR (alternatively):** Use `qq.each` instead of the `for` loop:
```javascript
qq.each(this._options.callbacks, function(callbackName, callbackFunc) {
    self._options.callbacks[callbackName] = function() {
        return safeCallback(callbackName, callbackFunc, arguments);
    };
});
```

**Comment by rnicholus** [comment]
Best way to address this would be to open up a pull request with tests that demonstrate the issue alongside a fix. Thanks for the report

**Comment by rnicholus** [comment]
The code in question has been in place for several years at this point. If there is an issue with a specific environment, please write unit tests that reproduce the issue or provide an executable test case. A pull request that includes a test and a fix is ideal. I'm going to close this for now since I haven't heard back in a while, but will be happy to consider re-opening if executable test cases and/or a PR can be contributed.

**Comment by sschuerz** [comment]
Sorry for my late response. I created executable test cases now.

### General remarks to my test cases

I implemented the needed adaptions directly in the built file `jquery.fine-uploader.js` (included in the FineUploader release file `fine-uploader.zip`) to be able to provide an example that is very similar to our real use case. The original source files that need to be adapted are mentioned in my initial issue (`client/js/jquery-plugin.js` and `client/js/uploader.basic.api.js`). I can provide a pull request that for the original source files if needed.

I implemented my suggested solutions for "First problem" and "Second problem" (see my initial issue), however I used my "alternative solution" involving the `qq` object in both cases.

### Contents of the ZIP files

- `fine-uploader` folder: Unzipped version of the FineUploader release file `fine-uploader.zip` from the latest release 5.12.0. The modified version of `jquery.fine-uploader.js` is additionally included as `jquery.fine-uploader.adapted.js`.
- `rico.js`: The version of Rico we use (1.1.2). I know this is an older version, but extending the `Object` prototype is also done in other (newer) JS libraries.
- `index_*.html`: I used your example at http://docs.fineuploader.com/quickstart/01-getting-started.html ("Traditional endpoint, UI feature set") as a starting point and adapted it as far as needed to show the problems. All my modifications are accompanied by comments.
  - `index_error.html`: File that includes the unmodified version of `jquery.fine-uploader.js` to show the error at initialization. The problem is explained in detail in my initial issue.
  - `index_working.html`: File that includes the modified version of `jquery.fine-uploader.js` (`jquery.fine-uploader.adapted.js`) and therefore produces no error at initialization.

### Why two ZIP files?

`example_jquery_2.2.3` uses jQuery 2.2.3 and represents our current use case with the problems I described in my initial issue.

`example_jquery_3.1.1` uses the latest jQuery version 3.1.1 and shows another problem similar to the two problems I described in my initial issue. See the section below for a description of this prolbem.

### Additional problem with jQuery >= 3.0.0

Since the implementation of `$.isPlainObject` has changed in jQuery 3.0.0 (see https://blog.jquery.com/2016/06/09/jquery-3-0-final-released/), a small additional modification is needed in the function `transformVariables` in the source file `client/js/jquery-plugin.js`:

In the iteration over the `source` variable, the `callbacks` options object now counts as "plain object", so the `else if` condition `$.isPlainObject(val)` evaluates to `true` (in jQuery < 3.0.0 the `else` path is entered here). Therefore, the `transformVariables` function is called recursively for the `callbacks` object and **all** of its properties (including "not own" properties, e.g. the Rico `extend` method) are added to the `xformed` object (as "own" properties), which is used for further options processing. So you end up with the problem at the regex execution in the `addCallbacks` function (`name = /^on(\w+)/.exec(prop)[1]` where `prop` is e.g. "extend") again.

I've solved this problem by using `qq.each` instead of $.each for object iteration in the `transformVariables` function (`qq.each` does not iterate over "not own" properties whereas `$.each` does).

I think in general it is usually seen as a good practice in JS not to iterate over "not own" properties (unless there is a special need to do so of course) to avoid unexpected results in varying usage environments.

### The ZIP files

[example_jquery_2.2.3.zip](https://github.com/FineUploader/fine-uploader/files/724122/example_jquery_2.2.3.zip)
[example_jquery_3.1.1.zip](https://github.com/FineUploader/fine-uploader/files/724123/example_jquery_3.1.1.zip)
