### ISSUE TITLE
Is cancel file upload by uuid possible?

### ISSUE THREAD

**Issue by ensean** [FineUploader/fine-uploader#1705]
### Exact steps required to reproduce the issue

From the docs, I find the method to cancel uploading a file is as follows:
![img](http://oi8cd6doq.bkt.clouddn.com/QQ%E6%88%AA%E5%9B%BE20161230173727.jpg)

It seems that the integer file id (0, 1, 2 etc.) should be used to cancel uploding. But in my web app, the user may trigger fineuploader many times to upload file. If the integer file id is used cancel file upload, the files uploaded by the last active fineuploader will always be canceled. 

Since there is an uuid for each file in fineuploader, is it possible to cancel file uploading by uuid?

**Comment by rnicholus** [comment]
Yes, it is: 

```js
var id = uploader.getId(uuid)
uploader.cancel(id)
```

**Comment by ensean** [comment]
I think I have not describe the issue clearly...

My code goes as follows

```
var uploader = new qq.FineUploaderBasic({
            button: $("#addAttLocal").get(0),
            maxConnections: 1,
            request: {
                endpoint: ctx + "/web/mail/attachment/fupload?" + urlUtil.serialize({
                    target: that.newMailId,
                    attachmentTypeId: 'MAIL_ATTACHMENT'
                })
            },
            multiple: true,
            validation: {
                sizeLimit: 50000000
            },
            callbacks: {
            //codes omited...
            }
        });
```
The issue maybe that the user could click the addAttLocal button several times, and the integer file ids may be duplicated across these clicks which resulting calling the cancel method will always affect the file processed by the latest uploader ...

**Comment by ensean** [comment]
By the way, I am using fineuploader in core/basic mode, it seems that the getId methods is for the UI mode ...

**Comment by rnicholus** [comment]
Ah yes, my mistake. Use this one instead http://docs.fineuploader.com/branch/master/api/methods.html#getUploads

**Comment by ensean** [comment]
Thanks for your update.
