### ISSUE TITLE
Manually Trigger Uploads demo depends on bootstrap.css

### ISSUE THREAD

**Issue by kb-ptti** [FineUploader/fine-uploader#1712]
## Type of issue [REQUIRED]
bug
## Uploader type [REQUIRED]
traditional

### Fine Uploader version [REQUIRED]
5.11.9 / 5.11.10

### Browsers where the bug is reproducible [REQUIRED]
Safari

### Operating systems where the bug is reproducible [REQUIRED]
macOS 10.12.2

### Exact steps required to reproduce the issue [REQUIRED]

visit http://fineuploader.com/demos.html#manually-trigger-uploads in a browser

### All of your Fine Uploader initialization JavaScript code [REQUIRED]
n/a

### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
n/a

### Detailed explanation of the problem [REQUIRED]

 Look at the "Upload" button.  It contains a circular icon with an upward-pointing arrow in it.  This icon is part of the bootstrap.css framework.  You can prove this by right-clicking on the icon and selecting "Inspect Element".  This shows an \<i\> element with a class "icon-upload" which is defined in bootstrap.min.css on line 409 and class "icon-white" which is defined on line 382 of the same file.  This comes from the following code snippet in the tailored template code in the example.
```
<button type="button" id="trigger-upload" class="btn btn-primary">
    <i class="icon-upload icon-white"></i> Upload
</button>
```
Noe a huge problem, but it did waste my time trying to work out why my "no dependencies" code didn't match the example.

**Comment by rnicholus** [comment]
You could say the same for the button styles too. Not seeing how this is a bug though. I'll happily accept a pull request to "fix" this though.

**Comment by kb-ptti** [comment]
It's a bug because the purpose of the example is to teach me about Fine-Uploader and its template system, so if I see something declared to have "no dependencies" then I have to assume that all the classes are something to do with Fine-Uploader templates because, by definition, I know nothing about them and am learning from this example.  So, yes, you're right, use of the boostrap.css "btn" and "btn-primary" button styling classes is also a bug, because I thought they were something to do with Fine-Uploaders template system too.
