### ISSUE TITLE
[Production files ?] Issue from archive usage of 5.12.0

### ISSUE THREAD

**Issue by vincent-guesnard** [FineUploader/fine-uploader#1715]
Hello,

Thank you, very much, for this amazing library. It works flawlessly, in a very great crossbrowser context. You did and begin to do a very good job.

I'm trying to update for 5.12.0. I'm encountering an issue : where are the production's files ? (ones present in your previous releases : jquery.fine-uploader.min.js, fine-uploader.min.css ... )

If i can help, in any matter, i'm available and ready to work with you.

**Comment by rnicholus** [comment]
Where are you looking for these files?

**Comment by vincent-guesnard** [comment]
Ok, i see that the owner just did an update of files on the 5.12.0 release. That's OK for me :)

Thank you !

**Comment by rnicholus** [comment]
yep - that was me. I forgot to upload the zip files for those that download from the website instead of via npm.
