### ISSUE TITLE
Error message from server: Exact one file in required even when only one file is selected for upload

### ISSUE THREAD

**Issue by matchon-on** [FineUploader/fine-uploader#1717]
## Type of issue [REQUIRED]
Bug
## Uploader type [REQUIRED]
Traditional

## Bug details [DELETE EVERYTHING IN THIS SECTION IF THIS IS A FEATURE REQUEST]

I use Aliyun as backend. When I try to upload a file, exactly one file, the server returned such message:

<Error>
  <Code>IncorrectNumberOfFilesInPOSTRequest</Code>
  <Message>POST requires exactly one file upload per request.</Message>

Is there a way to address this problem before a bug fix or new release? I really like this library and want to use it on my project.

### Fine Uploader version [REQUIRED]
5.12

### Browsers where the bug is reproducible [REQUIRED]
Chrome
### Operating systems where the bug is reproducible [REQUIRED]
Linux

### Exact steps required to reproduce the issue [REQUIRED]
For example:
1. Selected on one file, a image file.
2. The upload.

### All of your Fine Uploader initialization JavaScript code [REQUIRED]

```
        var manualUploader = new qq.FineUploader({
            element: document.getElementById('fine-uploader-manual-trigger'),
            template: 'qq-template-manual-trigger',
            request: {
                endpoint: 'https://shujubiji.cn/uppv/' // Backend on Aliyun object service.
            },
    multiple:false,
            thumbnails: {
                placeholders: {
                    waitingPath: 'client/placeholders/waiting-generic.png',
                    notAvailablePath: 'client/placeholders/not_available-generic.png'
                }
            },
            autoUpload: false,
            debug: true,
    callbacks: {
    onSubmit: setParams
    },

        });

        qq(document.getElementById("trigger-upload")).attach("click", function() {
            manualUploader.uploadStoredFiles();
        });

    function setParams(id, name) {

    var params =  {
        'key' : uppv.dir + name,
        'policy': uppv.policy,
        'OSSAccessKeyId': uppv.accessid, 
        'success_action_status' : '200', //Let server return 200.
        'signature': uppv.signature,
         expire : parseInt(uppv.expire)

    };

    this.setParams(params, id);
    }

    console.log(manualUploader);
    setKeyNames.bind(manualUploader);


```

### Detailed explanation of the problem [REQUIRED]

Backend returned with:

<Error>
  <Code>IncorrectNumberOfFilesInPOSTRequest</Code>
  <Message>POST requires exactly one file upload per request.</Message>

**Comment by rnicholus** [comment]
No idea. I don't see how this is a Fine Uploader issue - the error is coming from your backend code. If you can point to a specific problem with the client-side code, let me know.

**Comment by matchon-on** [comment]
The message says in the post request, 'IncorrectNumberOf FilesInPOSTRequest', and 'POST requires exactly one file upload per request.' . I selected only one file for upload. Is it possible that when the upload is submitted, somehow multiples files are put in the muliti part post data?

**Comment by rnicholus** [comment]
No, that is not possible as far as I know. But you can verify by looking at the request

**Comment by matchon-on** [comment]
Tried plupload. It worked.

Compared the multipart data. I found out your name field for file is : 'qqfile', while plupload is more standard 'file'. Is this why? Maybe my object service only knows 'file'.

Is there a way to set the field name for file in your API? I still prefer yours even plupload works. 

Yours:

------WebKitFormBoundary3nRlhLkzBAvp1aCi
Content-Disposition: form-data; name="qqfile"; filename="qrcode_for_gh_4ccf93996023_1280 (1).jpg"
Content-Type: image/jpeg

Plupload:

------WebKitFormBoundaryRASn1DYJKS7swdIA
Content-Disposition: form-data; name="file"; filename="qrcode_for_gh_4ccf93996023_430.jpg"
Content-Type: image/jpeg

**Comment by rnicholus** [comment]
Yes you can change it. See http://docs.fineuploader.com/branch/master/api/options.html#request.inputName.

**Comment by matchon-on** [comment]
Thanks.

t works now. But a new problem comes. Your lib attempts to parse the response body as Json automatically. But my object store service provider responds with xml.

Is it possible to override this? I tried onComplete callback by response parsing as json still happens before it is called.

Or should I use onError?

**Comment by rnicholus** [comment]
No, you must return JSON with a `success` property containing a value of `true`. This may be relaxed in a future breaking change release, but this has been a requirement since day 1.

**Comment by matchon-on** [comment]
Oh. Thanks for the response. Maybe I will have to hack your code now. :)

**Comment by rnicholus** [comment]
Please do. OSS is meant to be modified.
