### ISSUE TITLE
Chunking problem

### ISSUE THREAD

**Issue by standus** [FineUploader/fine-uploader#1722]
I tested v 5.12.0 with my htaccess configuration which blocking any php script. All staffs is redirected via ajax call. Seems that init FU forks well, but uploading not. I can not see any XHR request in browser. Why?
I see in console log:
[Fine Uploader 5.12.0] Error when attempting to parse xhr response text (Unexpected token < in JSON at position 0)
My browser is Chrome 55.
In FF 50.1 I see error: Error: No createObjectURL function found to create blob url, at fine-uploader.js:4051:31.
```
var URL = window.URL && window.URL.createObjectURL ? window.URL : window.webkitURL && window.webkitURL.createObjectURL ? window.webkitURL : null;
                    if (!URL) {
                        throw Error("No createObjectURL function found to create blob url");
                    }
```

**Comment by standus** [comment]
For other people I found that it is broken by ckeditor plugin named 'eqneditor'. By disabling it all works well.

**Comment by rnicholus** [comment]
Thanks. Going forward, please read the [issue guidelines](https://github.com/FineUploader/fine-uploader/blob/develop/.github/CONTRIBUTING.md) before opening new issues.
