### ISSUE TITLE
Remove content-length-range

### ISSUE THREAD

**Issue by dan-0** [FineUploader/fine-uploader#1725]
## Type of issue
Feature Request

## Uploader type
S3

### Detailed description of the feature
I was considering submitting a PR to change the implementation of "content-length-range" in the S3 implementation (client/js/s3/util.js:359-367) when requesting a signed policy from the server. While debating whether it was correct to submit a PR to change the implementation of "content-length-range" to a key/value JSON object, I started to wonder whether a client side implementation of content-length-range was necessary at all as it could even be misleadingly dangerous.

Having client side validation of sizeLimit, forces the server side implementation to at least receive the client side specified sizeLimit for an S3 signed policy request. This can lead to potentially bad security practices as some incorrect server side implementations may implicitly trust the client provided value. This may be fine in some cases, but I imagine in most cases allowing the client side to dictate the max size limit of an upload can allow someone to maliciously manipulate the content-length-range from the client side in hopes that the server trusts the provided values.

I propose to remove content-length-range as a mandatory value being submitted to the server if the developer chooses to implement a sizeLimit validation client-side. If a developer requires that this value be submitted by the client, then I suggest that it be implemented through an explicit declaration in customerHeaders instead. I may be wrong, but I can't think of a good use case for content-length-range to be a mandatory parameter from a security standpoint for most implementations. At the very least it might save someone from receiving a series of undesired 5TB uploads and jacking up their S3 bill.

**Comment by rnicholus** [comment]
Thanks for your summarizing the issue and bringing this to my attention. A few things to consider:

1. If `content-length-range` is _not_ included, the file size is unrestricted anyway.
2. `content-length-range` is _only_ sent for non-chunked requests (requests smaller than 5 MiB by default)
3. The inclusion of such a header, unvalidated by the server, seems to present no additional risk than if the header was omitted. Server-side implementations should check for this header if this is an important restriction.

Also, this would be a breaking change, so there is no chance this will be introduced anytime in the near future.

**Comment by dan-0** [comment]
All valid points. I was not aware of number 2, and that negates much of the potential seriousness of this.

With that considered, in addition to this being a breaking change, I would consider it to be something to be left to the developer implementing FileUploader to be concerned with. I agree with killing the issue.

**Comment by rnicholus** [comment]
Cool, thanks for the follow-up. And I do appreciate the your input on this as well.
