### ISSUE TITLE
Review capture attribute of input

### ISSUE THREAD

**Issue by xllily** [FineUploader/fine-uploader#1728]
## Type of issue
feature request

## Feature request details
[Answered my own question on stackoverflow](http://stackoverflow.com/questions/41831915/how-to-call-the-camera-on-mobile-device-by-the-fineuploader-library)

According to [**Capture Attribute**](https://www.w3.org/TR/html-media-capture/#dfn-media-capture-mechanism),

And **Fine-Uploader** only provided [`accept`](http://docs.fineuploader.com/branch/master/api/options.html#validation.acceptFiles) interface, 

there is no `capture` interface,

so when my  needs are  **"always** upload photos from the camera to shoot ",

I have to manually set capture attribute as the following code
    
    $(function() {
      new qq.FineUploader({
          element: ...,
          request: {
              endpoint: '...'
          },
          callbacks: {
              onAllComplete: function(suc, fail) {
                  addCaptureAttr();
              }
          },
          validation: {
              acceptFiles: 'image/*;'
          }
      });

      function addCaptureAttr() {
          //if only one input with file type
          $("input[type=file]").attr({
              capture: "camera" //(or any "truthy values")
          });
      }
      addCaptureAttr();
    });

So request to add capture prop in validation option,
just like:

      validation: {
           acceptFiles: 'image/*;',
           capture:"camera"
      }

**Comment by rnicholus** [comment]
let's discuss further on SO

**Comment by rnicholus** [comment]
I think this is best addressed by adding a `capture` option that takes a boolean which maps to the `capture` attribute on the file input element. Defaults to false. Would you be able to open up a pull request to address this?

**Comment by xllily** [comment]
@rnicholus  add a `capture` option inside to `"_createUploadButton"` of  `uploader.basic.api.js`,and then pull request to `dev` branch,Is it this way?

**Comment by rnicholus** [comment]
Not sure I understand what you're saying.

**Comment by xllily** [comment]
I mean I only be able to add a `capture` option in the packaged source code

**Comment by rnicholus** [comment]
Still not sure what you are saying.

What I'm asking is: Would you be interested in opening up a pull request to include this option in the source code?
