### ISSUE TITLE
request for a "onCancelComplete" calback event

### ISSUE THREAD

**Issue by dobrys** [FineUploader/fine-uploader#1731]
## Type of issue [REQUIRED]

feature request
## Uploader type [REQUIRED]

traditional

It will be very helpful to have "onCancelComplete" event , who will be fired when "onCancel" finish and "canceled" file was removed from list.

I make it in my code but only in JQuery version in such way:
....
                    onCancel: function(id, name, cancelFinalizationEffort) {
                        var promise = new qq.Promise();
                        self._handleCheckedCallback({
                            name: "onCancel",
                            callback: qq.bind(self._options.callbacks.onCancel, self, id, name),
                            onFailure: promise.failure,
                            onSuccess: function() {
                                cancelFinalizationEffort.then(function() {
                                    self._onCancel(id, name);
                                    //fire "onCancelComplete" event
                                    self._options.callbacks.onCancelComplete(id,name);
                                });
                                promise.success();
                            },
                            identifier: id
                        });
                        return promise;
                    },
.....

**Comment by rnicholus** [comment]
This doesn't seem necessary. You should be able to observe the existing onStatusChange event instead, looking for a newStatus of qq.status.CANCELED.
