### ISSUE TITLE
Aysnc task on onComplete event

### ISSUE THREAD

**Issue by farskid** [FineUploader/fine-uploader#1734]
## Type of issue [REQUIRED]
"feature request"

## Uploader type [REQUIRED]
"traditional"

### Detailed description of the feature
Currently fine uploader only accepts async tasks (promises) on some certain event handlers such as `onSubmit`. What I need is the same feature on `onComplete`. This could be useful as in the situation I'm currently experiencing, When file uploader writes to a local server and then server uploads to the actual physical server from the local server. In this case an async feature on `onComplete` could be really helpful to alert to the user that the actual upload has not been done.
Currently since no promise could be returned in `onComplete`, the uploader updates file's status to success but an error could happen on the second phase of uploading and there is no way to update the status again.

**Comment by rnicholus** [comment]
Not sure I understand what specific asynchronous task you'll monitor/create in your onComplete handler. Can you explain a bit more?

**Comment by farskid** [comment]
Yeah sure. My upload process has two phases. In the first phase, users submit their file to fine uploader and it uploads it to a temp folder inside my upload server. Then in phase two Nodejs streams these temp files to the permanent server.

##The problem
Fine uploader changes files status to success as soon as the file is uploaded to the temp server, but what I actually need is that I want to hold the file's status until Nodejs streams the file to the primary server successfully. It could be done (I guess), one `onComplete` listener accept a promise object and change the status to success one the promise resolves, or change it to failed when promises rejects.

**Comment by rnicholus** [comment]
How are you going to monitor this specific operation in your handler? And why not simply defer the response to fine uploader from your server until the second process has completed?

**Comment by farskid** [comment]
Don't know how to defer it to uploader from my server.
What I'm doing now is something like this:
```callbacks: {
  onSubmit: (id, name) => {
    return new Promise((resolve, reject) => {
      checkForUploadPermission(name, size).then((response) => {
        if (response.success) resolve(response)
        else reject('Not Permitted!')
      })
    }),
    onComplete: (id, name) => {
      // Since onComplete does not accept a promise, It doesn't wait for server resonse and evaluates the status to success immidiately
      return new Promise((resolve, reject) => {
        uploadToPermanentServer(name, size).then((response) => {
          if (response.success) resolve(response)
          else reject('Upload to permanent server failed!')
        })
      })
  }
}```

**Comment by rnicholus** [comment]
This introduces complexity for very little gain, and I think your use case is best solved by responding to fine uploader when all related server tasks are completed instead. I appreciate the report though.

**Comment by farskid** [comment]
I managed to solve the issue eventually by not using the `Gallery` higher order component. I used the stateless components such as `Thumbnail` manually and Did not listen to the status that uploader sends to the file after `onStatusChange`. What solved this was to connect the uploader component to my reducer which updates file's status when my NodeJS server has finished it's async upload back there.

**Comment by rnicholus** [comment]
Ah, I didn't realize this was related to react-fine-uploader. One nitpick: `<Thumbnail />` is not a stateless component.

If there is something specific missing from react-fine-uploader that could make this easier for you, please open up an issue in that repo so we can discuss further. Thanks for the update.

**Comment by farskid** [comment]
About the `Thumbnail`, My bad.
I added some useful components to my package of React fine uploader, I could send a PR if you wish. Thanks for the great support and fabiolous library.

**Comment by rnicholus** [comment]
Yes, please do open a PR. I'd love to discuss. Fair warning: I'm discerning (some would say annoyingly so) about code that goes into a number of my libraries. I'm big on pairing new code with automated tests and comprehensive documentation. I also try to be careful to keep the behaviors/API simple and intuitive, favoring integration code over in-library code wherever it makes sense. What this means is that, sometimes documentation is more appropriate than adding more code to the library. Just wanted to mention this, so it doesn't seem like I'm being arbitrarily harsh. I _do_ appreciate contributions whether they make it into the library or not.
