### ISSUE TITLE
bring setStatus to the public api list

### ISSUE THREAD

**Issue by CoolGoose** [FineUploader/fine-uploader#1738]
## Feature request details

I would like to have the setStatus method in the public api.
I want to handle the file delete process without doing an ajax call.
This works well using the onSubmitDelete event, and calling remove() on the dom node, but without changing the status of the file, it keeps it on the queue as valid, and the itemLimit property is broken because of that.

**Comment by rnicholus** [comment]
>I want to handle the file delete process without doing an ajax call.

How would you do this, exactly?

**Comment by CoolGoose** [comment]
Hi,
I'm using the below code to do some vuejs integration work (among other things, let me know if you want the full js code for the section.

```js
onSubmitDelete(id) {
    swal({
        title: 'Are you sure?',
        text: "Remember to save your changes!",
        type: 'warning',
        showCancelButton: true,
        confirmButtonColor: '#3085d6',
        cancelButtonColor: '#d33',
        confirmButtonText: 'Yes, delete it!'
    }).then(() => {
        vm.$store.dispatch(
            `addons/deleteFile`,
            { filename: this.getName(id), uploadRef: vm.uploadRef }
        ).then(() => {
            $(this.getItemByFileId(id)).remove();
        });
    });

    return false;
},
```

**Comment by rnicholus** [comment]
So you _are_ using an ajax request to delete a file, but you want to do this outside of Fine Uploader.

**Comment by CoolGoose** [comment]
I'm actually not even doing an ajax request on delete, i'm updating the list of available items in vue, and on the page's update method i'm saving it to persistance with the updated object containing the various aspects of the product (text, description, current image list and a flag that says it should trigger a delete process).

The point that you bring up is valid however, it's a way of controlling the delete process by itself outside of fineUploader, and the closest and fastest thing i could think of is allowing control of the various states of the files by hand.

**Comment by rnicholus** [comment]
Interesting. On a related note have you see the (in progress) [Vue Fine Uploader project](https://github.com/Elhebert/vue-fineuploader/tree/feature/refactor)?

I can see the need for this, but there is a bit of a problem: simply changing the status of a file is often not sufficient. There is other internal logic that leads up to a status change. You can see an example in the [internal `_onDeleteComplete` method](https://github.com/FineUploader/fine-uploader/blob/5.14.0-beta1/client/js/uploader.basic.api.js#L1436), where a number of internal state items are updated before the file is marked as deleted. 

I think it makes sense to expose `setStatus`, but I don't anticipate allowing any status to be set initially. Perhaps support for all status items could be phased in over time. Initially, `qq.status.DELETED` and `qq.status.DELETE_FAILED` would be the only status items supported, and this would require some internal refactoring to tie the logic in `_onDeleteComplete` to a requested state change of `qq.status.DELETED` or `qq.status.DELETE_FAILED`.

**Comment by CoolGoose** [comment]
@rnicholus didn't see that yet, thank you for the heads up.

My vue integration is way more crude, and it's based around the default fineUploader templates and methods, without a major sort of rewrite (hooking into events and api's)

The alternative for setStatus, would be a way of changing the status from within onSubmitDelete event, or allow it to 'pass' without doing any type of ajax request.

**Comment by rnicholus** [comment]
I think your suggestion may be easiest, but it sounds like a hack to me, and there may be real benefit in exposing, or at least starting to expose `setStatus`. The path forward for a library of this size is to make integration as easy as possible, and that means Fine Uploader's API needs to be flexible.

**Comment by CoolGoose** [comment]
@rnicholus that's true ;) I agree for a better long term solution that would help maintainability .

Would you want me to do an initial rough pull request with:

1. setStatus with DELETE and DELETE_FAILED
2. extract onDeleteComplete if/else into _handleDeleteSuccess / _handleDeleteFailed ?
3. update the docs with the info ?

**Comment by rnicholus** [comment]
That sounds good. I'm not sure exactly what the code will look like yet, but it should be easily extensible to support more status updates later. Also, for the delete case, we'll need new unit tests to cover this new feature. There are existing tests to cover the current behavior in the delete-file.js test file. Perhaps new tests to cover `setStatus` with the two deleted status values could exist in there. Or maybe it is more appropriate to create a new `setStatus` test file.

**Comment by CoolGoose** [comment]
@rnicholus I've written an initial pull requests so we can discuss the changes. https://github.com/FineUploader/fine-uploader/pull/1739
