### ISSUE TITLE
CHNAGELOG

### ISSUE THREAD

**Issue by jedie** [FineUploader/fine-uploader#1740]
https://blog.fineuploader.com/category/changelog/ is the official changelog. But last entry is for 5.10 and current version is 5.13 :(

There was #1294 that's closed, because of the Blog...

+1 for a simple CHANGELOG file in the repo

**Comment by rnicholus** [comment]
That's not the official changelog. I used that for a while, but decided to move the changelog to the repo itself at some point. See the releases section in the repo for details: https://github.com/FineUploader/fine-uploader/releases

**Comment by jedie** [comment]
Then you should create a blog entry with a link to https://github.com/FineUploader/fine-uploader/releases

And also add a link into README ;)
