### ISSUE TITLE
how to access session.endpoint json data in onDelete callbacks.

### ISSUE THREAD

**Issue by ajaysingh13500** [FineUploader/fine-uploader#1741]
## Uploader type [traditional]

hi.. straight to the point...
my session.endpoint json data have a unique id from the dataBase and i want that id in onDelete callback which i am going to pass for delete data from database..
can you please help how can i access that...

**Comment by ajaysingh13500** [comment]
hay why you closed it....

**Comment by rnicholus** [comment]
https://github.com/FineUploader/fine-uploader/blob/develop/.github/CONTRIBUTING.md
