### ISSUE TITLE
Console Error in Chrome 

### ISSUE THREAD

**Issue by sourabhnighot** [FineUploader/fine-uploader#1742]
## Type of issue [REQUIRED]
{ "bug"}

## Uploader type [REQUIRED]
{ "Azure"}

## Bug details [The error message:
jquery.fine-uploader.js:164 
Uncaught TypeError: Cannot read property 'addEventListener' of null
at Object.attach (jquery.fine-uploader.js:164)]

### Fine Uploader version [REQUIRED]
{5.11.8}

### Browsers where the bug is reproducible [REQUIRED]
{"Google Chrome"}

### Operating systems where the bug is reproducible [REQUIRED]
{"Windows 8"}

### Exact steps required to reproduce the issue [REQUIRED]
1. Just load a page containing Fine Uploader and the Error is visible in the console window of browser

### All of your Fine Uploader initialization JavaScript code [REQUIRED]
{We use fine uploader as source
![js_error_2017-01-30_09-07-30](https://cloud.githubusercontent.com/assets/25585862/22648581/56f5b3c4-ec9d-11e6-88b4-7d936e967a47.png)
}

### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
{}
### Detailed explanation of the problem [REQUIRED]
{We have a html page where we use the fine uploader to upload files. When the page is opened in Google Chrome there is a console error in the browser about the "AddEventListener". I have attached a screenshot.
![js_error_2017-01-30_09-07-30](https://cloud.githubusercontent.com/assets/25585862/22648465/dac2b18a-ec9c-11e6-82e9-67b0ea1ca309.png)
![js_error_2017-01-30_09-07-30](https://cloud.githubusercontent.com/assets/25585862/22648474/e33ace9c-ec9c-11e6-962a-4a47fa8a2500.png)

}

### Detailed description of the feature
{also include why this feature is necessary and what problems it solves}

**Comment by rnicholus** [comment]
Sorry, I'm unable to reproduce without seeing your code. This sounds like an issue specific to your setup/code, but I'll be happy to consider re-opening once you update the issue with all of the code needed to reproduce.

**Comment by sourabhnighot** [comment]
Hi Nicholas,

I have attached the html page in which we use fine uploader to upload file.
You can just open the html page and see the console error in the console
window of Google Chrome Browser.

**Comment by rnicholus** [comment]
Nothing is attached

**Comment by sourabhnighot** [comment]
Strange because I had attached and I can see. No problem I will attach the
html file again.
