### ISSUE TITLE
How can I use fine-uplaoder with angular 2 project ? 

### ISSUE THREAD

**Issue by rainstormza** [FineUploader/fine-uploader#1744]
## Type of issue [REQUIRED]
feature request

## Uploader type [REQUIRED]
traditional

### Fine Uploader version [REQUIRED]
5.13.0

## Feature request details [DELETE EVERYTHING IN THIS SECTION IF THIS IS A BUG REPORT]
using this library with angular 2

### Detailed description of the feature
how can I use this library with angular 2 project (angular-cli using webpack for generate project)

thanks

**Comment by rainstormza** [comment]
@rnicholus Is it not possible to use with angular 2 ?

**Comment by rnicholus** [comment]
It is possible to use it with any framework, of course. Why would it not be? 

Before you ask any further questions in the issue tracker, please read the contribution rules. They are linked to at the top of the new/create issue page.

**Comment by Mds92** [comment]
How can I use it in Angular 4 project?
