### ISSUE TITLE
option to customise _removeFileItem()

### ISSUE THREAD

**Issue by nalbion** [FineUploader/fine-uploader#1747]
## Type of issue
feature request

## Feature request details
I have had to monkey-patch `_removeFileItem()` to meet the needs of my project, but it would be good if there was an optional callback or method over-ride as there is for `showConfirm()`

### Detailed description of the feature
I wanted to animate file items being removed from the upload list (whether being deleted or cancelled).  This is my work-around:

```javascript
var _removeFileItem = this.uploader._removeFileItem;
        this.uploader._removeFileItem = (id: number) => {
            // Animate the item removal
            var element = this.uploader.getItemByFileId(id);
            element.style.height = element.offsetHeight + 'px';
            element.classList.add('ng-leave');
            $timeout(() => {
                element.classList.add('ng-leave-active');
            }, 0);

            // I also remove the file from my `uploadedFiles` array, but could probably be doing that in onStatusChange() or onDelete()

            // When animation complete, call the original _removeFileItem method
            $timeout(_removeFileItem.bind(this.uploader, id), 300);
        };
```

My concern is that because I'm using an undocumented private API, my application might not be compatible with future versions of FineUploader.

**Comment by rnicholus** [comment]
>My concern is that because I'm using an undocumented private API, my application might not be compatible with future versions of FineUploader.

This is a valid/correct concern. Underscored properties are not part of the public API and may change or be removed at any time without notice.

Your best bet it to utilize the fact that both `onCancel` and `onSubmitDelete` allow for promissory return values. In that case, you can do the following for each of your callbacks:

1. Return a `Promise`
2. Add the `'ng-leave' `className` to the underlying file element. You can find this element using the [`getItemByFileId()` UI API method].(http://docs.fineuploader.com/branch/master/api/methods.html#getItemByFileId).
3. After the desired time has elapsed. Add the 'ng-leave-active' `className` to the element.
4. Resolve the `Promise`.

**Comment by nalbion** [comment]
Thanks @rnicholus

**Comment by nalbion** [comment]
Actually, `onSubmitDelete` is called before `showConfirm()` - if the user cancels the delete operation I'd have to undo anything done in my animation.

`onDeleteComplete` is too late to animate because `qq.FileUploader,onDeleteComplete` has called `_removeFileItem()` (the method I had to monkey-patch) before calling `options.callbacks.onDeleteComplete`.

If I do the animation in `onDelete` it looks okay, as long as the network operation succeeds, otherwise I'd have to undo everything done in my "animation" in `onDeleteComplete(id, xhr, true)` - which actually includes `this.uploadedFiles.splice(i, 1)` where `i` is not guaranteed to be equal to `id`.
