### ISSUE TITLE
Meta fields for descriptions along with newly uploaded files

### ISSUE THREAD

**Issue by antwortzeit** [FineUploader/fine-uploader#1752]
## Type of issue
feature request

## Uploader type
traditional

## Feature request details 
Hey,

i'm using FineUploader for the first time on a project and was wondering, if there's an easy way to add a description field for each download. Or do i have to grab the data returned with jQuery and add the fields outside of the holding div?

Thanks in advance!

### Detailed description of the feature
{also include why this feature is necessary and what problems it solves}

**Comment by antwortzeit** [comment]
Uhm, why did you just close this? Is this feature already available and i just didn't see it?

**Comment by rnicholus** [comment]
This isn't a feature request, you've asked for support. Before you ask any further questions in the issue tracker, please read the contribution rules. They are linked to at the top of the new/create issue page.
