### ISSUE TITLE
itemLimit Validation in fineuploader isn't Working in case extraButtons are enabled with elements

### ISSUE THREAD

**Issue by stevenAric** [FineUploader/fine-uploader#1756]
kindly this is a bug report about a property in fineUploader , 
first of all I am using traditional uploader type and the problem is that I have extraButtons option enabled with element and validation rules provided and in validation rules I enabled itemLimit property to set limit to each extraButtons element, this itemLimit isn't working although all the rest of validation rules in each limit are working like sizeLimit or allowedExtensions.
 give a  look at my code.

`    
      
` 

            var uploader = new qq.FineUploader({
            debug: true,
            element: document.getElementById('my-uploader'),

            request: { 
                endpoint: "endpoint.php" 

        
            chunking: {
            enabled: true,
            concurrent: {
                enabled: true
            },
            success: {
                endpoint: "endpoint.php?done",
            }
        },
            deleteFile: {
                enabled: true,
                endpoint: "endpoint.php"
            },
            
            retry: {
            enableAuto: true,
            showButton: true
        },
         
     form:{
        
              element:"test",
     
    
        // autoUpload:true,
        //interceptSubmit:true
       },
      

     
         display:{
            prependFiles:true, 
            
         }, 
       
       
       validation: {
                allowedExtensions: ["png","jpg"], 
                  
                   itemLimit : 3, 
                  // sizeLimit:10000000000,
            },
            

```
 extraButtons: [
        {
            element: document.getElementById("upFileTwo"),
            validation: {
                allowedExtensions: ["jpg"],
                itemLimit:1
            }
        }
    ],
```
     
                     
          
            text:{
              defaultResponseError:" Error In Upload, Please Try Again. ", 
            },
 
            callbacks: {
            onError: function(id, name, errorReason, xhrOrXdr) {
             alert(qq.format("Error on file number {} - {}., Please Check Your Internet And Try Again", id, name));
       
            },
            
           onValidate:function(file){
        
            },
        
           onSubmitted:function(id,name){ 
        
              this.uploadStoredFiles(); 
            },
     
            onStatusChange:function(id,oldStatus,newStatus){
                if(oldStatus=="submitting"){ 
        
                }
                if(newStatus=="deleted"){
              }
            },
              onComplete:function(id,name,responseJSON,xhr){ 
            },
                onAllComplete:function(sucessArr,FailedArr){
                }
        
    },
            

            resume: {
                    enabled: true
                },
      
      
        });
        

 

Browser :chrome 
version : 56
Fine Uploader version :5.13.0
Operating system : Windows 7

#### Exact steps required to reproduce the issue

1. give to buttons id in a form to extraButtons element
2.in the general fineUploader Validation Object define itemLimit:3
3.specify validation rule of itemLimit:1 in the extraButtons specific Validation Rules
4.try to upload 2 images from the button of extraButtons Element, it will upload 2 images, not 1 which I specified in fineUploader ExtraButton Validation rules of itemLimit:1

**Comment by rnicholus** [comment]
Sounds like itemLimit was simply not accounted for when handling extraButton validation. Some investigation is needed to determine how difficult/possible it is to address this.

**Comment by stevenAric** [comment]
ok , take your time and iam waiting for a response.

**Comment by rnicholus** [comment]
Take my time with what?

**Comment by rnicholus** [comment]
This is pretty low on my priority list at the moment. It's unlikely I'll get to this in the near future. That said, you are free to look into the issue and help push this forward. I'd be happy to offer advice/assistance.

**Comment by stevenAric** [comment]
Mr rnicholus , i solved this issue on my side and worked prefectly, please review the code.
the change will be only in _onValidateBatchCallbackSuccess Event and I will remark the changes by making the font Bold. 



`_onValidateBatchCallbackSuccess: function(validationDescriptors, items, params, endpoint, button) {
              **var getAllSpecsOfCurrentButton=this._extraButtonSpecs[this._getButtonId(button)];//get Specifications of each button to get Validation Rules

if(getAllSpecsOfCurrentButton&&getAllSpecsOfCurrentButton.validation&&getAllSpecsOfCurrentButton.validation.itemLimit&&getAllSpecsOfCurrentButton.validation.itemLimit>0){ //if it is an extra button and containing validation rules and itemLimit , then make the global _currentItemLimit property = the itemLimit Specified in the validation Rules
                    this._currentItemLimit=getAllSpecsOfCurrentButton.validation.itemLimit;
                }
                else if(!getAllSpecsOfCurrentButton){ //if it isn't an extran button , that means it is the default uploader button ,so restore the itemLimit Global validation rules to the global _currentItemLimit variable
                    this._currentItemLimit=this._options.validation.itemLimit;
                }**
                
                var errorMessage, itemLimit = this._currentItemLimit, proposedNetFilesUploadedOrQueued = this._netUploadedOrQueued;
                if (itemLimit === 0 || proposedNetFilesUploadedOrQueued <= itemLimit) {
                    if (items.length > 0) {
                        this._handleCheckedCallback({
                            name: "onValidate",
                            callback: qq.bind(this._options.callbacks.onValidate, this, validationDescriptors[0], button),
                            onSuccess: qq.bind(this._onValidateCallbackSuccess, this, items, 0, params, endpoint),
                            onFailure: qq.bind(this._onValidateCallbackFailure, this, items, 0, params, endpoint),
                            identifier: "Item '" + items[0].file.name + "', size: " + items[0].file.size
                        });
                    } else {
                        this._itemError("noFilesError");
                    }
                } else {
                    this._onValidateBatchCallbackFailure(items);
                    errorMessage = this._options.messages.tooManyItemsError.replace(/\{netItems\}/g, proposedNetFilesUploadedOrQueued).replace(/\{itemLimit\}/g, itemLimit);
                    this._batchError(errorMessage);
                }
            },`

**Comment by rnicholus** [comment]
Please open a pull request. This will allow us to discuss the changes a bit more formally and efficiently.

**Comment by stevenAric** [comment]
I am sorry , but honestly,  I can't perfectly deal with repositories specifically on the point of where I should upload the new modified file, can I upload the file here or in StackOverflow as an issue?

**Comment by stevenAric** [comment]
By Mistake , i create this , https://github.com/FineUploader/fine-uploader/pull/1765 , you can delete it .
