### ISSUE TITLE
Apostrophe in filename

### ISSUE THREAD

**Issue by varby1984** [FineUploader/fine-uploader#1757]
## Type of issue
- [ ] Bug report

## Uploader type
- [ ] Traditional

I have a problem: when I want to upload a file that contains an apostrophe in filename, the request xhr is not really sent. The server does not receive its own request. I used the code base present in the official guide.
There is a solution for this problem?
Thanks.

#### Fine Uploader version
5.11.9

#### Browsers where the bug is reproducible
{example: "Firefox" and "Chrome"}

#### Operating systems where the bug is reproducible
{example: "Windows 8.1" and "Windows 10"}

**Comment by rnicholus** [comment]
Closing due to lack of runnable example code. If you edit your question to provide complete code, I will consider reopening.

**Comment by varby1984** [comment]
<script type="text/template" id="qq-template-gallery">
					<div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Drop files here">
						<div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
							<div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
						</div>
						<div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
							<span class="qq-upload-drop-area-text-selector"></span>
						</div>
						<div class="qq-upload-button-selector qq-upload-button">
							<div>Upload a file</div>
						</div>
						<span class="qq-drop-processing-selector qq-drop-processing">
							<span>Processing dropped files...</span>
							<span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
						</span>
						<ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
							<li>
								<span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
								<div class="qq-progress-bar-container-selector qq-progress-bar-container">
									<div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
								</div>
								<span class="qq-upload-spinner-selector qq-upload-spinner"></span>
								<div class="qq-thumbnail-wrapper">
									<img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
								</div>
								<button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
								<button type="button" class="qq-upload-retry-selector qq-upload-retry">
									<span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
									Retry
								</button>

								<div class="qq-file-info">
									<div class="qq-file-name">
										<span class="qq-upload-file-selector qq-upload-file"></span>
										<span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
									</div>
									<input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
									<span class="qq-upload-size-selector qq-upload-size"></span>
									<button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
										<span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
									</button>
									<button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
										<span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
									</button>
									<button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
										<span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
									</button>
								</div>
							</li>
						</ul>

						<dialog class="qq-alert-dialog-selector">
							<div class="qq-dialog-message-selector"></div>
							<div class="qq-dialog-buttons">
								<button type="button" class="qq-cancel-button-selector">Close</button>
							</div>
						</dialog>

						<dialog class="qq-confirm-dialog-selector">
							<div class="qq-dialog-message-selector"></div>
							<div class="qq-dialog-buttons">
								<button type="button" class="qq-cancel-button-selector">No</button>
								<button type="button" class="qq-ok-button-selector">Yes</button>
							</div>
						</dialog>

						<dialog class="qq-prompt-dialog-selector">
							<div class="qq-dialog-message-selector"></div>
							<input type="text">
							<div class="qq-dialog-buttons">
								<button type="button" class="qq-cancel-button-selector">Cancel</button>
								<button type="button" class="qq-ok-button-selector">Ok</button>
							</div>
						</dialog>
					</div>
				</script>
				
				<div id="fine-uploader-gallery"></div>
				<input class="hidden-dropzone" type="hidden" id="field-files" name="files" value="">
              </div>
			  
            </div>
			<script>
			
			
			<script>
				$('#fine-uploader-gallery').fineUploader({
						element: document.getElementById('fine-uploader-gallery'),
						template: 'qq-template-gallery',
						request: {
							endpoint: 'chunk-upload',
							params: {
								path: 'uploads/files/',
								operation: 'add',
								field_name: 'files'
							}
						},
						thumbnails: {
							placeholders: {
								waitingPath: 'fine-uploader/client/placeholders/waiting-generic.png',
								notAvailablePath: 'fine-uploader/client/placeholders/not_available-generic.png'
							}
						},
						validation: {
							itemLimit: 100,
							sizeLimit: 2048000000
						},
						chunking: {
							enabled: true,
							concurrent: {
								enabled: false
							},
							success: {
								endpoint: 'chunk-upload?done'
							}
						},
						resume: {
							enabled: true
						},
						retry: {
							enableAuto: true,
							showButton: false
						},
						deleteFile: {
							enabled: true,
							endpoint: 'chunk-upload'
						},
						
						callbacks: {
							onComplete: function(id, name, response) {
								this.setName(id, response.name);
							}
						}
					});
					
			</script>

**Comment by varby1984** [comment]
//<script type="text/template" id="qq-template-gallery">
//		<div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Drop files here">
//			<div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
//				<div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
//			</div>
//			<div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
//				<span class="qq-upload-drop-area-text-selector"></span>
//			</div>
//			<div class="qq-upload-button-selector qq-upload-button">
//				<div>Upload a file</div>
//			</div>
//			<span class="qq-drop-processing-selector qq-drop-processing">
//				<span>Processing dropped files...</span>
//				<span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
//			</span>
//			<ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
//				<li>
//					<span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
//					<div class="qq-progress-bar-container-selector qq-progress-bar-container">
//						<div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
//					</div>
//					<span class="qq-upload-spinner-selector qq-upload-spinner"></span>
//					<div class="qq-thumbnail-wrapper">
//						<img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
//					</div>
//					<button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
//					<button type="button" class="qq-upload-retry-selector qq-upload-retry">
//						<span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
//						Retry
//					</button>
//
//					<div class="qq-file-info">
//						<div class="qq-file-name">
//							<span class="qq-upload-file-selector qq-upload-file"></span>
//							<span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
//						</div>
//						<input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
//						<span class="qq-upload-size-selector qq-upload-size"></span>
//						<button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
//							<span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
//						</button>
//						<button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
//							<span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
//						</button>
//						<button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
//							<span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
//						</button>
//					</div>
//				</li>
//			</ul>
//
//			<dialog class="qq-alert-dialog-selector">
//				<div class="qq-dialog-message-selector"></div>
//				<div class="qq-dialog-buttons">
//					<button type="button" class="qq-cancel-button-selector">Close</button>
//				</div>
//			</dialog>
//
//			<dialog class="qq-confirm-dialog-selector">
//				<div class="qq-dialog-message-selector"></div>
//				<div class="qq-dialog-buttons">
//					<button type="button" class="qq-cancel-button-selector">No</button>
//					<button type="button" class="qq-ok-button-selector">Yes</button>
//				</div>
//			</dialog>
//
//			<dialog class="qq-prompt-dialog-selector">
//				<div class="qq-dialog-message-selector"></div>
//				<input type="text">
//				<div class="qq-dialog-buttons">
//					<button type="button" class="qq-cancel-button-selector">Cancel</button>
//					<button type="button" class="qq-ok-button-selector">Ok</button>
//				</div>
//			</dialog>
//		</div>
//	</script>
//	
//	<div id="fine-uploader-gallery"></div>
//	<input class="hidden-dropzone" type="hidden" id="field-files" name="files" value="">
//  </div>
//  
//</div>
//<script>
//
//
//<script>
//	$('#fine-uploader-gallery').fineUploader({
//			element: document.getElementById('fine-uploader-gallery'),
//			template: 'qq-template-gallery',
//			request: {
//				endpoint: 'chunk-upload',
//				params: {
//					path: 'uploads/files/',
//					operation: 'add',
//					field_name: 'files'
//				}
//			},
//			thumbnails: {
//				placeholders: {
//					waitingPath: 'fine-uploader/client/placeholders/waiting-generic.png',
//					notAvailablePath: 'fine-uploader/client/placeholders/not_available-generic.png'
//				}
//			},
//			validation: {
//				itemLimit: 100,
//				sizeLimit: 2048000000
//			},
//			chunking: {
//				enabled: true,
//				concurrent: {
//					enabled: false
//				},
//				success: {
//					endpoint: 'chunk-upload?done'
//				}
//			},
//			resume: {
//				enabled: true
//			},
//			retry: {
//				enableAuto: true,
//				showButton: false
//			},
//			deleteFile: {
//				enabled: true,
//				endpoint: 'chunk-upload'
//			},
//			
//			callbacks: {
//				onComplete: function(id, name, response) {
//					this.setName(id, response.name);
//				}
//			}
//		});
//		
//</script>

**Comment by varby1984** [comment]
I apologize, I realized now that the code has undergone a coding and not vinene displayed correctly. I 'the first time I write here. Something wrong?

**Comment by rnicholus** [comment]
Please _edit_ your question and include the code.

**Comment by varby1984** [comment]
thanks

**Comment by varby1984** [comment]
Hi  rnicholus. Do you have any news about my problem? Thanks!
