### ISSUE TITLE
Canceled uploads should not be auto-retried

### ISSUE THREAD

**Issue by strokirk** [FineUploader/fine-uploader#1758]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [x] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Support Request</summary>

#### Fine Uploader version
5.13.0

#### Question
Using `retry.enableAuto` is very useful to get automatic retrial of failed uploads, but sometimes we know from the response status code that it won't ever success. For example `413 REQUEST ENTITY TOO LARGE`.

I tried to use `this.cancel(id)` in my error handler to cancel the request, but FineUploader complains with this error:
```
Uncaught qq.Error {message: "[Fine Uploader 5.13.0] 0 is not a valid file ID to upload!"}
```

Is there any other way of aborting an upload before the next auto-upload?

#### Related code
JSFiddle with example: http://jsfiddle.net/6zdxpbj2/
</details>

**Comment by rnicholus** [comment]
If you want to prevent auto-retry, your server must return a JSON payload with a `"preventRetry": true` property. This is mentioned in the [server-side documentation page for traditional endpoints](http://docs.fineuploader.com/branch/master/endpoint_handlers/traditional.html).

**Comment by strokirk** [comment]
@rnicholus I see, thanks for the quick response.

In my case, I get the error response from a Nginx server which only returns the status code. Would it be possible to handle this case?

**Comment by rnicholus** [comment]
Yes, possibly. The question is: how can we best do this? Perhaps we could start simple by disabling auto-retry for 413 responses, or perhaps include a few other status codes that also indicate that the request should not be retried. This logic must be implemented in the [`_onAutoRetry` internal method](https://github.com/FineUploader/fine-uploader/blob/e372f8971eac77ff128285b6103f949fb622203b/client/js/uploader.basic.api.js#L1375).
