### ISSUE TITLE
Change progress bar from server side data

### ISSUE THREAD

**Issue by zaryk** [FineUploader/fine-uploader#1763]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [ ] Support request

I guess the main issue is that even though the an expiration can be set, in my case, it is not guaranteed a file will still be in the cache when a user wants to update a file.  This can be because the user wasn't paying attention and the upload did not complete, they are uploading an update after expiration, or the history can be cleared, and so is the cached data.  As far as I am aware, the onProgress only provides enough information to create a custom progressbar.  Currently, the workaround I have seems to work, so not really in hurry to receive an answer, but would like to see more flexibility in the events for server side calls.

## Uploader type
- [ ] Traditional
- [ ] S3
- [ ] Azure

<details>
I have a prompt that allows a user to overwrite, rename (appends _1, _2, server side), resume or cancels the download.  The prompt currently shows onsubmitting to retrieve information for each file, and places that information in hidden elements for each file.  OnUpload, it uses the information  (e.g. server side filesize) to compare against the uploading size.

I have modified fineuploader so that the below updateProgress calls the onprogress you have for updating the UI, and an added method on the handler to set a property only on resume, which is used to recalculate the progress of the chunk parts on sendNext.  NOTE:  Javascript is not my area of strength, took me a while to figure out where things were being called.

<pre>
                onUpload: function (id, name) {
                    var file = $(".qq-file-id-" + id);

                    var selectorValue = file.find("#duplicateSelectorValue").val();
                    if (selectorValue !== "") {
                        manualUploader.setParams({ operation: selectorValue }, id);
                    }
                    else
                    {
                        manualUploader.setParams({ guid: "", operation: "" }, id);
                    }

                    if(selectorValue === "append")
                    {
                        var file = $(".qq-file-id-" + id);
                        var oldSize = file.find("#oldSizeSelectorValue").val();
                        var newSize = file.find("#newSizeSelectorValue").val();
                        manualUploader.updateProgress(id, name, parseFloat(oldSize.substring(0, oldSize.indexOf("B"))), parseFloat(newSize.substring(0, newSize.indexOf("B"))));
                    }
                },
</pre>
</details>

<pre>
            _updateProgress: function (id, name, progress, total) {
                this._onProgress(id, name, progress, total);
                this._handler.setFileState(id, progress, total);
            },
</pre>

<pre>
            setFileState: function (id, loaded, total) {
                var state = this._getFileState(id);
                if (loaded && total) {
                    state.loaded = loaded;
                    state.CustomLoaded = loaded;
                }               
            },
</pre>

<pre>
sendNext: function (id) {

                var state = handler._getFileState(id);
                var nextIdx;
                var loaded = Math.ceil(state.loaded / options.chunking.partSize);
                if (state.CustomLoaded && (Math.ceil(state.file.size / options.chunking.partSize) - loaded + 1) !== state.chunking.remaining.length) {
                    state.chunking.remaining.splice(0, loaded)
                    nextIdx = chunked.nextPart(id);

                }
                else
                {
                    nextIdx = chunked.nextPart(id);
                }
</pre>

**Comment by rnicholus** [comment]
I'm having some trouble understanding your question. Can you try to re-phrase and clarify what you are looking for?

**Comment by zaryk** [comment]
Would you add/modify events/methods so that server side fileSize can be used to resume the upload even after the file has expired from cache, or browser history has been cleared?

The onProgress you have setup currently, I believe, only is there for creating a custom progressbar.  In my case, since the user should have the ability to resume an upload after expiration/cleared browser history, then I need to be able to update the progress of fineuploader based on server side file size.  I am not just saying that the UI should be updated, but be able to resume from the correct chunk part.

If you look at the sendNext method I provided above, I have set a value that is only used during the server side resume process (CustomLoaded).  

The below condition makes sure this value is set, which indicates the resume is in process, and checks to see if the the remaining length of chunkParts doesn't equal the new loaded chunkPart size.  This is because, if the file is still in the cache, then the remaining amount of chunkParts has already been spliced to the correct number and the two values should be equal.  But, if the file is not in cache anymore, then the full amount of the remaining chunkParts are being loaded, and would have to be spliced to get the correct remaining chunkParts.

<pre>
if (state.CustomLoaded && (Math.ceil(state.file.size / options.chunking.partSize) - loaded + 1) !== state.chunking.remaining.length) {
</pre>

**Comment by rnicholus** [comment]
>so that server side fileSize can be used to resume the upload 

There is a lot more information needed other than file size to resume a file.

I don't see providing another way to feed resume data into Fine Uploader at this time. But I would certainly look at and discuss a pull request, provided the changes are simple and well-tested.

**Comment by rnicholus** [comment]
>so that server side fileSize can be used to resume the upload 

There is a lot more information needed other than file size to resume a file.

The only reasonable way to do this would be to export the resume record(s) generated by Fine Uploader, store them server side, and then feed then into Fine Uploader via an API method.

**Comment by zaryk** [comment]
"There is a lot more information needed other than file size to resume a file."

I disagree based on what I have as a work around, though it may be more complicated than what I am doing, or so far, I haven't ran into an issue, but there may be an issue.  Also, I am not using s3 or azure, at this time.

Even though the events could be better suited for this type of thing, at least in this case, the only thing the developers would need is a better method exposed to indicate that this a special circumstance, and to compare the file size on the server with file being uploaded and move the chunkParts and UI appropriately.  Like I said, I already this working and it is all that I have already posted codewise (minus passthru methods to get to the handler), so at least low level method does work.  

1. File is uploaded, but paused or user closes browser.  
- parts have already been saved to server at the location they are going to be at when it finishes uploading.  The codebehind is handling where the file is being saved to based on database configuration.  I use c#.

2. File in fineuploader has been removed from cache, either through expiration or clearing history.

3. User drags and drops the same file, and the developer  (me and us) codes the events to handle what may happen if the file exists, like I have with the prompt.

Now if you want to handle actually getting the fileSize in the same progress or handle the prompt, it may be more complicated, but right now I have the fileSize returned onSubmitting and placed in file element, which is then used in the onUpload to change the progress of the chunks and UI.

**Comment by rnicholus** [comment]
The only reasonable way to do this would be to export the resume record(s) generated by Fine Uploader, store them server side, and then feed then into Fine Uploader via an API method.

**Comment by zaryk** [comment]
Well, I am not sure about the "only reasonable way", but I am sure that would require more work.  Having more control over the FineUploader regardless of whether we export the data or not would be my preferable way to go, and I don't see why both methods could not be added.

**Comment by rnicholus** [comment]
I'll admit I'm having a lot of trouble following your logic and your code. But it sounds like you want to be able to supply resume records from the server, and not just rely on `localStorage`.  In that case, I'm not sure why you are focusing on file progress/events. Progress really has nothing to do with resuming file uploads. I encourage you to take a close look at the resume upload logic in the library.

Having a complete understanding of the library and the various workflows: I think exporting the resume records and then re-importing them later would be, by far, the simplest route as well. This leaves a lot less margin of error as well.

**Comment by zaryk** [comment]
"But it sounds like you want to be able to supply resume records from the server, and not just rely on localStorage"

yes.

"In that case, I'm not sure why you are focusing on file progress/events."

With what is available and limited knowledge and time constraints, I had to use the above method to change both the UI progress bar percentage and chunkParts.  I am using the gallery template and not messing with much of the UI.  I had found out that calling your onProgress only changes the UI.  Then had to figure where to change the chunkParts.  I just need it to be called onUpload, so I made my own method to get there.  I am sure there were more builtin methods that I could have used, but this is my process of understanding the library and workflows, and getting what I have tasked to do done with limited knowledge.

"I think exporting the resume records and then re-importing them later would be, by far, the simplest route as well. This leaves a lot less margin of error as well."

If you think so, then I am all for it.

**Comment by rnicholus** [comment]
What I am trying to avoid is exactly what you are doing: "had to use the above method to change both the UI progress bar percentage and chunkParts". If you have a valid resume record, and the user drops/selects a file that matches the record, everything will "just work". So providing a way to export these records and store them wherever you like, along with an API method to import them again later from your storage location of choice, seems like an intuitive approach here.

**Comment by rnicholus** [comment]
Wherever this is, I'm not going to implement it
