### ISSUE TITLE
ValidateBatchAfterSubmit

### ISSUE THREAD

**Issue by zaryk** [FineUploader/fine-uploader#1768]
Type of issue

 Feature request

Add validateBatchAfterSubmit event which would come after OnSubmit

Uploader type

 Traditional
 S3
 Azure

I am looking for this:
<pre>
onValidateBatch(fileOrBlobDataArray, buttonContainer) {
                    
                },
</pre>
But instead this:
<pre>
onValidateBatchAfterSubmit(fileOrBlobDataArray, buttonContainer) {
                    
                },
</pre>
The fileOrBlobDataArray:
Would return the array of files that have passed through the OnSubmit.

P.S I really don't understand how "Add validateBatchAfterSubmit event which would come after OnSubmit" is not understandable.  Based on your docs, you don't have such a thing.

**Comment by rnicholus** [comment]
I'm pretty sure I was clear in my last comment what I expect in newly filed issues.
