### ISSUE TITLE
onCancelComplete and innerHTML?

### ISSUE THREAD

**Issue by Lance-Haysom** [FineUploader/fine-uploader#1772]
Type of issue
- [ ] Bug report
- [x] Feature request
- [x] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

#### Feature request details 
Is it possible to add `element.innerHTML = text;` to `setText()` or a terrible idea? I'd like a little more styling than plain text affords for error messages so I used `failedUploadTextDisplay` with a `mode: custom`. My server replies with some HTML. Without this it renders the markup to screen. I added the line and seems to work.

#### Support request details 
I too am interested in issue #1649. In an attempt to handle it myself I used the `onCancel` callback and `getUploads()` hoping to find 0 files to upload and I'd toggle a class to show/hide the :before message.
`getUploads` at this point, still has the cancelled file in it. I tried with a status of submitted - no deal.

I then got pretty nasty and counted the `<li>` dom elements and those also still have the cancelled file in there so `onCancel` is really `onBeforeCancel`? Possible for an `onCancelComplete`? 

I realise this is born from an already low priority issue so I know it's not a huge deal. I've resolved it for myself at the moment with -1 on `<li>` count. I feel dirty.

Are you meant to do something like `current_submitted = getUploads({status: qq.status.SUBMITTED}) - getUploads({status: qq.status.CANCELLED})` instead?

Feels like this is the wrong place for these minor things. Sorry if it is, couldn't find a better option.

**Comment by rnicholus** [comment]
>Is it possible to add element.innerHTML = text; to setText()

It's possible, but I don't want to do this. The expectation is that you input text, not HTML, given the name of the method. This would be a breaking change.

Regarding the other unrelated issue (#1649), please comment in that issue.
