### ISSUE TITLE
(Not an issue) Why the "qq" name ?

### ISSUE THREAD

**Issue by kavi87** [FineUploader/fine-uploader#1776]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [ ] Support request
- [x] Existential question

Just wondering ...

**Comment by rnicholus** [comment]
Ha! Nice issue type improvisation. This predates my involvement in Fine Uploader (project was created in 2010, I took over in 2012, more history in [my Medium article on the subject](https://medium.com/@RayNicholus/disrupting-open-source-the-story-of-fine-uploader-80160eb557d9#.td63lte1o)). Andrew Valums, the original creator, was looking for a short and unique namespace for the library. Apparently, `qq` fit the bill.

**Comment by rnicholus** [comment]
going to close this - but am not opposed to continuing the discussion
