### ISSUE TITLE
How to use with Cordova File Plugin

### ISSUE THREAD

**Issue by abroekhuis** [FineUploader/fine-uploader#1778]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [X] Support request

## Uploader type
- [X] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Support Request</summary>

#### Fine Uploader version
5.13.0

#### Question
I'm trying to use FineUploader from a Cordova based application. To get to the File I use the Cordova File Plugin. This provides a (partial) HTML5 File API.
I can get a File object, but as soon as I try to add it to the filelist, and try to start the upload, I get a console message '[Fine Uploader 5.13.0] Received 0 files.'. There are no exceptions or any other messages.
Am I doing something obvious wrong and how can I upload those files?

#### Related code
Output of the file object I try to upload:
File:
  end: 852
  lastModified: 1488211321000
  lastModifiedDate: 1488211321000
  localURL: "cdvfile://localhost/persistent/201702271701_file.csv"
  name: "201702271701_file.csv"
  size: 852
  start: 0
  type: "text/comma-separated-values"
</details>

**Comment by rnicholus** [comment]
>as soon as I try to add it to the filelist

How are you doing this? Please provide all related code.

**Comment by abroekhuis** [comment]
Sure thing,

I use a basic uploader, with no special headers or anything. If I try to upload a arbitrary blob the upload works fine. So the uploader itself is configured correctly.

var uploader = new qq.FineUploaderBasic({...});

I get the file using the File plugin api:
window.requestFileSystem(LocalFileSystem.PERSISTENT, 0,
  function (fileSystem) {
    fileSystem.root.getFile(filename, {create: false, exclusive: false},
    function (fileEntry) {
      // The fileEntry is not a File, so get the file from it
      fileEntry.file(function(file) {
        uploader.addFiles(file);
        uploader.uploadStoredFiles();
      });
    }
  }
);

**Comment by rnicholus** [comment]
can you please fix the formatting in your code? it's very hard to read

**Comment by abroekhuis** [comment]
Done, see my previous comment.

**Comment by rnicholus** [comment]
It's very possible that the file has not completed processing before you call `uploadStoredFiles`. There are a number of possible async tasks that Fine Uploader performs on each file before it is ready to be uploaded. This is why you should generally rely on callbacks. In your case, the file is ready to be uploaded when `onSubmitted` is called for that file, or when the file's status is updated to `qq.status.SUBMITTED`.

**Comment by abroekhuis** [comment]
I tried calling the uploadStoredFiles in the onSubmitted, but this didn't help.
I also now noticed that the onSubmit is never called when adding a file like this, so likewise the onSubmitted is never called as well.
Any other ideas?

**Comment by rnicholus** [comment]
Something is invalid with your "file" then. You'll need to set some breakpoints or logging statements in the code (specifically in the `addFiles` method of `uploader.basic.api.js` to figure out why your file is not able to be handled by Fine Uploader.

**Comment by abroekhuis** [comment]
The problem is from the call to check if the supplied argument is a File.
`return window.File && Object.prototype.toString.call(maybeFile) === "[object File]";`

The result of the toString call is [object Object]. I'll need to see if the Cordova Plugin can fix this.

In the meantime, is there some easy workaround for this?

**Comment by rnicholus** [comment]
Going to close this as I'm not sure what else I can do to help. You'll need to be sure you are passing one of the above types. If you can identify a bug in the library, please let me know so we can discuss. Alternatively, if you can identify a specific improvement that would help your case, let's also discuss that.

**Comment by rnicholus** [comment]
Can you show some code that details your workaround?

**Comment by abroekhuis** [comment]
Well, I totally skipped the File plugin for now. The mobile application is a data collection app, and instead of saving the data to a file, and then upload that file, I now store the data in memory, and create a blob out of it.

`var recordedData = []`
`recordedData.push(..)`
`var blob = new Blob(recordedData)`

Eventually, if the file is actually needed, I might just write the file, and when the upload is needed, read the file to memory again. So I can still use a Blob.

**Comment by rnicholus** [comment]
Are these large files? If so, is running out of memory a concern?

**Comment by abroekhuis** [comment]
With the data as text, we have files with a size of about 10-15 MB. We'll have to see how this works for now. In binary this is smaller of course..
