### ISSUE TITLE
How can delete file with local id?

### ISSUE THREAD

**Issue by hamdibayhan** [FineUploader/fine-uploader#1779]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [x] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Support Request</summary>

#### Fine Uploader version
 5.12.0

#### Question

I want to delete file but not with uuid, with local file id. To do that I am using the setDeleteFileEndpoint method but all file endpoint set with the endpoint of last file. Therefore when I delete a file, always last file is deleting. I don't know where am i making mistakes. Could this be a bug for setDeleteFileEndpoint method? My code like the below. Thanks for support.

#### Related code

```coffeescript
  $('#fine-uploader-gallery').fineUploader
        template: 'qq-template-gallery'
        request:
          inputName: $('#fine-uploader-gallery').data('input-name')
          endpoint: $('#fine-uploader-gallery').data('post-link')
        deleteFile:
          enabled: true,
          forceConfirm: true
        callbacks:
          onComplete: (id, name, response, xhr) ->
            @setDeleteFileEndpoint response.remove_url
            return
```

</details>

**Comment by rnicholus** [comment]
When you call `setDeleteFileEndpoint`, you are changing the delete endpoint for _all_ files. It probably makes more sense to use a single endpoint with parameters that vary per file. For that, use the [`setDeleteFileParams` method](https://docs.fineuploader.com/branch/master/api/methods.html#setDeleteFileParams).

**Comment by hamdibayhan** [comment]
@rnicholus Thanks for help.
