### ISSUE TITLE
Adding new fields like name, surname and store these details for each user/submission.

### ISSUE THREAD

**Issue by unittesting0** [FineUploader/fine-uploader#1784]
## Type of issue
- [ ] Feature request

## Uploader type
- [ ] Traditional [Not Specified Yet]

How can I make a form where the user can submit name, surname, phone number and multiple photos and all of these storing somewhere for each user or submission.

I'm having trouble where to start or how to make this work.

Thank you.

**Comment by rnicholus** [comment]
Sorry, this question is far too broad. Please re-open when you are able to show some code with a specific question.
