### ISSUE TITLE
Question: Can Fine Uploader be used twice on a one page application.

### ISSUE THREAD

**Issue by emilyrodriguez** [FineUploader/fine-uploader#1787]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [x] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<summary>Support Request</summary>

#### Fine Uploader version
 5.14.1

#### Question
As above, it's not really a bug just a question. I'm building a page web application that allows users to upload properties and edit them. The upload and edit are in two different divs that hide or show depending on button clicks. I want Fine Uploader to be available when users upload a property and again if they choose to edit the information. 

I've gotten it to show up on the create property div with no problem, but the UI doesn't show on the edit property div. I've tried including the gallery.html file twice but when that didn't work I thought I'd create a duplicate file and see if that worked. It didn't. Basically, the issue is that the template will not render twice.

#### Related code
This is how I include the gallery file in my HTML.
<img width="1280" alt="screen shot 2017-03-03 at 12 34 10 pm" src="https://cloud.githubusercontent.com/assets/18723209/23563805/e21a4b26-000d-11e7-9962-48ae46b6a1f1.png">
<img width="1280" alt="screen shot 2017-03-03 at 12 34 58 pm" src="https://cloud.githubusercontent.com/assets/18723209/23563808/e3775a40-000d-11e7-92dc-ad4753e67e3e.png">

 $(function(){
	$("#imageUpload").load("/fine-uploader/templates/gallery.html"); 
 });
 $(function(){
	$("#manageImage").load("/fine-uploader/templates/editGallery.html"); 
});

And this is what the debugger in my Chrome console says.
util.js:236[Fine Uploader 5.11.5] Parsing template
util.js:236[Fine Uploader 5.11.5] Template parsing complete
2util.js:236[Fine Uploader 5.11.5] Attempting to update thumbnail based on server response.
util.js:236[Fine Uploader 5.11.5] Rendering template in DOM.
util.js:236[Fine Uploader 5.11.5] Template rendering complete
util.js:236[Fine Uploader 5.11.5] Parsing template

util.js:236[Fine Uploader 5.11.5] Template parsing complete
2util.js:236[Fine Uploader 5.11.5] Attempting to update thumbnail based on server response.
util.js:236[Fine Uploader 5.11.5] Rendering template in DOM.
util.js:236[Fine Uploader 5.11.5] Template rendering complete
</details>

**Comment by rnicholus** [comment]
It sounds like you have two templates, and you need template A for one scenario, and template B for a different workflow. Is this correct?

**Comment by emilyrodriguez** [comment]
Yes, rnicholus that's correct. It's the same gallery template used both times, I just tried using two different files to see if that would get the UI to show up.

**Comment by rnicholus** [comment]
Ok, just to further clarify - you really only want to load one template, but you need two separate instances of Fine Uploader on the same page? Or do you need a single instance? I'm not following the workflow.

**Comment by emilyrodriguez** [comment]
I only want to load one template in two seperate instances of the Fine Uploader.

**Comment by rnicholus** [comment]
I see - in that case, as long as you've included the template in your document, there is nothing further required. The template must be present somewhere in the document before the Fine Uploader UI instance is created. By default, it will expect the template to have an `id` of "qq-template".

**Comment by rnicholus** [comment]
Closing this as I haven't heard back in a while and it looks like the question has been answered.
