### ISSUE TITLE
Question: Additional classes

### ISSUE THREAD

**Issue by kiarashi** [FineUploader/fine-uploader#1788]
## Type of issue
- [x] Support request

## Uploader type
- [x] Traditional

<details>
<summary>Support Request</summary>

#### Fine Uploader version
5.11.9

#### Question
I'm trying to add a `class` when new files are added inside the uploader. 
Please note: a plugin I use is using FineUploader, so I'm unable to change the original code that initialize the FineUploader. 

#### Related code
I first tried using 
```js
jQuery(function ($) {
    $(document).ready(function(){       
    $('.qq-upload-button').click(function() {
        var submittedFileCount = FineUploader.getUploads({status: qq.status.SUBMITTED}).length;

        if (submittedFileCount > 0) {
            $( ".qq-gallery" ).addClass( "qq-files-submitted" );
        }
    });         
    })
});
```

But in console I get an error `FineUploader is not defined`

I also tried using 

```js
jQuery(function ($) {
	$(document).ready(function(){
		
			$(".div-container-file-uploader").each(function(){
					
				var length = $('ul.qq-upload-list li').length;		
				console.log(length);
		
				if ( length >= 1 ) {
					$( '.qq-gallery' ).addClass( 'qq-files-submitted' );
				} else {
					$( '.qq-gallery' ).removeClass( 'qq-files-submitted' );
				}
			})
		
	})
});
```

But the `length` doesn't get updated if a new file is added to the uploader. Is there another way to add the extra css class? Or could additional classes be added as part of the FineUploader itself?

**Comment by rnicholus** [comment]
In your first code block, you'll need to locate the instance of Fine Uploader in order to call API methods. You haven't shared your initialization code. If Fine Uploader's jQuery wrapper is bound to an element with an className of "div-container-file-uploader", your code would look something like this:

```js
var submittedFileCount = 
   $('.div-container-file-uploader').fineUploader('getUploads', {status: qq.status.SUBMITTED}).length
```

More information and examples are available on the [jQuery wrapper documentation page](https://docs.fineuploader.com/integrating/jquery.html).

Regarding your second code block - most likely you are executing this only once, before any files have been submitted. Your code does not suggest otherwise.

**Comment by kiarashi** [comment]
Even when I use your code, I still get the `Uncaught TypeError: $(...).fineUploader is not a function` error.

The code of the plugin to initilize the FineUploader is slightly different than the examples given here in the docs and I'm new with jquery too.

The plugin's code (short version):

```
jQuery(document).ready(function ($) {
    'use strict';

    var Woo_File_Uploader;

    Woo_File_Uploader = {
        init : function () {
            this.general();
        },

        general : function () {

            $('.div-container-file-uploader').each(function () {
                var extensions = $(this).data('extensions');
                var item_id = $(this).data('item-id');                

                new qq.FineUploader({                    
                    ...
                    element: document.getElementById($(this).prop('id')),
                    callbacks: {
                        onComplete: function (id, name, response, xhr) {
                            ...
                        },
                        onDeleteComplete: function (id, xhr, iserror) {
                            ...
                        }
                    }
                });
            });

        }
    };
    Woo_File_Uploader.init();
});
```

**Comment by rnicholus** [comment]
You'll need to assign the result of `new qq.FineUploader` to a variable and call the method as indicated in the docs.

**Comment by kiarashi** [comment]
I'm ashamed to ask, but I still can't get it to work.

`[Fine Uploader 5.11.9] Caught exception in 'onSubmitted' callback - $(...).fineUploader is not a function`

My code:

```
jQuery(function ($) {
    $(document).ready(function(){   
		$('.div-container-file-uploader').each(function () {
			
			var uploader = new qq.FineUploader({
				
				element: document.getElementById($(this).prop('id')),		
				callbacks: {
					onSubmitted: function (id, name) {
						
						var submittedFileCount = $('.div-container-file-uploader').fineUploader( 'getUploads', {status: qq.status.SUBMITTED} ).length	
												
						if (submittedFileCount > 0 ) {
							$( ".qq-gallery" ).addClass( "qq-files-submitted" );
						}
						
					}
				}
			});
		
		});
		
	});
});
```

When I add this code inside the plugin js file that initialize FU, it works just fine.

```
onSubmitted: function (id, name) {
$( ".qq-gallery" ).addClass( "qq-files-submitted" );
},


```

When I use the code below in my theme instead, it overrides the plugin's FU options, which is not something I wish to happen for obvious reasons.

```
jQuery(function ($) {
    $(document).ready(function(){   
		$('.div-container-file-uploader').each(function () {
			
			var uploader = new qq.FineUploader({
				
				element: document.getElementById($(this).prop('id')),		
				callbacks: {
					onSubmitted: function (id, name) {
						
						onSubmitted: function (id, name) {
$( ".qq-gallery" ).addClass( "qq-files-submitted" );
},
						
					}
				}
			});
		
		});
		
	});
});
```

**Comment by rnicholus** [comment]
You'll need to assign the result of new qq.FineUploader to a variable and call the method as indicated in the docs.
