### ISSUE TITLE
Callback 'onComplete' does not fire on Chrome 

### ISSUE THREAD

**Issue by RaasAlGul** [FineUploader/fine-uploader#1791]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
When trying to fire a callback in Chrome, doesn't work, but in Mozilla Firefox it works.

<summary>Bug Report</summary>

What do I have to change to fire the callback in  Chrome.

#### Fine Uploader version
{example: 5.11.10}

#### Browsers where the bug is reproducible
{Chrome Versión 56.0.2924.87 (64-bit)}

#### Operating systems where the bug is reproducible
{example: "Windows 7"}

#### Exact steps required to reproduce the issue
For example:
1. Select a file 
2. Click on a button to execute the function uploader.uploadStoredFiles()
3. onComplete callback save data of the file uploaded to a database.

#### All relevant Fine Uploader-related code that you have written
```
uploader = new qq.FineUploader({
  element: document.getElementById("uploader"),
  autoUpload: false,
  request: {
      endpoint: './uploads/endpoint.php'
  },
  deleteFile: {
      enabled: true,
      endpoint: './uploads/endpoint.php'
  },
  retry: {
     enableAuto: true
  },
  validation: {
    allowedExtensions: ['pdf'],
    sizeLimit: 15360000, // 5 MB = 50000 * 1024 bytes, Archivos mas grandes no son permitidos
    itemLimit: 1 
  },
  callbacks: {
    onComplete:function(id, name, result, xhr){
        //uploader.reset();
        archivos = uploader.getUploads();
        //alert(JSON.stringify(archivos));
        $.ajax({
            type: "POST",
            url: "./modelo/mngr_postventa.php",
            data:{act: 'carga_docs', ent: 'general', idvivienda: data[0],archivos,tipodoc: 1},
            dataType: 'json',
            cache: false,
            error: function (xhr, ajaxOptions, thrownError) {
                alert(xhr.responseText);
                console.log(thrownError,xhr,ajaxOptions);
            }
        }).done(function (data) {
            if(data['OK']){
                $('#docs').attr('data-id_doc',data['id_doc']);
                //console.log('cyka',data['qry'],data['id_doc']);
                tk_log_documentos_propietario('docs',$('#docs').attr('data-action'));
            }
        });
      },
  },
  //multiple: false,
  showMessage: function(message) {
    alert(message);
    $('#btnupload').css('overflow','');
  }      
});
```
in another function I store the files:

```
uploader.uploadStoredFiles();
```

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)

```
<script type="text/template" id="qq-template">
        <div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Arrastre archivos aquí">
            <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
            </div>
            <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                <span class="qq-upload-drop-area-text-selector"></span>
            </div>
            <div class="qq-upload-button-selector button" id="btnupload">
                <div>Subir archivos</div>
            </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Procesando archivos...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
            <ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
                <li>
                    <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                    <div class="qq-progress-bar-container-selector qq-progress-bar-container">
                        <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                    </div>
                    <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                    <div class="qq-thumbnail-wrapper">
                        <img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
                    </div>
                    <button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
                    <button type="button" class="qq-upload-retry-selector qq-upload-retry">
                        <span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
                        Volver a intentar
                    </button>

                    <div class="qq-file-info">
                        <div class="qq-file-name">
                            <span class="qq-upload-file-selector qq-upload-file"></span>
                            <span class="qq-edit-filename-icon-selector qq-btn qq-edit-filename-icon" aria-label="Edit filename"></span>
                        </div>
                        <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                        <span class="qq-upload-size-selector qq-upload-size"></span>
                        <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
                            <span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
                        </button>
                        <button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
                            <span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
                        </button>
                        <button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
                            <span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
                        </button>
                    </div>
                </li>
            </ul>

            <dialog class="qq-alert-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Cerrar</button>
                </div>
            </dialog>

            <dialog class="qq-confirm-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">No</button>
                    <button type="button" class="qq-ok-button-selector">Si</button>
                </div>
            </dialog>

            <dialog class="qq-prompt-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <input type="text">
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Cancelar</button>
                    <button type="button" class="qq-ok-button-selector">Ok</button>
                </div>
            </dialog>
        </div>
    </script>

```
#### Detailed explanation of the problem
The fineuploader upload the file but doesn´t fire the callback "onComplete" in Chrome, it work perfectly in Firefox.
</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

<details>
<summary>Support Request</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Question
{ask your support question here & be as detailed and clear as possible}

#### Related code
{post any code related to your question here}
</details>

**Comment by rnicholus** [comment]
Unclear as to what the issue is exactly, or how to reproduce. Are you saying `onComplete` _never_ fires in Chrome for _any_ or the 3 completed files after following the steps in your report? If this is indeed a Chrome-only issue, perhaps there is some issue with an installed browser extension on your end?

**Comment by RaasAlGul** [comment]
I updated the issue, sorry for my bad explanation. Yes, the callback onComplete doesn't fire in Chrome, but in Firefox works fine.

**Comment by rnicholus** [comment]
Still unclear on the steps to reproduce. If I select 1 file and upload it in Chrome, are you saying that `onComplete` is not called when the upload request completes?

**Comment by RaasAlGul** [comment]
Yes that's the problem

**Comment by rnicholus** [comment]
Ok - please set the `debug` option to `true` and include all console logs in your description when reproducing the issue.

**Comment by RaasAlGul** [comment]
[Fine Uploader 5.11.10] Parsing template
util.js:236 [Fine Uploader 5.11.10] Template parsing complete
util.js:236 [Fine Uploader 5.11.10] Rendering template in DOM.
util.js:236 [Fine Uploader 5.11.10] Template rendering complete
util.js:236 [Fine Uploader 5.11.10] Received 1 files.
util.js:236 [Fine Uploader 5.11.10] Attempting to validate image.
util.js:236 [Fine Uploader 5.11.10] Generating new thumbnail for 0
util.js:236 [Fine Uploader 5.11.10] Attempting to draw client-side image preview.
util.js:236 [Fine Uploader 5.11.10] Attempting to determine if prueba.pdf can be rendered in this browser
util.js:236 [Fine Uploader 5.11.10] First pass: check type attribute of blob object.
util.js:236 [Fine Uploader 5.11.10] prueba.pdf is not previewable in this browser per the blob's type attr
util.js:236 [Fine Uploader 5.11.10] Not previewable
util.js:236 [Fine Uploader 5.11.10] Sending simple upload request for 0
util.js:236 [Fine Uploader 5.11.10] Resetting uploader...
util.js:236 [Fine Uploader 5.11.10] Resetting upload handler
util.js:236 [Fine Uploader 5.11.10] Cancelling 0
util.js:236 [Fine Uploader 5.11.10] Rendering template in DOM.
util.js:236 [Fine Uploader 5.11.10] Template rendering complete

**Comment by rnicholus** [comment]
Looks like something on your end is cancelling the upload. That would explain why `onComplete` is never called.

**Comment by RaasAlGul** [comment]
But I get from the endpoint this response `{"success":true,"uuid":"documentos","uploadName":"51950.pdf"}` , thats mean that the file was uploaded right?

**Comment by rnicholus** [comment]
according to the logs, the uploader is reset before the upload completes

**Comment by RaasAlGul** [comment]
Ok, thanks so much for the help.

**Comment by rnicholus** [comment]
sure thing. may i ask why you are calling `reset` at all?

**Comment by RaasAlGul** [comment]
I call it because I had the uploader in jquery ui-dialog modal, and every time the dialog is called I reset the uploader.
