### ISSUE TITLE
thumbnail gallery link to full size image

### ISSUE THREAD

**Issue by mattredman** [FineUploader/fine-uploader#1792]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [x] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

Hi there,
I've had a look through the documentation but cannot seem to see if there is a way to link directly to the image stored on the server. I'm using the traditional server, everything is working like a dream. I just want to be able to allow the users to click on a thumbnail in the uploader progress/dropzone and open up a lightbox style gallery. I can't even reference the URL in the thumbnails because the image is loaded via a data/image tag as opposed to a URL. How do I get the full URL to generate the link?

**Comment by rnicholus** [comment]
I'm changing this to a support request (from a feature request) as this better describes the issue in my opinion.

You don't want to use the thumbnail image for a gallery - these are very small. Instead, you'll want to generate a larger preview, ideally on-demand, and display that in a lightbox gallery. I did just that in [an Angular v1 integration example]. You should be able to pick out the portion of the example that generates that larger thumbnail and displays this in a lightbox for your purposes.

**Comment by mattredman** [comment]
Would it be possible to include a qq-specific tag on the img element? Maybe like so? I've stepped through and I can See it's the MegaPixImage plugin/component that's swapping out the url with the data tag.

Is there SOME way to generate something long these lines? Sadly, I'm not a javascript expert..

`<img class="qq-thumbnail-selector" qq-max-size="120" qq-orig-src="/path/to/image.png" qq-server-scale src="data:image/jpeg;base64....">`

**Comment by rnicholus** [comment]
>Would it be possible to include a qq-specific tag on the img element?

Of course you can update the DOM however you want, but why do you want to do this specifically? What new problem are you trying to solve?

**Comment by mattredman** [comment]
Specifically the client has asked to be able to click on the thumbnail images on the upload screen as displayed in the image so they can see the full size image as soon as it's uploaded.

![gallery](https://cloud.githubusercontent.com/assets/18690906/23885802/8bb55d9a-08c1-11e7-9272-64f5ae0ddf19.png)

**Comment by rnicholus** [comment]
Did you see my original message?

**Comment by mattredman** [comment]
Yes I did. I added a "callBacks" element into my initialization of fineuploader, but it was only called when an image was uploaded. I supply a "session" endpoint and populate images already supplied for this job so couldn't see how to make something like this work for these pre-populated images.

**Comment by rnicholus** [comment]
Please take another look at the example code. Here it is: https://github.com/FineUploader/integration-examples/tree/master/src/angularjs-nodejs. The click handler is added when handling the `onSubmitted` event, which occurs when the file is first selected by the user and all validation checks have completed. 

Alternate approach: 
1. Add a single click handler to the element that wraps the entire uploader
2. If the clicked element is a file `<img>`, use the [`getId` method](https://docs.fineuploader.com/branch/master/api/methods.html#getId) to determine the file ID.
3. Call [`drawThumbnail`](https://docs.fineuploader.com/branch/master/api/methods.html#drawThumbnail) to generate a large preview on a `<canvas>` or `<img>` element, which can then be rendered inside of a lightbox. This is also demonstrated in the demo I linked to previously.

**Comment by mattredman** [comment]
Yep. I think I may have glossed over a few of the key points there. Thanks for your patience.

**Comment by rnicholus** [comment]
No prob. Please also consider wrapping the `<img>` elements in a `<button>` to make them properly accessible as well.

**Comment by rssluca** [comment]
Not sure about OP's solution but this is the way I did it, I wrapped the <img> with a lightbox link in both uploads and session complete callbacks.

`onComplete: function(id, filename, responseJSON) {
                if (responseJSON.success) {
                    $('#fine-uploader-gallery').append(
                    
                    $('.qq-file-id-'+id+' img').wrap('<a href="'+responseJSON.data['originalUrl']+'" data-lightbox="gallery"></a>')
                }
            },
            onSessionRequestComplete: function(responseJSON, success) {
                
                if (success) {
                    $.each(responseJSON, function(index, value) {
                        $('.qq-file-id-'+index+' img').wrap('<a href="'+responseJSON[index]['originalUrl']+'" data-lightbox="gallery"></a>')
                    })
                }
            },`

**Comment by jcrombez** [comment]
I hope i'm not hijacking this issue but, i need to do something similar, i'm trying to add a link to the full size image.
It works well using the `onComplete` callback but for the initial files  i'm using `addInitialFiles` so i can't  use `onSessionRequestComplete` to add my links.

I don't think i can use the alternate approach rnicholus mentioned since there is other buttons in the uploader, but maybe i just misunderstood the said approach.

**Comment by averichev** [comment]
@jcrombez Tell me, please, could you solve the problem?
