### ISSUE TITLE
Setting custom xhr headers in fine-uploader.js (Node.js)

### ISSUE THREAD

**Issue by emilyrodriguez** [FineUploader/fine-uploader#1794]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [x] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Support Request</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Question
{ask your support question here & be as detailed and clear as possible}
Where exactly in fine-uploader.js can I set my own custom xhr.setRequestHeader? I tried setting it in gallery.html, but I get an error 401 because my authentication token isn't being passed (and I'm sure the other headers aren't either) with the post request. I see there's a setRequestHeaders function in fine-uploader.js that I found in the docs but I'm not sure what it wants from me. I'm a pretty junior dev so forgive me if it's common sense. Thanks.

#### Related code
{post any code related to your question here}
</details>

var uploader = new qq.FineUploader({
			element: document.getElementById("fine-uploader-manual-trigger"),
			template: 'qq-template-manual-trigger',
			request: {
				endpoint: 'api/ll/image'
				// customHeaders: {
				**// 	"token": landlordToken,
				// 	"county": countyId,
				// 	"property": propertyId,**
				// },
			},
			autoUpload: false,
			debug: true,
			thumbnails: {
				placeholders: {
					waitingPath: '/fine-uploader/placeholders/waiting-generic.png',
					notAvailablePath: '/fine-uploader/placeholders/not_available-generic.png'
				}
			},
			deleteFile: {
				enabled: true,
				endpoint: 'api/ll/image'
			}, 
			validation: {
				allowedExtensions: ['jpeg', 'jpg', 'png'],
				itemLimit: 5,
				sizeLimit: 2097152 // 2MB
			}
		});

		qq(document.getElementById("trigger-upload")).attach("click", function() {
			uploader.uploadStoredFiles();
		});

setCustomHeaders: function(headers, id) {
                this._customHeadersStore.set(headers, id);
            },
<img width="1280" alt="screen shot 2017-03-15 at 2 10 40 pm" src="https://cloud.githubusercontent.com/assets/18723209/23966397/324e4870-0989-11e7-92f2-231541461f55.png">

**Comment by rnicholus** [comment]
To which request do you want to add headers? The upload request? Or something else...

**Comment by emilyrodriguez** [comment]
To the upload request and most likely to the delete request. I only want users that are logged in and have an auth token to be able to upload/delete photos. I have a countyId and propertyId that I want to add as headers as well so my db knows what photo belongs to what table and property.

**Comment by rnicholus** [comment]
when do you need to set the header? when is the information you need to set the header available? Must the headers vary with each request?

**Comment by emilyrodriguez** [comment]
The headers need to be set when the edit button is pressed, that's when the countyId and propertyId are retrieved/where the Fine Uploader UI is present. The token changes everytime the user logs in but will be the same when the photo uploads are conducted. The headers will vary on each request depending on what property is selected as it dictates the countyId associated with it and queries the db for the info.

**Comment by rnicholus** [comment]
You can set the upload request headers at any time using [`setCustomHeaders`](https://docs.fineuploader.com/branch/master/api/methods.html#setCustomHeaders) on the uploader instance. You should pass an object with header names & values, and optionally an ID if you want to target a specific file. For delete file requests, you can set custom headers the same way using [`setDeleteFileCustomHeaders`](https://docs.fineuploader.com/branch/master/api/methods.html#setDeleteFileCustomHeaders).

You'll need to pick the appropriate callback or event handler to make these calls, depending on your needs.

**Comment by emilyrodriguez** [comment]
You're talking about these functions? Do I write them in a json format or a xhr.setRequestHeader  
setCustomHeaders: function(headers, id) {
                this._customHeadersStore.set(headers, id);
            },
            setDeleteFileCustomHeaders: function(headers, id) {
                this._deleteFileCustomHeadersStore.set(headers, id);
            },

And the callbacks for example would be these?
_onSubmit: function(id, name) {},
_onSubmitCallbackSuccess: function(id, name) {
                this._onSubmit.apply(this, arguments);
                this._uploadData.setStatus(id, qq.status.SUBMITTED);
                this._onSubmitted.apply(this, arguments);
                if (this._options.autoUpload) {
                    this._options.callbacks.onSubmitted.apply(this, arguments);
                    this._uploadFile(id);
                } else {
                    this._storeForLater(id);
                    this._options.callbacks.onSubmitted.apply(this, arguments);
                }
            },
            _onSubmitDelete: function(id, onSuccessCallback, additionalMandatedParams) {
                var uuid = this.getUuid(id), adjustedOnSuccessCallback;
                if (onSuccessCallback) {
                    adjustedOnSuccessCallback = qq.bind(onSuccessCallback, this, id, uuid, additionalMandatedParams);
                }
                if (this._isDeletePossible()) {
                    this._handleCheckedCallback({
                        name: "onSubmitDelete",
                        callback: qq.bind(this._options.callbacks.onSubmitDelete, this, id),
                        onSuccess: adjustedOnSuccessCallback || qq.bind(this._deleteHandler.sendDelete, this, id, uuid, additionalMandatedParams),
                        identifier: id
                    });
                    return true;
                } else {
                    this.log("Delete request ignored for ID " + id + ", delete feature is disabled or request not possible " + "due to CORS on a user agent that does not support pre-flighting.", "warn");
                    return false;
                }
            },

**Comment by rnicholus** [comment]
I'm not sure what you are referring to. 

Once you have a handle on the uploader instance, you can call any API methods listed in the documentation. For example, if you need to set a custom header of "Foo" with a value of "Bar" for _all_ upload requests, your code would look like this:

```js
uploader.setCustomHeaders({ Foo: 'bar' })
```

...and if you only want to set this header for an upload request for a file with an id of 3, your code instead would look like this:

```js
uploader.setCustomHeaders({ Foo: 'bar' }, 3)
```

You can follow the same pattern for `setCustomDeleteFileHeaders`. For more information on callbacks and how to use them, please see the callbacks section of the documentation, and/or the demos on fineuploader.com.

**Comment by emilyrodriguez** [comment]
Thanks. That helped. I appreciate your time.

**Comment by rnicholus** [comment]
No problem. Let me know if I can be of further assistance
