### ISSUE TITLE
Canceling an upload does not prevent an upload retry from happening

### ISSUE THREAD

**Issue by trevorharwell** [FineUploader/fine-uploader#1797]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.14.1

#### Browsers where the bug is reproducible
All

#### Operating systems where the bug is reproducible
All

#### Exact steps required to reproduce the issue
For example:
1. Add an onError callback callback
2. Cancel file upload in error callback
3. See that the file is still retried

#### Detailed explanation of the problem
When you cancel an upload inside of the onError callback the upload is still retried.
If you pause the upload then the upload is not retried (which is what I would expect).
I believe the line in question is here: https://github.com/FineUploader/fine-uploader/blob/5.14.1/client/js/uploader.basic.api.js#L1721
I would think that adding a `&& uploadData.status !== CANCELED` should do the trick.
</details>

**Comment by rnicholus** [comment]
Can you verify that this actually fixes your issue. I'm not sure it will.

**Comment by rnicholus** [comment]
Closing due to lack of feedback.
