### ISSUE TITLE
HTTP Status 500 on some file uploads, including MP4: XHR returned response code 500

### ISSUE THREAD

**Issue by OpenESignForms** [FineUploader/fine-uploader#1798]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [X] Support request

## Uploader type
- [X] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Support Request</summary>

#### Fine Uploader version
5.14.1

#### Browsers where the bug is reproducible
Safari, Chrome and Firefox (all up-to-date) on Mac OS X.
Server is Linux (CentOS 6) running Tomcat 8.0.35 with Java 1.8.0_91.

#### Question
We have just started using FineUploader (as we finally migrate away from Java Applets that are no longer supported for multi-file uploads with DND) and it's mostly working great.  That is, nearly all files we throw at it, it uploads them all just fine.

However, we do get the below error shown when uploading larger MP4s (41MB), but not for smaller MP4s (31.5MB).  We can (usually) succeed with a larger ZIP file (51.5MB), so it doesn't seem to be just a file size issue:

`Error on file number 0 - Test.mp4.  Reason: XHR returned response code 500`

On a normal, successful upload, our Tomcat 8 activity log shows:
xx.xx.xxx.xxx - - [21/Mar/2017:15:59:49 -0700] "POST /ssd/sendMessage/attachment.jsp?m=4305704838241 HTTP/1.1" **200** 17
xx.xx.xxx.xxx - - [21/Mar/2017:15:59:49 -0700] "GET /ssd/sendMessage/attachment.jsp?m=4305704838241&fineuploaderdone=1 HTTP/1.1" 200 17446

xx.xx.xxx.xxx - - [21/Mar/2017:16:01:24 -0700] "POST /ssd/sendMessage/attachment.jsp?m=4305704838241 HTTP/1.1" **500** 5155
xx.xx.xxx.xxx - - [21/Mar/2017:16:01:41 -0700] "GET /ssd/sendMessage/attachment.jsp?m=4305704838241&fineuploaderdone=1 HTTP/1.1" 200 14658

Because we are integrating with an old webapp that doesn't really use much javascript and our system generally expects pages to reload after each request, we use the main endpoint to submit the file, and when it's completed, we use another URL with the fineuploaderdone=1 param added in the onAllComplete callback to set the location.href so we get a final GET request that causes the page to reload and show the results of the uploaded file.

Because it's an older webapp, it also used a multipart/form-data uploader from O'Reilly in a package com.oreilly.servlet.MultipartRequest.

For grins, we updated that code to use org.apache.commons.fileupload.servlet.ServletFileUpload and it did not resolve anything.  In fact, it oddly also had some trouble with the status 500 being returned on the 51.5MB ZIP file as well.  

When in Java debug, we can see it just seems to crap out (no exception thrown) in the file upload code, as if Tomcat gets the error 500 and then just halts our servlet so we cannot see any underlying cause for the 500.  We see no errors in Tomcat logs that indicate memory errors, exceptions or the like.

#### Related code
My HTML form tag:
`<form method="post" action="/ssd/sendMessage/attachment.jsp;jsessionid=435E79DE28006DA1E4986D82315B7CF3?m=4305704838243" enctype="multipart/form-data" id="qq-form">
`
```
<!-- Fine Uploader DOM Element
====================================================================== -->
<div id="fine-uploader"></div>

<!-- Your code to create an instance of Fine Uploader and bind to the DOM/template
====================================================================== -->
<script>
    var manualUploader = new qq.FineUploader({
        element: document.getElementById('fine-uploader'),
        template: 'qq-template',
        thumbnails: {
            placeholders: {
                waitingPath: '../scripts/fineuploader/placeholders/waiting-generic.png',
                notAvailablePath: '../scripts/fineuploader/placeholders/not_available-generic.png'
            }
        },
        callbacks: {
        	onAllComplete: function(successArray,failedArray) { location.href = '/ssd/sendMessage/attachment.jsp;jsessionid=435E79DE28006DA1E4986D82315B7CF3?m=4305704838243&fineuploaderdone=1'; },
            onError: function(id,name,errorReason,xhrOrHxr) {
            	alert(qq.format("Error on file number {} - {}.  Reason: {}", id, name, errorReason));
            }
        },
        validation: {
        	sizeLimit: 100000000
        },
        autoUpload: false,
        debug: true
    });
</script>

```
#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
    <script type="text/template" id="qq-template">
        <div class="qq-uploader-selector qq-uploader" qq-drop-area-text="Drop files here">
            <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
            </div>
            <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                <span class="qq-upload-drop-area-text-selector"></span>
            </div>
            <div class="qq-upload-button-selector qq-upload-button">
                <div>Select file(s)...</div>
            </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped files...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
            <ul class="qq-upload-list-selector qq-upload-list" aria-live="polite" aria-relevant="additions removals">
                <li>
                    <div class="qq-progress-bar-container-selector">
                        <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                    </div>
                    <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                    <img class="qq-thumbnail-selector" qq-max-size="100" qq-server-scale>
                    <span class="qq-upload-file-selector qq-upload-file"></span>
                    <span class="qq-upload-size-selector qq-upload-size"></span>
                    <button type="button" class="qq-btn qq-upload-cancel-selector qq-upload-cancel">Cancel</button>
                    <button type="button" class="qq-btn qq-upload-retry-selector qq-upload-retry">Retry</button>
                    <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">Delete</button>
                    <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                </li>
            </ul>

            <dialog class="qq-alert-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Close</button>
                </div>
            </dialog>

            <dialog class="qq-confirm-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">No</button>
                    <button type="button" class="qq-ok-button-selector">Yes</button>
                </div>
            </dialog>

            <dialog class="qq-prompt-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <input type="text">
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Cancel</button>
                    <button type="button" class="qq-ok-button-selector">Ok</button>
                </div>
            </dialog>
        </div>
    </script>
</details>

**Comment by rnicholus** [comment]
Sorry, but there's not much help I can offer. If you were unable to uncover the reason for the 500 error on your server, there is certainly no way for me to make that determination.

**Comment by OpenESignForms** [comment]
That's too bad.  I mean, with a simple <input type=file> control, the file uploads fine (and is also the same multipart/form-data).  This would seem to indicate that our web server has no real issue accepting the file, just when it's transmitted via fineuploader.

Is there anything I can add to the javascript setup to help track down why it might suffer this when using xhr?  According to the progress meter, 100% of the file is transferred before it craps out.

**Comment by OpenESignForms** [comment]
While not positive, this small change seems to resolve that MP4 issue, ensuring the charset=UTF-8 is added to the form's enctype:

enctype="multipart/form-data;charset=UTF-8"

Hope this may help others who get this odd result.

**Comment by rnicholus** [comment]
>This would seem to indicate that our web server has no real issue accepting the file, just when it's transmitted via fineuploader.

Fine Uploader sends standard multipart encoded upload requests by default, just as if the files were sent by a traditional form submit. The issue is most definitely with your server. Take a look at some of the [Java server-side examples](https://github.com/FineUploader/server-examples/tree/master/java) for reference.

>Is there anything I can add to the javascript setup to help track down why it might suffer this when using xhr?

The issue is server-side, not client-side. So you'll need to either inspect the response payload in the browser and/or set breakpoints or log messages on your server to determine where the problem lies.

**Comment by OpenESignForms** [comment]
Thanks.  I'll keep investigating.

**Comment by OpenESignForms** [comment]
In case anybody sees this exchange:

You were right.  It was an out of memory error (damned tiny test server!) that somehow didn't appear in the tomcat logs.  I finally discovered this using the 'debug' option and looking at the javascript console where our "status code 500" error page included this helpful bit of information.  This also explains how it seemed to work, then failed, etc. and we couldn't figure out what the difference was.
