### ISSUE TITLE
Existing html form in firefox

### ISSUE THREAD

**Issue by braguzz** [FineUploader/fine-uploader#1799]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>In firefox I cant get the fileuploader works with existing form - chrome end IE works</summary>

#### Fine Uploader version
5.14.1

#### Browsers where the bug is reproducible
Firefox 52

#### Operating systems where the bug is reproducible
Windows 10

#### Exact steps required to reproduce the issue
Open the page in firefox.. ;)

#### All relevant Fine Uploader-related code that you have written
I just copy the example code and integrate it in mt cakephp project.

html form:

```js
<form action="/develop22/carkinds/add_upload" id="qq-form" class="well" method="post" accept-charset="utf-8">
<div style="display:none;">
<input type="hidden" name="_method" value="POST"/>
<input type="hidden" name="data[_Token][key]" value="cd30c897f2267fcc2880ef94842c1833a2d0c14b" id="Token1608912257"/></div> 

<input type="hidden" name="data[Carkind][name]" id="CarkindName"/> 
<div class="form-group"><label for="CarkindMetadata1" class=" control-label">Metadata1</label><input name="data[Carkind][metadata1]" class="form-control " maxlength="100" type="text" id="CarkindMetadata1"/></div> 
<div class="form-group"><label for="CarkindHash" class=" control-label">Hash</label><input name="data[Carkind][hash]" class="form-control " maxlength="100" type="text" id="CarkindHash"/></div> 
  <input name="submit" class="btn btn-lg btn-success " type="submit" value="ok"/>    
     <div style="display:none;"><input type="hidden" name="data[_Token][fields]" value="e792426a824a55474d08ede4394784413b55402e%3ACarkind.name" id="TokenFields1482448362"/><input type="hidden" name="data[_Token][unlocked]" value="submit" id="TokenUnlocked1480156504"/></div></form>
<!-- The element where Fine Uploader will exist. -->
     <div id="fine-uploader">
    </div>
```

script part:

  ```html
<script>
        var uploader = new qq.FineUploader({
            debug: true,
            element: document.getElementById('fine-uploader'),
            request: {  
                endpoint: 'https://10.116.76.245/develop22/carkinds/add'
            },
            chunking: {
            enabled: true,
            concurrent: {
                enabled: false
            },
            success: {
                endpoint: 'https://10.116.76.245/develop22/carkinds/done'
            }
        },
        validation: {
                        itemLimit: 1,
                        multiple: false,
                    },
            deleteFile: {
                enabled: false,
                endpoint: 'https://10.116.76.245/develop22/carkinds/add'
            },
            retry: {
               enableAuto: true
            }
        });
    </script>
```

#### Detailed explanation of the problem
In firefox I got these errors:
TypeError: "submit" is read-only[Ulteriori informazioni]  fine-uploader.js:5231:13
	maybeUploadOnSubmit https://10.116.76.245/develop22/js/fine-uploader.js:5231:13
	determineFormEl https://10.116.76.245/develop22/js/fine-uploader.js:5243:40
	qq.FormSupport https://10.116.76.245/develop22/js/fine-uploader.js:5248:18
	qq.basePrivateApi._initFormSupportAndParams https://10.116.76.245/develop22/js/fine-uploader.js:1843:55
	qq.FineUploaderBasic https://10.116.76.245/develop22/js/fine-uploader.js:2536:13
	qq.FineUploader https://10.116.76.245/develop22/js/fine-uploader.js:6421:9
	<anonimo> https://10.116.76.245/develop22/carkinds/add_upload:122:24

and nothing is inserted into the
<div id="fine-uploader">
    </div>

everything works fine in IE and Chrome

PS.I use https protocol

</details>

**Comment by rnicholus** [comment]
There is no form in your markup

**Comment by rnicholus** [comment]
This is an interesting issue. The key here is to understand that form fields are addressable by their `name` attribute as properties of the `HTMLFormElement` object. So, since you have an `<input type='submit' name='submit'>`, that element can be accessed as `document.getElementById('qq-form').submit`.

Now, Fine Uploader attempts to extend the `submit` function that is present on all `HTMLFormElement` objects in order to inject additional logic into the submit process if/when the `submit()` function is called directly. Since `submit` actually points to the submit button you have declared in your form (since it has `name='form'`), Fine Uploader is actually overwriting that `HTMLInputElement`. Apparently Firefox explicitly prevents this, which is not entirely surprising.

Quick fix: remove the `name='submit'` from your submit button, or change the `name` to something else.
