### ISSUE TITLE
Upon uploading a large file Page freezes

### ISSUE THREAD

**Issue by AnyaLavanya** [FineUploader/fine-uploader#1800]
HI,

   Upon Uploading a file with large size about 1GB using FineUploader, Page freezes for a certain period of time. None of the actions/links on the page are allowed to click. Could any one please help on how to resolve this.

**Comment by AnyaLavanya** [comment]
HI,
Have gone through this link https://github.com/FineUploader/fine-uploader/pull/1796
However the above is fix is once the debugger reaches onUpload, where as here in my case, once i ipload the file with large size neither ready method nor the call back methods like (upload etc) trigger. Page blocks for a certain time say 2 min then all the events trigger.

**Comment by rnicholus** [comment]
If you require help, you'll need to follow the instructions presented to you in the new issue description.
