### ISSUE TITLE
getUploads contains item with id:0 and success but getItemByFileId(0) errors and item is not displayed

### ISSUE THREAD

**Issue by andy-olson** [FineUploader/fine-uploader#1801]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [ ] Traditional
- [ ] S3
- [x] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.14.1

#### Browsers where the bug is reproducible
chrome 56.0.2924.87

#### Operating systems where the bug is reproducible
Windows 10

#### Exact steps required to reproduce the issue
1. Set options to include session.endpoint using list display
2. return json from server
3. in onSessionRequestComplete, call getUploads()
4. attempt to call getItemByFileId with the id of the first item in the returned array
5. error thrown..
6. side note, calling getName with the same id works

#### All relevant Fine Uploader-related code that you have written
var uploader = new qq.azure.FineUploader({
		element: document.getElementById('my-uploader'),
		retry: {
			enableAuto: true
		},
		chunking: {
			enabled: true
		},
		signature: {
			customHeaders: function (id) {
				var ctx = uploader;
				var fileitem = ctx.getItemByFileId(id);
				var docID = qq(fileitem).getByClass("view-btn")[0].getAttribute("data-customerDocumentId");
				return { 'x-filename': ctx.getName(id), 'x-uuid': ctx.getUuid(id), 'x-customerdocid':docID };
			},
			endpoint: '/api/Customer/42877202/Document/OtherCertification/getAssetSas'
		},
		uploadSuccess: {
			customHeaders: function (id) {
				var ctx = uploader;
				return { 'x-filename': ctx.getName(id), 'x-uuid': ctx.getUuid(id) };
			},
			endpoint: '/api/Customer/42877202/Document/OtherCertification/uploadComplete'
		},
		deleteFile: {
			enabled: true
		},
		session:{
			endpoint: '/api/Customer/42877202/Document/OtherCertification/getAssets'
		},
		callbacks: {
			onComplete: function (id, name, response) {
				var fileItem = this.getItemByFileId(id);

				if (response.success) {
					var viewBtn = qq(fileItem).getByClass("view-btn")[0];

					viewBtn.setAttribute("href", response.URI);
					viewBtn.setAttribute("data-customerDocumentId", response.CustomerDocumentID);
					qq(viewBtn).removeClass("hide");
				}
			},
			onDeleteComplete(id, xhr, isError) {
				if(isError)
				{
					// Ther server actually already did the delete, so we just remove the file from display
					uploader.setStatus(id, qq.status.DELETED);
				}
			},
			onStatusChange(id, old, newStatus){
				debugger;
			},
			onSessionRequestComplete(response, bBuccess, raw) {
				var ctx = this;
				$.each(uploader.getUploads(), function (i, item) {
					$.each(response, function (loadedFileIndex, loadedFile) {
						if (item.uuid == loadedFile.uuid) {
							var fileItem = ctx.getItemByFileId(item.id);
							var	viewBtn = qq(fileItem).getByClass("view-btn")[0];

							viewBtn.setAttribute("href", loadedFile.customerFile.URI);
							viewBtn.setAttribute("data-customerDocumentId", loadedFile.customerFile.CustomerDocumentID);
							qq(viewBtn).removeClass("hide");
						}
					})
				});
				debugger;
			}
		},
		multiple: true
	});

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
<div class="qq-uploader-selector qq-uploader">
        <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
            <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
        </div>
        
        <div class="qq-upload-button-selector qq-upload-button">
            <div>Upload a file</div>
        </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped files...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
        <ul class="qq-upload-list-selector qq-upload-list" aria-live="polite" aria-relevant="additions removals">
            <li>
                <div class="qq-progress-bar-container-selector">
                    <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                </div>
                <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                <span class="qq-upload-file-selector qq-upload-file"></span>
                <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
                <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                <span class="qq-upload-size-selector qq-upload-size"></span>
                <button type="button" class="qq-btn qq-upload-cancel-selector qq-upload-cancel">Cancel</button>
                <button type="button" class="qq-btn qq-upload-retry-selector qq-upload-retry">Retry</button>
				<a class="view-btn hide btn" target="_blank">View</a>
                <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">Delete</button>
                <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
            </li>
        </ul>

        <dialog class="qq-alert-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">Close</button>
            </div>
        </dialog>

        <dialog class="qq-confirm-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">No</button>
                <button type="button" class="qq-ok-button-selector">Yes</button>
            </div>
        </dialog>

        <dialog class="qq-prompt-dialog-selector">
            <div class="qq-dialog-message-selector"></div>
            <input type="text">
            <div class="qq-dialog-buttons">
                <button type="button" class="qq-cancel-button-selector">Cancel</button>
                <button type="button" class="qq-ok-button-selector">Ok</button>
            </div>
        </dialog>
    </div>

</details>

**Comment by rnicholus** [comment]
Please add a `console.log` for each record in the `getUploads()` call that you are iterating over, and include the output in your question.

**Comment by andy-olson** [comment]
Ok...  that was a little odd..  I just added the console.log and loaded the page once, and the first one came back with a status of deleted.  But that seems odd given that it was just loaded from the session endpoint.  Then I closed everything and reloaded it, and now I can't get it to repro.. Does uploader use any local storage?  Is it possible it was hanging on to some state for the first item in the list?

**Comment by rnicholus** [comment]
`localStorage` is only used for the resume feature. These records wouldn't be returned by `getUploads()` unless corresponding files were added to the uploader as well. Going to close this, but happy to re-open if you can reproduce w/ logs.
