### ISSUE TITLE
Incorrect target canvas dimensions with Pica

### ISSUE THREAD

**Issue by digitalmagnets** [FineUploader/fine-uploader#1805]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.14.1

#### Browsers where the bug is reproducible
Chrome  56.0.2924.87

#### Operating systems where the bug is reproducible
OS X 10.12.3

#### Exact steps required to reproduce the issue
1. Enable scaling using Pica
2. Select a portrait format image with orientation info embedded, which has a larger height than maxSize
3. Upload image

#### All relevant Fine Uploader-related code that you have written
```
var manualUploader = new qq.FineUploader({
    element: document.getElementById('uploader'),
    template: 'qq-template',
    request: {
        endpoint: '/endpoint'
    },
    folder: true,
    maxConnections: 2,
    dragAndDrop: {
        reportDirectoryPaths: true,
    },
    validation: {
        allowedExtensions: ['jpg', 'jpeg'],
        acceptFiles: 'image/jpg, image/jpeg',
        stopOnFirstInvalidFile: false
    },
    retry: {
        enableAuto: true
    },
    autoUpload: false,
    debug: true,
    allowEmpty: false,
    scaling: {
        includeExif: true,
        sendOriginal: false,
        sizes: [{
            name: "",
            maxSize: 800
        }],
        customResizer: !qq.ios() && function(resizeInfo) {
            return new Promise(function(resolve, reject) {
                pica.resizeCanvas(resizeInfo.sourceCanvas, resizeInfo.targetCanvas, {}, resolve);
            })
        }
    },
    showMessage: function(message) {
        console.log(message);
    }
});
qq(document.getElementById("trigger-upload")).attach("click", function() {
    manualUploader.uploadStoredFiles();
});
```

#### Detailed explanation of the problem
It appears that when using Pica with the suggested customResizer function, that the embedded orientation data is causing the target canvas to be incorrectly sized. The height and width are not correctly swapped. The resulting scaled images therefore appear squashed.

If I upload a portrait photo without orientation data but still larger than maxSize, the problem does not occur. It is only if orientation data is included that it happens.

Also, if I remove Pica resizing, the problem goes away.

Sincere apologies if this is not a bug. Perhaps I am not using Pica correctly? Do I need to include some orientation logic in the resize promise to handle orientation?
</details>

**Comment by rnicholus** [comment]
Please properly format your code. I'll also need some more concrete examples, such as a specific image used to reproduce. If you can link to a live site where I can reproduce, that will speed this up the most

**Comment by digitalmagnets** [comment]
Apologies for the code formatting, I am taking my first tentative steps here.

This is an example of a straight from camera image containing orientation data:

http://web.canon.jp/imaging/eosd/samples/eos70d/downloads/07.jpg

If it is uploaded and resized with Pica, the scaled dimensions are incorrect.

**Comment by digitalmagnets** [comment]
I have modified renderImageToCanvasWithCustomResizer(resizeInfo) with a hack:

```
        function renderImageToCanvasWithCustomResizer(resizeInfo) {
            var blob = resizeInfo.blob, image = resizeInfo.image, imageHeight = resizeInfo.imageHeight, imageWidth = resizeInfo.imageWidth, orientation = resizeInfo.orientation, promise = new qq.Promise(), resize = resizeInfo.resize, sourceCanvas = document.createElement("canvas"), sourceCanvasContext = sourceCanvas.getContext("2d"), targetCanvas = resizeInfo.canvas, targetHeight = resizeInfo.targetHeight, targetWidth = resizeInfo.targetWidth;
            transformCoordinate(sourceCanvas, imageWidth, imageHeight, orientation);
            targetCanvas.height = targetHeight;
            targetCanvas.width = targetWidth;
```            

Added:
```
            if(resizeInfo.orientation == 8) {
              targetCanvas.height = targetWidth;
              targetCanvas.width = targetHeight;              
            }
```            
```
           sourceCanvasContext.drawImage(image, 0, 0);
            resize({
                blob: blob,
                height: targetHeight,
                image: image,
                sourceCanvas: sourceCanvas,
                targetCanvas: targetCanvas,
                width: targetWidth
            }).then(function success() {
                targetCanvas.qqImageRendered && targetCanvas.qqImageRendered();
                promise.success();
            }, promise.failure);
            return promise;
        }
```

I know this is a cludge but it does fix the problem for me it seems.

**Comment by rnicholus** [comment]
That will definitely not work reliably

**Comment by lordleeslr** [comment]
I am seeing the same behavior, resizeInfo.sourceCanvas has the correct dimensions given the exif data but the resized resizeInfo.targetCanvas has the dimensions wrong, They should be flipped around.

**Comment by rnicholus** [comment]
what version of pica

**Comment by lordleeslr** [comment]
latest version 3.0.2. I have a fix for it in renderImageToCanvasWithCustomResizer add
`transformCoordinate(targetCanvas targetWidth, targetHeight, orientation);`
and remove 
` targetCanvas.height = targetHeight;`
`targetCanvas.width = targetWidth;`

**Comment by rnicholus** [comment]
Cold be an issue caused by breaking changes in Pica 3.x. That will probably need to be sorted out in Pica or integration code. I don't plan on making changes to Fine Uploader to accommodate changes in one specific 3rd-party lib.

**Comment by fundup** [comment]
Hy,

I had same problem when photos were comming from a camera. I think the problem is comming from fineuploader and not Pica. Indeed for portrait when sourceHeight > sourceWidht I had targetHeight < targetWidth. So I did a quick fix before resizing with Pica.

`                   var sourceWidth = resizeInfo.sourceCanvas.width;
                    var sourceHeight = resizeInfo.sourceCanvas.height;
                    //before resize target sizes
                    var targetWidth = resizeInfo.targetCanvas.width;
                    var targetHeight = resizeInfo.targetCanvas.height;
                    //switch if error
                    if(sourceHeight > sourceWidth &&  targetWidth > targetHeight) {
                        resizeInfo.targetCanvas.height = targetWidth;
                        resizeInfo.targetCanvas.width = targetHeight;
                    }
`
Hope it helps
