### ISSUE TITLE
onComplete and onError Events don't triggered on firefox

### ISSUE THREAD

**Issue by miguelangelss4** [FineUploader/fine-uploader#1806]
## Type of issue
- [X] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [X] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.10.1

#### Browsers where the bug is reproducible
Firefox 52.0.2

#### Operating systems where the bug is reproducible
Windows 8.1, and I guess any other

#### Exact steps required to reproduce the issue
For example:
1. Only upload any file or files using firefox

#### All relevant Fine Uploader-related code that you have written
		fineUploader.fineUploader({
			debug: true,
			request:{
				endpoint: '/wp-content/plugins/innovation-factory/includes/php/endpoint.php'
			},
			callbacks:{
				onComplete: function(id, name, responseJSON, xhr){
					console.log({
						_event: event,
						_id: id,
						_name: name,
						_responseJSON: responseJSON
					});
					
					if(responseJSON.success){
						adjuntos.push(responseJSON.uuid + "/" + responseJSON.uploadName);
					}
				},
				onUpload: function(id, name){
					console.log({_id: id, _name: name});
				},
				onError: function(id, name, errorReason, xhr){
					var error = {
						id_: id,
						name_: name,
						errorReason_: errorReason,
						xhr_: xhr,
					};
					console.error(error);
				}
			}
		});

#### Detailed explanation of the problem
FineUploader uploads correctly the file, but Firefox doesn't trigger de related event (onComple or onError). The server is returning the correct response, but firefox ignoers the events:
![imagen](https://cloud.githubusercontent.com/assets/15887424/24700443/7c1f1eb0-19f7-11e7-8dfa-1f0a7b0fff4c.png)
In chrome all works fine.
</details>

**Comment by rnicholus** [comment]
there must be some specific issue with your environment as i cannot reproduce and yours is the only report
