### ISSUE TITLE
addInitialFiles is calling onAllComplete multiple times

### ISSUE THREAD

**Issue by piernik** [FineUploader/fine-uploader#1807]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

As in topic. If I call `addInitialFiles` with array of ex. 3 files `onAllComplete` is called 3 times - should be one time.
Also there is no `onUpload` call.

#### Fine Uploader version
5.13.0

**Comment by rnicholus** [comment]
onUpload will not be called as nothing is being uploaded.

**Comment by piernik** [comment]
So there could be new event - `onContainerCreate` to indicate when new item is placed into DOM.
I have some custom  elements in item's template which need to be handled after inserting to DOM.

**Comment by rnicholus** [comment]
Listen for onSubmitted. For initial files, once a status changed of `qq.status.UPLOAD_SUCCESSFUL` Is broadcast, that initial file is now in the DOM.
