### ISSUE TITLE
Unable to select multiple files to upload on Firefox for Android

### ISSUE THREAD

**Issue by FasettoAndrew** [FineUploader/fine-uploader#1813]
## Type of issue
- [x] Bug report

## Uploader type
- [x] Traditional

<details>
<summary>Unable to select multiple files to upload on Firefox for Android</summary>

#### Fine Uploader version
5.12.0

#### Browsers where the bug is reproducible
Firefox on Android

#### Operating systems where the bug is reproducible
Firefox for Android version 52.0
Android version 6.0.1

#### Exact steps required to reproduce the issue
1.  Click an input html element to open Android upload intent
2.  Click documents to view devices full file contents
3.  Long press an item to attempt to select it

#### All relevant Fine Uploader-related code that you have written
\<input multiple="" type="file"\>

#### Detailed explanation of the problem
When using Firefox on Android devices, you cannot select multiple items to upload, even when HTML input element has the multiple attribute set.

If you attempt the same thing on the Android stock browser, you will see that you can perform a long press to be able to select multiple items when uploading from the "documents" Android intent
</details>

**Comment by rnicholus** [comment]
Doesn't sound like an issue with Fine Uploader. Perhaps something to bring up on bugzilla? If you can demonstrate that this only exists within Fine Uploader, I'll be happy to re-open.
