### ISSUE TITLE
Disabling Form inputs

### ISSUE THREAD

**Issue by braguzz** [FineUploader/fine-uploader#1815]
## Type of issue
- [x] Support request

## Uploader type
- [x] Traditional

<details>
<summary>Disabling Form inputs </summary>

#### Detailed explanation of the problem
I've followed docs to integrate my form with fineuploader and everithigs is working, but while the uploading progress, user can change inputs of the form.
How to disable inputs?
I've tried the onUpload callback without success.

Thanks in advance
</details>

**Comment by rnicholus** [comment]
Use JavaScript to set the `disabled` attribute on your inputs. Not a Fine Uploader issue.
