### ISSUE TITLE
Handle upload response myself

### ISSUE THREAD

**Issue by dawncold** [FineUploader/fine-uploader#1817]
## Type of issue
- [ ] Bug report
- [x] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Feature Request</summary>

#### Feature request details 
On traditional mode, I can choose create a server or use a storeage service (not S3 and Azure) as backend, some storeage service support upload files to their endpoint directly, but I can't expect they return a FineUploader compabible success or fail response. I have knowledge whether the response is success or not, and how to get error message from response.

Is it possible handle response by myself and return a FineUploader compatible response? This will extend traditional mode function.

Thanks!
</details>

**Comment by rnicholus** [comment]
Short answer: no. But in [v6.0.0](http://lab2023.com/rails-5-de-fineuploader-kullanimi.html), which may be released in the next 10 or 20 years, the requirement to return a JSON response with `"success": true` will be removed. See #1325 for details.

**Comment by dawncold** [comment]
I have to modify `qq.parseJson` to adding some fields which Fineuploader needs
