### ISSUE TITLE
Files tries to upload agian after 1 minute timeout.

### ISSUE THREAD

**Issue by jdor300** [FineUploader/fine-uploader#1825]
## Type of issue
- [x] Bug report

## Uploader type
- [X] Traditional

<details>
<summary>Bug Report</summary>
Files tries to upload again after 1 minute timeout by itself,
And in the end they get 504 gateway time-out.

I must be honest that I desperate we came to fine-uploader from dropzonejs, 
and the problem was also there.

#### Fine Uploader version
5.14.2

#### Browsers where the bug is reproducible
Chrome, Firefox

#### Operating systems where the bug is reproducible
Windows 10

#### Exact steps required to reproduce the issue
For example:
1. Select 1 file and upload it.
2. Let the file finish to upload to the server
3. Then hold the file in the server for long time (5 minutes, do some manipulation like sleep or something).
4. Let the fine-uploader show the spinning wheel, which says "waiting for response for the server".
5. The fine-uploader will restart the file upload after 1 minute.

#### All relevant Fine Uploader-related code that you have written
Can't bring the code here.

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
Can't bring the code here.

#### Detailed explanation of the problem
{describe the bug here}
</details>

Hello guys we have a big problem which don't let us to move on in our project,
We have a website with a dropzone for files (using fine-uploader of course), 
clients upload all kind of file sizes (1mb-5g), 
when the upload is finished we doing a manipulation on the file which taking some time (depending on the file size, can take 5 minutes if the file size is 2g-3g), the users are aware of it.
Meantime the file is shown with the spinning wheel (waiting for response), and after 1 minute approximately the file is uploaded again (progress bar is rested ! and upload again ! and again ! until it get 504 gateway time-out).

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>
I saw this problem a lot in the internet, people who upload large files and manipulate them.
<details>
<summary>Support Request</summary>

#### Fine Uploader version
5.14.2

#### Question
{ask your support question here & be as detailed and clear as possible}

#### Related code
{post any code related to your question here}
</details>

**Comment by rnicholus** [comment]
It's not clear what specific question you are asking here. Can you clarify? The 504 is an issue beyond the control of Fine Uploader.

**Comment by jdor300** [comment]
I will handle the 504, I just told you all the story.
The problem is why after 1 minute the fine uploader is waiting for a response, he start to upload the file again.

**Comment by rnicholus** [comment]
the timeout has nothing to do with the retry - but the 504, which fails the upload, is likely the cause. but this is expected if you've enabled autoRetry. You haven't listed any of your code, as requested in the issue template, so I have to assume you've enabled `autoRetry`.

**Comment by jdor300** [comment]
Sorry that i didn't mentioned it but the retry of the upload is happening after 1 minute,
the 504 problem is happening after like 3-4 minutes (meantime the fine-uploader already did 1-2 retries).
I also must mention that back in the server the file is fine, 
the web get 504 after 3-4 minutes but we in the back end finish the manipulation after another 1 minute.
