### ISSUE TITLE
 Error when attempting to parse xhr response text 

### ISSUE THREAD

**Issue by emre190693** [FineUploader/fine-uploader#1831]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

[Fine Uploader 5.14.2] Error when attempting to parse xhr response text (JSON.parse: unexpected character at line 1 column 1 of the JSON data)  jquery.fine-uploader.js:422:25

my code

    $('#fine-uploader-manual-trigger').fineUploader({
            template: 'qq-template-manual-trigger',
            request: {
                endpoint: '/placeholders/'
            },
            thumbnails: {
                placeholders: {
                    waitingPath: '/placeholders/waiting-generic.png',
                    notAvailablePath: '/placeholders/not_available-generic.png'
                }
            },
            autoUpload: true
        });

**Comment by rnicholus** [comment]
I've seen this message a thousand times and it always means that your server is not responding with valid JSON.

**Comment by zenonp** [comment]
Could you please hint at what to look for and where, to fix this?

**Comment by rnicholus** [comment]
I would start by looking at the response
