### ISSUE TITLE
fine-uploader error "Unexpected end of JSON input" when chunked upload does not succeed

### ISSUE THREAD

**Issue by akaegi** [FineUploader/fine-uploader#1832]
## Type of issue
- [ x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x ] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.14.2 (FineUploaderBasic only)

#### Browsers where the bug is reproducible
Chrome

#### Operating systems where the bug is reproducible
Windows 10

#### Exact steps required to reproduce the issue
1. Upload big file with chunking enabled 
2. Let the upload fail on the server side ("success": false)
3. Fine-uploader error "Unexpected end of JSON input" appears on console

#### Detailed explanation of the problem
Note: server responds with correct json for all requests (with either "success": true or false)

For a chunked upload fine-uploader reports the following error when the server responds with "success": false for one of the chunks:
> [Fine Uploader 5.14.2] Error when attempting to parse xhr response text (Unexpected end of JSON input)

I suspect the problem comes from the canceled requests (presumably cancelled by fine-uploader) of the other chunks.

This is an annoying issue for us, since the error handler won't report the error code anymore (always 0) after the above error. 

Problem does not occur for a small file with only one chunk and failed upload.

**Comment by rnicholus** [comment]
0 = aborted xhr request

**Comment by rnicholus** [comment]
Probably a bug, but really a very benign one. The upload has already failed, so i'm not seeing how additional error console logs is much of an issue. Not likely I'll be able to look into this myself, but if this can be resolved cleanly with a PR, that may help.
