### ISSUE TITLE
Folder uploads to azure

### ISSUE THREAD

**Issue by tlouth19** [FineUploader/fine-uploader#1834]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [ ] Traditional
- [ ] S3
- [x] Azure

<details>
<summary>Uploading a folder to Azure</summary>

#### Fine Uploader version
Version 5.14.2 (Azure Core)

#### Browsers where the bug is reproducible
All

#### Detailed explanation of the problem
When I try to upload a folder using the core uploader to azure it returns an error. Uploading a file or a zipped folder with the same uploader has no issues. Zipping files for upload isn't an option for my current environment. 

Is it possible to upload a folder to an azure blob?

</details>

**Comment by rnicholus** [comment]
Fine Uploader doesn't upload folders - it uploads files. So, if you drop a folder, all files in that folder and all other folders in that folder will be uploaded in dedicated requests.
