### ISSUE TITLE
obj2url method prepending '&' to qquuid after calling qq.setparams a second time

### ISSUE THREAD

**Issue by FasettoAndrew** [FineUploader/fine-uploader#1837]
## Type of issue
- [X] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [X] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.12.0

#### Browsers where the bug is reproducible
All (tested on Firefox, IE11 and Chrome)

#### Operating systems where the bug is reproducible
All (tested on Windows 10, Android 7, Android 6, iOS 9, iOS 10)

#### Exact steps required to reproduce the issue
1. Select a file to upload.
2. Set a parameter for the file using the set params method.
3. In the onSubmit callback, create a new parameter, call set params again.
4. In the request header that is sent to the server, the key for 'qquuid' now contains an '&' prefix to qquuid and shows '&qquuid'

#### Detailed explanation of the problem
When calling the setParams method twice, once from inital upload method and once from onSubmit callback, the parameter for 'qquuid' gets changed to '&qquuid' in the request header.

After investigating the issue as much as we can, we beileve the issue lies in the obj2url method that is called from setParams, but simply do not have the time to investigate further.

</details>

**Comment by rnicholus** [comment]
please show your code

**Comment by FasettoAndrew** [comment]
The fine uploader instanse is declared as it is in this issue:
https://github.com/FineUploader/fine-uploader/issues/1812

With the var being set as:
`var uploader = new qq.FineUploaderBasic({...`

In our upload method, we set files to the auto uploader using:
```
// Add them to the uploader 
uploader.addFiles(files, parameters);

 // Start uploading files
uploader.uploadStoredFiles();
```

Then, in the onSubmit callback from the uploader, we call set params for the file with a new set of parameters
```
// Pass it as a parameter for this file
uploader.setParams(updatedParams, id);
```

In neither of the parameter sets do we modify or set the qquuid. But if we comment out the uploader.setParams method above in the onSubmit callback, the issue goes away.

I can't show you any further code or server code, but the following shows the inspected request header keys on the server.

![image](https://cloud.githubusercontent.com/assets/13521143/26238725/38d159d2-3c72-11e7-9391-116df7deca4d.png)

**Comment by rnicholus** [comment]
What does `updatedParam` look like _exactly_?

**Comment by FasettoAndrew** [comment]
Sorry i've not had chance to reply to this, been to busy.

After further use and testing, I believe the issue is related to using DateTime's as parameters because doing the following also causes the same issue:

```
var params = new { uploadPath = "Uploads", lastModified = System.DateTime.Now };

// Add them to the uploader 
uploader.addFiles(files, params);
```

However, called the ToString method on the DateTime appears to fix the issue.
