### ISSUE TITLE
S3 Sign - Generate policy on the backend

### ISSUE THREAD

**Issue by staskij** [FineUploader/fine-uploader#1842]
<summary>Support Request</summary>

#### Fine Uploader version
5.14.2

#### Question
I'm trying to generate the signed policy on the backend.
The default fineuploader flow is to generate a policy client-side, send it to the backend, have it verified, signed and send policy, signature and file to s3.
What I'm trying to accomplish is to have fineuploader only send fileName to the signing backend, let it generate a key and the policy, along with defining the bucket, acl, region, ... and then fineuploader uses the /sign response url, policy and signature to upload the file to s3.

Schematically (example uses signature v4):
- Client -> signing backend:
  - Request:
    - `{ filename: "something.txt"}`
  - Response:
```
{ 
    url: "https://<bucket-name>.s3.<region>.amazonaws.com",
    policy: <Base64 encoded policy>,
    x-amz-algorithm: "AWS4-HMAC-SHA256",
    x-amz-credential: <your-access-key-id>/<date>/<aws-region>/<aws-service>/aws4_request,
    x-amz-date: <timestamp>,
    x-amz-signature: <signature>,
}
```
- Client > <s3 endpoint (from the previous response)>
  - Request:
```
{ 
    policy: <Base64 encoded policy>,
    x-amz-algorithm: "AWS4-HMAC-SHA256",
    x-amz-credential: <your-access-key-id>/<date>/<aws-region>/<aws-service>/aws4_request,
    x-amz-date: <timestamp>,
    x-amz-signature: <signature>,
}
```

#### Why
Now we generate the policy client-side, we verify it's correct on the backend and we sign it.
Why not generating the policy direcly on the backend? We'd have control over the key (#1120), we can change the destination bucket on the backend, acl, region, expire date,...
I can't find any reason to generate the policy client-side, the only information which needs to be supplied is the filename.
With default settings this is what FineUploader sends to the signing backend:
```
{
    "conditions": [
        {
            "acl": "private"
        },
        {
            "bucket": "http"
        },
        {
            "Content-Type": "image/png"
        },
        {
            "success_action_status": "200"
        },
        {
            "x-amz-algorithm": "AWS4-HMAC-SHA256"
        },
        {
            "key": "e5db5a27-9adb-4110-9e73-e9ac19b36661.png"
        },
        {
            "x-amz-credential": "null/20170522/us-east-1/s3/aws4_request"
        },
        {
            "x-amz-date": "20170522T140418Z"
        },
        {
            "x-amz-meta-qqfilename": "example.png"
        }
    ],
    "expiration": "2017-05-22T14:09:18.865Z"
}
```
Excluding filename and Content-Type we can derive all other fields on the backend, while now we do the same work twice, as if I want to ensure I'm using the right bucket, I have to set `request.endpoint`, then set a constant in the backend with the same bucket to ensure i'm signing for the correct one: seems to me to be twice the work.

Other reason being that there's tons of backend aws libraries to generate those fields ([AWS ruby, java and .NET SDK](https://docs.aws.amazon.com/AmazonS3/latest/dev/PresignedUrlUploadObject.html),[boto3](https://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Client.generate_presigned_post)), so the generation is much more simple than the verification.

Am I missing a way to proxy the policy from the backend to s3 without fineuploader changing it?
If the signing backend returns a 
```
{
    policy: <Base64 encoded policy>,
    signature: <signature>
}
```
I'm getting the signature proxied, but the backend policy is ignored and overridden with the client-side generated one.

Please, correct me If I'm saying anything wrong.

**Comment by rnicholus** [comment]
do you not plan on using chunked requests or uploading large files?

**Comment by rnicholus** [comment]
>Why not generating the policy direcly on the backend? We'd have control over the key (#1120), we can change the destination bucket on the backend, acl, region, expire date,...

It is not that easy. If you change/set the bucket or region, etc on the backend, how does Fine Uploader know about this? I guess it would have to parse the policy file? And, as mentioned before, this only covers non-chunked uploads anyway.

**Comment by staskij** [comment]
I understand.

Moving the generation of the policy to the backend would require passing (or parsing from the policy) key, bucket, etc. to fineuploader, meaning that fineuploader has to implement the logic to change the request parameters according to the backend response: this means that the backend doesn't have to verify anything, but fineupload would have to keep its current behaviour and also allowing its request fields to be overridden. Not so many advantages for the required effort.

Thanks for the answer.

**Comment by Rux77** [comment]
I faced the same issue, Iam using s3 mode and Iam generating the **signature** and **policy** (endpoint) for V4 on backend using this package [Directo](https://github.com/kfirba/Directo) and this package uses its own policy inputs when singing the policy:

```php
$policy = [
            'expiration' => $this->expirationDate(),
            'conditions' => [
                ['bucket' => $this->bucket],
                ['acl' => $this->options->acl],
                ['starts-with', '$key', $this->options->valid_prefix],
                [$contentTypePrefix, '$Content-Type', $this->options->content_type],
                ['content-length-range', 0, $this->mbToBytes($this->options->max_file_size)],
                ['success_action_redirect' => $this->options->success_action_redirect],
                ['success_action_status' => $this->options->success_action_status],
                ['x-amz-credential' => $this->credentials->AMZCredentials()],
                ['x-amz-algorithm' => 'AWS4-HMAC-SHA256'],
                ['x-amz-date' => gmdate('Ymd\THis\Z', $this->time)]
            ]
        ];
```

 Which is different from Fineuploader request payload for the file Iam trying to upload: 

    {"expiration":"2018-03-16T09:10:45.082Z",
    "conditions":
    \[{"acl":"private"},
    {"bucket":"bucket-name"},
    {"Content-Type":"image/jpeg"},
    {"success\_action\_status":"200"},
    {"x-amz-algorithm":"AWS4-HMAC-SHA256"},
    {"key":"37f86eae-46e9-4047-91c1-c8ee2cbf90b6.jpg"},
    {"x-amz-credential":"GWRQRFFXBA3C3S7GOVQQ/20180316/eu-central-1/s3/aws4\_request"},
    {"x-amz-date":"20180316T090545Z"},
    {"x-amz-meta-qqfilename":"JPG-GG\_400x400.jpg"},
    \["content-length-range","0","23424"\]\]}
    
so when I try to upload the file I will face many errors: 
policy doesn't match ... etc ..
