### ISSUE TITLE
Thumbnail on file select but not on drop

### ISSUE THREAD

**Issue by popart-dev** [FineUploader/fine-uploader#1843]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [ X ] Support request

## Uploader type
- [ ] Traditional
- [ X ] S3
- [ ] Azure

<details>
<summary>Support request</summary>

#### Fine Uploader version
5.14.2-rc1

#### Browsers where the problem is reproducible
Chrome, Firefox, Safari

#### Operating systems where the problem is reproducible
OS X (haven't tried others)

#### Exact steps required to reproduce the issue
For example:
1. Click FU component, select file from file selection dialog
2. Thumbnail displays as expected
3. Drag-drop file onto FU component
4. Generic placeholder icon is displayed instead of thumbnail

#### All relevant Fine Uploader-related code that you have written
Here's my React component:

    import FineUploaderS3 from 'fine-uploader-wrappers/s3'
    import Gallery from 'react-fine-uploader'

    export default class FileUploader extends React.Component {

        constructor(props){
            super(props)
            
            this.state = {
                showModal: props.showModal || false,
                fileName: props.fileName,
                s3Key: props.s3Key,
                title: props.title,
                description: props.description,
                fileUrl: props.fileUrl,
                success: props.success || true,
            }

            let uploaderInstance = null

            this.uploader = () =>{
                uploaderInstance = new FineUploaderS3({
                    options: {
                        chunking: {
                            enabled: true 
                        },
                        resume: {
                            enabled: true 
                        },
                        request: {
                            endpoint: 'http://ourbucketurl',
                            accessKey: ourAccessKeyId,
                        },
                        signature: {
                            endpoint: '/api/s3handler', 
                        },
                        uploadSuccess: {
                            endpoint: '/api/s3uploadsuccess', 
                        },
                        callbacks: {
                            onComplete: this.uploadCompleteHandler
                        },
                    }
                })

                return uploaderInstance
            }

            this.uploadCompleteHandler = (id, name, responseJSON) => {
                //still need to figure out how to get file size.
                this.setState({showModal: responseJSON.success,
                    s3Key: responseJSON.key,
                    fileName: responseJSON.name,
                    fileUrl: `https://ourbucketurl/${responseJSON.key}`})
            }

        render() {

            return <div>
                <Gallery uploader={this.uploader()} />
            </div>
        }
    }

#### Detailed explanation of the problem
When using the UI component in a React context, the component will show a thumbnail when the file is selected, but not when it is dragged and dropped. When the file is dropped on the component, I only get a generic placeholder icon.

</details>

**Comment by rnicholus** [comment]
any reason you asked a question on SO _and_ filed an issue here?

**Comment by popart-dev** [comment]
Because I wasn't aware the 2 shared anything in common. Apologies if I
violated protocol. I'll happily take one or the other down if one is
preferred.

Damion Moyer
Senior Software Engineer
Pop Art, Inc.
www.popart.com
(503) 548-9015 desk
(503) 242-4292 main
(503) 422-1402 mobile

**Comment by rnicholus** [comment]
this belongs in the react-fine-uploader repo
