### ISSUE TITLE
removing files from outside drop area

### ISSUE THREAD

**Issue by cmnstmntmn** [FineUploader/fine-uploader#1844]
## Type of issue
- [√ ] Support request

## Uploader type
- [√ ] Traditional

## Details
hey, i'm having a cart section that holds a cart summary and next to it the drop area. 
i can't manage remove associated files (inside drop area) when the product is removed.

## Question
How could i remove a file from outside drop area ?

<img width="243" alt="screen shot 2017-05-24 at 11 45 21" src="https://cloud.githubusercontent.com/assets/2312755/26394717/8286ff84-4076-11e7-9f8c-bf70e54cc92b.png">

## Code

this is how i init the fineuploader object

```js
var dropZoneObject = function(el) {
    uploader = new qq.FineUploader({
        element: el,
        debug: true
        ....
```

**Comment by rnicholus** [comment]
You can get a handle on a file element in the UI via [getItemByFileId](https://docs.fineuploader.com/branch/master/api/methods.html#getItemByFileId), which you can remove with [`Node.removeChild`](https://developer.mozilla.org/en-US/docs/Web/API/Node/removeChild).
