### ISSUE TITLE
Recommendation for multi-part downloads?

### ISSUE THREAD

**Issue by keiranmraine** [FineUploader/fine-uploader#1845]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [x] Support request

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

<details>
<summary>Support Request</summary>

#### Fine Uploader version
NA

#### Question
Do you have any recommendations for a library that handles multipart _downloads in-browser?
(if there's a email list for this type of question please feel free to point me to it).
</details>

**Comment by rnicholus** [comment]
I  do not have any recommendations
