### ISSUE TITLE
How do I upload files and hidden input values directly to s3 with detailed control?

### ISSUE THREAD

**Issue by brandoncc** [FineUploader/fine-uploader#1847]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [x] Support request

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

<details>
<summary>Support Request</summary>

#### Fine Uploader version
5.14.3

#### Question
I have read everything I can find in the documentation, including all of the setup documentation for s3 and the "form support" page.

Here is my scenario:

I have a form which allows users to attach up to five images. Those images are uploaded to Heroku via a standard form submission, which often times out. Because of that, I need to use direct uploads to s3. The images are managed on the Rails server using the carrierwave gem.

Here is the plan I have come up with:

I would like to upload each file directly to s3, and in a callback, modify my HTML. I need to use the s3 url as the value of a new hidden input which will be submitted in the form to my server and used by carrierwave as a remote image url. Some of my forms also have images which are base64 encoded as values of hidden inputs.

If someone changes the file chosen with a `file` input, I need to be able to upload that file again, processing the callback with the url, etc.

---

I have been reading the documentation for hours (as well as other days) and this is as far as I have gotten:

    var uploader = new qq.s3.FineUploaderBasic({
      autoUpload: false,
      request: {
        endpoint: 'https://' + s3BucketName + '.s3.amazonaws.com',
        accessKey: accessKey
      },
      signature: {
        endpoint: '/s3/signature'
      },
      uploadSuccess: {
        endpoint: '/s3/success'
      },
      iframeSupport: {
        localBlankPagePath: '/success.html'
      },
      retry: {
        enableAuto: true // defaults to false
      },
      validation: {
        allowedExtensions: ["png", "jpg"]
      }
    });

---

It is worth mentioning that I need to be able to control the entire process, and I don't want any special UI generated by fine uploader. The users click through a wizard and when they click "next" and arrive at the last step, I am going to fire off the s3 uploads. If they go back and change a file, I need to be able to upload only the changed file. I show them a progress bar already which I will update with the status of the s3 uploads.

Thank you in advance!

</details>

**Comment by rnicholus** [comment]
>It is worth mentioning that I need to be able to control the entire process, and I don't want any special UI generated by fine uploader.

Where is your current UI?
