### ISSUE TITLE
setParams after OnInit using typescript

### ISSUE THREAD

**Issue by sreerag-av** [FineUploader/fine-uploader#1848]
## Type of issue
- [ ] Support request

## Uploader type
- [ ] Traditional
<details>
I am trying to pass some extra parameters using setParams, using a variable, but the UI options are set 
on init, and is undefined. but on changing the variable is there a way to pass the values again

@SinghSukhdeep can you please help me with this.

<details>
<summary>Support Request</summary>

#### Fine Uploader version
5.14.2

#### Question
I need to send some extra parameters or an ngform along with the uploaded file. i am trying to set the parameters, but the parameters are undefined.I want this to work on page load.

I can call set-param when auto upload is enabled,it works but i need this to work after init too.

also, is there a way to check if a file has been uploaded.or if there are files in the queue,so that i can trigger actions based on that.

ps: I am newbie to angular 2 and typescript

#### Related `code`
````
ngOnInit() {
    this.uiOptionsInit();
    this._init();
}

### manual trigger event
uploadFiles() {
    this.uploader.uploadStoredFiles();
}

_init() {
    this.uploader = new qq.FineUploader(this.uiOptions);
}
uiOptionsInit(){
this.uiOptions = {
    debug: false,
    autoUpload: false,
    element: document.getElementById('fine-uploader-gallery'),
    template: 'qq-template-gallery',
    request: {
        endpoint: 'http://server/chunked'
    },
     chunking: {
            enabled: true,
            concurrent: {
                enabled: true
            },
            success: {
                endpoint: 'http://server/chunked?done=true'
            },
            partSize: 4000000
    },
      resume: {
        enabled: true
    },
     callbacks: {
            onUpload: function (id, fileName) {
              const defaultParams = {};
              defaultParams['categories'] = this.inputCategories;
              this.uploader.setParams(defaultParams);
        }}
};
}
}
````
</details>

**Comment by SinghSukhdeep** [comment]
I'm not sure I understand your question exactly.
What exactly isn't working and where is it in your code?
The initialization `this.uploader = new qq.FineUploader(this.uiOptions);` is working or not?

**Comment by sreerag-av** [comment]
`this.uploader = new qq.FineUploader(this.uiOptions)`
this works, i had to call it like this, in order for it to call access the uploader in the manual trigger event.
```
## manual trigger event
uploadFiles() {
    this.uploader.uploadStoredFiles();
}

```
the problem lies in the onUpload callback
i want to send along some parameters along with the request (endpoint) that the uploader makes to the server. but 

`defaultParams['categories'] = this.inputCategories;`

this.inputCategories is a user input inputed during upload, not during init
so this.inputCategories is undefined and so at the server end it is passed as undefined
how can i get this value,

also is there any way to find out whether there is a file in the upload queue

**Comment by SinghSukhdeep** [comment]
Hmm, I see what you're doing.
This seems like an issue with the value of `this` at different points in your code. You are using `this.inputCategories` inside an callback function where `this` might belong to something else other than what you expect (the component).
Try `console.log(this)` at that point to see what you have in `this`.
If such is the case then you'll have to declare another variable like `let __this = this;` before entering the callback function and use the new `__this` in there.

Little TS tip, Don't declare the new variable as `_this` with single underscore, because that is reserved by TS compiler and you shouldn't declare a variable with that name anywhere in your code.

**Comment by SinghSukhdeep** [comment]
[This](https://docs.fineuploader.com/branch/master/api/methods.html#getInProgress) method should help to determine items that are currently uploading or queued.

**Comment by sreerag-av** [comment]
```
ngOnInit() {
this.uiOptions = {
    debug: true,
    autoUpload: false,
    element: document.getElementById('fine-uploader-gallery'),
    template: 'qq-template-gallery',
    request: {
        endpoint: 'http://localhost:3000/docapi/v1/documents/chunked'
    },
     chunking: {
            enabled: true,
            concurrent: {
                enabled: true
            },
            success: {
                endpoint: 'http://localhost:3000/docapi/v1/documents/chunked?done=true'
            },
            partSize: 4000000
    },
      resume: {
        enabled: true
    },
     callbacks: {
            onUpload: function (id, fileName) {
              const defaultParams = {};
              defaultParams['categories'] = __this.inputCategories;  #it will say cannot find name __this
              this.uploader.setParams(defaultParams);
        }}
    };
 this.uploader = new qq.FineUploader(this.uiOptions);
}

uploadFiles() {
    let __this = this;  ## its define here on the trigger event.
    console.log("value of this is "+__this.inputCategories);
    this.uploader.uploadStoredFiles();
}
```
i tried your solution, but it says cannot find name __this.

Is it that i can only access variables using 'this' inside ngInit , but then ngInit is called once and i can't pass any variables to it, after initialisation. is there a work around for this.

can i pass again the uiOptions to qq.Fineuploader without reinitialising it.

**Comment by sreerag-av** [comment]
Ok wait i got it working

```
ngOnInit() {

this.uiOptions = {
    debug: true,
    autoUpload: false,
    element: document.getElementById('fine-uploader-gallery'),
    template: 'qq-template-gallery',
    request: {
        endpoint: 'http://localhost:3000/docapi/v1/documents/chunked'
    },
     chunking: {
            enabled: true,
            concurrent: {
                enabled: true
            },
            success: {
                endpoint: 'http://localhost:3000/docapi/v1/documents/chunked?done=true'
            },
            partSize: 4000000
    },
      resume: {
        enabled: true
    },
     callbacks: {
            onUpload: function (id, fileName) {}
        }
    };

this.uploader = new qq.FineUploader(this.uiOptions);
}

uploadFiles() {
    this.defaultParams['categories'] = this.inputCategories;
    this.uploader.setParams(this.defaultParams);
    this.uploader.uploadStoredFiles();
}
```

**Comment by SinghSukhdeep** [comment]
sorry I forgot about it.

you need to declare `let __this = this;` inside ngOnInit just like you've done in your `uploadFiles()` function if you want to use it.

Anyway, where is your variable `inputCategories` declared?
If it is declared inside your class then it should be accessible by doing `this.inputCategories` anywhere in your component.

It's might just be the case that `this` refers to something else other than your component inside the callback function.

try `console.log(this)`  at different stages in your functions and see what comes up.

**Comment by SinghSukhdeep** [comment]
Closing as no further information is provided.
