### ISSUE TITLE
Upload to alternative S3 implementations e.g. minio.io

### ISSUE THREAD

**Issue by seyhbold** [FineUploader/fine-uploader#1854]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [x] Support request

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

<details>
<summary>Support Request</summary>

#### Fine Uploader version
{example: 5.14.3}

#### Question
Is there any documentation how to use alternate S3 endpoints like minio.io?

</details>

**Comment by rnicholus** [comment]
No, there is not
