### ISSUE TITLE
No concurrent uploads in onProgress

### ISSUE THREAD

**Issue by sophanox** [FineUploader/fine-uploader#1856]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [*] Support request

## Uploader type
- [*] Traditional
- [ ] S3
- [ ] Azure

#### Fine Uploader version: example: 5.14.2

Hi there,

I'm using onProgress to update custom progress bars. I have multiple uploads enabled via the options.
```
                uploader = new qq.FineUploader({
                element: document.getElementById('fine-uploader-gallery'),
                autoUpload: false,
                template: 'qq-template-gallery',
                maxConnections: 4,
                multiple: true,
                debug: true,
                request: {
                    endpoint: '/files/UploadFileChunk',
                },
                thumbnails: {
                    placeholders: {
                        waitingPath: '/Images/Uploads/placeholders/waiting-generic.png',
                        notAvailablePath: '/Images/Uploads/placeholders/not_available-generic.png',
                    },
                },
                chunking: {
                    mandatory: true,
                    partSize: 2000000, // 2MB
                    enabled: true,
                    concurrent: {
                        enabled: true,
                    },
                    success: {
                        endpoint: '/files/chunksDone',
                    },
                },
                callbacks: {

                    onProgress: (id, name, uploadedBytes, totalBytes) => {
                        console.log(id + ':' + name);
                        uploads.updateProgress(id, uploadedBytes, totalBytes);
                    },
```
One file only ever uploads at a time however - when I thought 4 would given the maxConnections? The console.log in onProgress indicates one file is uploading at a time - i.e. the ID:Name will remain constant until that download is paused - then the next file will start downloading and be logged there.

Any suggestions as to what I'm doing wrong?

Thanks!

**Comment by rnicholus** [comment]
This is explained on the concurrent chunking feature page. Reading this will clear up your confusion on the matter. https://docs.fineuploader.com/branch/master/features/concurrent-chunking.html
