### ISSUE TITLE
List of files to upload without thumbnail

### ISSUE THREAD

**Issue by m3ldro** [FineUploader/fine-uploader#1857]
## Type of issue
- [ ] Bug report
- [X] Feature request
- [ ] Support request

## Uploader type
- [X] Traditional
- [ ] S3
- [ ] Azure

Is it possible to have just a list of files to upload whitout any thumbnails?

**Comment by rnicholus** [comment]
yes, it is. Simple remove the thumbnail elements from the template, or do not use Fine Uploader UI at all - simple use the core APIs and build your own UI.
