### ISSUE TITLE
 Error displaying file size

### ISSUE THREAD

**Issue by KevinGorin** [FineUploader/fine-uploader#1860]
## Type of issue
- [x ] Bug report

## Uploader type
- [x ] Traditional

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.14.13

#### Browsers where the bug is reproducible
All

#### Operating systems where the bug is reproducible
Windows10

#### Detailed explanation of the problem
The size of the file displayed when upload is incorrect. 
For example when I upload a file of 634Mo (664 932 609 octets) this shows me 664MB next to the file.
</details>

**Comment by rnicholus** [comment]
Not an issue with the library. Fine Uploader reports file sizes directly from data supplied by the browser/OS
