### ISSUE TITLE
Placeholder not showing after delete candidates

### ISSUE THREAD

**Issue by seltix5** [FineUploader/fine-uploader#1861]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>After adding some files as candidates to upload, if you delete them the placeholder is not showing (as it shuld since the field is now empty)
http://imgur.com/a/i5Psa</summary>

#### Fine Uploader version
5.14.3

#### Browsers where the bug is reproducible
Chrome, Firefox, IE

#### Operating systems where the bug is reproducible
Windows 7

#### Exact steps required to reproduce the issue
1. Select 1 or more files
2. Delete them from the candidates list
</details>

**Comment by SinghSukhdeep** [comment]
There is already an issue for this #1649

**Comment by SinghSukhdeep** [comment]
Closing as the issue already exists
