### ISSUE TITLE
few concerns

### ISSUE THREAD

**Issue by priyankoctal** [FineUploader/fine-uploader#1863]
I am looking forward to use your below product.

https://fineuploader.com/demos.html#amazon-demo

But before that can you let me know what is maximum file size limit to upload VIDEO ?

Also let us know if you transcode video and any format and what are allowed extension of videos which we can upload.

**Comment by priyankoctal** [comment]
Hi, I am not sure why this is closed ?

**Comment by rnicholus** [comment]
You ignored the template/instructions
