### ISSUE TITLE
enhancement - Total Progress Bar

### ISSUE THREAD

**Issue by seltix5** [FineUploader/fine-uploader#1864]
## Type of issue
- [ ] Bug report
- [x] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [x] S3
- [x] Azure

<details>
<summary>Hi, there is 2 enhancements that i think it should be done :

1 - the total progress bar should only be shown at the same time the others progress bar (only on uploading. when the upload is manual the total progress bar showns after adding any candidate.

2 - the total progress bar should have state classes like the other bars (in-progress for exaple, i dont know if there is more)</summary>

#### Fine Uploader version
5.14.3

#### Browsers where the bug is reproducible
chrome at least

#### Operating systems where the bug is reproducible
win 7
</details>

**Comment by rnicholus** [comment]
Why?

**Comment by seltix5** [comment]
to be able to style it with css, this is already done this way for each item =)

**Comment by rnicholus** [comment]
I disagree with point 1 especially, but will reopen if others find this valuable
