### ISSUE TITLE
feature - thumbnail generated with resize and crop

### ISSUE THREAD

**Issue by seltix5** [FineUploader/fine-uploader#1865]
## Type of issue
- [ ] Bug report
- [x] Feature request
- [ ] Support request

## Uploader type
- [x ] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>hi, is there a way to set fineuploader to generate the thumbnails to a specific size in resize and crop mode, generating always a picture with the same size?</summary>

#### Fine Uploader version
5.14.3

#### Browsers where the bug is reproducible
chrome

#### Operating systems where the bug is reproducible
windows 7
</details>

**Comment by rnicholus** [comment]
Please read https://docs.fineuploader.com/branch/master/features/thumbnails.html

**Comment by seltix5** [comment]
hi,
i already read that, thank you. yet i dont see any information about my question, i want to resize and crop to a specific size. using the default thumbnail creator it will only resize the picture.
I supose i need to use a custom resizer for that?
thank you.

**Comment by seltix5** [comment]
hi, the example given does not work anymore :
`thumbnails: {
    customResizer: !qq.ios() && function(resizeInfo) {
        return new Promise(function(resolve, reject) {
            pica.resizeCanvas(resizeInfo.sourceCanvas, resizeInfo.targetCanvas, {}, resolve)
        })
    },
    ...
}`

can you update it? thanks!

**Comment by rnicholus** [comment]
It does still work.
