### ISSUE TITLE
Unable to sign request on s3 when making chunks request

### ISSUE THREAD

**Issue by abhisharkjangir** [FineUploader/fine-uploader#1868]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [1] Support request

## Uploader type
- [ ] Traditional
- [1] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Browsers where the bug is reproducible
{example: "Firefox" and "IE11"}

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}

#### Exact steps required to reproduce the issue
For example:
1. Select 3 files
2. Pause the 2nd file before it completes, but after it has started.
3. Attempt to resume the paused file.

#### All relevant Fine Uploader-related code that you have written
{simply copy and paste the JS used to control Fine Uploader browsers-ide}
{also include your template HTML if related to a UI issue}

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
{simply copy and paste your template markup}

#### Detailed explanation of the problem
{describe the bug here}
</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

<details>
<summary>Support Request</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Question
When we are making a chunk request to upload on s3 its giving error "SignatureDoesNotMatch" and 403 Forbidden. But if we are disabling chunks then its working correctly.

Please find our configuration in code below.

Can you please help me out on this, that where we doing something wrong?

#### Related code
var s3Uploader = new qq.s3.FineUploader({
      debug: false,
      autoUpload: true,
      element: document.getElementById('fine-uploader-s3'),
      template: 'add-art-template',
      request: {
        endpoint: "https://s3-ap-southeast-1.amazonaws.com/dauble-******-upload",
        accessKey: "********C7B6A",
        region: 'ap-southeast-1',
        forceMultipart: true
      },
      signature: {
        endpoint: "http://192.168.30.29:2000/v1/upload/s3/signature",
        version: 4
      },
      objectProperties: {
        region: 'ap-southeast-1',
        bucket: 'dauble-******-upload',
        host: 's3-ap-southeast-1.amazonaws.com'
      },
      uploadSuccess: {
        endpoint: "http://192.168.30.29:2000/v1/upload/success",
        params: {
          isBrowserPreviewCapable: qq.supportedFeatures.imagePreviews
        }
      },
      multiple: false,
      cors: {
        expected: true
      },
      chunking: {
        enabled: true,
        concurrent: {
          enabled: false
        },
        partSize: 5*1024*1024
      },
      maxConnections: 5,
      resume: {
        enabled: true
      },
      retry: {
        enableAuto: false,
        maxAutoAttempts: 2,
        autoAttemptDelay: 10
      },
      validation: {
        allowedExtensions: [
          'jpeg', 'jpg', 'png', 'zip'
        ]
        // ,
        // itemLimit: 5,
        // sizeLimit: 30 *1024 *1024, // 50 kB = 50 * 1024 bytes,
        // allowEmpty: false
      },
      callbacks: {
        onComplete: function(id, name, response) {
          if (response.success) {
            $scope.imgLink = 'https://s3-ap-southeast-1.amazonaws.com/dauble-bulk-upload/' + response.data;
            launchEditor($scope.imgLink);
          }
        },
        onError: function(id, name, reason, xhrCache) {
          console.log(reason);
          // moveUpload({from: 'active', to: 'error', hash: activeUpload.hash}).then(() => bad(new Error('upload error - ' + reason)));
        },
        onUploadChunk : function (id,name,chunkData) {
          console.log(id,name,chunkData);
          // s3Uploader.uploadChunk(id,name,chunkData);
        }
      }
    });
</details>

**Comment by rnicholus** [comment]
Sorry, but I can't understand the issue here at all. Take some time time to clean this up and I'll consider reopening
