### ISSUE TITLE
CORS form response, it is not necessary include the UUID

### ISSUE THREAD

**Issue by ICELI** [FineUploader/fine-uploader#1872]
## Type of issue
- [ ] Bug report
- [x] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

#### Feature request details 
[CORS DOCS](https://docs.fineuploader.com/branch/master/features/CORS.html) Handling iframe CORS upload requests server-side
` and the valid JSON portion must include the UUID of the associated file. `
why? 
In other cases uuid is not necessary, but it's need the UUID when CORS in the form response JSON.
[form.upload.handler.js#L114](https://github.com/FineUploader/fine-uploader/blob/develop/client/js/upload-handler/form.upload.handler.js#L114)
```js
var fileId = getFileIdForIframeName(iframeName),
      response = handler._parseJsonResponse(message),
      uuid = response.uuid, // here
      onloadCallback;
```
I think it is not necessary~

**Comment by rnicholus** [comment]
It is necessary

**Comment by ICELI** [comment]
@rnicholus it‘s for security？

**Comment by ICELI** [comment]
https://github.com/FineUploader/fine-uploader/blob/develop/client/js/upload-handler/form.upload.handler.js#L88
uuid  is already statemented
