### ISSUE TITLE
Add custom upload handlers for other third-party services

### ISSUE THREAD

**Issue by jmhellman** [FineUploader/fine-uploader#1875]
## Type of issue
- [ ] Bug report
- [x] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Feature Request</summary>
We utilize a third party file storage service that does not return a JSON object as a response from the file upload. Instead it is simply a 200 OK response. The Traditional uploader parseResponse() function assumes the response is JSON. Support for other third party file upload providers (other than S3 and Azure) could be gained by providing a configuration to define what constitutes a successful or failed upload. Alternatively, support could be provided for defining a custom upload handler of sorts that handles this and other extensible options.
</details>

**Comment by rnicholus** [comment]
I have no plans to add any new features at this point, especially something this elaborate.
