### ISSUE TITLE
function as delete endpoint

### ISSUE THREAD

**Issue by buganini** [FineUploader/fine-uploader#1876]
## Type of issue
- [ ] Bug report
- [x] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

#### Feature request details 
To postpone deleting action until being submitted with a form, it's useful if endpoint can be a function, or just do nothing if endpoint is null, then do local deleting logic in callbacks.onDelete.

**Comment by rnicholus** [comment]
duplicate of #1320
