### ISSUE TITLE
IE8 with 5.14.5 fine-uploader.core.min.js is not work...

### ISSUE THREAD

**Issue by ICELI** [FineUploader/fine-uploader#1878]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.14.5 fine-uploader.core.min.js

#### Browsers where the bug is reproducible
 "IE8"

#### Operating systems where the bug is reproducible
"Windows 10"

#### Exact steps required to reproduce the issue
For example:
1. IE8 with 5.14.5 fine-uploader.core.js is work fine.
2. When i change fine-uploader.core.js to 5.14.5 fine-uploader.core.min.js, it is not work, throw an error:
```js 
SCRIPT3: Member not found.
util.js (86,13)
```
I think uglify-js need the command line options `--ie8`
···
</details>

**Comment by rnicholus** [comment]
Not a very high priority since IE 8 is a dead browser, but I'll accept a pull request that fixes this

**Comment by rnicholus** [comment]
Sorry - I'm not interested in fixing IE8 bugs
