### ISSUE TITLE
2 and more process combineChunks & upload error 

### ISSUE THREAD

**Issue by falsebyte** [FineUploader/fine-uploader#1879]
I use a squid/3.1.8 proxy server and I have a few problem with that.
I upload big file and I see two combine chunks process and then I see upload error. 

## Type of issue
- [  ] Bug report
- [  ] Feature request

## Uploader type
- [  ] Traditional

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
[Fine Uploader 5.12.0]

#### Browsers where the bug is reproducible
Google Chrome 59.0.3071.115 

#### Operating systems where the bug is reproducible
Windows 7 and other

#### Exact steps required to reproduce the issue

1. Select 1 big file ~50Gb. 
2. Push Upload button.
3. After last chunk uploaded fine-uploader send done request.
4. Default config Squid proxy server make resend done request after 50 second. 
It's look like this:

```
first chunk 
[05/Jul/2017:12:09:32 +0300] "POST /server/endpoint.php HTTP/1.1" 200 80 "http://servername" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" **1/1907700**
last chunk | combine chunk request 
[05/Jul/2017:12:21:45 +0300] "POST /server/endpoint.php?done HTTP/1.1" 200 62 "http://servername" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" **472/472088840**
last combine request resend by squid
[05/Jul/2017:12:22:35 +0300] "POST /server/endpoint.php?done HTTP/1.1" 200 62 "http://servername" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36" **425/425058691**
```
5. Server accept this second request and starting new combineChunk process and this increase server load and time to combine chunks.
6. After a few minutes in uploader web form i will see upload error because squid terminate connections without answers after 2 minutes 50 seconds with resend last request and client will can't wait answer 10 minutes.
7.If I do nothing after fail then process combineChunk will finish anyway and file will accessible state in the server.

```
Combine chank process start at:
[05/Jul/2017:12:21:45 +0300]
And finish at: 
Modify: 2017-07-05 12:29:40.730375882  
```

First bug (2 and more combine process) 
I fixed it this way: 
in  handler.php     public function combineChunks($uploadDirectory, $name = null) 
```
              $target = fopen($targetPath, 'wb');
+added+       flock ($target, LOCK_EX);
                      for ($i=0; $i<$totalParts; $i++){
                         $chunk = fopen($targetFolder.DIRECTORY_SEPARATOR.$i, "rb");
                         stream_copy_to_stream($chunk, $target);
                         fclose($chunk);
              }
```
This work for me.

But second bug i don't know how fix it myself. One idea is the progress bar for the function combineChunks. Users will be able to see the percentage of the build and the fine-uploader will continue to exchange queries and responses with the server while the server continues to combine chunks.  It's fix both problem. 
Feature Request? 

I can change my proxy server config but users can use another proxy at any possible place. Even more i suppose it will be more user frendly interface when appears progress bar of chunk combininig  at server side. 

</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
Maybe you can add progress bar about combine chunk process? 
I think this function can fix both bug.  
 
</details>

**Comment by rnicholus** [comment]
If you have suggestions to improve the code, please do so in a pull request. You haven't mentioned what this "second bug" even is

**Comment by falsebyte** [comment]
Second bug is not actually bug but  my proxy server squid terminate connections without answers after 2 minutes 50 seconds and i see upload error when file is big.

**Comment by rnicholus** [comment]
Ok, there's nothing Fine Uploader can do about that
