### ISSUE TITLE
[Fine Uploader 5.14.5] POST request for 10 has failed - response code 400

### ISSUE THREAD

**Issue by urbanrotnik** [FineUploader/fine-uploader#1880]
## Type of issue
-  Bug

## Uploader type
-  S3

<summary>Bug Report</summary>

#### Fine Uploader version
Fine Uploader 5.14.5

#### Browsers where the bug is reproducible
"Chrome 59.0.3071", "Safari 10.1.1", "Chrome Mobile iOS 56.0.2924", "Mobile Safari 10.0" ...

#### Operating systems where the bug is reproducible
Windows 10, Mac OS X 10, iOS 10.3.2... 

#### Exact steps required to reproduce the issue
Haven't find exact steps how to reproduce this. Looks like occur randomly. We 've tried with connection throttling but still cannot find problem... 

#### All relevant Fine Uploader-related code that you have written
```
Uploader = {
  s3Uploader:null,

  path: null,
  minetypes: null,
  multiple: true,
  $trigger: null,

  init: function(){
    $(document).on('click','.upload-action',this.onUploadAction.bind(this));
    $(document).on('opening', '.remodal.upload', this.onRemodalOpening.bind(this));
    $(document).on('closing', '.remodal.upload', this.onRemodalClosing.bind(this));
    $(document).on('opened', '.remodal.upload', this.onRemodalOpened.bind(this));
  },

  onUploadAction: function(e){
    var $target = $(e.currentTarget);
    this.path = $target.attr('data-path').substring(1);
    this.minetypes = $target.attr('data-minetypes');
    this.multiple = true;

    if($target.attr('data-multiple') === "false"){
      this.multiple = false;
    }

    this.$trigger = $target;

    $('.remodal.upload .success-overlay').addClass('hidden');
    $('.remodal.upload').remodal().open();
  },


  onRemodalClosing: function(){
    if(this.s3Uploader){
      this.s3Uploader.reset();
    }
  },

  onRemodalOpened: function(){
    this.initUploader();

  },

  onRemodalOpening: function (e){
    console.log('open');
  },

  getPath: function(fileId){
    var uuid = this.s3Uploader.getUuid(fileId);
    var name = this.s3Uploader.getName(fileId);
    var newName = uuid+'-'+name;
    return this.path+newName;
  },

  initUploader: function(){
    var self = this;
    this.s3Uploader = new qq.s3.FineUploader({
      debug: true,
      element: document.getElementById('fine-uploader'),
      template: 'qq-template',
      request: {
        endpoint: 'https://'+UploaderConfig.endpoint,
        accessKey: UploaderConfig.accessKey
      },
      objectProperties: {
        key:'filename'
      },
      cors: {
        expected: true
      },
      chunking: {
        enabled: true,
        mandatory: true,
        // partSize: 5242880,
        concurrent: {
          enabled: false
        }
      },
      resume: {
        enabled: true
      },
      retry: {
        enableAuto: true,
        maxAutoAttempts: 5
      },
      camera:{
        ios:true
      },
      signature: {
        endpoint: "/manager/s3upload",
        version: 2,
        customHeaders: {
          "X-CSRF-Token": $("meta[name='csrf-token']").attr("content")
        }
      },
      validation: {
        acceptFiles: this.minetypes
      },
      workarounds: {
        iosEmptyVideos: false,
        ios8BrowserCrash: false,
        ios8SafariUploads: false
      },
      thumbnails: {
        placeholders: {
          notAvailablePath: "/placeholders/not_available-generic.png",
          waitingPath: "/placeholders/waiting-generic.png"
        }
      },
      multiple: this.multiple,
      callbacks: {

        onSubmit: function(id){
          this.setName(id,self.getPath(id));
        },

        onAllComplete: function(succeeded, failed) {
          var files = [];
          for(var i = 0; i < succeeded.length; i++){
            var file = self.s3Uploader.getUploads({id: succeeded[i]});
            var fileData = self.s3Uploader.getFile( succeeded[i]);
            files.push({
              key: file.name,
              mimetype: fileData.type,
              filename: file.originalName,
              container: UploaderConfig.endpoint,
              isWriteable: true,
              client: 'computer',
              size: file.size,
              id: succeeded[i],
              url: 'https://'+UploaderConfig.endpoint+'/'+file.name
            });
          }

          if(files.length > 0){
            var $filePicker = this.$trigger.siblings('.filepicker');
            $filePicker.trigger('uploaded',{files:files});

            $('.remodal.upload .success-overlay').removeClass('hidden');
          }



        }.bind(this)
      }
    });
  }
};


$(document).ready(function() {
 Uploader.init();
});
```
Controller 
```
  def s3upload
    if params[:headers].nil?
      signPolicy
    else
      signHeader
    end
  end

  def signHeader
    signature = Base64.encode64(OpenSSL::HMAC.digest(OpenSSL::Digest.new('sha1'),ENV['AWS_UPLOADER_SECRET'], params[:headers])).gsub("\n","")
    render json: {
      signature: signature
    }
  end

```

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)

```
<script type="text/template" id="qq-template">
  <div class="qq-uploader-selector qq-uploader qq-gallery" qq-drop-area-text="Drop files here">
    <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
      <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
    </div>
    <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
      <span class="qq-upload-drop-area-text-selector"></span>
    </div>
    <div class="qq-upload-button-selector qq-upload-button">
      <div>Upload a file</div>
    </div>
    <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped files...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
    <ul class="qq-upload-list-selector qq-upload-list" role="region" aria-live="polite" aria-relevant="additions removals">
      <li>
        <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
        <div class="qq-progress-bar-container-selector qq-progress-bar-container">
          <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
        </div>
        <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
        <div class="qq-thumbnail-wrapper">
          <a class="preview-link" target="_blank">
            <img class="qq-thumbnail-selector" qq-max-size="120" qq-server-scale>
          </a>
        </div>
        <button type="button" class="qq-upload-cancel-selector qq-upload-cancel">X</button>
        <button type="button" class="qq-upload-retry-selector qq-upload-retry">
          <span class="qq-btn qq-retry-icon" aria-label="Retry"></span>
          Retry
        </button>

        <div class="qq-file-info">
          <div class="qq-file-name">
            <span class="qq-upload-file-selector qq-upload-file"></span>
            <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
          </div>
          <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
          <span class="qq-upload-size-selector qq-upload-size"></span>
          <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">
            <span class="qq-btn qq-delete-icon" aria-label="Delete"></span>
          </button>
          <button type="button" class="qq-btn qq-upload-pause-selector qq-upload-pause">
            <span class="qq-btn qq-pause-icon" aria-label="Pause"></span>
          </button>
          <button type="button" class="qq-btn qq-upload-continue-selector qq-upload-continue">
            <span class="qq-btn qq-continue-icon" aria-label="Continue"></span>
          </button>
        </div>
      </li>
    </ul>

    <dialog class="qq-alert-dialog-selector">
      <div class="qq-dialog-message-selector"></div>
      <div class="qq-dialog-buttons">
        <button type="button" class="qq-cancel-button-selector">Close</button>
      </div>
    </dialog>

    <dialog class="qq-confirm-dialog-selector">
      <div class="qq-dialog-message-selector"></div>
      <div class="qq-dialog-buttons">
        <button type="button" class="qq-cancel-button-selector">No</button>
        <button type="button" class="qq-ok-button-selector">Yes</button>
      </div>
    </dialog>

    <dialog class="qq-prompt-dialog-selector">
      <div class="qq-dialog-message-selector"></div>
      <input type="text">
      <div class="qq-dialog-buttons">
        <button type="button" class="qq-cancel-button-selector">Cancel</button>
        <button type="button" class="qq-ok-button-selector">Ok</button>
      </div>
    </dialog>
  </div>
</script>

<style>
  #fine-uploader .preview-link {
    display: block;
    height: 100%;
    width: 100%;
  }
</style>

```

#### Upload randomly simply not working, just repeating and than show "retry cta"
Console output
`[Fine Uploader 5.14.5] POST request for 10 has failed - response code 400`
`[Fine Uploader 5.14.5] Complete response status 400, body = <Error><Code>InvalidPart</Code><Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.</Message><UploadId>kDkL2yTlN85jsL.Z8SFDmnv36XrbA5xmmic4HZQEHKeVqSAmlHDRL03lcK0j7zgjf7b0N32iZAHiARXd7QqLHNlRva3DXouCh4boUnWdBKd38N3KXzm8R3x0xFzl1dkG</UploadId><PartNumber>2</PartNumber><ETag>null</ETag><RequestId>F5EE071DC27E97D6</RequestId><HostId>FbAKer63i+5ak9Bepmpo4yxkUQsgbkWbtZP5TFbWmhY7J3nNAutxGSd/a1tSKvtTCihTYB38JyQ=</HostId></Error>`
`[Fine Uploader 5.14.5] Complete Multipart Upload request for 10 failed with status 400.`
`[Fine Uploader 5.14.5] Received response status 400 with body: <Error><Code>InvalidPart</Code><Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.</Message><UploadId>kDkL2yTlN85jsL.Z8SFDmnv36XrbA5xmmic4HZQEHKeVqSAmlHDRL03lcK0j7zgjf7b0N32iZAHiARXd7QqLHNlRva3DXouCh4boUnWdBKd38N3KXzm8R3x0xFzl1dkG</UploadId><PartNumber>2</PartNumber><ETag>null</ETag><RequestId>F5EE071DC27E97D6</RequestId><HostId>FbAKer63i+5ak9Bepmpo4yxkUQsgbkWbtZP5TFbWmhY7J3nNAutxGSd/a1tSKvtTCihTYB38JyQ=</HostId></Error>`
`[Fine Uploader 5.14.5] This is an unrecoverable error, we must restart the upload entirely on the next retry attempt.`
`[Fine Uploader 5.14.5] Problem finalizing chunks for file ID 10 - One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.`
`[Fine Uploader 5.14.5] Server or callback has ordered chunking effort to be restarted on next attempt for item ID 10`
`[Fine Uploader 5.14.5] Waiting 5 seconds before retrying img/47/12894/cf30d4a2-2a06-49e3-9c73-ce5791d05048-IMG_4627.MOV...
400 Bad Request: POST https://my.bucket.com/img/folder1/folder2/cf30d4a2-2a06-49e3-9c73-ce5791d05048-IMG_4627.MOV?uploadId=123123123123id.etc...`
`[Fine Uploader 5.14.5] POST request for 22 has failed - response code 400`
`[Fine Uploader 5.14.5] Complete response status 400, body = <Error><Code>InvalidPart</Code><Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.</Message><UploadId>CwZ3CX02wWxAzu3DlGOTT3jqF_UETUn8EjXYnrFeLSDSVlI51GtAbxEqFEYgKmg5o30aNMVKgEHnCRaK1PbC47JWVqcqSFUYEltZzC3A0so2q1TVnYyFm8inAggmb5u1</UploadId><PartNumber>1</PartNumber><ETag>null</ETag><RequestId>0268F13AB1CA2CF1</RequestId><HostId>5oK0CXNvfj9VZ/82ljXSe5HxY6utrwjovE0uaifR3mdqwrL0ft6/UzYrPcMDf6nsaKm6qMTaHnM=</HostId></Error>`
`[Fine Uploader 5.14.5] Complete Multipart Upload request for 22 failed with status 400.`
`[Fine Uploader 5.14.5] Received response status 400 with body: <Error><Code>InvalidPart</Code><Message>One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.</Message><UploadId>CwZ3CX02wWxAzu3DlGOTT3jqF_UETUn8EjXYnrFeLSDSVlI51GtAbxEqFEYgKmg5o30aNMVKgEHnCRaK1PbC47JWVqcqSFUYEltZzC3A0so2q1TVnYyFm8inAggmb5u1</UploadId><PartNumber>1</PartNumber><ETag>null</ETag><RequestId>0268F13AB1CA2CF1</RequestId><HostId>5oK0CXNvfj9VZ/82ljXSe5HxY6utrwjovE0uaifR3mdqwrL0ft6/UzYrPcMDf6nsaKm6qMTaHnM=</HostId></Error>`
`[Fine Uploader 5.14.5] This is an unrecoverable error, we must restart the upload entirely on the next retry attempt.`
`[Fine Uploader 5.14.5] Problem finalizing chunks for file ID 22 - One or more of the specified parts could not be found.  The part may not have been uploaded, or the specified entity tag may not match the part's entity tag.`
`[Fine Uploader 5.14.5] Server or callback has ordered chunking effort to be restarted on next attempt for item ID 22`
And so on... Let's say that happe for around 10-20% of users. Diffrent OS, diffrent browsers...

I would  appreciate any help.

**Comment by rnicholus** [comment]
Sorry - I simply don't have the time to handle support requests anymore. If you can locate a specific bug in the library or would like to contribute a feature, please do and I will do my best to assist.
