### ISSUE TITLE
--LOOKING FOR HELP MAINTAINING THIS PROJECT--

### ISSUE THREAD

**Issue by rnicholus** [FineUploader/fine-uploader#1881]
I've been maintaining and evolving Fine Uploader faithfully on an almost daily basis since mid-2012. But I no longer rely on Fine Uploader myself, and have lost the motivation and time to continue supporting and evolving this library. 

Fine Uploader has a large user base, and many projects built on top of it, including React Fine Uploader. I'm looking for a new dedicated maintainer to continue to support and evolve Fine Uploader and its related projects. I have a lot of big plans for the project, but I feel the time has come to pass the torch on to someone else. Please respond here if you are interested.

**Comment by gohabsgo** [comment]
Hi Ray, I'm Steph, the CTO at MASV.io (LiveQoS Inc.) based in Ottawa, Canada (between Montreal and Toronto).

MASV.io is a new SaaS offering that caters to the Media & Entertainment, massive file transfer vertical.

Timing is everything!  I'm just in the midst of planning next 6-12 months which includes major enhancements to our Rush web uploader, as well as deploying MASV REST API, and in both cases I was considering flipping over from our in-house uploader to FineUploader.

I have a small team of developers, skin in the game, and an interest in monetizing usage of our cloud, but not the tools that promote such usage. 

Would you consider someone from or team to maintain it? I can offer you an assurance that we'll have the community's interest in mind and keep your baby alive.

Would be great to speak to you actually, I'd like to know more about you and see if we have any common interests. I can also share with you my vision of MASV and how FU would benefit.  Regardless, I would really like to hear your vision for FineUploader and know what you wish you had time to do. Do you have time for a call next week Wed-Fri?

Thanks for your time,
Stéphane Brunet
steph@masv.io
Mob. 613-265-9924

**Comment by rnicholus** [comment]
Thanks for this Steph. I'll be in London all next week for Holacracy training, but perhaps we can coordinate and speak via phone sometime in the evening UTC. I'll follow up with an email shortly.

**Comment by toabm** [comment]
Hi Ray,

I am Ángel. 

I'm 32 years old and have been developing webs, apps, UI and so on since I was a kid. always supporting open source software.

I'd love to participate and keep Fine Uploader alive. We can have a skype meeting if you like, I live in Madrid.

Thanks for your job during all this years,

    Ángel

**Comment by martinkouba** [comment]
Hi Ray,

I am Martin. We are a small team based in Austria developing a Plattform where file upload is an essential part. So we have an interest in having a properly maintained library we can build upon. I can picture us becoming maintainer of the FineUploader project.

Let me know about your plans. I dropped you a message in Skype.

Martin

**Comment by rnicholus** [comment]
Hey @toabm, I'll send you an email shortly. Thanks for responding.

@martinkouba let's talk more offline. How would you like to coordinate?

**Comment by rnicholus** [comment]
Unfortunately nothing has panned out on this front. But it looks like I will have some time and motivation to address some of the bigger feature requests as part of my work on [BrickFTP](https://brickftp.com).

**Comment by martinkouba** [comment]
I did send you an invitation to your Skype account, though.

**Comment by rnicholus** [comment]
Reopening as support requests are increasing and my time to work on some key features has been pushed back slightly due to other commitments

**Comment by rnicholus** [comment]
Well, while many users are quick to demand further work from me (for free of course) I have had zero reasonable offers to step up and help maintain the library or even help pay the AWS bills (which have since lapsed). Even though I continue to develop the library for the benefit of everyone (see #1917) I’m very disappointed with the community.

**Comment by martinkouba** [comment]
I am happy to have a chat about that on Skype. I have resent my Skype invitation.

**Comment by rnicholus** [comment]
Hi Martin: I’m not even aware of a Skype account that I may or may not hold. Please contact me on Twitter and we can exchange contact information there. Thanks.

**Comment by rnicholus** [comment]
RayNicholus on Twitter btw

**Comment by martinkouba** [comment]
Hi,

I think this is you ;-)

I hardly use Twitter but I will dig out my account for you

**Comment by rnicholus** [comment]
Well, finding a suitable maintainer has been far more difficult than I anticipated.

**Comment by martinkouba** [comment]
I can see your pain.

Would have loved to see it otherwise. Alas, we have postponed our switch to fineuploader. Other stuff got higher priority.

Maybe next year.

**Comment by ScotsScripts** [comment]
I wish I could help but it's not part of my skill set, however I'm curious about something you wrote- "But I no longer rely on Fine Uploader myself,..." What do you use instead of Fine Uploader?

**Comment by rnicholus** [comment]
@ScotsScripts Actually, that is no longer true. I do indeed rely on Fine Uploader and React Fine Uploader in a project i'm working on with my new/current employer. In fact, I have some substantial changes in progress that have been under observation in my environment for a little while now - https://github.com/FineUploader/fine-uploader/pull/1939

**Comment by rnicholus** [comment]
Changed the title to reflect the current status: "looking for help maintaining this project".

**Comment by rcheung9** [comment]
Just curious as I read your Medium story on how this came to be.

You said you used to do this on your free time but it wasn't worth it until you started charging for licenses which made you good money then your company Widen took over the project and was providing you with a team or allowing you to work on this as part of your employment.

Is that no longer the case seeing as you have a "new employer"? Since you continue to own it, does that mean Widen never officially sponsored it?

Since that is the case, why don't you go back to your old licensing model.  Free for community use, license for commercial use.

**Comment by galvinhsiu** [comment]
@rnicholus i am interested, drop me a line.

**Comment by rnicholus** [comment]
How shall I contact you @galvinhsiu? You can DM me on Twitter, if you'd like. My DMs are open at the moment.

**Comment by rnicholus** [comment]
@rcheung9 I have no plans to ever charge for Fine Uploader again in any capacity. It will remain FOSS for as long as I'm around.

**Comment by sizzlefinger** [comment]
Please DM me on Twitter @sizzlefinger with some details.  I would like to see if there is some way to work something out on maintaining and commercially sponsoring the project.  I use the project in my app and would love to help.  -sf

**Comment by rnicholus** [comment]
Thanks @sizzlefinger - just sent you a DM

**Comment by patentshell** [comment]
Grew up in Eau Claire, went to Madison, would love to help you keep this maintained.

**Comment by LukeM12** [comment]
Hey rnicholus. If you need some support ping me lukescotian@outlook.com

Interested to know more. 

Luke

**Comment by Yulietta** [comment]
Hi,
i am interested.
Greetings, Yuli

**Comment by rnicholus** [comment]
Anyone interested: please contact me via Twitter so we can discuss further. https://twitter.com/RayNicholus

**Comment by Yulietta** [comment]
ok i did. DM is disabled so tweeted at least

**Comment by rnicholus** [comment]
Thanks to @SinghSukhdeep for taking the reins!
