### ISSUE TITLE
Large files fail with azure uploader

### ISSUE THREAD

**Issue by mmartain** [FineUploader/fine-uploader#1886]
## Type of issue
- [ ] Bug report
## Uploader type
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.5.1

#### Browsers where the bug is reproducible
Chrome

#### Operating systems where the bug is reproducible
Windows 10

#### Exact steps required to reproduce the issue
For example:
1. upload a large file to azure (mine is 528MB)
2. wait until it stops progressing.
3. Receive error

#### All relevant Fine Uploader-related code that you have written
   videoUploader = new qq.azure.FineUploader({

//end point information omitted
                retry: {
                    enableAuto: true
                },
                chunking:
                {
                    partSize: 2000000,
                },
   validation: {
                    allowedExtensions: ["mp4"],
                    itemLimit: 1,
                    //2GB file size limit
                    sizeLimit: 2147483648,
                },
                messages: {
                    typeError: "{file} has an invalid extension. Only mp4 files are allowed."
                },
                debug: true,
            })
#### Detailed explanation of the problem

Upload fails at 52%. ERror in chrome log is : ERR_CONNECTION_RESET.

Uploader tries for 3 times and then fails. No file is ever found in blob storage. Small files do work without hickups.
</details>

**Comment by rnicholus** [comment]
Sounds like an issue with your network/environment or sas server. Nothing fine uploader can do about network issues. This is definitely not a bug, as it is written.

**Comment by mmartain** [comment]
Well, it was an issue afterall: On the azure api documentation page there is a mention about chunking, but not that u have to put the enabled flag also. So in the end the documentation was a bit confusion making me not realize you have to enable chunking explicitly... Maybe something to add in the documentation?
