### ISSUE TITLE
onComplete function appears to be interrupted

### ISSUE THREAD

**Issue by msavvy** [FineUploader/fine-uploader#1887]
## Type of issue
- [ x ] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [ x ] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
Fine Uploader 5.14.3

#### Browsers where the bug is reproducible
Opera 10.0

#### Operating systems where the bug is reproducible
iOS 10

#### Exact steps required to reproduce the issue
For example:
1. Select files
2. Wait until completes

#### All relevant Fine Uploader-related code that you have written
$("#fine-uploader-manual-trigger").fineUploader({
  autoUpload: true,
  debug: true,
  element: document.getElementById('fine-uploader-manual-trigger'),
  template: 'qq-template-manual-trigger',
  session: {
    endpoint: settings.savvyapplication.session
  },
  request: {
    endpoint: settings.savvyapplication.endpoint
  },
  thumbnails: {
    placeholders: {
      waitingPath: settings.savvyapplication.fine_uploader_path + '/placeholders/waiting-generic.png',
      notAvailablePath:  settings.savvyapplication.fine_uploader_path + '/placeholders/not_available-generic.png'
    }
  },
  validation: {
    itemLimit: 5,
    allowedExtensions: ["jpeg", "jpg", "png", "pdf", "gif"],
  },
  deleteFile: {
    enabled: true,
    method: "POST",
    endpoint: settings.savvyapplication.endpoint,
  },
  cors: {
    expected: false,
  },
  resume: {
    enabled: true,
  },
  callbacks: {
    onError: function(id, name, errorReason, xhrOrXdr) {
      var app_info = {};
      app_info.status = 'Upload error';
      app_info.page = Drupal.settings.savvyapplication.step;
      app_info.name = name;
      app_info.email = Drupal.settings.savvyapplication.email;
      app_info.errorReason = errorReason;
      $.post(Drupal.settings.savvyapplication.app_log, {app_info: app_info});
    },
    onUpload: function(id, name) {
      var extension_name = $.trim(name.split(".").pop());
      var uploaded_filename = name.replace("." + extension_name, "");
      if(uploaded_filename.length > 25) {
        uploaded_filename = uploaded_filename.substr(0,25) + '..';
      }
      uploaded_filename += "." + extension_name;

      $(".qq-file-id-" + id).find("span.qq-upload-file-selector.qq-upload-file").text(uploaded_filename);
    },
    onComplete: function(id, name, response) {

      if(response.success) {

        if(response.method == 'upload') {

          var fileuuid = response.uuid;
          var filename = response.uploadName;
          var file_info = this.getFile(id);
          var filesize = file_info.size;

          var uploaded_files = {
            uuid: fileuuid,
            uploadName: filename,
            size: filesize,
            sequence: id,
          }

          var uploaded_files_json = sessionStorage.getItem('fine_uploader_session');

          if(uploaded_files_json === undefined || uploaded_files_json === null) {
            uploaded_files_json = [];
          }
          else {
            uploaded_files_json = JSON.parse(uploaded_files_json);
          }

          uploaded_files_json.push(uploaded_files);

          sessionStorage.setItem('fine_uploader_session', JSON.stringify(uploaded_files_json));

          var extension_name = $.trim(response.uploadName.split(".").pop());
          var uploaded_filename = response.uploadName.replace("." + extension_name, "");
          if(uploaded_filename.length > 25) {
            uploaded_filename = uploaded_filename.substr(0,25) + '..';
          }

          uploaded_filename += "." + extension_name;

          var file_link = settings.savvyapplication.image_path + fileuuid + '/' + filename;

         var upload_log = {};
           
         upload_log.fileuuid = fileuuid;
         upload_log.status = 'Dropdown update meta';
         upload_log.email = Drupal.settings.savvyapplication.email;
         upload_log.filename = filename;
          $.post(Drupal.settings.savvyapplication.app_log, {app_info: upload_log});
          $(".qq-file-id-" + id).find("select.file-classify").attr("data-uuid", fileuuid).attr("data-file-name", filename);

          $(".qq-file-id-" + id).find("a.view-image").attr("href", file_link);

          $(".qq-file-id-" + id).find("select.file-classify").parent().removeClass('sa-hide');
          var app_info = {};
          app_info.status = 'Upload success';
         app_info.page = Drupal.settings.savvyapplication.step;
         app_info.uploaded_files = JSON.stringify(uploaded_files);
          app_info.email = Drupal.settings.savvyapplication.email;
         app_info.uploaded_files_json = JSON.stringify(uploaded_files_json);
          $.post(Drupal.settings.savvyapplication.app_log, {app_info: app_info});

          $('html,body').animate({ scrollTop: ($(".qq-file-id-" + id + " > .file-classification").offset().top - 50) }, 1000, 'swing');                      
        }
      }
    },
    onAllComplete: function(succeeded, failed) {
      console.log('all complete');
      console.dir(succeeded);
      var uploaded_files_json = sessionStorage.getItem('fine_uploader_session');

      if(uploaded_files_json !== undefined && uploaded_files_json !== null) {

        $.ajax({
          url: settings.savvyapplication.update_session,
          method: "POST",
          data: { uploaded_files: uploaded_files_json, action: 'update' },
        });
      }

    },
    onDelete: function(id) {
      $(".qq-upload-delete").css("visibility", "hidden");
    },
    onDeleteComplete: function(id, xhr, isError) {

      if(!isError) {

        var uploaded_files;

        var uploaded_files_json = sessionStorage.getItem('fine_uploader_session');

        if(uploaded_files_json !== undefined && uploaded_files_json !== null) {
          var uploaded_files = JSON.parse(uploaded_files_json);

          if(uploaded_files[id] !== undefined && uploaded_files[id] !== null) {
            for(var i = 0; i < uploaded_files.length; i++) {
              if(uploaded_files[i].sequence == id) {
                uploaded_files = uploaded_files.splice(i, 1);
              }
            }
            uploaded_files_json = JSON.stringify(uploaded_files);
            sessionStorage.setItem('fine_uploader_session', uploaded_files_json);
          }
        }

        var deleted_file = JSON.parse(xhr.response);

        var deleted_uuid;

        if(!deleted_file.success) {
          deleted_uuid = deleted_file.path;
        }
        else {
          deleted_uuid = deleted_file.uuid;
        }

        setTimeout(function() {
          savvy_application_remove_uploaded(deleted_uuid);
        }, 500);

        for(var c = 1; c <= 5; c++ ){
          $("#edit-field-supporting-document-link-" + c + "-und-0-value").val('');
          $("#edit-field-document-type-" + c + "-und-0-value").val('');
        }

        if($(".file-classify") !== undefined && $(".file-classify") !== null) {
          if($(".file-classify").length > 0) {
            $(".file-classify").each(function () {
              var nth_element = $(this).parent().parent().index() + 1;
              $("#edit-field-supporting-document-link-" + nth_element + "-und-0-value").val($(this).attr("data-uuid") + '/' + $(this).attr("data-file-name"))
              $("#edit-field-document-type-" + nth_element + "-und-0-value").val($(this).val());
            });
          }
        }

        $(".qq-upload-delete").css("visibility", "visible");
      }
    },
    onSessionRequestComplete: function(response, success, xhrOrXdr) {

      var uploaded_files = [];
      for(var f = 0; f < response.length; f++) {
        var extension_name = $.trim(response[f].name.split(".").pop());
        var uploaded_filename = response[f].name.replace("." + extension_name, "");
        if(uploaded_filename.length > 25) {
          uploaded_filename = uploaded_filename.substr(0,25) + '..';
        }

        var uploaded_file_object = {
          uuid: response[f].uuid,
          uploadName: response[f].name,
          size: response[f].size,
        }

        uploaded_files.push(uploaded_file_object);

        uploaded_filename += "." + extension_name;

        $(".qq-file-id-" + f).find("select.file-classify").attr("data-uuid", response[f].uuid).attr("data-file-name", response[f].name);
        $(".qq-file-id-" + f).find("span.qq-upload-file-selector.qq-upload-file").text(uploaded_filename);

        var file_link = settings.savvyapplication.image_path + response[f].uuid + '/' + response[f].name;
        $(".qq-file-id-" + f).find("a.view-image").attr("href", file_link);

        $(".qq-file-id-" + f).find("select.file-classify").parent().removeClass('sa-hide');
      }

      uploaded_files_json = JSON.stringify(uploaded_files);
      sessionStorage.setItem('fine_uploader_session', uploaded_files_json);

    },
  }
});

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
<script type="text/template" id="qq-template-manual-trigger">
  <div class="qq-uploader-selector qq-uploader" qq-drop-area-text="Drop files here">
    <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
      <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
    </div>
    <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone> 
      <span class="qq-upload-drop-area-text-selector"></span> 
    </div>
    <div class="buttons"> 
      <div class="qq-upload-button-selector qq-upload-button"> 
        <div class="choose-file"><i class="app-icon savvy-application-choose-file1"></i>Choose file</div>
      </div>
    </div>
    <span class="qq-drop-processing-selector qq-drop-processing"> 
      <span>Processing dropped files...</span> 
      <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span> 
    </span> 
    <ul class="qq-upload-list-selector qq-upload-list" aria-live="polite" aria-relevant="additions removals"> 
      <li> 
        <div class="qq-progress-bar-container-selector"> 
          <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
        </div>
        <span class="qq-upload-spinner-selector qq-upload-spinner"></span> 
        <i class="uploaded-icon savvy-application-uploaded2"></i> 
        <span class="qq-upload-file-selector qq-upload-file"></span> 
        <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span> 
        <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
        <span class="qq-upload-size-selector qq-upload-size"></span> 
        <button type="button" class="qq-btn qq-upload-cancel-selector qq-upload-cancel">Cancel</button> 
        <button type="button" class="qq-btn qq-upload-retry-selector qq-upload-retry">Retry</button> 
        <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete"><i class="savvy-application-63260"></i></button> 
        <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span> 
        <span role="classify" class="file-classification sa-hide"> 
          <select name="classify-file" class="form-select file-classify sa-error"> 
            <option value="">Please classify</option> 
            <option value="Drivers Licence Front">Drivers Licence Front</option> 
            <option value="Drivers Licence Back">Drivers Licence Back</option> 
            <option value="Drivers Licence Front and Back">Drivers Licence Front and Back</option> 
            <option value="Payslip 1">Payslip 1</option>
            <option value="Payslip 2">Payslip 2</option>
            <option value="AllInOne">All In One</option> 
          </select>
          <span class="dropdown-arrow"></span> 
          <a class="view-image" href="#" target="_blank"><i class="savvy-application-126476"></i></a>
        </span> 
      </li>
    </ul> 
    <dialog class="qq-alert-dialog-selector"> 
      <div class="qq-dialog-message-selector"></div>
      <div class="qq-dialog-buttons"> 
        <button type="button" class="qq-cancel-button-selector">Close</button> 
      </div>
    </dialog> 
    <dialog class="qq-confirm-dialog-selector"> 
      <div class="qq-dialog-message-selector"></div>
      <div class="qq-dialog-buttons"> 
        <button type="button" class="qq-cancel-button-selector">No</button> 
        <button type="button" class="qq-ok-button-selector">Yes</button> 
      </div>
    </dialog> 
    <dialog class="qq-prompt-dialog-selector"> 
      <div class="qq-dialog-message-selector"></div>
        <input type="text"> <div class="qq-dialog-buttons"> 
        <button type="button" class="qq-cancel-button-selector">Cancel</button> 
        <button type="button" class="qq-ok-button-selector">Ok</button> 
      </div>
    </dialog> 
  </div>
</script>

#### Detailed explanation of the problem
on the onComplete callback, it adds attributes to a corresponding select tag, however, there are times when the attributes are not added to the select tag it's as if it was skipped or interrupted. No error was reported on console, I have logs that indicated that the file was uploaded successfully, but select tag custom attributes are not created.

Thank you.

</details>

**Comment by rnicholus** [comment]
We definitely do no support opera on iOS. Also, the issue, as you're describing it, is also definitely not an issue with this library

**Comment by msavvy** [comment]
Ok, Thanks.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
