### ISSUE TITLE
Global window drop event handling for uploading

### ISSUE THREAD

**Issue by danielHalan** [FineUploader/fine-uploader#1894]
## Type of issue
- [ ] Support request

## Uploader type
- [ ] Traditional

Hi, is it possible to initiate a file upload from a global window.drop-event, i.e. to forward the content of drop to a fineUploader. 

Main scenario is that the FineUploader drop-area is not initially visible, but when a user 'drops' into window, it will appear and would then also handle the drop. (Example of handling global window drop event, https://codepen.io/matthiasmeier/pen/XmvQqG )

A different user scenario, when FineUploader is always visible, noticed that the FineUploader changes UI on window-drop, but if user drops anywhere outside the 'drop-zone'-area, the drop is ignored by FineUploader, is there any setting to allow a window-wide drops?

**Comment by rnicholus** [comment]
Sorry - I simply don't have the time to handle support requests anymore. If you can locate a specific bug in the library or would like to contribute a feature, please do and I will do my best to assist.
