### ISSUE TITLE
Using with a local development s3 server?

### ISSUE THREAD

**Issue by charlesswanson** [FineUploader/fine-uploader#1895]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [X] Support request

## Uploader type
- [ ] Traditional
- [X] S3
- [ ] Azure

I'm interested in using FineUploader with the direct to s3 feature. I'm hoping to do development by running a fake s3 server on my local laptop. I'd like to use a service like: https://github.com/scality/S3
Is it possible for FineUploader to work with a mock s3 server. Or, do you recommend doing development work against the real S3 with a non-production testing bucket?

Thanks

**Comment by rnicholus** [comment]
It should, assuming the mock S3 actually behaves like the real s3

**Comment by charlesswanson** [comment]
How do I configure fine-uploader to hit my local s3 endpoint? For example, my local s3 server might be running on localhost port 10001. 
related: https://github.com/jubos/fake-s3/wiki/Supported-Clients

**Comment by rnicholus** [comment]
Set the endpoint accordingly? What issue are you having?
