### ISSUE TITLE
S3 upload with Safari 9.1

### ISSUE THREAD

**Issue by jfpaulin** [FineUploader/fine-uploader#1896]
## Type of issue
- [x] Bug report

## Uploader type
- [x] S3

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.14.5

#### Browsers where the bug is reproducible
Safari 9.1

#### Operating systems where the bug is reproducible
iOS El Captan

#### Exact steps required to reproduce the issue
Upload one file
#### Detailed explanation of the problem
All files upload failed on that version of Safari with a 403 response code.
</details>

**Comment by rnicholus** [comment]
Not enough info in here to debug, but I'm not seeing how fine uploader is the culprit given the response code. Most likely a server or environment issue on your end

**Comment by jfpaulin** [comment]
I can put the code in here but the code is working with every other browsers we tested.
Which part do you need? Do you want all the HTML, JS and PHP code?

**Comment by rnicholus** [comment]
So far, yours is the only such report, which suggests this is not an issue with Fine Uploader. So if you find a specific bug in the code or a root cause, I can look further

**Comment by jfpaulin** [comment]
I did some digging into that and I found that the problem is with the 'chunking' feature. If I disable this feature, the upload is working fine on Safari 9.1. But when I do enable it here is the error I get from AWS S3 :

<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>********</AWSAccessKeyId><StringToSign>PUT

,

x-amz-date:Thu, 03 Aug 2017 13:23:46 GMT
/webcargo-usstd-trial-dev/1501766626-a501aab81a61d41afd192f39db69e169.zip?partNumber=1&amp;uploadId=WMEx5fYwfnvkG4oiF8ooh5ohG0UjZfitJ6QzpTdAhT3qe_AoakW2fbra3OaiMa4qVB5IFKH7yg6vyslbFGJvtqCM7JBT4Ui7pErjNbpJnvNY9op8PhtMv.EHQH1xkAe7</StringToSign><SignatureProvided>vRTTJ0znaCCl8WiyzbTlm/F2Yn8=</SignatureProvided><StringToSignBytes>50 55 54 0a 0a 2c 0a 0a 78 2d 61 6d 7a 2d 64 61 74 65 3a 54 68 75 2c 20 30 33 20 41 75 67 20 32 30 31 37 20 31 33 3a 32 33 3a 34 36 20 47 4d 54 0a 2f 77 65 62 63 61 72 67 6f 2d 75 73 73 74 64 2d 74 72 69 61 6c 2d 64 65 76 2f 31 35 30 31 37 36 36 36 32 36 2d 61 35 30 31 61 61 62 38 31 61 36 31 64 34 31 61 66 64 31 39 32 66 33 39 64 62 36 39 65 31 36 39 2e 7a 69 70 3f 70 61 72 74 4e 75 6d 62 65 72 3d 31 26 75 70 6c 6f 61 64 49 64 3d 57 4d 45 78 35 66 59 77 66 6e 76 6b 47 34 6f 69 46 38 6f 6f 68 35 6f 68 47 30 55 6a 5a 66 69 74 4a 36 51 7a 70 54 64 41 68 54 33 71 65 5f 41 6f 61 6b 57 32 66 62 72 61 33 4f 61 69 4d 61 34 71 56 42 35 49 46 4b 48 37 79 67 36 76 79 73 6c 62 46 47 4a 76 74 71 43 4d 37 4a 42 54 34 55 69 37 70 45 72 6a 4e 62 70 4a 6e 76 4e 59 39 6f 70 38 50 68 74 4d 76 2e 45 48 51 48 31 78 6b 41 65 37</StringToSignBytes><RequestId>E65298EF59E59EEE</RequestId><HostId>usbzx1aNF3rOWnqT3bstf1V26dYF981hFzZYs9c+XDPydlMPXS30ax7Kwl0LPzoXDIAOydnSbIw=</HostId></Error>

Do you think you can take a look? Or do you need more information? I can also send you a link to our implementation if you want to test it.
