### ISSUE TITLE
Prevent qqfilename/key modified based on file type interrogation

### ISSUE THREAD

**Issue by keiranmraine** [FineUploader/fine-uploader#1900]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [x] Support request

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

<details>
<summary>Support Request</summary>

#### Fine Uploader version
fine-uploader: 5.15.0
react-fine-uploader: 1.0.2
fine-uploader-wrappers: 1.0.0

#### Question
I need to upload [BAM files](https://en.wikipedia.org/wiki/Binary_Alignment_Map) to S3 (ceph) using the react extensions.  As the file is actually a variant of bgzip the file extension is modified to `.gz`.

e.g.
Real filename = `1.12.3-rc1.bam`
qqfilename = `1.12.3-rc1.bam.gz`
key = `<uuid>.gz`

Is there any way to prevent this modification?

#### Related code
Options passed to FineUploaderS3 component:

```
var uploadOptions = {
      cors: {
        expected: true
      },
      objectProperties: {
        bucket: config.s3bktup,
        host: config.s3srv
      },
      request: {
          endpoint: 'https://'+ config.s3bktup + '.' + config.s3srv,
          accessKey: config.s3access, // access, NOT secret
          params: { dsuuid: this.props.match.params.uuid }
      },
      signature: {
          customHeaders: { tokenid: this.props.tokenId },
          endpoint: config.restUrl+"/s3/sign",
          params: { dsuuid: this.props.match.params.uuid }
      },
      uploadSuccess: {
          customHeaders: { tokenid: this.props.tokenId },
          endpoint: config.restUrl+"/s3/success",
          params: { dsuuid: this.props.match.params.uuid }
      },
      deleteFile: {
          customHeaders: { tokenid: this.props.tokenId },
          method: 'POST',
          enabled: true,
          endpoint: config.restUrl+"/s3/delete",
          params: { dsuuid: this.props.match.params.uuid }
      },
      chunking: {
          enabled: true,
          concurrent: {
              enabled: true
          }
      },
      resume: {
          enabled: true
      },
      retry: {
          enableAuto: false,
          preventRetryResponseProperty: "error"
      }
    }
```

</details>

**Comment by rnicholus** [comment]
Sorry - I simply don't have the time to troubleshoot. If you can locate a specific bug in the library, I will be happy to re-open and address.
