### ISSUE TITLE
Using server-side generated thumbnails for the “Initial File List”

### ISSUE THREAD

**Issue by electrotype** [FineUploader/fine-uploader#1906]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [ X] Support request

## Uploader type
- [ X] Traditional
- [ ] S3
- [ ] Azure

Hi, I asked a question about server-side generated thumbnails on StackOberflow, but didn't get any answers. Maybe someone here can help?

https://stackoverflow.com/questions/45935016/fine-uploader-using-server-side-generated-thumbnails-for-the-initial-file-lis

The question : 

> I saw a couple of messages about this topic, but I still haven't found how to make Fine Uploader use thumbnails generated by the server for the Initial File List files.
>
>I use a "traditional" server-side Fine Uploader implementation, for pictures upload, as described in the Getting Started section. But I also want to use Fine Uploader as a gallery to show already uploaded pictures, so I use the "session" config to populate it, when it loads...
>
>This works, but Fine Uploader creates Base64 images for those already uploaded images, even if I return a thumbnailUrl property for each of them, pointing to already resized thumbnails... Indeed, when I upload pictures, I generate thumbnails on the server, by myself. I want Fine Uploader to display those thumbnails when the "Initial File List" is received. How can I achieve this?
>
>I've read about the drawThumbnail() function, but I don't know exactly how to use it. Should I call it manually in the onSessionRequestComplete event? Will that prevent Fine Uploader to create Base64 thumbnails by itself?

Thanks in advance!

**Comment by rnicholus** [comment]
Sorry - I simply don't have the time to troubleshoot. If you can locate a specific bug in the library, I will be happy to re-open and address.
