### ISSUE TITLE
new integration library for php

### ISSUE THREAD

**Issue by Mehrdad-Dadkhah** [FineUploader/fine-uploader#1908]
## Type of issue
- [ ] Feature request
- [ ] Support request

## Uploader type
- [x] Traditional

I develop new integration library for php. I have some problem with old script.

[php-fine-uploader](https://github.com/Mehrdad-Dadkhah/php-fine-uploader) is here. 

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{example: 5.5.1}

**Comment by rnicholus** [comment]
Please open a pull request with your changes.
