### ISSUE TITLE
405 (Method Not Allowed) @ s3.jquery.fine-uploader.min.js:6

### ISSUE THREAD

**Issue by guzial** [FineUploader/fine-uploader#1909]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [x] Support request

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

<summary>Support Request</summary>

#### Fine Uploader version
Fine Uploader 5.15.0

#### Question
I have adjusted code from demo:
https://github.com/Widen/fine-uploader-examples/tree/master/src/s3-no-server

I'm working with amazon cognito i have authenticated and authorized user (accessKeyId, secretAccessKey is available and correct) when trying to upload file i get this error:

s3.jquery.fine-uploader.min.js:6 POST http://someMyBucket.s3-website.eu-central-1.amazonaws.com/ 405 (Method Not Allowed)
(anonymous) @ s3.jquery.fine-uploader.min.js:6
then @ s3.jquery.fine-uploader.min.js:2
send @ s3.jquery.fine-uploader.min.js:6
(anonymous) @ s3.jquery.fine-uploader.min.js:6
then @ s3.jquery.fine-uploader.min.js:2
(anonymous) @ s3.jquery.fine-uploader.min.js:6
then @ s3.jquery.fine-uploader.min.js:2
y.key.promise.then.n.failure.error @ s3.jquery.fine-uploader.min.js:6
then @ s3.jquery.fine-uploader.min.js:2
start @ s3.jquery.fine-uploader.min.js:6
send @ s3.jquery.fine-uploader.min.js:4
now @ s3.jquery.fine-uploader.min.js:4
maybeSendDeferredFiles @ s3.jquery.fine-uploader.min.js:4
maybeDefer @ s3.jquery.fine-uploader.min.js:4
start @ s3.jquery.fine-uploader.min.js:4
upload @ s3.jquery.fine-uploader.min.js:4
_uploadFile @ s3.jquery.fine-uploader.min.js:3
_onSubmitCallbackSuccess @ s3.jquery.fine-uploader.min.js:3
(anonymous) @ s3.jquery.fine-uploader.min.js:2
_handleCheckedCallback @ s3.jquery.fine-uploader.min.js:3
_upload @ s3.jquery.fine-uploader.min.js:3
(anonymous) @ s3.jquery.fine-uploader.min.js:3
then @ s3.jquery.fine-uploader.min.js:2
_onValidateCallbackSuccess @ s3.jquery.fine-uploader.min.js:3
(anonymous) @ s3.jquery.fine-uploader.min.js:2
_handleCheckedCallback @ s3.jquery.fine-uploader.min.js:3
_onValidateBatchCallbackSuccess @ s3.jquery.fine-uploader.min.js:3
(anonymous) @ s3.jquery.fine-uploader.min.js:2
_handleCheckedCallback @ s3.jquery.fine-uploader.min.js:3
_prepareItemsForUpload @ s3.jquery.fine-uploader.min.js:3
_prepareItemsForUpload @ s3.jquery.fine-uploader.min.js:7
addFiles @ s3.jquery.fine-uploader.min.js:2
_onInputChange @ s3.jquery.fine-uploader.min.js:3
onChange @ s3.jquery.fine-uploader.min.js:2
(anonymous) @ s3.jquery.fine-uploader.min.js:2

</details>

**Comment by rnicholus** [comment]
https://stackoverflow.com/questions/19327410/fine-uploader-to-s3-bucket-getting-405-method-not-allowed-error

**Comment by guzial** [comment]
i have not  mapped my custom domain name to mine S3
i'm hosting my site also on S3 without own domain

**Comment by rnicholus** [comment]
Then it's possible you have the bucket configured as a website endpoint. Regardless, this is not a fine uploader issue and some googling should present you with a solution.
