### ISSUE TITLE
Typescript definition file for fine-uploader-wrappers

### ISSUE THREAD

**Issue by rakeshmotghare** [FineUploader/fine-uploader#1911]
## Type of issue
- [ ] Bug report
- [ ] Feature request

## Uploader type
- [ ] Traditional

<summary>Feature Request</summary>
#### Fine Uploader version
5.15.0

#### Fine Uploader Wrappers version
1.0.0
#### Browsers where the bug is reproducible
Almost All

#### Operating systems where the bug is reproducible
Windows 10
#### Feature request details 
It will really help and time saver if you provide a typescript definition file during the npm install. 
</details>

<details>
<summary>Feature Request</summary>

 I am getting error while committing my changes to VSTS. Could not find a declaration file for module 'fine-uploader-wrappers'. 'd:\a\1\s\WebUI\node_modules\fine-uploader-wrappers\traditional.js' implicitly has an 'any' type

In my local, I have resolved this issue by creating a .d.ts file for the FineUploaderTraditional I am using from fine uploader wrappers. But when I create a pull request it fails as the build does a npm install which overwrites the contents in fine-uploader-wrappers folder in node_modules folder.
</details>

**Comment by rnicholus** [comment]
I don't have such a file, and this is the wrong repository to ask about fine-uploader-wrappers. PRs welcome at https://github.com/FineUploader/fine-uploader-wrappers.

**Comment by rakeshmotghare** [comment]
Thanks for the reply,
