### ISSUE TITLE
Ability to use without the UI?

### ISSUE THREAD

**Issue by pruhstal** [FineUploader/fine-uploader#1912]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [X] Support request

## Uploader type
- [ ] Traditional
- [X] S3
- [ ] Azure

<details>
<summary>Support Request</summary>

#### Fine Uploader version
5.15.0

#### Question
I'd like to know if it'd be possible to use the core of this library without using the UI (buttons, etc.). All I really need to use this for is chunked uploading and my UI is already built out.

**Comment by rnicholus** [comment]
Yes. Please read the getting started guide at https://docs.fineuploader.com/quickstart/01-getting-started.html.

**Comment by pruhstal** [comment]
@rnicholus thank you very much :)
