### ISSUE TITLE
Can't upload via AWS CloudFront

### ISSUE THREAD

**Issue by nomadus** [FineUploader/fine-uploader#1915]
## Type of issue
Bug report

## Uploader type
S3

I am using a CloudFront distribution with origin set to AWS S3. As S3 does not provide SSL, I had to enable CloudFront. When I try to upload file I have the following error:
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>InvalidRequest</Code><Message>The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.</Message><RequestId>676FC5F89859FFEC</RequestId><HostId>zOXcEk5cmjIR5+eIx9LWO/WVYd32ilSjN/efBHdRRiIYh9XH7E6ijpGw8k9+cetQk6QxwNjAHyk=</HostId></Error>

But the same code works OK if I use direct to S3 uploads.

#### Fine Uploader version
 "fine-uploader": "^5.15.0",
  "react-fine-uploader": "^1.0.3",

#### Browsers where the bug is reproducible
{example: "Firefox" and "IE11"}
Tested with Chrome and Mozilla

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}
Windows 10

#### Exact steps required to reproduce the issue
Standard steps.

I use JAVA server side code, which is available here https://github.com/FineUploader/server-examples/tree/master/java/s3

Uploader code is:
uploader = new FineUploaderS3({
    options: {
      debug: true,
      deleteFile: {
        enabled: true,
        endpoint: `${config.environment.api_baseUrl}/s3`,
        customHeaders: {
          'Authorization': 'Basic ' + btoa(config.WS_USERNAME + ':' + config.WS_PASSWORD)
        }
      },
      request: {
        endpoint: `${config.AWS_S3_END_POINT}`,
        accessKey: `${config.AWS_S3_ACCESS_KEY}`
      },
      signature: {
        endpoint: `${config.environment.api_baseUrl}/s3/signature`,
        version: 4,
        customHeaders: {
          'Authorization': 'Basic ' + btoa(config.WS_USERNAME + ':' + config.WS_PASSWORD),
        }
      },
      uploadSuccess: {
        endpoint: `${config.environment.api_baseUrl}/s3/success`,
        customHeaders: {
          'Authorization': 'Basic ' + btoa(config.WS_USERNAME + ':' + config.WS_PASSWORD)
        }
      },
      validation: {
        sizeLimit: 5000000,
        itemLimit: 10
      },
      callbacks: {
        onComplete: (id, fileName, responseJSON) => {
          const { submittedFiles } = this.state;
          let newFile = {
            name: responseJSON.name,
            s3Bucket: responseJSON.s3Bucket,
            s3Key: responseJSON.s3Key,
            size: this.uploader.methods.getSize(id),
            uuid: responseJSON.uuid
          }

          submittedFiles.push(newFile);
          this.setState({ submittedFiles });
        },
        onDeleteComplete: (id) => {
          const { submittedFiles } = this.state;
          let newUuid = this.uploader.methods.getUuid(id);
          let removeElement = arrayObjectIndexOf(submittedFiles, newUuid, 'uuid');

          submittedFiles.splice(removeElement, 1);
          this.setState({ submittedFiles });
        }
      },
      messages: {
        tooManyItemsError: 'You can only add 10 files'
      },
      chunking: {
        enabled: true
      },
      objectProperties: {
        region: `${config.AWS_S3_REGION}`
      }
    }
  })

**Comment by rnicholus** [comment]
The error suggests you need to use version 4 signatures. This is covered throughout the library documentation. With the current formatting, it's too difficult for me to determine if you have initialized the library correctly

**Comment by nomadus** [comment]
@rnicholus 
Thanks for the response, I shall add formatting, I missed that.
In the signature block I put
`      signature: {
        endpoint: `${config.environment.api_baseUrl}/s3/signature`,
        version: 4,
        customHeaders: {
          'Authorization': 'Basic ' + btoa(config.WS_USERNAME + ':' + config.WS_PASSWORD),
        }
      },`
Also, the code works with no changes OK when I do not use CloudFront and instead directly upload to S3.

**Comment by nomadus** [comment]
@rnicholus Is there some testing environment, where I could reproduce the issue?

**Comment by rnicholus** [comment]
Sounds like a configuration issue with your CloudFront distribution. If you find a specific issue in the fine uploader codebase, let me know and I can reopen this.

**Comment by nomadus** [comment]
This is strange, do you happen to know if there are any recommendations to setup cloudfront? All the settings seem to be default, except the ssl.

**Comment by nomadus** [comment]
I have created an S3 bucket in different region, which supports v2 signature and pointed CF to this, newly created S3. The upload works, so it seems to be not CF settings issue.

**Comment by rnicholus** [comment]
If you find a specific issue in the fine uploader codebase, let me know and I can reopen this.
