### ISSUE TITLE
Core adds ui css to input element created by createInput

### ISSUE THREAD

**Issue by karms** [FineUploader/fine-uploader#1918]
## Type of issue
- Bug report

## Uploader type
- all (probably)

<details>
<summary>
When creating a new input with core, there's css added that does not need to exist.
</summary>

#### Fine Uploader version
all, probably

#### Browsers where the bug is reproducible
all versions 

#### Operating systems where the bug is reproducible
not applicable

#### Exact steps required to reproduce the issue
Implement core. Upload button is huge and lays over content.

#### All relevant Fine Uploader-related code that you have written

Cleanup up example code:

```
 var el  = document.getElementById('someElement');
   var action = 'http://www.google.com';
   var div = jQuery('<div style="display:none"></div>');
   $(el).before(div);

   var uploader = new qq.FineUploaderBasic({
     debug: true,
     button: el,
     element: div,
     multiple: false,
     request: {
       endpoint: action,
     },
   });
```

Input created by fine-uploader core:

`<input qq-button-id="bb386256-d527-4e0d-8dd7-0f56d232013c" title="" multiple="" type="file" name="qqfile" style="position: absolute; right: 0px; top: 0px; font-family: Arial; font-size: 118px; margin: 0px; padding: 0px; cursor: pointer; opacity: 0; height: 100%;">
`

#### Detailed explanation of the problem
 This css is the basis used to style the ui when using the full fine uploaded. This then needs to be overridden when implementing core.

See UploadButton's createInput() at around line 791:

`
            qq(input).css({
                position: "absolute",
                right: 0,
                top: 0,
                fontFamily: "Arial",
                fontSize: qq.ie() && !qq.ie8() ? "3500px" : "118px",
                margin: 0,
                padding: 0,
                cursor: "pointer",
                opacity: 0
            });
            !qq.ie7() && qq(input).css({
                height: "100%"
            });
`

I'd rather see it styled with display:none.
</details>

**Comment by rnicholus** [comment]
Show your code

**Comment by karms** [comment]
Updated.

**Comment by rnicholus** [comment]
If your button is "huge", then you'll need to set the parent element to have `position: relative`.

**Comment by karms** [comment]
The button is has no opacity and is positioned over the element that I add the fine uploader to such that I cannot click on it to start the upload. This is because the file input added by fine uploader _always_ has a style that makes the input wider, taller, and invisible. I'll refer to the code again that's part of core, and I'll include the whole function so there's a better understanding of what is happening:
```

function createInput() {
            var input = document.createElement("input");
            input.setAttribute(qq.UploadButton.BUTTON_ID_ATTR_NAME, buttonId);
            input.setAttribute("title", options.title);
            self.setMultiple(options.multiple, input);
            if (options.folders && qq.supportedFeatures.folderSelection) {
                input.setAttribute("webkitdirectory", "");
            }
            if (options.acceptFiles) {
                input.setAttribute("accept", options.acceptFiles);
            }
            input.setAttribute("type", "file");
            input.setAttribute("name", options.name);
            qq(input).css({
                position: "absolute",
                right: 0,
                top: 0,
                fontFamily: "Arial",
                fontSize: qq.ie() && !qq.ie8() ? "3500px" : "118px",
                margin: 0,
                padding: 0,
                cursor: "pointer",
                opacity: 0
            });
            !qq.ie7() && qq(input).css({
                height: "100%"
            });
            options.element.appendChild(input);
            disposeSupport.attach(input, "change", function() {
                options.onChange(input);
            });
            disposeSupport.attach(input, "mouseover", function() {
                qq(options.element).addClass(options.hoverClass);
            });
            disposeSupport.attach(input, "mouseout", function() {
                qq(options.element).removeClass(options.hoverClass);
            });
            disposeSupport.attach(input, "focus", function() {
                qq(options.element).addClass(options.focusClass);
            });
            disposeSupport.attach(input, "blur", function() {
                qq(options.element).removeClass(options.focusClass);
            });
            return input;
        }
```

I posit that the css that is included, should be changed into simply `qq(input).css({display: none'});` and the css added here to be moved into the version that has the UI included.

**Comment by rnicholus** [comment]
definitely not - the CSS in place is needed to properly style the container, and there are consequences with simply hiding a file input element as you suggested. I've already explained how to address your issue above
