### ISSUE TITLE
Unable to disable camera

### ISSUE THREAD

**Issue by howardengelhart** [FineUploader/fine-uploader#1919]
## Type of issue
- [x] Bug report
- [ ] Feature request
- [ ] Support request

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.15.0  (s3.fine-uploader.min.js)

#### Browsers where the bug is reproducible
Mobile Safari

#### Operating systems where the bug is reproducible
iOS 10.3.3

#### Detailed explanation of the problem
When running a test wage page (Based on your gallery demo) on mobile safari, after clicking on the button to select an image I am alway given the "Take Photo or Video" option, regardless of whether I set the option camera.ios = false, or omit the configuration altogether.

</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

<details>
<summary>Support Request</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Question
{ask your support question here & be as detailed and clear as possible}

#### Related code
{post any code related to your question here}
</details>

**Comment by rnicholus** [comment]
I don't believe this can be disabled anymore.
