### ISSUE TITLE
Fine Uploader 5.14.5 SignatureDoesNotMatch

### ISSUE THREAD

**Issue by msavvy** [FineUploader/fine-uploader#1921]
## Type of issue
- [ ] Bug report
- [ ] Feature request
- [ x ] Support request

## Uploader type
- [ ] Traditional
- [ x ] S3
- [ ] Azure

<summary>Support Request</summary>
Please help me fix SignatureDoesNotMatch 403 on s3 fineuploader, your help is greatly appreciated.

#### Fine Uploader version
5.14.5

#### Question
May i please ask why S3 is returning SignatureDoesNotMatch issue even when the client keys matches and sign policies are validated?

here's my code/configurations

CORS
`<?xml version="1.0" encoding="UTF-8"?>
    <CORSConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/">
    <CORSRule>
        <AllowedOrigin>*</AllowedOrigin>
        <AllowedMethod>GET</AllowedMethod>
        <AllowedMethod>POST</AllowedMethod>
        <AllowedMethod>PUT</AllowedMethod>
        <AllowedMethod>DELETE</AllowedMethod>
        <MaxAgeSeconds>3000</MaxAgeSeconds>
        <ExposeHeader>ETag</ExposeHeader>
        <AllowedHeader>*</AllowedHeader>
    </CORSRule>
    </CORSConfiguration>`

JQuery
`$('#fineuploader').fineUploaderS3({
      debug: true,
      template: 'qq-template-custom',
      objectProperties: {
        region: 'bucket-region',
      },
      request: {
        endpoint: "the-bucket.s3.amazonaws.com",
        accessKey: "THE_ACCESS_KEY"
      },
      signature: {
        endpoint: 'http://localhost/s3-cors/signature',
      },
      uploadSuccess: {
        endpoint: "success.html"
      },
    });`

JSON for signing
`{"expiration":"2017-09-20T04:08:37.038Z","conditions":[{"acl":"private"},{"bucket":"the-bucket"},{"Content-Type":"image/png"},{"success_action_status":"200"},{"key":"2c542003-a547-4a49-acd7-a5e7383d0023.png"},{"x-amz-meta-qqfilename":"fivestar-rating-star.png"}]}`

JSON returned after signing
`{"policy":"eyJleHBpcmF0aW9uIjoiMjAxNy0wOS0yMFQwMzo1NTo0OS4wNThaIiwiY29uZGl0aW9ucyI6W3siYWNsIjoicHJpdmF0ZSJ9LHsiYnVja2V0Ijoic2F2dnktZHJ1cGFsIn0seyJDb250ZW50LVR5cGUiOiJpbWFnZS9wbmcifSx7InN1Y2Nlc3NfYWN0aW9uX3N0YXR1cyI6IjIwMCJ9LHsia2V5IjoiMmM1NDIwMDMtYTU0Ny00YTQ5LWFjZDctYTVlNzM4M2QwMDIzLnBuZyJ9LHsieC1hbXotbWV0YS1xcWZpbGVuYW1lIjoiZml2ZXN0YXItcmF0aW5nLXN0YXIucG5nIn1dfQ==","signature":"p80niWffxFcHNfFK/ogrHBkjcIg="}`

returned by S3
`[Fine Uploader 5.14.5] Received response status 403 with body: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your key and signing method.</Message><AWSAccessKeyId>THE_ACCESS_KEY</AWSAccessKeyId><StringToSign>eyJleHBpcmF0aW9uIjoiMjAxNy0wOS0yMFQwNDowODozNy4wMzhaIiwiY29uZGl0aW9ucyI6W3siYWNsIjoicHJpdmF0ZSJ9LHsiYnVja2V0Ijoic2F2dnktZHJ1cGFsIn0seyJDb250ZW50LVR5cGUiOiJpbWFnZS9wbmcifSx7InN1Y2Nlc3NfYWN0aW9uX3N0YXR1cyI6IjIwMCJ9LHsia2V5IjoiMmM1NDIwMDMtYTU0Ny00YTQ5LWFjZDctYTVlNzM4M2QwMDIzLnBuZyJ9LHsieC1hbXotbWV0YS1xcWZpbGVuYW1lIjoiZml2ZXN0YXItcmF0aW5nLXN0YXIucG5nIn1dfQ==</StringToSign><SignatureProvided>Y6EpvkFYK66mqMQKNtMGVQBmfC8=</SignatureProvided><StringToSignBytes>65 79 4a 6c 65 48 42 70 63 6d 46 30 61 57 39 75 49 6a 6f 69 4d 6a 41 78 4e 79 30 77 4f 53 30 79 4d 46 51 77 4e 44 6f 77 4f 44 6f 7a 4e 79 34 77 4d 7a 68 61 49 69 77 69 59 32 39 75 5a 47 6c 30 61 57 39 75 63 79 49 36 57 33 73 69 59 57 4e 73 49 6a 6f 69 63 48 4a 70 64 6d 46 30 5a 53 4a 39 4c 48 73 69 59 6e 56 6a 61 32 56 30 49 6a 6f 69 63 32 46 32 64 6e 6b 74 5a 48 4a 31 63 47 46 73 49 6e 30 73 65 79 4a 44 62 32 35 30 5a 57 35 30 4c 56 52 35 63 47 55 69 4f 69 4a 70 62 57 46 6e 5a 53 39 77 62 6d 63 69 66 53 78 37 49 6e 4e 31 59 32 4e 6c 63 33 4e 66 59 57 4e 30 61 57 39 75 58 33 4e 30 59 58 52 31 63 79 49 36 49 6a 49 77 4d 43 4a 39 4c 48 73 69 61 32 56 35 49 6a 6f 69 4d 6d 4d 31 4e 44 49 77 4d 44 4d 74 59 54 55 30 4e 79 30 30 59 54 51 35 4c 57 46 6a 5a 44 63 74 59 54 56 6c 4e 7a 4d 34 4d 32 51 77 4d 44 49 7a 4c 6e 42 75 5a 79 4a 39 4c 48 73 69 65 43 31 68 62 58 6f 74 62 57 56 30 59 53 31 78 63 57 5a 70 62 47 56 75 59 57 31 6c 49 6a 6f 69 5a 6d 6c 32 5a 58 4e 30 59 58 49 74 63 6d 46 30 61 57 35 6e 4c 58 4e 30 59 58 49 75 63 47 35 6e 49 6e 31 64 66 51 3d 3d</StringToSignBytes><RequestId>1306BAEE6E3DE7C9</RequestId><HostId>ZbIX72r/fZYhQ+KBabta0aXQUSV9VzeWMz4Gdgyz9h2pyXpEGvI5NLUtqMsDmOZ4o1scHv0kVy0=</HostId></Error>
XHR failed loading: POST "http://the-bucket.s3.amazonaws.com/".`

#### Related code
{post any code related to your question here}
</details>

**Comment by rnicholus** [comment]
Sorry - I simply don't have the time to troubleshoot, and will shortly remove the "support request" option from the issue tracker. If you can locate a specific bug in the library, I will be happy to re-open and address.
