### ISSUE TITLE
[Fine Uploader 5.15.0] Error when attempting to parse xhr response text (Unexpected end of JSON input)

### ISSUE THREAD

**Issue by Ztachi** [FineUploader/fine-uploader#1922]
## Type of issue
- [x] Bug report
- [ ] Feature request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version 
5.14.5

#### Browsers where the bug is reproducible 
chrome 61.0.3163.91

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}

#### Exact steps required to reproduce the issue
upload a video
normal parameters
validation: {
            allowedExtensions: ['mepg', 'vob', 'mp4', 'avi', 'mpg', 'wmv', 'mov', 'mkv'],
            itemLimit: 1,
            sizeLimit: 500 * 1024 * 1024, // 500MB = 500 * 1024 * 1024 bytes
        }
upload fail when upload a video greater than or equal to 500MB.

![image](https://user-images.githubusercontent.com/6995332/30731616-03852802-9fa1-11e7-9f0c-a4b1025bc65e.png)

**Comment by rnicholus** [comment]
This is due to your server sending an invalid response
