### ISSUE TITLE
How to get uploader instance from element?

### ISSUE THREAD

**Issue by Viky-zhang** [FineUploader/fine-uploader#1924]
## Type of issue
[ √ ] Feature request

## Uploader type
[ √ ] Traditional

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Feature Request</summary>

#### Feature request details 
How to get uploader instance from element?
</details>

**Comment by Viky-zhang** [comment]
Found a non-doc way:

Get uploader instance: `let uploader = $('.uploader').data('fineuploader').uploader`

Get uploader upload results: `let uploadResults=uploader.getUploads()`

**Comment by rnicholus** [comment]
...or just don’t use the jquery wrapper since it provides no benefits and will be removed in 6.0

**Comment by Viky-zhang** [comment]
How can I get uploader instance from element with current version ? 
Where is the doc ?

**Comment by rnicholus** [comment]
You can’t, because you don’t need to. Again: don’t use the jquery wrapper.

**Comment by Viky-zhang** [comment]
Even not use the jquery wrapper, I need it, because I have more than one uploader in one page.
I don't want to cache the loader variable.
