### ISSUE TITLE
Not able to upload video using macbook safari

### ISSUE THREAD

**Issue by Saty7476** [FineUploader/fine-uploader#1925]
## Type of issue
- [x] Bug report

## Uploader type
- [x] Traditional

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
 5.5.1

#### Browsers where the bug is reproducible
Safari

#### Operating systems where the bug is reproducible
iOS 9.1.0

#### Exact steps required to reproduce the issue

1. Select 1 files
2. Start upload
3. It will stuck in 100%
4. Sometime stuck in 13%
5. Reproduce 5 out of 10 times

#### All relevant Fine Uploader-related code that you have written
```
$('#fine-uploader-manual-trigger').fineUploader({
    template: 'qq-template-manual-trigger',
    request: {
        endpoint: urls + '/third_party/endpoint.php'
    },
    validation: {
       // acceptFiles: 'video/mp4,video/x-m4v,video/*',
        allowedExtensions: ['mp4', 'mkv', 'mov', 'mpg', 'avi', 'm4v','mpeg','3gp']
    },
    multiple: false,
    ios: true,
    chunking: {
        enabled: true,
        concurrent: {
            enabled: true
        },
 	mandatory: true,
        partSize: 10000000,
        success: {
            endpoint: urls + "third_party/endpoint.php?done=done"
        }
    },
    retry: {
        enableAuto: true
    },
 	debug: true,
    callbacks: {
        onComplete: function (id, fileName, responseJSON) {
            //this._handler.expunge(id);
           // alert("Success: " + fileName);
            // alert(urls + '/video/snapshot/' + responseJSON.uuid);
            if (responseJSON.success) {
                location.href = urls + '/video/snapshot/' + responseJSON.uuid;
            }
        }

    },
    autoUpload: false
})
```

**Comment by rnicholus** [comment]
Sounds like a network issue to me. How is this a library bug, and why are you still using such an old version?

**Comment by rnicholus** [comment]
Also, MacBooks don’t run iOS. Closing until specific issues with the library surface.

**Comment by Saty7476** [comment]
I have tested  this with
![imgpsh_fullsize](https://user-images.githubusercontent.com/32536447/31220257-7029edd0-a9dd-11e7-8721-9801e14588cd.png) attached system info and the problem is same.

Its not a network issue because I am able to upload video using chrome with same system and it is working flawless.

**Comment by rnicholus** [comment]
Why does your report list iOS? Why are you using an incredibly old version of the library?

**Comment by Saty7476** [comment]
Sorry my mistake I'm using 5.15.0 version of library.

**Comment by rnicholus** [comment]
If the default browser on Mac was unable to upload files, your report would not be the first, or the only report. If you can point to a bug in the library, I will consider.
