### ISSUE TITLE
Edit image name is not available after showing a custom error for an image

### ISSUE THREAD

**Issue by beingak** [FineUploader/fine-uploader#1926]
## Type of issue
- [ ] Bug report
- [ ] Feature request

## Uploader type
- [ ] Traditional
- [ ] S3
- [ ] Azure

I am not sure if this is a bug or will be a new feature request, I am using traditional uploader.

In my application, it checks for image name( it contain information related to image). If image information is not correct then it returns an error to correct image name. Edit image name option was available before uploading an image but it doesn't appear after showing error.

Let me know if I have missed something from documentation regarding this.

Thanks for this great plugin.

Regards,
Arun

**Comment by rnicholus** [comment]
Where is your code, and what is an “edit image name”?

**Comment by beingak** [comment]
A screenshot will make much more sense.

Before uploading an image: There is an option to edit image name.
![admin cbd](https://user-images.githubusercontent.com/22137199/31228541-8598ae68-a9fb-11e7-9d4c-5127c2b03fde.png)

After displaying custom error message edit option is no more.
![admin cbd - error](https://user-images.githubusercontent.com/22137199/31228634-c73002c2-a9fb-11e7-840d-f6ef94345ac8.png)

Does this make sense now? I am using Fine Uploader 5.14.1

Thank you.

**Comment by rnicholus** [comment]
You can’t change a file name after the upload has already started

**Comment by beingak** [comment]
This was the case when on uploading server return success as false and custom error message was shown. I am not sure this case is under upload started. If yes then thanks for all your help and for this great plugin. I will look into another way so that user can rename image after error too. If there is something can be changed in core files, please let me know.
