### ISSUE TITLE
quickstart documentation issues w/ getElementById

### ISSUE THREAD

**Issue by headdab** [FineUploader/fine-uploader#1930]
## Type of issue
- [ x] Bug report
- [ ] Feature request

## Uploader type
- [x ] Traditional
- [x ] S3
- [ x] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>
Most getElementById entries in the code examples in 01-getting-started.jmd need 'document.' preprended.

#### Fine Uploader version
{example: 5.5.1}
5.15.0

#### Browsers where the bug is reproducible
{example: "Firefox" and "IE11"}

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}

#### Exact steps required to reproduce the issue
For example:
1. Select 3 files
2. Pause the 2nd file before it completes, but after it has started.
3. Attempt to resume the paused file.

#### All relevant Fine Uploader-related code that you have written
{simply copy and paste the JS used to control Fine Uploader browsers-ide}
{also include your template HTML if related to a UI issue}

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
{simply copy and paste your template markup}

#### Detailed explanation of the problem
{describe the bug here}
</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

**Comment by rnicholus** [comment]
thanks for catching these typos - care to open a PR with a fix?

**Comment by headdab** [comment]
I tried to do that, but I couldn't upload my changes.

**Comment by rnicholus** [comment]
You can edit the file directly in your browser
