### ISSUE TITLE
Feature Request: sha1 sum of a file as a S3 key

### ISSUE THREAD

**Issue by Netherdrake** [FineUploader/fine-uploader#1934]
FineUploader will by default generate an `uuid` for S3 upload file name. 
This allows one to upload exact same file unlimited times.

Would it be possible to have an option in FineUploader calculate sha1 sum of the file before its uploaded to S3, and use the hex hash of the sum as S3 key value?

**Comment by rnicholus** [comment]
No reason for Fine Uploader to do this. Use th API to do it yourself. In particular, read the objectProperties.key configuration docs.

**Comment by Netherdrake** [comment]
Any tips for how to hook into FineUploader and perform the sha1checksum?

**Comment by rnicholus** [comment]
You can get th file using the getFile API method. From there you can do anything you like with the file bytes
