### ISSUE TITLE
Add setUploadSuccessEndpoint for traditional uploader

### ISSUE THREAD

**Issue by JeffreyATW** [FineUploader/fine-uploader#1935]
## Type of issue
Feature request

## Uploader type
Traditional

## Details
I would like to be able to call a `setUploadSuccessEndpoint` method for my traditional uploader, as I often have to call `setEndpoint` to replace a specific file. Since I'm introducing chunking, it would be great to also change where a success call is made.

This method is available for S3 and Azure builds, but I'm not sure why it's not available for the traditional build as it also supports chunked uploads. If this is too tall of a request, recommendations on how to otherwise modify an uploader's success endpoint are welcome.

**Comment by rnicholus** [comment]
Are you talking about the chunking success endpoint? If so, #1917 includes a change to the `chunking.success.endpoint` option that allows you to return a function, which is called with the file ID. You can then return an appropriate chunking success endpoint for each file.

**Comment by JeffreyATW** [comment]
Ooh, that’s great to hear. The bad news in my case is that I’m trying to associate the file with the button that was clicked, and react-fine-uploader’s `<FileInput />` element doesn’t assign a `qqButtonId`, so I’m not sure what I’d do in the success function. But I’ll file a separate issue. Thanks!

**Comment by rnicholus** [comment]
Sounds like something to discuss in the React Fine Uploader issue tracker
