### ISSUE TITLE
Possible to clear file list every time user selects files?

### ISSUE THREAD

**Issue by UweKeim** [FineUploader/fine-uploader#1940]
Using core mode, is it possible to clear the internal file list, every time the user selects files to upload?

Currently I'm binding to the `change` event of the underlying `<input type=file>` but this seems to fire too late.

The default behaviour is add the newly selected files to the internal list of files to upload, but to me it is more intuitive to only select the last uploaded files.

**Comment by rnicholus** [comment]
why do you care about the internal state?

**Comment by rnicholus** [comment]
so, since you ignored the template, which I feel would have answered the question above, I'm going to close this.
