### ISSUE TITLE
Cannot download. githus displaying 404

### ISSUE THREAD

**Issue by amin2009** [FineUploader/fine-uploader#1941]
## Type of issue
- [ ] Bug report
- [ ] Feature request

## Uploader type
- [ ] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Browsers where the bug is reproducible
{example: "Firefox" and "IE11"}

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}

#### Exact steps required to reproduce the issue
For example:
1. Select 3 files
2. Pause the 2nd file before it completes, but after it has started.
3. Attempt to resume the paused file.

#### All relevant Fine Uploader-related code that you have written
{simply copy and paste the JS used to control Fine Uploader browsers-ide}
{also include your template HTML if related to a UI issue}

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
{simply copy and paste your template markup}

#### Detailed explanation of the problem
{describe the bug here}
</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

**Comment by rnicholus** [comment]
just fixed - thanks
