### ISSUE TITLE
On S3 Success Callback

### ISSUE THREAD

**Issue by Netherdrake** [FineUploader/fine-uploader#1942]
When Fine Uploader finishes uploading a file to S3, it calls `/s3/success` endpoint, as set in:

```
var uploader = new qq.s3.FineUploader({
    ...
    uploadSuccess: {
        endpoint: '/s3/success'
    }
    ...
});
```

Is there a way to get a callback on what the server replied on `/s3/success`?

I couldn't find it here:
https://docs.fineuploader.com/branch/master/api/events.html
https://docs.fineuploader.com/branch/master/api/events-s3.html

**Comment by rnicholus** [comment]
Documented at https://docs.fineuploader.com/branch/master/endpoint_handlers/amazon-s3.html
