### ISSUE TITLE
azure file upload error : 405 The resource doesn't support specified Http Verb.

### ISSUE THREAD

**Issue by harisankarbradsol** [FineUploader/fine-uploader#1944]
I tried to upload image to Azure using FineUploader plugin. 

I got this error as response from server:

Request Method:GET
Status Code:405 The resource doesn't support specified Http Verb.

My Signature Endpoint is : 
https://bradsol.blob.core.windows.net/nrl-imagery/nrl-image.jpg?restype=service&comp=properties&sv=2017-04-17&ss=b&srt=sco&sp=rwdlac&se=2017-12-01T00:00:00Z&st=2017-11-01T00:00:00Z&spr=https,http&sig=6xQPKuBohCCm9CJm1cm2uX8kSFM%2BV3CNBTtkxIiadf0%3D

Container Name : nrl-imagery
Blob Name : nrl-image.jpg

My CORS configuration is as follows:

Allowed origins | Allowed methods | Allowed headers | Exposed headers | Max age |  
*                        | GET, PUT               |       *                    |          *                  |     200    |

Can anyone suggest if I am committing any mistake here ?
Your coopearation is highly appreciable. Thanks in Advance.

**Comment by rnicholus** [comment]
How is anyone supposed to help you without seeing any of your code?  I’m also closing this because you completely ignored the template.
