### ISSUE TITLE
Calling reset() method results in duplicate templates with v5.15.3

### ISSUE THREAD

**Issue by kaliatech** [FineUploader/fine-uploader#1945]
## Type of issue
- [X] Bug report
- [ ] Feature request

## Uploader type
- [X] Traditional
- [X] S3
- [X] Azure

<summary>Bug Report</summary>
<details>
#### Fine Uploader version
5.15.3

#### Detailed explanation of the problem
I believe recent changes, released in 5.15.3, introduced a bug related to the core [`reset`](https://docs.fineuploader.com/api/methods.html#reset) method.   Each call to `reset()` results in a new qq template being appended to the container rather then resetting the existing contents.

I believe this issue was introduced in commit "https://github.com/FineUploader/fine-uploader/commit/0bfae7b4beda031707e7339153d5039465b79854" as part of PR #1903.

Previously, each call to template render would replace the contents (via innerHtml). But now, render appends contents as a child and does not clear existing contents.

I'm not very familiar with fine-uploader codebase or reasons for that PR, but if the changes in the PR are valid, then perhaps the core reset method needs to explicitly clear the container contents before calling render.

</details>

**Comment by rnicholus** [comment]
PR please?

**Comment by quasi13** [comment]
I have also observed this in 'Traditional'.  This does not occur in v5.15.0, but it does occur in v5.15.3.  I didn't test the intermediate '.1' release.  In debugging, it seemed as though the .dispose() method wasn't doing what it implied.

**Comment by rnicholus** [comment]
Likely a small regression caused by #1819.

**Comment by edwardsph** [comment]
I am seeing the same issue in 5.15.4 - I reverted to 5.15.2 and the problem disappeared.
