### ISSUE TITLE
Azure FineUploader Issue :: 405 The resource doesn't support specified Http Verb.

### ISSUE THREAD

**Issue by harisankarbradsol** [FineUploader/fine-uploader#1947]
## Type of issue
- [ ] Bug report

## Uploader type
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{5.15.0}

#### Browsers where the bug is reproducible
{"Firefox" and "Chrome"}

#### Operating systems where the bug is reproducible
{ "Windows 10"}

#### Exact steps required to reproduce the issue
1. Select 1 file to upload it to Azure Container.
2. Attempt to upload the selected file.

#### All relevant Fine Uploader-related code that you have written
We have used azure.fine-uploader.min.js 

This is how we tried to instantiate Azure uploader:

var uploader;
      uploader = new qq.azure.FineUploader({
    	  element: this.rugbyFineUploaderSettings.uploaderElement,    	  
    	  debug: true,    	  
          autoUpload: false,
          request: {
              endpoint: 'https://MyAccountName.blob.core.windows.net/MyContainerName/',
          },          
          cors: {
              expected: true,
              sendCredentials: true             
           },          
          signature: {
              endpoint: "https://MyAccountName.blob.core.windows.net/MyContainerName/rugby-image.jpg?restype=service&comp=properties&sv=2017-04-17&ss=b&srt=sco&sp=rwdlac&se=2017-12-01T00:00:00Z&st=2017-11-01T00:00:00Z&spr=https,http&sig=6xQPKuBohCCm9CJm1cm2uX8kSFM%2BV3CNBTtkxIiadf0%3D"
          },          
          uploadSuccess: {
              endpoint: '/nrlflex/success'
          },          
          retry: {
        	enableAuto: false
          },
          deleteFile: {
              enabled: true
          }        
      });

**My CORS configuration is as follows:**
Allowed Origins : *
Allowed methods: Get, Put
Allowed headers: *
Exposed headers: *
Max age: 200

#### Detailed explanation of the problem
This is what I am getting as response:

GET https://bradsol.blob.core.windows.net/nrl-imagery/nrl-image.jpg?restype=service&comp=properties&sv=2017-04-17&ss=b&srt=sco&sp=rwdlac&se=2017-12-01T00:00:00Z&st=2017-11-01T00:00:00Z&spr=https,http&sig=6xQPKuBohCCm9CJm1cm2uX8kSFM%2BV3CNBTtkxIiadf0%3D&bloburi=https%3A%2F%2Fbradsol.blob.core.windows.net%2Fnrl-imagery%2F%2F35f5387d-fa0a-4f53-a8de-95b2d2bd5d30.jpg&_method=PUT&qqtimestamp=1510725973786 405 (The resource doesn't support specified Http Verb.)

Failed to load https://bradsol.blob.core.windows.net/nrl-imagery/nrl-image.jpg?restype=service&comp=properties&sv=2017-04-17&ss=b&srt=sco&sp=rwdlac&se=2017-12-01T00:00:00Z&st=2017-11-01T00:00:00Z&spr=https,http&sig=6xQPKuBohCCm9CJm1cm2uX8kSFM%2BV3CNBTtkxIiadf0%3D&bloburi=https%3A%2F%2Fbradsol.blob.core.windows.net%2Fnrl-imagery%2F%2F35f5387d-fa0a-4f53-a8de-95b2d2bd5d30.jpg&_method=PUT&qqtimestamp=1510725973786: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'. Origin 'http://localhost' is therefore not allowed access. The credentials mode of requests initiated by the XMLHttpRequest is controlled by the withCredentials attribute.

</details>

**Comment by rnicholus** [comment]
>Note: Support requests cannot be accepted due to lack of time.
