### ISSUE TITLE
FineUploader - completely replace instance / dynamically update options

### ISSUE THREAD

**Issue by sreaney89** [FineUploader/fine-uploader#1953]
## Type of issue
- [ ] Bug report
- [X] Feature request

## Uploader type
- [X ] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Feature Request</summary>

#### Feature request details 

Hi, we have a requirement for which we need to dynamically switch between options depending a form drop-down selection. Struggling to figure this out and whether is actually doable. 

What has been tried thus far - calling a function "RenderFineUploader" and have the option replace with a dynamic global. 

For instance - 

allowedExtensions: extensions

Depending on the drop down selection this option needs to be different, so we need to re-render on change of this option, the problem I find is I suspect this creates two instances, I am able to to a reset prior to the render, in which case I get the no files selected (for the prior rendered fineuploader) and also a successfully submitted file for the next render for which the user has been able to add a file and click a submit, I get both successful and this error showing up on single submission.

So its holding a reference to the prior fine uploader, any ideas / solution to this, note I have read the docs, but nothing so specific to this issue, maybe I have just missed it.

</details>

**Comment by rnicholus** [comment]
Options cannot be changed once they are set. If there is a specific one you need to adjust dynamically and it isn't already accounted for in the methods/API documentation, please open up a case w/ the specifics.
