### ISSUE TITLE
clearStoredFiles doesn't work as expected

### ISSUE THREAD

**Issue by zhe1ka** [FineUploader/fine-uploader#1954]
## Type of issue
- [ ] Bug report

## Uploader type
- [ ] Traditional

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.15.4

#### Browsers where the bug is reproducible
Google chrome

#### Operating systems where the bug is reproducible
iOS 10.13.2

#### All relevant Fine Uploader-related code that you have written
        new qq.FineUploader({
            element: document.getElementById('template-manual-trigger'),
            template: 'qq-template-manual-trigger',
            multiple: false,
            autoUpload: false,
            validation: {
                allowedExtensions: [ 'jpeg', 'jpg', 'png' ],
                itemLimit: 1
            },
            callbacks: {
                onValidateBatch() {
                    if (this._netUploadedOrQueued > 1) {
                        this.clearStoredFiles();
                        this._netUploadedOrQueued = 1;
                    }
                }
           }
      });

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
Couldn't put HTML here
![image](https://user-images.githubusercontent.com/6460571/34157428-24850e78-e4ca-11e7-9506-02b411beee4e.png)

#### Detailed explanation of the problem
I have " itemLimit: 1". So I need to clean the previous image if I try to upload one more (a simple upload box for an avatar). I use the method "clearStoredFiles" and the image is reseted, it's ok. But when I try to upload one more I've got an error box with the text "Too many items (2) would be uploaded. Item limit is 1.". I decided to rewrite a private field "_netUploadedOrQueued" manually and it works correctly. But it seems like a hack than a right way to resolve the problem.
</details>

**Comment by rnicholus** [comment]
> So I need to clean the previous image if I try to upload one more

You cannot do this using `clearStoredFiles` - that clears out files that have not yet been uploaded, to be used only when `autoUpload` is set to `false`. You can `reset` though.
