### ISSUE TITLE
unnecessary parent div in template

### ISSUE THREAD

**Issue by MrSpoocy** [FineUploader/fine-uploader#1959]
## Type of issue
- [X] Bug report
- [ ] Feature request

## Uploader type
- [X] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.15.5

#### Browsers where the bug is reproducible
Chrome 63.x

#### Operating systems where the bug is reproducible
iOS Sierra 10.12.6

#### Detailed explanation of the problem
When I make a simple test, based on the documentation (qq-tempate row based & traditional upload)

He render all the markdown in <script type="text/template" id="qq-template"> but add a unnecessary div directly under there id-container.

At the end looks like
```
<div id="qq-template>
	<div> <-- unnecessary -->
		<div class="qq-uploader-selector qq-uploader" qq-drop-area-text="Drop files here"> ... </div>
	</div>
</div>
```
</details>

**Comment by rnicholus** [comment]
Closing as you haven’t shown your code. Will consider reopening if that is fixed.
