### ISSUE TITLE
Example of Minio integration

### ISSUE THREAD

**Issue by dels07** [FineUploader/fine-uploader#1960]
## Type of issue
- [ ] Bug report
- [x] Feature request

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

<details>
<summary>Feature Request</summary>
Currently I'm having trouble with setting up FineUploader to work with Minio, since all the documentation available only applied to S3. Currently I use controller example from this repo:
https://github.com/FineUploader/php-laravel-s3-server

The error I'm receiving in chrome dev console:
```
...
[Fine Uploader 5.15.5] Sending simple upload request for 0
[Fine Uploader 5.15.5] Submitting S3 signature request for 0
[Fine Uploader 5.15.5] Sending POST request for 0
s3/endpoint Failed to load resource: the server responded with a status of 419 (unknown status)
[Fine Uploader 5.15.5] POST request for 0 has failed - response code 419
[Fine Uploader 5.15.5] Response does not include the base64 encoded policy!
[Fine Uploader 5.15.5] Policy signing failed.  Response does not include the base64 encoded policy!
```

Likely trouble with policy signing as the code returning error on **line 73** on this file:
https://github.com/FineUploader/php-laravel-s3-server/blob/master/ExampleController.php

Can anyone give me an example of working Minio integration with FineUploader?

Thanks
</details>

**Comment by rnicholus** [comment]
Sorry - the issue tracker is only for feature requests and bug reports.
