### ISSUE TITLE
xhr returns response code 0 when uploading some files

### ISSUE THREAD

**Issue by asadadams** [FineUploader/fine-uploader#1963]
## Type of issue
- [x ] Bug report
- [ ] Feature request

## Uploader type
- [x ] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
Fine Uploader 5.15.4

#### Browsers where the bug is reproducible
Chrome

#### Operating systems where the bug is reproducible
Windows 10

#### Exact steps required to reproduce the issue
1. Select one file and upload

#### All relevant Fine Uploader-related code that you have written
{simply copy and paste the JS used to control Fine Uploader browsers-ide}
{also include your template HTML if related to a UI issue}

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
Using Fine Uploader UI

#### Detailed explanation of the problem
Upload works perfect locally but on the server returns xhr response code 0  and
[Fine Uploader 5.15.4] xhr - server response received for 1
[Fine Uploader 5.15.4] responseText = 
[Fine Uploader 5.15.4] Received response status 0 with body

in the console

**Comment by rnicholus** [comment]
Sounds like a server or networking issue. No time to offer tech support, sorry.
