### ISSUE TITLE
Function based endpoint URIs

### ISSUE THREAD

**Issue by fairbairn** [FineUploader/fine-uploader#1967]
## Type of issue
- [ ] Bug report
- [X] Feature request

## Uploader type
- [X] Traditional
- [X] S3
- [X] Azure

Is there any way / upcoming support for the server-side endpoints to be functions / promises instead of hard-coded strings?

Our JS -> Server REST has a pretty robust API with real-time nonces and signature verifications built in, we'd like to generate the full endpoint URL at the time it is needed through our functions and return that back, rather than hard-coding a string in the qq object.

Is this possible today?

Again, we're talking about the communication between our JS (and your JS) to our back-end server for signature verification and other server-side endpoints.  We need these URLs to be more robust.

**Comment by rnicholus** [comment]
Please look at #1939. I've added support to accommodate a workflow where the endpoint for each upload/chunk is only known at runtime via some ajax call or other async process.
