### ISSUE TITLE
Demo site is giving an error.

### ISSUE THREAD

**Issue by BrianTolman** [FineUploader/fine-uploader#1970]
## Type of issue
- [X ] Bug report
- [ ] Feature request

## Uploader type
- [ ] Traditional
- [X ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

The S3 demo is not working.  And giving the same error I am getting.
https://fineuploader.com/demos.html

#### Fine Uploader version
Whatever is on the demo

#### Browsers where the bug is reproducible
{example: "Firefox" and "IE11"} All

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"} All

#### Exact steps required to reproduce the issue

1. Select a file.
2. Drag and drop it.
3. Wait for error

#### Detailed explanation of the problem
The S3 demo is not working.  And giving the same error I am getting on my server.

https://fineuploader.com/demos.html
</details>

**Comment by rnicholus** [comment]
This is expected. I stopped paying the AWS bills out of my own pocket a while ago, and i don't intend to pay them going forward. So until someone volunteers to pay these bills (~$40/month) the S3 demo will continue to be broken.

**Comment by BrianTolman** [comment]
ok - thanks.  I guess this issue is closed?

**Comment by rnicholus** [comment]
well, yes and no. I'm hoping somehow i'll get someone to sponsor the project such that the relatively small AWS bills can be paid again. I do feel bad not paying them myself, but i've put countless hours into this project as it is, and i'd rather not drop any more actual money into this project myself.
