### ISSUE TITLE
After returning false for invalid file inside of onvalidate function, it is showing invalid files during next time upload in the queue.

### ISSUE THREAD

**Issue by rkbansal** [FineUploader/fine-uploader#1972]
## Type of issue
- [x] Bug report
- [ ] Feature request

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Browsers where the bug is reproducible
{example: "Firefox" and "IE11"}

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}

#### Exact steps required to reproduce the issue
For example:
1. Select 3 files
2. Pause the 2nd file before it completes, but after it has started.
3. Attempt to resume the paused file.

#### All relevant Fine Uploader-related code that you have written
{simply copy and paste the JS used to control Fine Uploader browsers-ide}
{also include your template HTML if related to a UI issue}

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
{simply copy and paste your template markup}

#### Detailed explanation of the problem
{describe the bug here}
</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

**Comment by rnicholus** [comment]
I’m sorry, but I cannot assist without a properly completed bug report

**Comment by rkbansal** [comment]
**Fine Uploader version**
5.2.1

**Browsers where the bug is reproducible**
Google chrome

**Operating systems where the bug is reproducible**
Windows 10

**Exact steps required to reproduce the issue**

1. Select any number of files only with invalid filename (invalid file name is any file which contains any of these ,/\|'";: characters in my case)
2. After that, upload any valid filename.
3. You can see the fineuploader is trying to upload all the files including previous invalid files.

**Your Fine Uploader template markup**
We are using our Own UI. And i think there is no need of UI in this case, if yes, then please let me know.

**Detailed explanation of the problem**
This is my onValidate function
`onValidate: function(file){
			if(file && file.name)
			{
				var pattern = /[,/\|'";:]/ ;
				return !pattern.test(file.name);
			}}`

**I just want to remove the invalid files from the queue which is not happening by default when i am returning false from onValidate function. Any kind help will be fine.**

**Comment by rkbansal** [comment]
Okay! I got it. It is maintaining the status of each file, so I can filter out files by status and show the files with status "submitting" in the UI.
