### ISSUE TITLE
I can not upload GIF to S3 via FineUploader

### ISSUE THREAD

**Issue by wann2** [FineUploader/fine-uploader#1975]
## Type of issue
[Fine Uploader 5.15.5] EXIF header parse failed: 'Not a valid JPEG!' 
[Fine Uploader 5.15.5] EXIF data could not be parsed (Not a valid JPEG!).  Assuming orientation = 1.

## Uploader type
S3

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.15.5

#### Browsers where the bug is reproducible
Chrome

#### Operating systems where the bug is reproducible
MacBook Pro

#### All relevant Fine Uploader-related code that you have written
$('#fineuploaderS3_img').fineUploaderS3({
    template: 'qq-template-s3',
    request: {
        endpoint: T.aws.s3ImageHostNm,
        accessKey: T.aws.awsUserAccessKey
    },
    signature: { endpoint: '/cp/s3handler_file_upload' },
    uploadSuccess: { endpoint: '/cp/advt/advt_image_file_upload_success' },
    objectProperties: {
        key: function (fileId) { 
            var filename = $('#fineuploaderS3_img').fineUploader('getName', fileId);
            var uuid = $('#fineuploaderS3_img').fineUploader('getUuid', fileId);
            ext = filename.substr(filename.lastIndexOf('.') + 1); 
            return 'advt/'+$('#advtId').val()+'/'+$('#advtId').val()+'.'+ext;
        }
    },
    validation: {
        allowedExtensions: ['png','gif','jpg','jpeg'],
        // acceptFiles: "video/mp4",
        sizeLimit: 10*1000*1000,
        itemLimit: 1
    },
    cors: { expected: true },
    retry: { enableAuto: true  /* defaults to false */ },
    chunking: { enabled: true },
    resume: { enabled: true },
    debug: true,
    callbacks: {
        onError: function(id, name, errorReason, xhrOrXdr) {
            console.log(qq.format("Error on file number {} - {}.  Reason: {}", id, name, errorReason));
        },
        onComplete: function(id, name, response) {
            if (response.success) {
                console.log(id);
                console.log(name);
                console.log(response);
            }
        }
    }
});

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
    <link rel="stylesheet" href="/jsutil/fine-uploader.s3/fine-uploader-gallery.css">
    <script src="/jsutil/jquery/jquery.min.js"></script>
    <script src="/jsutil/fine-uploader.s3/s3.jquery.fine-uploader.js"></script>

#### Detailed explanation of the problem
    I tried a GIF file to S3, but It always fails.

</details>

**Comment by rnicholus** [comment]
I see no failure here. All that failed was EXIF header parsing, which is expected.

**Comment by wann2** [comment]
Could you show me how to change the config so that I can have success about Gif file?
(so that EXIF header parsing can accept GIF)

**Comment by rnicholus** [comment]
there is no exif header in a gif file

**Comment by wann2** [comment]
How can I add exif header in gif?
Do you have any guide?

**Comment by rnicholus** [comment]
it's not clear you understand what an EXIF header is - you can start reading here: https://en.wikipedia.org/wiki/Exif
