### ISSUE TITLE
Reported directory path (qqpath) is wrong if file name occurs in one of the parent directory names

### ISSUE THREAD

**Issue by ogvolkov** [FineUploader/fine-uploader#1976]
## Type of issue
- [x] Bug report
- [ ] Feature request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.15.6

#### Browsers where the bug is reproducible
Chrome 64.0.3282.167, FF 58.0.2, Edge 41.16299.248.0

#### Operating systems where the bug is reproducible
Windows 10

#### Exact steps required to reproduce the issue
1. Setup Fine Uploader UI with dragAndDrop.reportDirectoryPaths set to true.
2. Prepare a directory with files on the local filesystem where one of the file names appears in a directory name. For example, create directory named "data" containing a file named "data".
3. Drop the directory onto Fine Uploader.
4. Observe that qqpath is incorrect or missing from the data passed to the backend. In the data/data example, qqpath parameter will not be present in the request altogether.

#### All relevant Fine Uploader-related code that you have written
```
var uploader = new qq.FineUploader({
            element: document.getElementById("uploader"),
            multiple: true,
             dragAndDrop: {
                reportDirectoryPaths: true
            }
        })

```
</details>

**Comment by rnicholus** [comment]
what does "incorrect" mean? Looking at the code, i'm not seeing any evidence of an issue. Can you provide more concrete details?

**Comment by rnicholus** [comment]
If you can update the issue with all of your Fine Uploader config code _and_ the full request/response headers+payload as well as any console.log statements, that would be helpful.

**Comment by ogvolkov** [comment]
There is a pull request which fixes it already.

But to clarify, if I upload a folder "data" which contains a folder "sub" which contains a file "ub", the resulting payload is
------WebKitFormBoundaryxwMePIf55gNLuxW1
Content-Disposition: form-data; name="qqpath"

data/s
------WebKitFormBoundaryxwMePIf55gNLuxW1
Content-Disposition: form-data; name="qquuid"

8bbf2d77-7f76-457d-97f4-a327afb673fa
------WebKitFormBoundaryxwMePIf55gNLuxW1
Content-Disposition: form-data; name="qqfilename"

ub
 etc.

The reason is the code tries to remove the file name from the path by find a first occurrence via indexOf, so "/data/sub/ub" without "ub" becomes "/data/s", which clearly incorrect
