### ISSUE TITLE
Broken images while scaling with Firefox 58

### ISSUE THREAD

**Issue by shikazu** [FineUploader/fine-uploader#1979]
## Type of issue
- [x] Bug report
- [ ] Feature request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.15.17

#### Browsers where the bug is reproducible
Firefox 58

#### Operating systems where the bug is reproducible
Mac OS X 10.13.3

#### Exact steps required to reproduce the issue
1. Select Many images
2. Wait for the gallery template to show all thumbnails

#### All relevant Fine Uploader-related code that you have written
https://jsfiddle.net/judm9dhh/11/

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
https://jsfiddle.net/judm9dhh/11/

#### Detailed explanation of the problem
I experienced a bug which is not reproducible all the time, because i haven't found the actual reason why this happens. When a lot of images are added, the chance is bigger, that the problem is visible.

The scaled image is broken sometimes, where as the start of the thumbnail is shown normally but then turns white till the end. 

Example:
https://imgur.com/a/tfFG1

We turned scaling off and this doesn't happen anymore. Also it does only happen with firefox, we also tested with chrome and safari but these don't show these errors. The error first came up in January, but we weren't able to track it down until recently. 

Also we tried to replace the scaling methods using pica, but this also had broken images. So if pica and fine-uploader aren't using the same methods, it has to do with recent changes on firefox. 

Maybe there is something like a memory limit per tab or so, which leads to this behavior. Also when uploading the files to a server with concurrent connections the error happens more often (2 is enough to test). 

We can't turn off scaling, because our customers are usually uploading 200+ images and therefore it would take hours to upload. Hope you guys have an idea what i can do now. 

Will also try with firefox on windows right now and report back if it happens there also.

Thanks in advance!

Edit: tried with 2600 images from windows 10 with firefox 58.0.2 and had 12 broken pictures.

</details>

**Comment by nicompte** [comment]
Hi, it seems they had the same issue on https://github.com/nodeca/pica/issues/130. There is now a reported bug on firefox: https://bugzilla.mozilla.org/show_bug.cgi?id=1450302.

**Comment by rnicholus** [comment]
Thanks for looking into this @nicompte. I was unable to find the time to do that myself. I’ll close this as a 3rd party bug.
