### ISSUE TITLE
Compress on upload

### ISSUE THREAD

**Issue by onhate** [FineUploader/fine-uploader#198]
Hello all...

At first, I would like to thank you for this great js!!

And at second.... I would like to know if there is a way to compress the file using gzip, I know that many browsers (almost all) implements gzip...

**Comment by siddo420** [comment]
How about using something like https://stuk.github.io/jszip/ now? 

Can this be integrated soon?

**Comment by rnicholus** [comment]
There will definitely not be any such library integrated into Fine Uploader as part of the core library. Zip compression is not appropriate for many files, such as images and videos (to name a few). But of course you are free to compress files however you see fit and then submit them to Fine Uploader.
