### ISSUE TITLE
Using chunking success params function removes qquuid from the request body

### ISSUE THREAD

**Issue by vishal-akg** [FineUploader/fine-uploader#1980]
## I can't send parameters with the chunk successful upoad
- [ ] Bug report

## Uploader type
- [ ] Traditional

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Browsers where the bug is reproducible
{example: "Firefox" and "IE11"}

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}

#### Exact steps required to reproduce the issue
For example:
1. Select 3 files
2. Pause the 2nd file before it completes, but after it has started.
3. Attempt to resume the paused file.

#### All relevant Fine Uploader-related code that you have written
{simply copy and paste the JS used to control Fine Uploader browsers-ide}
{also include your template HTML if related to a UI issue}

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
{simply copy and paste your template markup}

#### Detailed explanation of the problem
{describe the bug here}
</details>
let info = {} ;
let content_id = 'b67020e9-6ad9-4b20-a514-65c9575ae5f8';

			var uploader = new qq.FineUploaderBasic({
				debug:true,
				retry: {
					enableAuto: true
				},
				request: {
					endpoint:'/contents/uploadAudio/',
					params:{
						content_id: content_id,
						filename:'audio'
					},
				},
				callbacks: {
					onAutoRetry: function(id, name, attemptNumber) {

					},
					onTotalProgress:function(totalUploadedBytes, totalBytes)
					{
						console.log(totalUploadedBytes/totalBytes * 100);
					},
					onComplete:function(id, name, responseJSON, xhr) {
						info.content_id = this.getUuid(id);
					}
				},
				chunking:{
					enabled:true,
					success:{
						params:function(id)
						{
							console.log(id);
							
							return {
								type:'audio',
								qquuid:content_id
							};
						},
						endpoint:'/contents/combineAudio/'
					}
				},
				resume:{
					enabled:true	
				},
				validation:{
					allowedExtensions:["flv", "mp4"]
				},
				element: document.getElementById("uploader"),
				button:document.getElementById("file_input")
			});

firstly the way request parameters can be passed is very inconsistent, in request params options one has to pass the json object while in chunking success params a callback function is to be provided.
This callback function has certain bugs 
1 - value passed to callback function is zero , what does this indicated.
2- by using this function requested parameters are not appended instead overwrites previous parameters
3 - i can't find a way to get the qquuid inside this function, this.getUuid(id) doesn't work  
<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

**Comment by rnicholus** [comment]
Sorry, I can’t understand most of what you wrote in your question. Please try to focus on one specific issue and explain with code examples.

**Comment by vishal-akg** [comment]
Okay just simply tell me how to pass parameters in chunking success params i.e when all the chunks has been successfully uploaded.
as per documentation [https://docs.fineuploader.com/branch/master/api/options.html#chunking.success.params](url)
can be used.

**Comment by rnicholus** [comment]
Set a function that returns the params when called. Since Fine Uploader will pass a file ID to your function,the params can be file specific, or not.

**Comment by vishal-akg** [comment]
By doing so i have to send qquuid too, which i am not able to get, in any possible way.

**Comment by rnicholus** [comment]
Use the getUuid method

**Comment by vishal-akg** [comment]
this object inside function callback doesn't have getUuid method.

**Comment by rnicholus** [comment]
It doesn’t need to. 

uploader.getUuid(fileId)

**Comment by vishal-akg** [comment]
ok thanks.
But the way parameters are passed in request.params options is json object while in chunking.success.params in callback function. 
In request params i don't have to pass qquuid and other parameters but in case of chunking success params i have to pass each parameters explicitly.

**Comment by rnicholus** [comment]
I’m not seeing a question there. The bottom line is: pass whatever params you want (or none) as I’ve described.
