### ISSUE TITLE
Determine if scaled image is oriented

### ISSUE THREAD

**Issue by jayasurya101010** [FineUploader/fine-uploader#1981]
## Type of issue
- [ ] Bug report
- [x] Feature request

## Uploader type
- [ ] Traditional
- [ ] S3
- [x] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Feature Request</summary>

#### Feature request details 
It would be really helpful if we have an API to find out if a scaled image is oriented.  We can determine this using other third party libraries but since fineuploader is already fetching the orientation data from EXIF, we believe using additional libraries would cause unnecessary overhead.

Thanks
</details>

**Comment by rnicholus** [comment]
Fine Uploader will orient any image with EXIF data during scaling by default, so there should be no need to use another library to do this.
