### ISSUE TITLE
Bug Fix 5.16.0 iOS image preview

### ISSUE THREAD

**Issue by larrycosta** [FineUploader/fine-uploader#1982]
## Type of issue
- `Bug report`

## Uploader type
- `Traditional`

#### Remove line 6519 and 6520
`this._handler.cancelAll();`
`this._clearList();`

#### Fine Uploader version
`5.16.0`

#### Browsers where the bug is reproducible
`Chrome`

#### Operating systems where the bug is reproducible
`All iOS`

#### Exact steps required to reproduce the issue
```
1. camera: { ios: true }
2. send one image 
3. send image again
```

#### Detailed explanation of the problem

> The image is replaced and will always have a single thumbnail when using iOS, to solve this problem it is necessary to remove this._handler.cancelAll(); and this._clearList();

**Comment by rnicholus** [comment]
Sorry, I don’t really understand the problem here, and it isn’t realistic to make changes based off of line numbers in combined JavaScript files generated by the build process. Please open a PR with any required changes. Thanks.
