### ISSUE TITLE
chunking success endpoint is never requested when chunking is enabled and chunk size is greater than filesize itself

### ISSUE THREAD

**Issue by vishal-akg** [FineUploader/fine-uploader#1991]
## Type of issue
request is never sent to chunking success endpoint when chunking is enabled and file size is less than chunk size.
By default chuck size is 2MB and if i set chunking enabled while uploading a file is less than 2MB then request is sent to request endpoint but never to chunking success endpoint. 

## Uploader type
- Traditional

#### Exact steps required to reproduce the issue
For example:
1. create fineUploaderBasic object with chunking enabled
2. upload a file less than 2MB
3. Check network tab of browser developer console , request is never sent to chunking success endpoint.

**Comment by rnicholus** [comment]
This is expected as the upload is not actually chunked. To always chunk, set the chunking.mandatory option - https://docs.fineuploader.com/branch/master/api/options.html#chunking.mandatory
