### ISSUE TITLE
Fine Uploader not working in React App 

### ISSUE THREAD

**Issue by YashKharel19** [FineUploader/fine-uploader#1992]
## Type of issue
- [x] Bug report

## Uploader type
- [x] Traditional
BUG Report 

#### Fine Uploader version
5.16.0

#### Browsers where the bug is reproducible
Chromium
Version 65.0.3325.181 (Official Build) Built on Ubuntu

#### Operating systems where the bug is reproducible
running on Ubuntu 16.04 (64-bit)

#### Exact steps required to reproduce the issue
1. npm install all the dependencies required. 
2. write code according to documentation.
3 run npm 
#### All relevant Fine Uploader-related code that you have written
package.json
{
  "name": "fileuploader",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "fine-uploader": "^5.16.0",
    "fine-uploader-wrappers": "^1.0.1",
    "object-assign": "^4.1.1",
    "promise-a-plus": "^0.7.0",
    "react": "^16.3.0",
    "react-dom": "^16.3.0",
    "react-fine-uploader": "^1.0.9",
    "react-resumable-js": "^1.1.24",
    "react-scripts": "1.1.1",
    "react-transition-group": "^2.3.0",
    "tus-js-client": "^1.4.5"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test --env=jsdom",
    "eject": "react-scripts eject"
  }
}

fineUploader.js

import React, { Component } from 'react';
import FineUploaderTraditional from 'fine-uploader-wrappers';
import Gallery from 'react-fine-uploader';

// ...or load this specific CSS file using a <link> tag in your document
import 'react-fine-uploader/gallery/gallery.css';

const uploader = new FineUploaderTraditional({
    options: {
        chunking: {
            enabled: true
        },
        deleteFile: {
            enabled: true,
            endpoint: '/uploads'
        },
        request: {
            endpoint: '/uploads'
        },
        retry: {
            enableAuto: true
        }
    }
})

class UploadComponent extends Component {
    render() {
        return (
            <Gallery uploader={ uploader } />
        )
    }
}

export default UploadComponent;

app.js

import React, { Component } from 'react';

import UploadComponent from './fineuplader';
// import ExampleForm from './resumable';

export default class App extends Component {
  render() {
    return (
      <div>
        <UploadComponent />
      </div>
    );
  }
}

#### Detailed explanation of the problem
{describe the bug here}
</details>

Hi,
I am new to frontEnd Development.
I am trying  to use fine uploader in React App and i have installed the  A+/Promise as it asked to install itself for the dependencies and also according to the react fine uploader documentation  i used the same code,but when i run my react app it says compiled successfully but in the browser side it shows two error  with same message 

"Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports."

**Comment by rnicholus** [comment]
sounds related to https://github.com/FineUploader/react-fine-uploader/issues/166
