### ISSUE TITLE
Response headers available in callback

### ISSUE THREAD

**Issue by DonGiulio** [FineUploader/fine-uploader#1997]
## Type of issue
- [x] Feature request

## Uploader type
- [x] Traditional

## Details
Hello, 

I found that in the `response` object of the `onComplete` callback, contains only the raw response json, i.e. headers are missing. I think it makes sense to have the headers available in there, so that they can be used for any purpose. 

In my app I'm using [redux-token-auth](https://github.com/kylecorbelli/redux-token-auth) to authenticate users, I'm having troubles mixing `redux-token-auth` and `fine-uploader` (via `react-fine-uploader`), in order enable only authenticated users to upload images. 

I opened [this issue](https://github.com/kylecorbelli/redux-token-auth/issues/34) as well.

I managed to perform an image upload by configuring the uploader with: 

      request: {
        endpoint: backend.createImage,
        customHeaders: {
          "access-token": localStorage.getItem("access-token"),
          "token-type": localStorage.getItem("token-type"),
          client: localStorage.getItem("client"),
          uid: localStorage.getItem("uid")
        }
      },

token auth is designed so that at each request it generates a new token, that needs to be saved in the client, so that it can be used for the next time. I would need to be able to access the response headers in the callback in order to save them back. 

      onComplete: (id, name, response) => {
      if (response.success) {
        reduxTokenAuth.updateToken({
          "access-token": response.headers["access-token"],
          "token-type": response.headers["token-type"],
          client: response.headers["client"],
          uid: response.headers["uid"]
        });
        console.log("UPLOAD SUCCESS: response: " + JSON.stringify(response, 0, 2));
      } else { [..] }
    };

**Comment by rnicholus** [comment]
The XHR instance is passed to your callback as a fourth parameter. You can obtain the headers from this. See the docs for more details.
