### ISSUE TITLE
[bug] Memory leak in special scenes with multiple mode

### ISSUE THREAD

**Issue by sukonzer** [FineUploader/fine-uploader#2000]
## Type of issue
- [ ] Bug report

## Uploader type
- [ ] Traditional

### Note: Support requests cannot be accepted due to lack of time.

<summary>Bug Report</summary>

#### Fine Uploader version
{5.16.2}

#### Browsers where the bug is reproducible
{chrome 66.0.3359.117}

#### Operating systems where the bug is reproducible
{windows 10 x64}

#### Exact steps required to reproduce the issue
For example:
1. Click "select file" button.
2. drag file into dropzone area from the opened window.

#### All relevant Fine Uploader-related code that you have written
All demo have this issue

#### Detailed explanation of the problem
According to the reproduce steps with twice or more, the browser is crashed.

**Comment by rnicholus** [comment]
what is the issue exactly?

**Comment by sukonzer** [comment]
@rnicholus 
Reproduce steps:
1. Click "select file" button.
2. Drag file into dropzone area from the pop-up window.
Please repeat several times above operation
High reproduce rate

**Comment by rnicholus** [comment]
You are clicking select file and then dragging a file into the dropzone? Sorry, but that doesn’t make any sense to me. Why exactly would you do that?
