### ISSUE TITLE
qqfile data missing on original file

### ISSUE THREAD

**Issue by webdevnerdstuff** [FineUploader/fine-uploader#2002]
## Type of issue
Bug report

## Uploader type
Traditional

## Summary
qqfile data missing on original file upload

#### Fine Uploader version
5.16.0
5.16.2

#### Browsers where the bug is reproducible
Chrome Version 66.0.3359.117 (Official Build) (64-bit)

#### Operating systems where the bug is reproducible
Win7

#### Exact steps required to reproduce the issue
1. Select an image to upload (in my case it uploads automatically)

#### All relevant Fine Uploader-related code that you have written
**Front-End**

      var uploader = new qq.FineUploader({
             dropZoneElements: [document.getElementById('drop-zone-area')],
             multiple: false,
             debug: true,
             element: document.getElementById('uploader'),
             request: {
                   endpoint: '/ajax/media/upload',
             },
            scaling: {
                   defaultQuality: 100,
                  hideScaled: true,
                   sendOriginal: true,
                  includeExif: true,
                  sizes: [
                        {
                              name: 'sm',
                              maxSize: 100,
                        },
                        {
                             name: 'md',
                            maxSize: 500,
                       },
                       {
                             name: 'lg',
                             maxSize: 1000,
                        },
                ],
           },
          validation: {
                 allowedExtensions: [
                       'gif', 'jpeg', 'jpg', 'png', 'csv', 'docx', 'pdf', 'pptx', 'txt', 'xlsx', 'zip',
                 ],
                 itemLimit: 4,
                 sizeLimit: 1000000000,
          },
    });

**Backend:**

Fails on `while ( $buff = fread( $in, 4096 ) )`

	public function upload()
	{
		$post 		= $this->input->post();
		$file_data 	= isset( $_FILES ) ? $_FILES : null;

		$year = date( 'Y' );
		$month = date( 'm' );

		$path 		= exec( 'pwd' );
		$target_dir = str_replace( 'web', 'uploads', $path ) . '/temp/';

		// Remove old files //
		$cleanup_target_dir = true;

		// Temp file age in seconds //
		$max_file_age = 5 * 0;

		// Get a file name //
		if ( isset( $post['qqfilename'] ) )
		{
			$file_name = $post['qqfilename'];
		}
		elseif ( !empty( $_FILES ) )
		{
			$file_name = $_FILES['qqfilename']['name'];
		}
		else
		{
			$file_name = uniqid('file_');
		}

		$file_name 		= str_replace( ')', '', preg_replace( '/( \()/', '-', $file_name ) );
		$file_path 		= $target_dir . $file_name;

		// Chunking might be enabled
		$chunk 	= isset( $_REQUEST['chunk'] ) 	? intval( $_REQUEST['chunk'] ) 	: 0;
		$chunks = isset( $_REQUEST['chunks'] ) 	? intval( $_REQUEST['chunks'] ) : 0;

		// Remove old temp files
		if ( $cleanup_target_dir )
		{
			if ( !is_dir( $target_dir ) || !$dir = opendir( $target_dir ) )
			{
				$return = array(
					'code'		=> '101',
					'status'	=> 'error',
					'message'	=> "Failed to open temp directory."
				);
			}

			while ( ( $file = readdir( $dir ) ) !== false )
			{
				$temp_file_path = $target_dir . $file;

				// If temp file is current file proceed to the next //
				if ( $temp_file_path == "{$file_path}.part" ) {
					continue;
				}

				// Remove temp file if it is older than the max age and is not the current file //
				if ( preg_match( '/\.part$/', $file ) && ( filemtime( $temp_file_path ) < time() - $max_file_age ) )
				{
					@unlink($temp_file_path);
				}
			}

			closedir( $dir );
		}

		// Open temp file //
		if ( !$out = @fopen("{$file_path}.part", $chunks ? "ab" : "wb" )) {
			$return = array(
				'code'		=> '102',
				'status'	=> 'error',
				'message'	=> "Failed to open output stream."
			);
		}

		if ( !empty( $_FILES ) )
		{
			if ( $_FILES['qqfile']['error'] || !is_uploaded_file( $_FILES['qqfile']['tmp_name'] ) )
			{
				$return = array(
					'code'		=> '103',
					'status'	=> 'error',
					'message'	=> "Failed to move uploaded file."
				);
			}

			// Read binary input stream and append it to temp file //
			if ( !$in = @fopen( $_FILES['qqfile']['tmp_name'], "rb" ))
			{
				$return = array(
					'code'		=> '104',
					'status'	=> 'error',
					'message'	=> "Failed to open input stream."
				);
			}
		}
		else
		{
			if ( !$in = @fopen( "php://input", "rb" ) ) {
				$return = array(
					'code'		=> '105',
					'status'	=> 'error',
					'message'	=> 'Failed to open input stream.'
				);
			}
		}

		while ( $buff = fread( $in, 4096 ) )
		{
			fwrite( $out, $buff );
		}

		@fclose($out);
		@fclose($in);

		// Check if file has been uploaded
		if ( !$chunks || $chunk == $chunks - 1 )
		{
			// Strip the temp .part suffix off
			rename( "{$file_path}.part", $file_path );

			$image_data = array(
				'file_path'	=> $file_path,
				'name'		=> $file_name
			);

			$save_dir 		= 'uploads/' . $year . '/' . $month . '/';
			$save_temp_dir 	= $path . '/' . $save_dir ;

			if ( !file_exists( $save_temp_dir ) ) {
				mkdir( $save_temp_dir, 0777, true);
			}

			// Check for duplicate file names //
			$extension 		= pathinfo( $file_name, PATHINFO_EXTENSION );
			$file_name_bit 	= pathinfo( $file_name, PATHINFO_FILENAME );
			$file_counter 	= 1;

			// Check for preexisting file name and append count if duplicate //
			while ( file_exists( $save_temp_dir . $file_name ) )
			{
				preg_match('/-lg|-md|-sm/', $file_name, $size );
				$org_file_name 	= pathinfo( str_replace($size[0], '', $file_name), PATHINFO_FILENAME );
				$file_name 		= $org_file_name . '-' . $file_counter++ . $size[0] . '.' . $extension;
			}

			rename( $file_path, $save_temp_dir . $file_name);

			// Get file type //
			switch ($extension) {
				case 'gif':
				case 'jpeg':
				case 'jpg':
				case 'png':
				$file_type = 'image';
				break;

				case 'csv':
				case 'docx':
				case 'pdf':
				case 'pptx':
				case 'txt':
				case 'xlsx':
				case 'zip':
				$file_type = 'document';
				break;

				default:
				$file_type = 'unknown';
				break;
			}

			// Collect data to save //
			$file_info = (object) array(
				'title' 		=> $file_name_bit,
				'file_name' 	=> $file_name,
				'file_path' 	=> $save_dir,
				'file_type' 	=> $file_type,
				'file_size' 	=> $post['qqtotalfilesize'],
				'file_uuid' 	=> $post['qquuid'],
				'parent_uuid' 	=> isset( $post['qqparentuuid'] ) 	? $post['qqparentuuid'] : $post['qquuid'],
				'mime_type' 	=> $file_data['qqfile']['type'],
			);

			// Update Database //
			$file_info->media_id = $this->media_model->save_file( $file_info );

			$return = array(
				'code'		=> '100',
				'status'	=> 'success',
				'success' 	=> true,
				'message'	=> "File successfully uploaded.",
				'data' 		=> $file_info
			);
		}
		else
		{
			$return = array(
				'status' => 'chunk'
			);
		}

		$this->load->view( 'json/empty', array( "json" => json_encode( $return ) ) );
	}

#### Detailed explanation of the problem
When uploading an image with scaling and sending original image qqfile data is not passing information to the ajax for the original image. 

Ex. from $_FILES passed to backend

    [qqfile] => Array
        (
            [name] => hello-world.jpg
            [type] => 
            [tmp_name] => 
            [error] => 1
            [size] => 0
        )

Noting how **type**, **tmp_name** are missing and **size** is 0. This information is coming directly from $_FILES. The $_REQUEST data has all of the correct information of **qquuid**, **qqfilename**, and **qqtotalfilesize**.

All images do upload including the original image (original file is broken after uploaded), only the original image has this issue where the incomplete $_FILES data. It does not happen with all images. Because of the data not being sent, it messes up some of the back-end logic that get's info from the file to save into the database as well as the server. 

When using the _onError_ callback, it returns that the error is unknown.

The only solution I have been able to figure out so far is to re-save the image by opening it in Photoshop and saving it as a new image. Unfortunately I'm not the end user that will be using it, nor are they very technically proficient, so it's not a great solution. I have tried other settings, but all seem to have a problem. I had been using chunking, but that was causing a host of other problems when the original file was going in with the mime-type of application/octet-stream.

I'm a little lost at this point, any help would be appreciated. Thank you.

**Comment by rnicholus** [comment]
Can you show me the exact payload (and headers) of the upload request in question? One easy way to do this is via Chrome's dev tools network tab.

**Comment by webdevnerdstuff** [comment]
The mime type for image/jpeg is in the request payload. The headers are for the most part identical for an image that doesn't have this issue.

Also in case it helps or you need it, here is one [image](http://mikevision.com/temp/hello-world.jpg) that is having this issue.

## General
Request URL: https://dev.somedomain.com/ajax/media/upload
Request Method: POST
Status Code: 200 OK
Remote Address: ###.###.##.##:###
Referrer Policy: no-referrer-when-downgrade

## Response Headers
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 551
Content-Type: text/html; charset=UTF-8
Date: Fri, 27 Apr 2018 16:59:08 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Server: Apache/2.4.7 (Ubuntu)
Set-Cookie: ci_session=c7bf0b6d6798267124d09e894a9e28024ab7eeec; expires=Fri, 27-Apr-2018 18:59:08 GMT; Max-Age=7200; path=/; httponly
Vary: Accept-Encoding
X-Powered-By: PHP/5.5.9-1ubuntu4.24

## Request Headers
Accept: application/json
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,la;q=0.8,da;q=0.7
Cache-Control: no-cache
Connection: keep-alive
Content-Length: 6318639
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryeQx97ncMIhhvpQPg
Cookie: ci_session=c7bf0b6d6798267124d09e894a9e28024ab7eeec
Host: dev.somedomain.com
Origin: https://dev.somedomain.com
Referer: https://dev.somedomain.com/admin/media/add
User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/66.0.3359.139 Safari/537.36
X-Requested-With: XMLHttpRequest

## Request Payload
------WebKitFormBoundaryeQx97ncMIhhvpQPg
Content-Disposition: form-data; name="qquuid"

b67350a8-5407-4cf7-a514-cbfe40eca8a6
------WebKitFormBoundaryeQx97ncMIhhvpQPg
Content-Disposition: form-data; name="qqfilename"

hello-world.jpg
------WebKitFormBoundaryeQx97ncMIhhvpQPg
Content-Disposition: form-data; name="qqtotalfilesize"

6318098
------WebKitFormBoundaryeQx97ncMIhhvpQPg
Content-Disposition: form-data; name="qqfile"; filename="hello-world.jpg"
Content-Type: image/jpeg


------WebKitFormBoundaryeQx97ncMIhhvpQPg--

**Comment by webdevnerdstuff** [comment]
I would also note that if I have chunking enabled I don't get this problem, which might wind up being the thing I have to change. As the larger file size could be what's messing things up. I would just need to accommodate for that on the backed as it saves each chunk and doesn't result in a completed image being saved currently. That and it comes in with the mime-type of application/octet-stream instead of image/jpeg.

**Comment by webdevnerdstuff** [comment]
Wow, just found this page. Going to take a look into using this instead of my code.

https://github.com/FineUploader/php-traditional-server

**Comment by webdevnerdstuff** [comment]
After integrating the php from that page, it has a similar issue.

**Comment by webdevnerdstuff** [comment]
After full integration of that PHP from the page I found, I have things working. I guess one thing that would be very helpful and useful for certain things is sending the qqfile data to the chunking.success.endpoint.

So I guess you can just close this one out. But please consider adding the qqfile data with the chunking.success.endpoint, as getting that information once the chunks are complete is still eluding me. I basically just said screw it and changed some of the other logic involved that was using the mime-type.

**Comment by rnicholus** [comment]
Are you asking to send the entire file to the chunking success endpoint? Or...?
