### ISSUE TITLE
Browser upload: File validation or preview

### ISSUE THREAD

**Issue by elgalu** [FineUploader/fine-uploader#2004]
- [x] Feature request
- [x] S3

We need to create a single page app that will allow uploading huge CSV files (e.g. 4 GB) to S3.

Some basic CSV validation should be in place, at least for first N lines of the file.

If there are errors in the file we would abort the upload and show the validation error to the user.

Is that possible with this library?

**Comment by rnicholus** [comment]
Yes, see https://docs.fineuploader.com/branch/master/api/events.html#submit
