### ISSUE TITLE
Valid json with [ ] is not accepted

### ISSUE THREAD

**Issue by harryshepard** [FineUploader/fine-uploader#2006]
## Type of issue
- [x] Bug report
- [ ] Feature request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{example: 5.16.2}

#### Browsers where the bug is reproducible
Chrome, FF

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}

#### Exact steps required to reproduce the issue
1. Just return [{ "success": true }] in the upload handler instead of { "success": true } and it doesn't work

#### All relevant Fine Uploader-related code that you have written
No modifications, just the stock code from the documentation.

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
Stock UI from docs

#### Detailed explanation of the problem
I'm using gson.toJson(json) to output my json which adds [ ] around it and is still valid json according to https://jsonlint.com/ (and my old upload script)

{ "success": true } and [{ "success": true }] are both valid, but I'm having to strip the [] to make fineuploader accept the response
</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

**Comment by rnicholus** [comment]
A JSON object is expected, and you're returning a JSON array.
