### ISSUE TITLE
How to move project to other folder structure

### ISSUE THREAD

**Issue by PhamQuiToan** [FineUploader/fine-uploader#2009]
## Type of issue
- [ ] Bug report
- [X] Feature request

## Uploader type
- [X] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Feature Request</summary>

#### Feature request details 
Please show me how to move to other folder structure in case of changing server.
</details>

**Comment by rnicholus** [comment]
Sorry, but I can’t handle support requests
