### ISSUE TITLE
Not working at all(Nothing shows up when I run the code)

### ISSUE THREAD

**Issue by jedmarasigan** [FineUploader/fine-uploader#2011]
## Type of issue
- [ ] Bug report
- [x] Feature request

## Uploader type
- [ ] Traditional

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{example: 5.16.2}

#### Browsers where the bug is reproducible
{Chrome}

#### Operating systems where the bug is reproducible
{"Windows 8"}

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
{
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    
    <link href="C:/Users/Jed/AppData/Roaming/SPB_16.6/pdsmart/node_modules/fine-uploader/fine-uploader/fine-uploader-new.css" rel="stylesheet">

    
    <script src="node_modules/fine-uploader/fine-uploader/fine-uploader.js" type="text/javascript"></script>

    <link href="node_modules/fine-uploader/fine-uploader/fine-uploader-new.css" rel="stylesheet" type="text/css"/>

    
    <script type="text/template" id="qq-template-manual-trigger">
        <div class="qq-uploader-selector qq-uploader" qq-drop-area-text="Drop files here">
            <div class="qq-total-progress-bar-container-selector qq-total-progress-bar-container">
                <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-total-progress-bar-selector qq-progress-bar qq-total-progress-bar"></div>
            </div>
            <div class="qq-upload-drop-area-selector qq-upload-drop-area" qq-hide-dropzone>
                <span class="qq-upload-drop-area-text-selector"></span>
            </div>
            <div class="buttons">
                <div class="qq-upload-button-selector qq-upload-button">
                    <div>Select files</div>
                </div>
                <button type="button" id="trigger-upload" class="btn btn-primary">
                    <i class="icon-upload icon-white"></i> Upload
                </button>
            </div>
            <span class="qq-drop-processing-selector qq-drop-processing">
                <span>Processing dropped files...</span>
                <span class="qq-drop-processing-spinner-selector qq-drop-processing-spinner"></span>
            </span>
            <ul class="qq-upload-list-selector qq-upload-list" aria-live="polite" aria-relevant="additions removals">
                <li>
                    <div class="qq-progress-bar-container-selector">
                        <div role="progressbar" aria-valuenow="0" aria-valuemin="0" aria-valuemax="100" class="qq-progress-bar-selector qq-progress-bar"></div>
                    </div>
                    <span class="qq-upload-spinner-selector qq-upload-spinner"></span>
                    <img class="qq-thumbnail-selector" qq-max-size="100" qq-server-scale>
                    <span class="qq-upload-file-selector qq-upload-file"></span>
                    <span class="qq-edit-filename-icon-selector qq-edit-filename-icon" aria-label="Edit filename"></span>
                    <input class="qq-edit-filename-selector qq-edit-filename" tabindex="0" type="text">
                    <span class="qq-upload-size-selector qq-upload-size"></span>
                    <button type="button" class="qq-btn qq-upload-cancel-selector qq-upload-cancel">Cancel</button>
                    <button type="button" class="qq-btn qq-upload-retry-selector qq-upload-retry">Retry</button>
                    <button type="button" class="qq-btn qq-upload-delete-selector qq-upload-delete">Delete</button>
                    <span role="status" class="qq-upload-status-text-selector qq-upload-status-text"></span>
                </li>
            </ul>

            <dialog class="qq-alert-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Close</button>
                </div>
            </dialog>

            <dialog class="qq-confirm-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">No</button>
                    <button type="button" class="qq-ok-button-selector">Yes</button>
                </div>
            </dialog>

            <dialog class="qq-prompt-dialog-selector">
                <div class="qq-dialog-message-selector"></div>
                <input type="text">
                <div class="qq-dialog-buttons">
                    <button type="button" class="qq-cancel-button-selector">Cancel</button>
                    <button type="button" class="qq-ok-button-selector">Ok</button>
                </div>
            </dialog>
        </div>
    </script>

    <style>
        #trigger-upload {
            color: white;
            background-color: #00ABC7;
            font-size: 14px;
            padding: 7px 20px;
            background-image: none;
        }

        #fine-uploader-manual-trigger .qq-upload-button {
            margin-right: 15px;
        }

        #fine-uploader-manual-trigger .buttons {
            width: 36%;
        }

        #fine-uploader-manual-trigger .qq-uploader .qq-total-progress-bar-container {
            width: 60%;
        }
    </style>

    <title>Fine Uploader Manual Upload Trigger Demo</title>
</head>
<body>

<div id="fine-uploader-manual-trigger"></div>

<script>
    var manualUploader = new qq.FineUploader({
        element: document.getElementById('fine-uploader-manual-trigger'),
        template: 'qq-template-manual-trigger',
        request: {
            endpoint: '/server/uploads'
        },
        thumbnails: {
            placeholders: {
                waitingPath: 'C:/Users/Jed/AppData/Roaming/SPB_16.6/pdsmart/node_modules/fine-uploader/fine-uploader/placeholders/waiting-generic.png',
                notAvailablePath: 'C:/Users/Jed/AppData/Roaming/SPB_16.6/pdsmart/node_modules/fine-uploader/fine-uploader/placeholders/not_available-generic.png'
            }
        },
        autoUpload: false,
        debug: true
    });

    qq(document.getElementById("trigger-upload")).attach("click", function() {
        manualUploader.uploadStoredFiles();
    });
</script>
</body>
</html>
}

#### Detailed explanation of the problem
{describe the bug here}
</details>
(I don't know why the above portion of code is not inside, this is my first time posting an issue)

I am using NodeJs, Express, and writing this code in an ejs file. The problem I am having is that when I try to run the code nothing is happening. I followed all the steps given to integrate fine-uploader, and i downloaded the node-modules. I am a beginner in web development so any help would be greatly appreciated.

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

**Comment by fakefarm** [comment]
@jedmarasigan Please paste or link us to some code so we can try to help. We don't know if this issue is related to Node, Express, ES or other. In the meantime, press on.

**Comment by rnicholus** [comment]
I regret that I can’t take time to answer support requests. Best of luck though
