### ISSUE TITLE
Feature Request: allow user defined callback for `getExtension`

### ISSUE THREAD

**Issue by keiranmraine** [FineUploader/fine-uploader#2012]
## Type of issue
- [ ] Bug report
- [x] Feature request

## Uploader type
- [ ] Traditional
- [x] S3
- [ ] Azure

<details>
<summary>Feature Request: allow user defined callback for `getExtension`</summary>

At present it only possible to have a key generated as a base uuid with traditional file extension.

Many biology file formats have multiple "extensions" to denote various types of underlying text file formats compressed in some way (mostly gzip).

It would be very beneficial if `getExtension`, as used [here](https://github.com/FineUploader/fine-uploader/blob/e6ae6253e4bf2f1a428855e4ac265e55554e83bf/client/js/s3/uploader.basic.js#L341), could be exposed as a user definable function receiving `filename`.

This would allow end-users to the flexibility to support things like `*.fq.gz`

```
function getExtensionUserDef(fileId) {
  let matches = fileId.match(/(\.f[ast]*q.gz)$/);
  let extension = null;
  if(matches !== null) {
    extension = matches[1];
  } else {
    matches = fileId.match(/(\.[^\.]+)$/);
    extension = matches[1];
  }
  return extension;
}
```

Happy to test if you are able to support this request, currently using via the react-fine-uploader package.

</details>

**Comment by rnicholus** [comment]
Please open up a PR with your proposal and we can discuss further. I wouldn't expect to add a callback or another option though. Instead, follow the pattern of other options that allow both function and non-function values ([objectProperties.key](https://docs.fineuploader.com/branch/master/api/options-s3.html#objectProperties.key) is a perfect example).
