### ISSUE TITLE
Reset after deleteFile gives status error

### ISSUE THREAD

**Issue by bazzacad** [FineUploader/fine-uploader#2020]
## Type of issue
- [X ] Bug report

## Uploader type
- [X ] Traditional

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.16.2

#### Browsers where the bug is reproducible
Chrome

#### Operating systems where the bug is reproducible
Win. 10

#### Exact steps required to reproduce the issue
Click to upload the file.
Click button outside of Fine Uploader to delete the file & reset.

#### All relevant Fine Uploader-related code that you have written
```
function addTask() {
	var postdata = {};
	postdata.listID = listID;
	$.post('ajax/addTask.php', postdata, 
			function(data) { 
				uploader.deleteFile(0);
				uploader.reset();
	});
}
//addTask.php copies the file from the upload folder to a network share.
```

#### Detailed explanation of the problem
It seems like the reset is trying to happen before the deleteFile is finished.
If I remove the reset, all works fine.

![fineuploaderreset](https://user-images.githubusercontent.com/23222121/42074918-5982468c-7b23-11e8-9f90-2614b9f3feef.png)

</details>

**Comment by rnicholus** [comment]
How is this a fine Uploader issue? Don’t call reset until the delete operation completes.

**Comment by bazzacad** [comment]
OK, then how can I tell if the delete operation is finished?

**Comment by bazzacad** [comment]
Oops sorry, I found the callback events:
https://docs.fineuploader.com/api/events.html
