### ISSUE TITLE
Server Side Python AWS version 4 upload

### ISSUE THREAD

**Issue by salishaukat** [FineUploader/fine-uploader#2025]
## Type of issue
- Feature Request

## Uploader type
- S3

### Note: Support requests cannot be accepted due to lack of time.

<summary>Unable to found suitable example python AWS version 4 upload</summary>

As there is no suitable server side aws version 4 python file upload is not available. We need this code example because now few aws regions are not accepting version uploading requests
</details>

**Comment by rnicholus** [comment]
Sorry, this doesn’t belong in the JS issue tracker. There a plenty of non-py examples that can be used to update one of the many existing py servers to handle v4 signatures. Also, there’s http://blog.stratospark.com/secure-serverless-file-uploads-with-aws-lambda-s3-zappa.html
