### ISSUE TITLE
addInitialFiles(initialFiles) extremely slow

### ISSUE THREAD

**Issue by jwcharp** [FineUploader/fine-uploader#2026]
## Type of issue
- [ x ] Bug report
- [ ] Feature request

## Uploader type
- [ x ] Traditional
- [ ] S3
- [ ] Azure

<details>
Using addInitialFiles(initialFiles) or session methods to pre load already upload files from the server act syncronously, and take upto 1 second to load a file no matter how big or small.

How do you make this asyncrconous, I have tried upping the maxConnections, but I believe that is only related to chunking.

#### Fine Uploader version
5.16.2

#### Browsers where the bug is reproducible
Google Chrome 

#### Operating systems where the bug is reproducible
Windows 10

#### Exact steps required to reproduce the issue
Using addInitialFiles (initialFiles) functionality only loads 1 photo at a time, extremely slow if you want to preload 100+ photos

#### All relevant Fine Uploader-related code that you have written
No edits made, using the Gallery View instatiation

#### Detailed explanation of the problem
{describe the bug here}
</details>

**Comment by rnicholus** [comment]
Without a clear description of the issue, I can only assume you need to adjust https://docs.fineuploader.com/branch/master/api/options-ui.html#thumbnails.timeBetweenThumbs
