### ISSUE TITLE
Requesting SAS URI for every chunk

### ISSUE THREAD

**Issue by yurykovshov** [FineUploader/fine-uploader#2027]
Hi,

I have a question. You [write](https://docs.fineuploader.com/branch/develop/features/azure.html) "Fine Uploader will call your signature server before each and every request, asking for a SAS URI." 

Why do you do that? For every chunk, you request a "new" SAS URI, whereas a shared access signature is given for a whole blob, and basically every time is the same.
Why don't you request SAS in the beginning and just use it further?

The same question with OPTIONS. Why call it for every chunk?

**Comment by rnicholus** [comment]
I don’t recall specifics as it’s been a while since I wrote that code, but I would expect each SAS to be very short-lived, for obvious reasons.

**Comment by rnicholus** [comment]
If you have specific improvements in mind, please open a PR
