### ISSUE TITLE
FineUploder : Image upload error for image of 80MB

### ISSUE THREAD

**Issue by sagarsolace** [FineUploader/fine-uploader#2028]
## Type of issue
- [ ] Bug report

## Uploader type
- [ ] Traditional

<details>
<summary>Bug Report</summary>

#### Exact steps required to reproduce the issue
For example:
1. Select Image of 80 MB in size
2. Upload image

#### Fine Uploader template markup  
[Fine Uploader 5.1.3] Could not render preview, file may be too large!

#### Detailed explanation of the problem
Hello 

When I tried to upload image of 80 MB in size which throws, following error:

[Fine Uploader 5.1.3] Could not render preview, file may be too large!

Please suggest.

</details>

**Comment by sagarsolace123** [comment]
Hello Guys, I have created a demo with fine uploader latest version but it also not produce image preview when I try to upload an image over the size of 120 MB
	
http://www.solaceinfotech.com/projects/fineuploaderdemo/fudemo.php

Please suggest.

**Comment by rnicholus** [comment]
This is not a bug. There is a limit set here to prevent tying up the UI thread or memory when attempting to preview images. Does not affect uploads
