### ISSUE TITLE
FineUploder : Image upload error for image of 80MB

### ISSUE THREAD

**Issue by louis-ramage** [FineUploader/fine-uploader#2029]
FineUploder : Image upload error for image of 80MB

## Type of issue
- [ ] Bug report

## Uploader type
- [ ] Traditional

<details>
<summary>Bug Report</summary>

#### Exact steps required to reproduce the issue
For example:
1. Select Image of 80 MB in size
2. Upload image

#### Fine Uploader template markup  
[Fine Uploader 5.1.3] Could not render preview, file may be too large!

#### Detailed explanation of the problem
Hello 

When I tried to upload image of 80 MB in size which throws, following error:

[Fine Uploader 5.1.3] Could not render preview, file may be too large!

Please suggest.

</details>

**Comment by rnicholus** [comment]
Duplicate of #2028
