### ISSUE TITLE
fine-uploader-new.css filename is not descriptive enough

### ISSUE THREAD

**Issue by raulferras** [FineUploader/fine-uploader#2034]
## Type of issue
- [ ] Bug report
- [x] Feature request

## Uploader type
- [x] Traditional
- [x] S3
- [x] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>
File `fine-uploader/fine-uploader-new.css` has a bad name. "new" word does not describes what this file implements.

#### Fine Uploader version
5.5.1

#### Detailed explanation of the problem
File `fine-uploader/fine-uploader-new.css` has a bad name. It should describe better what differences this from other css files.  "new" word becomes obsolete as soon as another theme is implemented. Even if no new themes are implemented, `new` word feels weird.
</details>

<details>
<summary>Give a more descriptive name to this file</summary>

#### Feature request details 
Documentation states to use this file if one wants to use a "Row based UI" so maybe `fine-uploader-row.css` would be a better name.
</details>

**Comment by rnicholus** [comment]
Updating th documentation to point at this specific file is sufficient. Changing the name of the file would be a breaking change and that isn’t appropriate for something this minor.

**Comment by raulferras** [comment]
May be then this can be planned for a major version bump?

**Comment by rnicholus** [comment]
I don’t think that is necessary or prudent. Again, I think a documentation update is best. In a major version release, only critical or exceptionally useful breaking changes should be introduced.

**Comment by raulferras** [comment]
I respect your decision, but then, how will you name a new possible template? `fine-uploader-new-2.css`?
Easy of usage is an important topic and good naming goes with it.
Just my opinion.

**Comment by rnicholus** [comment]
I don’t expect to ever create another template
