### ISSUE TITLE
Can I set a file status to UPLOAD_SUCCESSFUL

### ISSUE THREAD

**Issue by Yang2007** [FineUploader/fine-uploader#2036]
I will check if the file exists on the server before uploading the file.
If true I want to set the file status to UPLOAD_SUCCESSFUL.

promise.failure() in function onUpload   will set the file status to UPLOAD_FAILED,
and setStatus does not work.

Is there a function just like success(id) or success(id, partIndex)

How can I do?

**Comment by rnicholus** [comment]
please don't delete the issue template
