### ISSUE TITLE
How can I restrict the validation for itemLimit and sizeLimit on each upload session?

### ISSUE THREAD

**Issue by w4ling** [FineUploader/fine-uploader#2038]
## Type of issue
- [ ] Bug report
- [ ] Feature request

## Uploader type
- [ ] Traditional

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.5.1 (s3)

#### Validation code
validation: { itemLimit: 2, sizeLimit: 4294967296, allowedExtensions: arr, stopOnFirstInvalidFile: false }

#### Exact steps required to reproduce the issue
For example:
1. Select 2 files
2. After upload is done, select other 2 files.
3. It pops up with a  message saying that the total uploaded files is over limit (2).

How can reset the total count of the uploaded files and the total size of the uploaded files so I can keep uploading files without refresh the page? I thought itemLimit and sizeLimit will be for each uploading operation right? I want to achieve the same behavior of the last example on your demo page. With the validation rule of itemLimit and sizeLimit, I can keep dragging files (within the item limit) to upload. Although the example is running as s3 fineuploader. With traditional fineuploader, can I do this?

I know there is a "reset" method to reset the fineuploader. But after I call this, it breaks other feature of my page.

**Comment by rnicholus** [comment]
Your only options are to call reset, or create a new Uploader instance.
