### ISSUE TITLE
[Firefox] NS_ERROR_FILE_TARGET_DOES_NOT_EXIST

### ISSUE THREAD

**Issue by storeman** [FineUploader/fine-uploader#2042]
## Type of issue
- [X] Bug report
- [ ] Feature request

## Uploader type
- [X] Traditional
- [ ] S3
- [ ] Azure

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.16.2

#### Browsers where the bug is reproducible
Firefox 61.0

#### Operating systems where the bug is reproducible
Android 8.1.0

#### Exact steps required to reproduce the issue
1. Select multiple files

#### Detailed explanation of the problem

When selecting multiple files for upload, nothing happens. When connecting the WebIDE to the Android device, is see the error:
NS_ERROR_FILE_TARGET_DOES_NOT_EXIST (line: 1830), relevant part:
```
_handleNewFile: function(file, batchId, newFileWrapperList) {
                var self = this, uuid = qq.getUniqueId(), size = -1, name = qq.getFilename(file), actualFile = file.blob || file, handler = this._customNewFileHandler ? this._customNewFileHandler : qq.bind(self._handleNewFileGeneric, self);
                if (!qq.isInput(actualFile) && actualFile.size >= 0) {
                    size = actualFile.size;
                }
```

The error occurs when calling `actualFile.size`. 

I tried to add a separate upload element and add the files using the .addFiles method like this:
```
    $('#file-input').on({
        change: function (e) {
            fineUploader.addFiles(this.files);
        }
    });
```
The same error occurs.

A more detailed error from the WebIDE console:
```
    NS_ERROR_FILE_TARGET_DOES_NOT_EXIST: fine-uploader.js:1830
        _handleNewFile                         uploader.basic.api.js:1112:17
        addFiles/processFileOrInput<    uploader.basic.api.js:67:24
        qq.bind/<                                 util.js:691:23
        addFiles/<                                uploader.basic.api.js:88:24
        qq.each                                    util.js:654:29
        addFiles                                   uploader.basic.api.js:86:16
        change                                    [url].vh8fe097a7cb.js:5:370
        dispatch                                  [url]/jquery-2.1.4.js:3:6414
        add/r.handle                           [url]/jquery-2.1.4.js:3:3224
        _sendMessage/<                    jar:jar:file:///data/app/org.mozilla.firefox-H3aFdZSu70puU4aL0Vymgw==/base.apk!/assets/omni.ja!/components/FilePicker.js:23:144
```

I tried substituting the `actualFile` with `file`, but it makes no difference. When inspecting the object, is see the .size getter, but I cannot retrieve its value.

On the normal Firefox version, all is normal. Picking files one by one also is not an issue.

</details>

**Comment by SinghSukhdeep** [comment]
Its unclear as to what the issue is and I haven't seen this issue before.
And again, please show your code as we can't do much without looking..
Issues will be closed soon if no further update arrives..
