### ISSUE TITLE
Add how to integrate with Angular 2

### ISSUE THREAD

**Issue by Chiff** [FineUploader/fine-uploader#2043]
## Type of issue
- [ ] Bug report
- [x] Feature request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

#### Feature request details 
When I wanted to integrate your plugin into my app I couldn't find how to do this in docs. Then I found [this](https://github.com/SinghSukhdeep/fine-uploader-ts) repo in issues. If you at least reference it in docs it would save other FineUploader + Angular2 users more time.

**Comment by SinghSukhdeep** [comment]
ES6, CommonJS, TypeScript and Angular support documentation is listed here https://docs.fineuploader.com/branch/master/features/modules.html

**Comment by Chiff** [comment]
Yes they are, but there is nothing how to really use them inside component. It's better to see it in working example, like in your repo. Well at least for me it was helpful and I wanted to share that.

**Comment by SinghSukhdeep** [comment]
Well, there isn't anything special about using FU inside an Angular component, but still if you need more reference I recommend looking at [this ](https://github.com/FineUploader/fine-uploader/blob/master/client/typescript/fine-uploader.test.ts)file.

My repo is pretty old and probably outdated as I was using it just for testing purposes.
Hope this helps
