### ISSUE TITLE
Firefox - Large single file - does not free memory

### ISSUE THREAD

**Issue by inzanez** [FineUploader/fine-uploader#2048]
## Type of issue
- [x] Bug report
- [ ] Feature request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.
<details>
<summary>Bug Report</summary>

#### Fine Uploader version
Latest version

#### Browsers where the bug is reproducible
Firefox 61.0 64-bit

#### Operating systems where the bug is reproducible
Linux/Windows

#### Exact steps required to reproduce the issue

1. Select 1 file, 10-20GB size
2. Upload
3. Wait till all memory is used up, including swap space

I'm not doing anything fancy, just chunked uploading of a very large file with a chunk size of 4MByte, using a <input...> to select the file.
Using Chrome or Chromium, this works well, the browser seems to free memory during upload and memory usage never goes up too high.

Using Firefox however, the browser seems to literally eat all the memory, continue with the swap space and render the system unusable. The upload will stall of course.

</details>

**Comment by rnicholus** [comment]
please show your code - currently, i'm not sure what i can do to help here

**Comment by inzanez** [comment]
Sure, I'll compose something minimal and will get back to you.

**Comment by inzanez** [comment]
I will need to do some more tests. It seems that enabling concurrent chunking somehow got rid of the problem, maybe you know why that would be.
I will do some more tests with different systems though...

**Comment by inzanez** [comment]
Well, I can confirm that the error is gone using concurrent chunking,...
