### ISSUE TITLE
upload about browser and upload problem

### ISSUE THREAD

**Issue by niyangfeng** [FineUploader/fine-uploader#2049]
## Type of issue
- [yes ] Bug report
- [ ] Feature request

## Uploader type
- [ yes] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time
<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Browsers where the bug is reproducible
{example: "Firefox" and "IE11"}

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}

#### Exact steps required to reproduce the issue
For example:
1. Select 3 files
2. Pause the 2nd file before it completes, but after it has started.
3. Attempt to resume the paused file.

#### All relevant Fine Uploader-related code that you have written
{simply copy and paste the JS used to control Fine Uploader browsers-ide}
{also include your template HTML if related to a UI issue}

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
{simply copy and paste your template markup}

#### Detailed explanation of the problem
{describe the bug here}
</details>

I want to upload 2,000 photos at a time, about 7.8 megabytes each, which will cause the browser to crash. Is there a good solution? At the same time, I want to ask when the onUpload event occurs before each upload or uploading, I need request AJAX to set up params before uploading, but now there is always a problem

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

**Comment by rnicholus** [comment]
Saying “the browser crashes” and “there is a problem” doesn’t provide anywhere near the level of detail needed to assist. Please take another look at the issue template, follow it, and focus on one specific issue that is not a support request.
