### ISSUE TITLE
[Bug report] - Body without file in qqfile

### ISSUE THREAD

**Issue by FernandoFreitasPixelhouse** [FineUploader/fine-uploader#2051]
## Type of issue
- [x] Bug report
- [ ] Feature request

## Uploader type
- [x] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.14.1

#### Browsers where the bug is reproducible
Chrome 67.0.3396.87

#### Operating systems where the bug is reproducible
iOS 11.4 

#### Exact steps required to reproduce the issue
For example:
1. Access site www.nicephotos.com.br
2. Click in "menu" icon
3. Click in "entrar" link
4. Use the following credentials do access:
login: teste@fineuploader.com.br
password: 123456
5. Click in "menu" icon
6. Click in "Revelação de Fotos" link
7. Click in "Revelar Agora" button
8. Click in "Meu dipositivo" button
9. Select "Photo Library" Link
10. Select 10 pictures
11. Click on "Prosseguir" button
12. Error usually happens two times of three, It will be showed a pop-fade with the title "Atenção!..."

#### Detailed explanation of the problem
For some reason fineuploader sent the post of the image without write the image file, on area "qqfile".
This happens just sometimes and just for some pictures usually the first.
In my tests when I change "maxConnections" to "1", I can't reproduce the problem anymore.
After the problem happens if we call "retry(id)" usually works (95% of times).
I can't reproduce this problem on desktop
Follows attached the log example of the body incompleted.

</details>
[log.txt](https://github.com/FineUploader/fine-uploader/files/2420222/log.txt)

**Comment by SinghSukhdeep** [comment]
Can you please show your code?
Can't help you without looking at your code.
Please read the issue template.....

**Comment by FernandoFreitasPixelhouse** [comment]
Hi @SinghSukhdeep,

Do you want see my server code? I didn't undesrstand.
In relation a "Please read the issue template....." what I did wrong?

This problems happens only sometimes and aparently in iOs Devices.
It seems that problem happens in line bellow of file "fine-uploader.js":
"formData.append(spec.inputName, fileOrBlob);"

**Comment by SinghSukhdeep** [comment]
In the issue template there is this section..

> #### All relevant Fine Uploader-related code that you have written
> {simply copy and paste the JS used to control Fine Uploader browsers-ide}
> {also include your template HTML if related to a UI issue}

I need to see you browser side JS and HTML, not your server side code.

**Comment by FernandoFreitasPixelhouse** [comment]
Follows attached the html's and JS's.

[Files.zip](https://github.com/FineUploader/fine-uploader/files/2441811/Files.zip)

**Comment by rnicholus** [comment]
No one is download a zip file to look at your code. Again, as already mentioned, do not delete the issue template & follow the directions listed.

**Comment by rnicholus** [comment]
>For some reason fineuploader sent the post of the image without write the image file

Your server writes the image file to disk, not Fine Uploader. I can guarantee that the file is always sent by fine uploader.

**Comment by FernandoFreitasPixelhouse** [comment]
Hi @rnicholus ,

I used the debug mode in Mac connected with an iPhone.
When I did this I comprove that content-length of pictures with trouble a so smaller that the pictures that are ok.
Ex.: content-length: 800 ( in post with error) and content-length: about: 4000 (in post ok)
When I change "maxConnections" to 1 the problem didn't happen anymore.
