### ISSUE TITLE
General Error on Simplest File

### ISSUE THREAD

**Issue by koryp123** [FineUploader/fine-uploader#2053]
I am able to successfully upload a file with headers:  email, first, last

if there's any other column, like address, city, state, zip it fails.  i've tried everything i can think of. 

sorry I know this is a very general description, but i'm wondering if there's something easy i'm missing.  i'm not sure which version it is, but i thin it's pretty old

thanks

## Type of issue
- [ ] Bug report
- [ ] Feature request

## Uploader type
- [ ] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Browsers where the bug is reproducible
{example: "Firefox" and "IE11"}

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}

#### Exact steps required to reproduce the issue
For example:
1. Select 3 files
2. Pause the 2nd file before it completes, but after it has started.
3. Attempt to resume the paused file.

#### All relevant Fine Uploader-related code that you have written
{simply copy and paste the JS used to control Fine Uploader browsers-ide}
{also include your template HTML if related to a UI issue}

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
{simply copy and paste your template markup}

#### Detailed explanation of the problem
{describe the bug here}
</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

**Comment by koryp123** [comment]
OK, here's the error:
 "attempting to parse xhr response text" "unexpected token < in JSON at position 0"

**Comment by koryp123** [comment]
it's requiring the 4 digit appendage to all zip codes and doesn't like it when there's only a 5 digit zip

**Comment by SinghSukhdeep** [comment]
Can't help you without looking at your code, this is your server side issue anyway. Fine Uploader is expecting JSON response but your server isn't sending valid JSON. Check your server side script.
