### ISSUE TITLE
Refused to apply style from ...fine-uploader-gallery.css because its MIME type ('text/html') is not a supported stylesheet MIME type, and strict MIME checking is enable

### ISSUE THREAD

**Issue by alexxmed** [FineUploader/fine-uploader#2054]
## Type of issue
- [X] Bug report
- [ ] Feature request

## Uploader type
- [X] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
{example: 5.5.1}

#### Browsers where the bug is reproducible
{example: "Firefox" and "IE11"}
Chrome, Firefox

#### Operating systems where the bug is reproducible
{example: "iOS 9.1.0" and "Windows 8.1"}
Ubuntu Linux 18.04 

#### Exact steps required to reproduce the issue
For example:
1. Select 3 files
2. Pause the 2nd file before it completes, but after it has started.
3. Attempt to resume the paused file.

#### All relevant Fine Uploader-related code that you have written
{simply copy and paste the JS used to control Fine Uploader browsers-ide}
{also include your template HTML if related to a UI issue}

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
{simply copy and paste your template markup}

#### Detailed explanation of the problem
{describe the bug here}
</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

**Comment by SinghSukhdeep** [comment]
This is an issue with your server config, its not returning valid css files with correct MIME type, not a Fine Uploader issue and without looking at your code can't help.
