### ISSUE TITLE
Issue trying to select multiple photos on iPhone 8 using Fine-Uploader S3 configuration

### ISSUE THREAD

**Issue by inglesuniversal** [FineUploader/fine-uploader#2057]
I love your script. However if I try to pick several photos at once with the S3 upload configuration. As soon as I pick an image thumbnail on my iPhone... The script takes me immediately back to the upload screen without allowing me to pick more than one image.

Interestingly enough though, this works flawlessly on your standard JS / jQuery setup.

Can anybody help me find a solution for this issue?

Regards

**Comment by SinghSukhdeep** [comment]
How are we supposed to help you without looking at your code?
Please read the issue template bud.

**Comment by inglesuniversal** [comment]
Sorry bud if I didn't give you all the details, but the same issue happens with your sample code right at your domain page. I just double checked tonight.

**Comment by rnicholus** [comment]
most likely `multiple` is set to `false`. Please see the options docs
