### ISSUE TITLE
Failed s3 upload only for certain image files

### ISSUE THREAD

**Issue by Aryan1** [FineUploader/fine-uploader#2058]
## Type of issue
- [ ] Bug report

## Uploader type
- [ ] S3

#### Fine Uploader version
5.16.2

#### Detailed explanation of the problem
I setup fineuploader s3. It's working very fine but the problem is certain 'jpeg' image files cannot be uploaded.

These are the steps taken by me so far:-

1. I modified the filenames, extensions etc. it did not work
2. When I disabled chunking it works fine. I mean I can upload those image files which I couldn't earlier.
3, When I open the image in MS Paint and then re-save it, it just works fine
4. I checked the request being sent to signature generation server and found that the request data is different for those certain files that I cannot upload. Here's the dump for the data.

array:2 [
  "headers" => """
    AWS4-HMAC-SHA256\n
    20181008T050528Z\n
    20181008/ap-south-1/s3/aws4_request\n
    POST\n
    /614248b2-bc07-436f-a6c2-9105da0a7907.JPG\n
    uploads=\n
    host:someuser.s3.amazonaws.com/\n
    x-amz-acl:private\n
    x-amz-content-sha256:e3b0c44298fc1c149afce4c8998fb92427ae41e4649b934ca495991b7852b855\n
    x-amz-date:20181008T050528Z\n
    x-amz-meta-qqfilename:_DSC2300.JPG\n
    \n
    host;x-amz-acl;x-amz-content-sha256;x-amz-date;x-amz-meta-qqfilename\n
    e3c0c44298fc1c149afbf4c8996fb02427ab41e4649b934ca495991b7852b855
    """
  "v4" => "true"
]
How does fineuploader decides when to send headers or when to send json request for signature?

**Comment by rnicholus** [comment]
can't reproduce w/out code. feel free to open a new issue, following the template this time
