### ISSUE TITLE
make build generates unhandled promise rejection error

### ISSUE THREAD

**Issue by rinebob** [FineUploader/fine-uploader#2062]
## Type of issue
- [x ] Bug report
- [ ] Feature request

## Uploader type
- [ x] Traditional
- [ ] S3
- [ ] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.16.2

#### Browsers where the bug is reproducible
chrome

#### Operating systems where the bug is reproducible
windows 10
using git bash

#### Exact steps required to reproduce the issue
Installation problem.  running commands from getting started page:

git clone https://github.com/FineUploader/fine-uploader.git
cd fine-uploader
npm install
make build

problem occurs on make build command

#### All relevant Fine Uploader-related code that you have written
no code written yet - unable to get running

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
None

#### Detailed explanation of the problem
trying to install in node.js environment.  ran instructions from 'getting started':

Build Fine Uploader yourself from the GitHub repo
git clone https://github.com/FineUploader/fine-uploader.git
cd fine-uploader
npm install
make build

upon make build command received following error:

(node:1204) UnhandledPromiseRejectionWarning: undefined

ran command again using --debug generated following output:

(dir command output shown first)

Bob@LAPTOP-06COO3JJ MINGW64 /c/aa_local_code/mean/express/fine-uploader (master)
$ dir
$@  ATTRIBUTION.txt  client  config  docs  LICENSE  Makefile  node_modules  -p  package.json  package-lock.json  README.md  test

Bob@LAPTOP-06COO3JJ MINGW64 /c/aa_local_code/mean/express/fine-uploader (master)
$ make build --debug
  make:cli Make init CLI with env namespace success name options +0ms
  make:cli Run build targets +19ms
make i info Invoking build target
  make:cli Prerequities "\" for target build +7ms
  make:cli Emit target:unknown +3ms
  make:cli Handled true +6ms
(node:1204) UnhandledPromiseRejectionWarning: undefined
(node:1204) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1204) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
make × ERR  not found: make-\
  make:cli Load templates from 3 directories +27ms
  make:cli Load templates from C:\Users\Bob\AppData\Roaming\npm\node_modules\make\templates +4ms

  $ make <target...> [options]

  Options:
    --help             Show this help output
    --version          Show package version
    --debug            Enable extended log output

  Targets:
    preamble = "// Fine Uploader $(version) - MIT licensed. http Run target preamble = "// Fine Uploader $(version) - MIT licensed. http
    clean              Run target clean
    lint               Run target lint
    _build             Run target _build
    uglify = $(npm-bin)/uglifyjs -b --preamble $(preamble) -e window Run target uglify = $(npm-bin)/uglifyjs -b --preamble $(preamble) -e window
    uglify-min = $(npm-bin)/uglifyjs -c -m --preamble $(preamble) -e window Run target uglify-min = $(npm-bin)/uglifyjs -c -m --preamble $(preamble) -e window
    build-dnd-standalone Run target build-dnd-standalone
    build-dnd-standalone-min Run target build-dnd-standalone-min
    build-core-traditional Run target build-core-traditional
    build-core-traditional-min Run target build-core-traditional-min
    build-ui-traditional Run target build-ui-traditional
    build-ui-traditional-min Run target build-ui-traditional-min
    build-ui-traditional-jquery Run target build-ui-traditional-jquery
    build-ui-traditional-jquery-min Run target build-ui-traditional-jquery-min
    build-core-s3      Run target build-core-s3
    build-core-s3-min  Run target build-core-s3-min
    build-ui-s3        Run target build-ui-s3
    build-ui-s3-min    Run target build-ui-s3-min
    build-ui-s3-jquery Run target build-ui-s3-jquery
    build-ui-s3-jquery-min Run target build-ui-s3-jquery-min
    build-core-azure   Run target build-core-azure
    build-core-azure-min Run target build-core-azure-min
    build-ui-azure     Run target build-ui-azure
    build-ui-azure-min Run target build-ui-azure-min
    build-ui-azure-jquery Run target build-ui-azure-jquery
    build-ui-azure-jquery-min Run target build-ui-azure-jquery-min
    build-all-core     Run target build-all-core
    build-all-core-min Run target build-all-core-min
    build-all-ui       Run target build-all-ui
    build-all-ui-min   Run target build-all-ui-min
    build              Run target build
    start-test-resources-server Run target start-test-resources-server
    start-root-server  Run target start-root-server
    test-resources-server.PID Run target test-resources-server.PID
    root-server.PID    Run target root-server.PID
    stop-test-resources-server Run target stop-test-resources-server
    stop-root-server   Run target stop-root-server
    test               Run target test
    zip                Run target zip
    zip-traditional    Run target zip-traditional
    zip-s3             Run target zip-s3
    zip-azure          Run target zip-azure
    zip-all            Run target zip-all
    setup-dist         Run target setup-dist
    copy-build-to-dist Run target copy-build-to-dist
    copy-dnd           Run target copy-dnd
    copy-traditional-dist Run target copy-traditional-dist
    copy-traditional-jquery-dist Run target copy-traditional-jquery-dist
    copy-s3-dist       Run target copy-s3-dist
    copy-s3-jquery-dist Run target copy-s3-jquery-dist
    copy-azure-dist    Run target copy-azure-dist
    copy-azure-jquery-dist Run target copy-azure-jquery-dist
    copy-all-dist      Run target copy-all-dist
    docs               Run target docs
    maybe-update-root-docs Run target maybe-update-root-docs
    docs-travis        Run target docs-travis
    install-docfu      Run target install-docfu
    tag-release        Run target tag-release
    push-to-npm        Run target push-to-npm
    publish            Run target publish
    setup-dev          Run target setup-dev
    start-local-dev    Run target start-local-dev
    update-dev         Run target update-dev
    rev-version        Run target rev-version

  Templates:
    ava                Generate ava setup (ava)
    cli                Generate cli setup (minimist, tabtab, ge...)
    default            Generate default setup (babel-cli, babel-plu...)
    eslint             Generate eslint setup (eslint, eslint-confi...)
    livereactload      Generate livereactload setup (babel-plugin-react-t...)
    mocha              Generate mocha setup (mocha)
    simple             Generate simple setup
************ end ***********

Next - I saw the scripts in package.json and I was able to successfully run:

make clean

I then tried to run:

make build-traditional-ui
and:
make build-all-ui

both gave error output:

Bob@LAPTOP-06COO3JJ MINGW64 /c/aa_local_code/mean/express/fine-uploader (master)
$ make build-all-ui
make i info Invoking build-all-ui target
make i info Invoking _build target
A subdirectory or file -p already exists.
Error occurred while processing: -p.
A subdirectory or file $@ already exists.
Error occurred while processing: $@.
make × ERR  mkdir -p $@
cp -pR $(src-dir)/placeholders $@
cp -pR $(src-dir)/html/templates $@
cp LICENSE $@
cp $(src-dir)/*.css $@
cp $(src-dir)/*.gif $@
$(npm-bin)/cleancss --source-map $@/fine-uploader.css -o $@/fine-uploader.min.css
$(npm-bin)/cleancss --source-map $@/fine-uploader-gallery.css -o $@/fine-uploader-gallery.min.css
$(npm-bin)/cleancss --source-map $@/fine-uploader-new.css -o $@/fine-uploader-new.min.css
make × ERR  Recipe exited with code %d
(node:16640) UnhandledPromiseRejectionWarning: Error: Recipe exited with code %d
    at ChildProcess.<anonymous> (C:\Users\Bob\AppData\Roaming\npm\node_modules\make\src\cli.js:143:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:16640) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16640) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

************* end *************

next - I deleted the -p and @ directories and ran:

make build-all-ui

which generated the error output:

$ make build-all-ui
make i info Invoking build-all-ui target
make i info Invoking _build target
'$' is not recognized as an internal or external command,
operable program or batch file.
make × ERR  $(uglify) $(all-files) -o $(build-out-dir)/all.fine-uploader.js --source-map $(build-out-dir)/all.fine-uploader.js.map
make × ERR  Recipe exited with code %d
(node:7224) UnhandledPromiseRejectionWarning: Error: Recipe exited with code %d
    at ChildProcess.<anonymous> (C:\Users\Bob\AppData\Roaming\npm\node_modules\make\src\cli.js:143:28)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
(node:7224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

****************** end ***********

not sure where to go from here.  I'd really like to get this running but...  looks like a great app!

Thought you'd like to know what happened.

Bob (github un: rinebob)

</details>

<details>
<summary>Feature Request</summary>

#### Feature request details 
{why is this feature important, not just for you, but for many others?}
</details>

**Comment by rnicholus** [comment]
The build will likely not work on a non-POSIX system, sorry.
