### ISSUE TITLE
Unable to use with Internet Explorer 11 ... object properties not supported when trying to attach files

### ISSUE THREAD

**Issue by mjamati** [FineUploader/fine-uploader#2063]
## Type of issue
- [x] Bug report
- [ ] Feature request

## Uploader type
- [ ] Traditional
- [ ] S3
- [x] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

Version 5.14.5

Browser IE11

OS Windows 10; Windows 7 ...

Note: this does not happen with Chrome, Safari, or even with Edge. I tried using EDGE in emulation mode all the way down to Explorer 8 and it still worked. It seems to block on IE11 (as well as E11 with any emulation setting).

#### Exact steps required to reproduce the issue
1. Open download portal (using fine-uploader)
2. Attempt to attach file (form opens, select a file, click enter)
3. File does not upload

#### Detailed explanation of the problem
Developer Tools ... Console errors:
[Fine Uploader 5.15.4] Caught exception in 'onStatusChange' callback - Object doesn't support property or method 'find'
[Fine Uploader 5.15.4] Caught exception in 'onUpload' callback - 'Promise' is undefined
[Fine Uploader 5.15.4] Caught exception in 'onStatusChange' callback - Object doesn't support property or method 'find'
[Fine Uploader 5.15.4] Caught exception in 'onComplete' callback - Object doesn't support property or method 'find'

Updating the package version using yarn does not seems to change the version shown in the error messages. And the version does not actually match the packages installed (tried with 5.14.5 and also 5.16.2)
</details>

**Comment by rnicholus** [comment]
>1. Open download portal (using fine-uploader)

what does this mean?
