### ISSUE TITLE
Drag and drop from Open dialog then cancelling dialog sometimes makes Chrome hang

### ISSUE THREAD

**Issue by gwilson2151** [FineUploader/fine-uploader#2066]
## Type of issue
- [x] Bug report
- [ ] Feature request

## Uploader type
- [x] Traditional
- [ ] S3
- [x] Azure

### Note: Support requests cannot be accepted due to lack of time.

<details>
<summary>Bug Report</summary>

#### Fine Uploader version
5.16.2

#### Browsers where the bug is reproducible
Chrome Version 70.0.3538.77 (Official Build) (64-bit) using incognito window with no extensions enabled.

#### Operating systems where the bug is reproducible
Windows 10 (version 1803, build 17134.167)

#### Exact steps required to reproduce the issue
1. Visit https://fineuploader.com/demos.html in Chrome.
2. In the first uploader demo (Gallery View for Images) click Upload Files button.
3. Using the Open dialog find a folder with a bunch of images (png, jpg|jpeg, gif).
4. Drag many images, say 50-ish for best chance of it happening, from the open dialog to dropzone of uploader.
5. Click Cancel button on open dialog fairly quickly, before all of the image previews have shown in the dropzone ideally.
6. Chrome stops responding. You may have to try a few times, it can be tricky to get to happen.

#### All relevant Fine Uploader-related code that you have written
Whatever is in the demo page is sufficient. Looks like you might need to have autoUpload and drag and drop features for this behaviour to occur.

#### Your Fine Uploader template markup (if using Fine Uploader UI and the issue is UI-related)
Whatever's in the demo page...

#### Detailed explanation of the problem
Chrome stops responding and never seems to come back. I've waited quite a while and it remains hung, you have to kill the task.
</details>

I know @rnicholus is spread thin but any insight or domain knowledge that can be shared that may help me investigate this further or work around this would be appreciated. I'm having a hard time identifying what exactly is going on in FineUploader at the moment it hangs due to the inconsistent reproduction and it's also hard to see what's going on inside Chrome since it hangs.

**Comment by rnicholus** [comment]
I've pretty much stepped away from the project as I don't have any time to dedicate to this project anymore, and I don't have any use for something like Fine Uploader at the moment.

**Comment by SinghSukhdeep** [comment]
@gwilson2151 can you try using the latest version and see if the issue persists

**Comment by gwilson2151** [comment]
The issue was actually found on the latest version. I was providing detail for the demo page, I'll fix that up in the bug report.

**Comment by gwilson2151** [comment]
It looks like it's a Chrome bug. You can close this issue if you'd like.
https://crbug.com/843040
