### ISSUE TITLE
Cannot use dropZone

### ISSUE THREAD

**Issue by cc010cc** [FineUploader/fine-uploader#2071]
## Type of issue
- [x] Bug report

## Uploader type
- [ ] Traditional
- [ ] S3
- [ ] Azure

Element ref was specified as a string (dropZone) but no owner was set. This could happen for one of the following reasons:
1. You may be adding a ref to a functional component
2. You may be adding a ref to a component that was not created inside a component's render method
3. You have multiple copies of React loaded
See https://fb.me/react-refs-must-have-owner for more information.

**Comment by rnicholus** [comment]
this has nothing to do with fine uploader
