### ISSUE TITLE
I think this is probably a pretty accurate description of what this newly built uploader looks like, and the "10 npm script calls" https://twitter.com/Dataflow_G/status/1063405073777156097

### ISSUE THREAD

**Issue by waynebloss** [FineUploader/fine-uploader#2072]
😆

_Originally posted by @rnicholus in https://github.com/FineUploader/fine-uploader/issues/2035#issuecomment-439397680_

Thanks for your concern! As a matter of fact, my simple uploader built in a couple days, which is (now) a tiny part of the online video editing system that I built, has been working without error for tens of thousands of uploads since I replaced this huge, fragile dependency with it.

Turns out, when you keep things simple and don’t try to implement every feature under the sun, then you don’t end up with anything at all like what you referenced in that tweet.  I guess your experience has been different. ;)

**Comment by rnicholus** [comment]
Indeed - i'm glad your uploader is working for your single project. This particular uploader is working for countless projects. In fact, it's a flexible uploader meant to serve many use cases. So now you understand how OSS works. 🙇
