### ISSUE TITLE
How to add params

### ISSUE THREAD

**Issue by aucman** [FineUploader/fine-uploader#473]
Hi!

I have a question regarding params. As far as I have tested fine uploader the only way to have dynamical parameters is to load whole plugin again in a page.

If I have

``` javascript
params: {

                    imageType: $('#ImageType').val(),

                }
```

and ImageType is a dropdown with some values. The first time value is correct since it is equel to value that dropdown has when page loads. If I change dropdown value and upload an image the value is still the same as when page has loaded. Is this correct behaviour or am I missing something?

**Comment by pradeepbrh** [comment]
@aucman Thanks for your code. I was stuck at some point and it gave me idea to resolve the issue.
