### ISSUE TITLE
Feature Request: Custom Server Response

### ISSUE THREAD

**Issue by pbauerochse** [FineUploader/fine-uploader#478]
I think it would be nice to enable a custom server response. Instead of returning the fixed structure with

```
{success: false, error: "My error message"}
```

I'd like to return a different structure with a different success identifier. I guess a nice way to override this could be to return a boolean in the onComplete handler. There one could react to the server response and manually determine whether the response indicates a success or error.

Example:

```
[..]
   .on('complete', function(event, id, fileName, responseJSON) {
        // custom validation of responseJSON here

        return responseJSON.myCustomSuccessIdentifier;
   });
```

Best Regards

Patrick

**Comment by dawncold** [comment]
Hi, I'm integrating FineUploader with a cloud service, which provides storage service, I can upload file directly to storage service like Amazon S3, but the service http response is not compatible with FineUploader's expection. I want to handler response first and return to FineUploader later, is it possible?
