### ISSUE TITLE
commonjs exports

### ISSUE THREAD

**Issue by akre54** [FineUploader/fine-uploader#513]
It would be nice to be able to `require` FineUploader using my standard CommonJS importer instead of needing to bind it to the window object. I have a number of places where I'm trying to keep my global dependencies as low as possible.

Should be as simple as changing the header to

``` javascript
if (typeof exports !== 'undefined') {
    if (typeof module !== 'undefined' && module.exports) {
      exports = module.exports = qq;
    }
    exports.qq = qq;
  } else {
    qq || (qq = qq);
  }
```

(borrowed from [underscore](https://github.com/documentcloud/underscore/blob/master/underscore.js#L53-L64))

and then wrapping the script in a self-calling closure.

**Comment by rnicholus** [comment]
CommonJS support will be added in 5.8.0 (in progress). See #1562 for details.
