### ISSUE TITLE
Prevent selecting the same file more than once

### ISSUE THREAD

**Issue by JonoB** [FineUploader/fine-uploader#702]
At the moment, it seems possible to select the same file more than once if you manually trigger uploads. 

Is it possible to prevent this?

**Comment by VenubabuSunkara** [comment]
It is working for single file, If when i uploaded multiple files return false is not uploading remaining files that is wrong

**Comment by VenubabuSunkara** [comment]
onValidate: function (id) {
                    if (qq.indexOf(selectedFiles, id.name) === -1) {
                        selectedFiles.push(id.name);
                        return true;
                    }
                    else {
                        return false;
                    }
                },


I selected one existing file and 3 new files, above code not allowing new 3 files also
