### ISSUE TITLE
3 - Include folder path in request params

### ISSUE THREAD

**Issue by ashkmehr** [FineUploader/fine-uploader#750]
Hi.

When I try to drag & drop a folder. when I drop the folder instead of the folder will be uploaded and the files that were in the folder is still inside the folder, the folder disappearing and only the files being uploaded and it does not appear that the files belong to any folder. So when I drop two different folders, files are not displayed in two completely different folders and files are displayed as a folder. What I done wrong?

Thanks

**Comment by jdq22** [comment]
I'm not sure if this is the best place to ask, but is there any intention to add the qqPath property directly to the objects within the array returned by getUploads()? I'm using the setParams method, but I want to access a file's qqPath in other places besides the endpoint (like within the UI, for example, or a secondary endpoint).

**Comment by rnicholus** [comment]
You can access the `qqPath` property on the actual `File` object, which can be obtained via the `getFile(id)` API method.

**Comment by danielHalan** [comment]
Is there any option to enable, that the filepath is included in the filename when sent to the server "upload"-request-endpoint? in case a user would upload files with same name but in different sub-folders.

**Comment by kashifshabbir** [comment]
How to use `dragAndDrop.reportDirectoryPaths` on S3 Uploader options?
```
const uploader = new FineUploaderS3({
  options: {
    request: {
      endpoint: 'BUCKET_NAME',
      accessKey: 'ACCESS_ID'
    },
    signature: {
      endpoint:
        '/HANDLER
    },
    dragAndDrop: { reportDirectoryPaths: true },
    retry: { enableAuto: true },
    chunking: { enabled: true },
    resume: { enabled: true }
  }
});
```
Can I use `dragAndDrop` as shown in above example?
