### ISSUE TITLE
param functions are evaluated more then once per file/part

### ISSUE THREAD

**Issue by laeubi** [FineUploader/fine-uploader#753]
I have some "function-params", the problem is, that if the request fails or if a request is splitted into parts, for each retry/part the function is evaluated.

So take the example with the fileNum, and a file with 3 parts, the first part will get fileNum1, the second 2, the third 3.
The next file uploaded (in one chunk) will get the 4.
The excpectation would be that File one get the 1 and file two the 2.

A Solution might be, that all params are copied and functions are evaluated at submit time, because the function has no chance to react since no context information is given (it might be a good ide to hand some information over to the functions like the ID etc. anyways...).

**Comment by rnicholus** [comment]
Closing this as it's quite old and I'm not certain anything needs to be done here. If additional integrators have concerns or suggestions, I will consider re-opening.
