### ISSUE TITLE
Hitting Chrome browser back button during an upload causes error

### ISSUE THREAD

**Issue by kleesman** [FineUploader/fine-uploader#754]
In Chrome 25 (Firefox does not do this, did not test any other browsers), if you press the back button while an upload is pending the onerror callback is hit immediately and gives the error: XHR returned response code 0. It does pop up the javascript confirm about leaving the page, but the upload has already errored out by that point. 

Attempting to leave the page via navigating to another page, or closing the browser works as expected with the warning prompt.

**Comment by rnicholus** [comment]
Not seeing this anymore in latest chrome.
