### ISSUE TITLE
CORS Headers not allowed (X-File-Name, Cache-Control)

### ISSUE THREAD

**Issue by lpaulger** [FineUploader/fine-uploader#818]
I needed to remove 
        xhr.setRequestHeader("X-File-Name", encodeURIComponent(name));
        xhr.setRequestHeader("Cache-Control", "no-cache");
in order to get my CORS POST requests to work.

Maybe there is a better solution for this?

**Comment by antongorodezkiy** [comment]
I know that this is the old thread. But I have the issue with `Cache-Control` header when trying upload directly to Vimeo:

Here is the error from Chrome console:
`XMLHttpRequest cannot load http://1511655198.cloud.vimeo.com/upload?ticket_id=69d.......ae231c. Request header field Cache-Control is not allowed by Access-Control-Allow-Headers.`

If I comment the line with `Cache-Control` header the uploader works fine.

**Comment by rnicholus** [comment]
@antongorodezkiy Please open a new question either here or on Stackoverflow. This issue is 2 years old.
