### ISSUE TITLE
Add new getUploads() to return JSON array of uploads

### ISSUE THREAD

**Issue by andrew-kzoo** [FineUploader/fine-uploader#822]
Add a `getUploads()` method (or similar) would return a JSON array of uploads:

``` json
[
  {
    name: "Example.jpg",
    uuid: "d12fd2c2-09ec-4c98-bcc7-ff0427cd5f25"
  },
  {
    ...
  }
]
```

Related to #813 and #821

**Comment by ajschmaltz** [comment]
@andrew-kzoo how did you end up implementing this?  I'm something akin to:

---
  form = $(this).serializeArray()
  form.push({name: 'files', value: JSON.stringify(uploader.getUploads()) })
---
