### ISSUE TITLE
Possible to prevent upload?

### ISSUE THREAD

**Issue by jstayton** [FineUploader/fine-uploader#848]
Hey there,

I have auto-upload disabled to give the user a chance to input a name for each file before upload. If the name is not unique — a check I do with an XHR request in `onSubmit` — I'd like to prevent the file from being uploaded until the name is unique (checked on `keyup`). I tried returning `false` in `onUpload`, but that doesn't seem to be supported, as the file is still uploaded. I know it's possible to prevent a file from being _added_, but that doesn't really help in this case. I'd like the file to be added, but prevent _upload_. Can you think of a way I can accomplish this flow?

I'm using v3.3 of the jQuery plugin.

Love the work you're doing — thanks!

**Comment by rnicholus** [comment]
Note that I'm currently implementing support for a return type of `Promise` for the `onUpload` callback in #1917. Rejecting will attempt to auto retry if auto retry is enabled _and_ if the rejected object does not contain a `preventRetry: true` entry.
