### ISSUE TITLE
1 - Allow upload with empty file.

### ISSUE THREAD

**Issue by AidasK** [FineUploader/fine-uploader#903]
"AutoRun.inf is empty, please select files again without it."
Empty file is also a file and this message bothers users a lot.
It is more for drag and drop uploads, because all uploads get canceled. 
But it would be nice to have empty file upload feature.

To implement this we only need to make optional validation in: 
_validateFileOrBlobData
and change this:

``` javascript
else if (size === 0){
        this._itemError('emptyError', name);
        valid = false;
}
```

to

``` javascript
else if (!this._options.validation.allowEmpty && size === 0){
        this._itemError('emptyError', name);
        valid = false;
}
```

**Comment by achung-miovision** [comment]
Are there any updates to getting this PR merged and released?

**Comment by rnicholus** [comment]
@achung-miovision This isn't a PR

**Comment by achung-miovision** [comment]
My apologies, there's a linked PR https://github.com/FineUploader/fine-uploader/pull/1673 that's been sitting around.

**Comment by rnicholus** [comment]
Remaining in that PR:

- unit tests
- documentation

If someone can tackle those items, I can merge and release after some manual tests on my end.

**Comment by adrianchung** [comment]
@rnicholus I've enhanced the PR and opened up a new PR here: https://github.com/FineUploader/fine-uploader/pull/1710
