### ISSUE TITLE
xhr.upload.onprogress not fired on Android 4.0.4 Stock Browser 

### ISSUE THREAD

**Issue by feltnerm** [FineUploader/fine-uploader#931]
The stock Android 4.0.4 browser does not appear to fully follow the spec for [XMLHttpRequest objects](https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html/). Specifically, the XHR object does not fire [ProgressEvents](https://dvcs.w3.org/hg/progress/raw-file/tip/Overview.html#suggested-names-for-events-using-the-progressevent-interface) as it should [1]. This does not appear to affect Chrome on Android.

This means no progress updates or progress-bar during currently occurring uploads, and that `onProgress` will *not* fire until the end of the upload.

Inspired via a StackOverflow question [2].

1 - https://code.google.com/p/android/issues/detail?id=46958&q=onprogress&colspec=ID%20Type%20Status%20Owner%20Summary%20Stars#makechanges
2 - http://stackoverflow.com/questions/17901630/fineuploader-onprogress-callback-does-not-work-for-android?noredirect=1#17901630

**Comment by rnicholus** [comment]
This should be moved to the docs site

**Comment by rnicholus** [comment]
- [ ] test

**Comment by rnicholus** [comment]
This seems pretty old. Closing, but will re-open if recent versions of Android still have this issue.
