### ISSUE TITLE
"xhr" doesn't accept HTTP 201

### ISSUE THREAD

**Issue by ghost** [FineUploader/fine-uploader#95]
fileuploader.js thinks that a 201 status code on the "xhr" post is a fail.  i think it should accept 201 as success:

http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html

**Comment by phbernard** [comment]
As a reference: this issue has been fixed, see https://github.com/FineUploader/fine-uploader/blob/e6ae6253e4bf2f1a428855e4ac265e55554e83bf/client/js/traditional/traditional.xhr.upload.handler.js#L77
